lsst-sqre/phalanx

logging/Dockerfile.kibana_no_security
logging/README.md
logging/create.sh
logging/destroy.sh
logging/es-values.yaml
logging/fluentd-es-values.yaml
logging/ingress.yaml
logging/kibana-values.yaml

This allows for a kubernetes cluster to run fluentd to collect and manage logs from the hosts and the kubernetes pods running on them.  This is then sent to an elasticsearch index and is available to kibana for front end searching by admins.  The kibana endpoint is protected with the auth proxy, although the kibana auth is currently disabled.

[DM-19540] Add logging infrastructure

---

logging/fluentd-es-values.yaml

This was because we noticed high memory usage, probably because
of logs being ingested but then the GC never really gives up
enough memory.

[DM-19540] Adjust fluentd GC

---

lsst-lsp-int/landing-page.yaml

Add in a new directory for lsst-lsp-int, with the values used for
the landing-page to deploy it on int.

[DM-22090] landing-page helm values for int

---

argo-cd/argo-cd-values.yaml
argo-cd/create.sh
argo-cd/destroy.sh
argo-cd/lsst-lsp-int-values.yaml
lsst-lsp-int/cadc-tap.yaml
science-platform-int/Chart.yaml
science-platform-int/templates/landing-page-application.yaml
science-platform-int/templates/tap-application.yaml
science-platform/Chart.yaml
science-platform/requirements.yaml
science-platform/templates/firefly-application.yaml
science-platform/templates/landing-page-application.yaml
science-platform/templates/tap-application.yaml
science-platform/values-google.yaml

This contains apps and helpers for setting up argo-cd on -int, and GKE.  This includes an app and some ideas at different layouts.
Since this is deployed to -int right now, taking this to master.

[DM-22180] Prototype argo-cd control for -int

---

science-platform-int/templates/landing-page-application.yaml
science-platform-int/templates/nublado-application.yaml
science-platform-int/templates/tap-application.yaml

This sets up argocd to control the nublado application (now part of the science-platform-int app of apps), which uses the helm chart that we tested out before.

[DM-22328] Add nublado application to -int

---

lsst-lsp-int/nublado.yaml

Okay so due to this bug, GPDF has said we should set nublado back
to using the old firefly demo URL until this linked issue is fixed.

[DM-22330] Point -int back to lsst-demo firefly

---

argo-cd/lsst-lsp-stable-values.yaml
lsst-lsp-stable/nublado.yaml

Okay so we found a regression on argocd 1.3.0 where it didn't like
the values files passed in with an explicit full URL for some reason.
Also, nublado stable needs a different signing key for the JWT tokens.

[DM-22376] Set argo version to 1.2.4, new signing key for nublado

---

lsst-lsp-stable/landing-page.yaml

This is needed to point at the updated URL for portal which is on
stable.

[DM-22501] Deploy landing page 3.0 to stable

---

science-platform-int/templates/landing-page-application.yaml
science-platform-int/templates/nublado-application.yaml
science-platform-int/templates/portal-application.yaml
science-platform-int/templates/tap-application.yaml
science-platform-stable/templates/landing-page-application.yaml
science-platform-stable/templates/nublado-application.yaml
science-platform-stable/templates/portal-application.yaml
science-platform-stable/templates/tap-application.yaml
science-platform/templates/landing-page-application.yaml
science-platform/templates/nublado-application.yaml
science-platform/templates/portal-application.yaml
science-platform/templates/tap-application.yaml
science-platform/values-google.yaml
services/landing-page/Chart.yaml
services/landing-page/requirements.yaml
services/landing-page/values-int.yaml
services/landing-page/values-stable.yaml
services/nublado/Chart.yaml
services/nublado/requirements.yaml
services/nublado/values-int.yaml
services/nublado/values-stable.yaml
services/portal/Chart.yaml
services/portal/requirements.yaml
services/portal/values-int.yaml
services/portal/values-stable.yaml
services/tap/Chart.yaml
services/tap/requirements.yaml
services/tap/values-gke.yaml
services/tap/values-int.yaml
services/tap/values-stable.yaml

Bring in another level of indirection via the services directory.  These directories allow for a place to store helm values.yaml files for different environments altogether by component.  I wanted the organization to be the other way first (environments then applications) but it seems like this model is more native to the way argo expects.  Plus, getting rid of the links should make the gitops checking easier.

[DM-22518] Refactor argocd apps

---

logging/create.sh
logging/es-values.yaml
logging/fluentd-es-values.yaml
logging/ingress-int.yaml

This overrides some configuration from the parent chart, especially having to do with log line concatenation.  While this worked for only kubernetes and docker logs, for qserv it seemed to struggle, so I limited this filter to only the kubernetes logs.

[DM-22582] Fixing qserv logs

---

science-platform-int/templates/landing-page-application.yaml
science-platform-int/templates/nublado-application.yaml
science-platform-int/templates/portal-application.yaml
science-platform-int/templates/tap-application.yaml

Apparently having this part in where setting prune to True (the
default is false) also turns on the automated sync.  I don't see
any settings for the manual sync in the CRD definition at:
https://argoproj.github.io/argo-cd/operator-manual/application.yaml
So I hope by taking out this part that it will go to manual mode.

[DM-22666] Argocd to manual

---

services/tap/values-gke.yaml
services/tap/values-int.yaml
services/tap/values-stable.yaml

Now we can update the values.yaml files with the configuration for
the bucket to use in the helm chart, which now supports setting this
bucket.  This goes right on through to the TAP server as a parameter.

[DM-22649] Fix TAP async by using configurable buckets

---

argo-cd/lsst-lsp-int-values.yaml
argo-cd/lsst-lsp-stable-values.yaml

The logging service uses a new helm chart repository for the fluentd
chart.  These need to be explicitly whitelisted in the helm config
for argocd.

[DM-22775] Add helm repo for kiwigrid

---

argo-cd/lsst-lsp-int-values.yaml

For some reason, this version wasn't pinned, although I thought we
had done this.

[DM-22775] Pin argocd version on int

---

services/logging/values-int.yaml

Okay so with further detailed testing, I had it right to start,
and this line is actually a redherring:
2019/12/31 16:53:18 Warning: Building values map for chart 'fluentd-elasticsearch'. Skipped value (map[]) for 'env', as it is not a table.
It makes it sound like the values-int.yaml is wrong, but looking
at the dry-run output, it is in there.  So this warning must be
generated by something else.  But it looks like it is now injecting
things correctly.

[DM-22775] One more time on fluentd environment variable

---

services/logging/values-int.yaml

Now that the charts aren't installed by name, and as one big subchart
the linkages are dependent on the name of the app (which is now,
'logging').  So we have to update these points where everyone knows
where to look for elasticsearch.

[DM-22775] Update service names for logging

---

services/tap/values-int.yaml
services/tap/values-stable.yaml

This uses these values changes to configure where the TAP server
connects to.

[DM-22787] Use new TAP chart to point to qserv-master01:31111

---

services/tap/values-int.yaml
services/tap/values-stable.yaml

I accidentally put in the default, which is port 4040, but int and
stable need port 31111, just like the commit message said!

[DM-22787] Actually set port to 31111!

---

services/tap/values-int.yaml
services/tap/values-stable.yaml

We're stopping the k8s experiment on qserv for now.  Back to the
old port.

[DM-22956] Move TAP back to qserv-master01:4040

---

services/logging/values-roundtable.yaml

This is just a configuration difference between versions.

[DM-23217] New version of kibana changed url -> hosts

---

science-platform-int/templates/authnz-application.yaml

This is an attempt to get argo-cd to recognize the auth application.

Fix for application name on auth

---

services/vault-secrets-operator/templates/vault-secrets-operator-ns.yaml

We need to make sure this namespace exists, and since this is a
standalone app, the namespace should be here with the rest of the
chart.

[DM-23653] Create the vault-secrets-operator namespace

---

services/authnz/values-int.yaml
services/authnz/values-stable.yaml

Reflecting a manual change made in stable, tell Argo CD to use
30 days for the token expiration length for internally-created
tokens based on CILogon logins.

[DM-23863] Increase token session length to 30d

---

science-platform/templates/authnz-application.yaml
services/authnz/values-nublado.yaml

Deploy authnz on nublado.  This will install it and configure its
routes, but not put it in front of anything (including the LSP).
It will be used for test deployments and iterative development of
the authnz platform.

[DM-23775] Add authnz to nublado

---

services/authnz/values-int.yaml
services/authnz/values-nublado.yaml
services/authnz/values-stable.yaml

Specify both host and ingress.host for NCSA deployments, and add
host but not ingress.host for nublado.lsst.codes.

[DM-23775] Adjust authnz for new Helm chart

---

science-platform-stable/templates/authnz-application.yaml
services/authnz/values-stable.yaml

Enable Argo CD management of authnz on stable, and upgrade stable
to the new release matching the current int deployment. Switch stable to
using a persistent volume claim for Redis.

[DM-23645] Argo CD management of authnz on stable

---

science-platform/templates/gafaelfawr-application.yaml
services/gafaelfawr/Chart.yaml
services/gafaelfawr/requirements.yaml
services/gafaelfawr/values-nublado.yaml
services/nublado/values-nublado.yaml

Deploy Gafaelfawr instead of authnz on nublado.lsst.codes and
switch to protecting nublado with it.  Deploy from the PR branch
for now while code review is in progress.

[DM-23776] Protect Nublado with Gafaelfawr

---

services/gafaelfawr/requirements.yaml
services/gafaelfawr/values-nublado.yaml

Use the new Gafaelfawr Helm chart and switch to CILogon
authentication from GitHub.  This allows returning to the default
group mappings.

[DM-23877] Switch to CILogon authentication

---

science-platform-int/templates/logging-application.yaml

Point logging to this branch.  This will allow me to work on -int's
values file for the new set of charts without disrupting stable or
other environments.  This will be a bit of a tricky dance, since I
am worried a bit about backward compability, but only while I work
on this (and have to have it checked in).

[DM-24542] Point int logging to branch

---

services/gafaelfawr/values-nublado.yaml

A typo in values-nublado.yaml prevented the setting from being
properly applied.

[DM-23877] Fix token expiration configuration

---

argo-cd/lsst-lsp-int-values.yaml

Temporarily remove authnz from in front of the Argo CD console on
int.  Port forwarding does not work properly to access the console
for that version of Argo CD, which makes it unsafe to upgrade auth
with auth in front of the UI.  This is behind a VPN and has its own
separate password, so this should be safe as a temporary measure
until the upgrade is complete.

[DM-24595] Remove auth from int Argo CD

---

services/gafaelfawr/templates/logout-ingress.yaml

The old nublado logout sent the user to /oauth2/sign_in.  Intercept
that and send it to /logout.

[DM-24598] Add rewrite for /logout

---

services/gafaelfawr/values-int.yaml
services/gafaelfawr/values-nts.yaml
services/gafaelfawr/values-nublado.yaml
services/gafaelfawr/values-stable.yaml

Add login_params settings to all Gafaelfawr deployments since the
new Gafaelfawr chart doesn't force the skin: "LSST" setting.
Force the IdP to NCSA for nublado.lsst.codes.  If this works, we'll
do the same for the other environments.

[DM-24662] Add login_params, force IdP on nublado.lsst.codes

---

services/gafaelfawr/requirements.yaml
services/nublado/values-nublado.yaml

Use the new custom error page to suppress caching of 403 errors for
Nublado on nublado.lsst.codes.  If this works properly, it will
later be rolled out to other environments.

[DM-24753] Enable 403 handling for nublado.lsst.codes

---

services/nublado/values-int.yaml

This handler forces the error page to not be cached.

[DM-24753] Enable custom Nublado 403 error page on int

---

services/gafaelfawr/values-tucson-teststand.yaml

The old one was owned by an individual.  Replace the OAuth
integration with a new client owned by lsst-sqre.

[DM-24922] Update GitHub client_id for Tucson teststand

---

science-platform/templates/nginx-ingress-application.yaml
services/nginx-ingress/values-nublado.yaml

Forgot to add this part which points to the proper helm values
files.  This was preventing usage of the SSL certificate.

[DM-25185] Fix nginx-ingress to point to values files

---

services/nginx-ingress/values-bleed.yaml
services/nginx-ingress/values-nublado.yaml

I thought helm would expand out these keys with the dots, like it
does on the command line.  Apparently it will just silently set
keys with dots.

[DM-25185] Fix yaml files

---

services/nginx-ingress/values-bleed.yaml

Configure bleed to send full X-Forwarded-For headers to debug the
Gafaelfawr support for proper client IP address logging.

[DM-24810] Use full X-Forwarded-For on bleed

---

services/nginx-ingress/values-bleed.yaml

The documentation I found was confusing.  controller.config should
contain the configmap entries directly.

[DM-24810] Fix syntax of nginx-ingress config

---

services/nginx-ingress/values-bleed.yaml

On the bleed NGINX ingress, set externalTrafficPolicy Local to
try to preserve source IP addresses.

[DM-24810] Set externalTrafficPolicy Local on ingress

---

science-platform-base/Chart.yaml
science-platform-int/Chart.yaml
science-platform-nts/Chart.yaml
science-platform-stable/Chart.yaml
science-platform-summit/Chart.yaml
science-platform-tucson-teststand/Chart.yaml
science-platform/Chart.yaml
services/gafaelfawr/Chart.yaml
services/landing-page/Chart.yaml
services/logging/Chart.yaml
services/nginx-ingress/Chart.yaml
services/nublado-users/Chart.yaml
services/nublado/Chart.yaml
services/obstap/Chart.yaml
services/portal/Chart.yaml
services/postgres/Chart.yaml
services/tap/Chart.yaml
services/vault-secrets-operator/Chart.yaml
services/wf/Chart.yaml

Add required metadata so that Renovate can parse the Helm charts
and look for dependencies that require updates.

[DM-25183] Add required Helm chart metadata

---

science-platform/templates/mobu-application.yaml

Forgot the part where we pick out the values files, but this worked
because the chart's zip file had the right values.

[DM-24246] Pass in values file for mobu

---

science-platform/templates/cert-manager-application.yaml
science-platform/values-base.yaml
science-platform/values-bleed.yaml
science-platform/values-int.yaml
science-platform/values-nts.yaml
science-platform/values-nublado.yaml
science-platform/values-stable.yaml
science-platform/values-summit.yaml
science-platform/values-tucson-teststand.yaml
science-platform/values.yaml
services/cert-manager/Chart.yaml
services/cert-manager/requirements.yaml
services/cert-manager/templates/cluster-issuer.yaml
services/cert-manager/values.yaml

Prepare to use LetsEncrypt to issue certificates rather than using
the wildcard certificate by adding cert-manager to non-NCSA
deployments.  (NCSA uses their own process for certs.)  This will
not do anything as configured until we change Ingress resources to
use the cert-manager annotations for certificates and remove the
nginx-ingress configuration for the default TLS certificate.

[DM-25487] Add cert-manager to non-NCSA deployments

---

science-platform/templates/cert-manager-application.yaml

All the applications need to be in the argocd namespace or really
weird things happen.

Move cert-manager application into argocd namespace

---

science-platform/templates/cert-manager-application.yaml
science-platform/values-summit.yaml
services/cert-manager/README.md
services/cert-manager/templates/default-certificate.yaml
services/cert-manager/values-base.yaml
services/cert-manager/values-bleed.yaml
services/cert-manager/values-nublado.yaml
services/cert-manager/values-summit.yaml
services/cert-manager/values-tucson-teststand.yaml

Tell cert-manager to generate a default certificate
For those environments where we deploy cert-manager, configure
creation of a default certificate in the default-certificate secret.
This requires parameterizing the values.yaml file by environment to
set different FQDNs.
This change does not yet make nginx-ingress use that certificate.
That will be done in a subsequent change.

[DM-25487] Generate a default certificate

---

services/nginx-ingress/values-nublado.yaml

Change the default certificate to the Let's Encrypt issued
certificate for nublado.lsst.codes.

[DM-25487] Switch nublado.lsst.codes to LE certificate

---

services/cert-manager/templates/cluster-issuer.yaml

See if this is the reason why Argo CD doesn't think the resource
exists even though it does.  The mutating webhook changes the
apiVersion to v1alpha3, and it looks like we can use that version
from the start.

[DM-25487] Update apiVersion of ClusterIssuer

---

services/nginx-ingress/requirements.yaml

Only affects bleed and nublado.lsst.codes for now, so we can test it there and then upgrade other environments as they're subsumed into the new framework.

[DM-25487] Upgrade nginx-ingress to 1.40.1

---

renovate.json

Enable Renovate scanning, which will pick up outdated Helm chart
dependencies.

[DM-25183] Enable WhiteSource Renovate for this repository

---

services/vault-secrets-operator/requirements.yaml

This reverts commit e6a1c843214cc2012284731eedcdbc0bda37a8b0.
Argo CD reports an error:
map: map[] does not contain declared merge key: name

Revert "Update helm chart vault-secrets-operator to v1.7.1"

---

services/gafaelfawr/values-gold-leader.yaml
services/gafaelfawr/values-red-five.yaml
services/gafaelfawr/values-rogue-two.yaml

Apparently this was wrong, what I want is the default which uses the
/login endpoint.  If this is set, then it uses that URL, which isn't
configured in the CILogon part, and won't work.

[DM-25730] Remove callback url

---

services/nginx-ingress/values-gold-leader.yaml
services/nginx-ingress/values-red-five.yaml
services/nginx-ingress/values-rogue-two.yaml

Go back to the default tls cert since there are problems using
the cert manager bot.  That means we need to point the path here
back.

[DM-25730] Use cert from installer on test environments

---

services/tap/values-int.yaml
services/tap/values-stable.yaml

This will tell java to allow a larger heap size, which is independent
of the kubernetes limits.  Otherwise java will try to compute it by
itself and get confused.

[DM-23047] Set java heap size for TAP

---

services/vault-secrets-operator/requirements.yaml
services/vault-secrets-operator/values.yaml

Upgrade to the latest upstream Helm chart.  The syntax of the
environmentVars values.yaml override has changed to now match the
syntax used in deployments, so update accordingly.

[DM-25708] Upgrade vault-secrets-operator

---

services/cert-manager/templates/vault-secret.yaml

.Values, not Values, when testing whether the DNS solver is
configured.

[DM-25487] Fix syntax error in cert-manager secret template

---

services/cert-manager/templates/cluster-issuer.yaml
services/cert-manager/templates/vault-secret.yaml
services/cert-manager/values-tucson-teststand.yaml

Helm templates don't like dashes, so change the parameters for
cert-manager configuration to underscores.  Add another layer of
conditional because Helm can't understand that a boolean test on
a non-existent setting should be false and apparently doesn't have
short-circuiting "and" either.
This makes the cluster-issuer.yaml template temporarily messy by
repeating the else block.  I'm not bothering to fix this for now
because this will go away when we standardize on the DNS solver.

[DM-25487] Work around design flaws in Helm templating

---

services/cert-manager/templates/cluster-issuer.yaml

No idea why this is required since Route 53 is regionless, but the
schema apparently requires it anyway.

[DM-25487] Add region to DNS solver

---

science-platform/values-tucson-teststand.yaml
services/nginx-ingress/values-tucson-teststand.yaml

Take over management of nginx-ingress on the Tucson teststand,
and switch from the wildcard certificate to the Let's Encrypt
certificate.

[DM-25487] Manage nginx-ingress on Tucson teststand

---

services/nginx-ingress/values-bleed.yaml
services/nginx-ingress/values-gold-leader.yaml
services/nginx-ingress/values-nublado.yaml
services/nginx-ingress/values-red-five.yaml
services/nginx-ingress/values-rogue-two.yaml

Copy the settings of large-client-header-buffers, proxy-body-size,
proxy-buffer-size, and ssl-redirect from NCSA (int) to the
enviroments where we manage the ingress so that the nublado ingress
consistently uses the same settings everywhere.

[DM-25487] Standardize nginx-ingress settings with NCSA

---

renovate.json

We don't need to get the pull requests as soon as a new release
happens.  This aligns with Monday being the day that we merge
third-party dependency updates.

Set a weekly schedule for Renovate

---

services/cert-manager/requirements.yaml

This reverts commit ec8bd0daf71473e8d0010a8efac699b462a0a593.
Applying this update hangs due to a bug in Kubernetes.

Revert "Update helm chart cert-manager to v0.16.0"

---

installer/generate_secrets.py
installer/install.sh
services/cert-manager/values-bleed.yaml
services/cert-manager/values-gold-leader.yaml
services/cert-manager/values-nublado.yaml
services/cert-manager/values-red-five.yaml
services/cert-manager/values-rogue-two.yaml

Change all remaining environments where we manage the ingress to
use the DNS solver for cert-manager.  This removes the need to
provide the wildcard certificate as input to install.sh, so remove
the handling there and instead add a prompt for the AWS secret key.

[DM-25487] Switch to DNS solver for cert-manager

---

services/gafaelfawr/requirements.yaml
services/gafaelfawr/values-bleed.yaml

Pause here until we're ready to release a new version of Gafaelfawr
and roll out Redis authentication everywhere.

Revert Gafaelfawr back to 1.3.5

---

installer/install.sh

Before it was at 24h, which would shorten the lifetime of the
read tokens.  Therefore these would expire if they were not
renewed within 24h.

[DM-26523] Set vault-secrets-operator lifetime to 1y

---

docs/argo-cd/index.rst
docs/index.rst

Primarily this is upgrade documentation along with warnings about
some Argo CD behavior and upgrade pitfalls.  Backups, restores, and
fixing upgrade and bad restoration failures required a lot of
research, so document them for posterity.

[DM-26549] Add operational documentation for Argo CD

---

services/nublado/values-base.yaml
services/nublado/values-bleed.yaml
services/nublado/values-gold-leader.yaml
services/nublado/values-nublado.yaml
services/nublado/values-red-five.yaml
services/nublado/values-rogue-two.yaml
services/nublado/values-summit.yaml
services/nublado/values-tucson-teststand.yaml

The nublado chart uses proxy.ingress.tls.cluster_issuer, not
proxy.ingress.tls.issuer, since the configured name must be a
cluster issuer.

[DM-25487] Fix TLS issuer configuration for nublado

---

services/landing-page/values-bleed.yaml
services/mobu/values-bleed.yaml
services/obstap/values-bleed.yaml
services/portal/values-bleed.yaml
services/tap/values-bleed.yaml

There appears to be no way to avoid using the default certificate
with nginx and also use the * virtual host with TLS certificates
because nginx can't find the appropriate certificate to use and
falls back on the self-signed one.  Convert all the bleed app
installs to naming the ingress host so that TLS works properly.

[DM-25487] Switch bleed.lsst.codes to named virtual hosts

---

installer/install.sh
services/gafaelfawr/values-gold-leader.yaml
services/gafaelfawr/values-nublado.yaml
services/gafaelfawr/values-red-five.yaml
services/gafaelfawr/values-rogue-two.yaml
services/landing-page/values-gold-leader.yaml
services/landing-page/values-nublado.yaml
services/landing-page/values-red-five.yaml
services/landing-page/values-rogue-two.yaml
services/logging/values-red-five.yaml
services/mobu/values-gold-leader.yaml
services/mobu/values-nublado.yaml
services/mobu/values-red-five.yaml
services/mobu/values-rogue-two.yaml
services/nublado/values-gold-leader.yaml
services/nublado/values-nublado.yaml
services/nublado/values-red-five.yaml
services/nublado/values-rogue-two.yaml
services/obstap/values-gold-leader.yaml
services/obstap/values-nublado.yaml
services/obstap/values-red-five.yaml
services/obstap/values-rogue-two.yaml
services/portal/values-gold-leader.yaml
services/portal/values-nublado.yaml
services/portal/values-red-five.yaml
services/portal/values-rogue-two.yaml
services/tap/values-gold-leader.yaml
services/tap/values-nublado.yaml
services/tap/values-red-five.yaml
services/tap/values-rogue-two.yaml

Certificate management by configuring the TLS certificate for
nublado's JupyterHub proxy and letting everyone else inherit it
via TLS merging on a virtual host only works with named virtual
hosts because ingress-nginx won't merge TLS for the * virtual host.
Therefore, change all enviroments to named virtual hosts.
This was already the case for the NCSA, summit, base, and Tucson
test stand environments, so this change is only in the GKE
enviroments.  Also add a parameter to the install.sh installer
script for the hostname so that Argo CD can be configured with the
appropriate named virtual host as well.

[DM-25487] Switch to named virtual hosts everywhere

---

science-platform/templates/cert-issuer-application.yaml

It needs to sync after cert-manager.  The sync wave was set on the
individual resources, but not on the application.  See if setting it
on the application will help.

[DM-25487] Move cert-issuer to a later sync wave

---

science-platform/templates/cert-issuer-application.yaml

The secret for a ClusterIssuer has to be in the cert-manager
namespace, so creating a separate cert-issuer namespace does not
work.

[DM-25487] Move cert-issuer to cert-manager namespace

---

docs/cert-issuer/index.rst

Document the need to create a CNAME to tls.lsst.codes for any
new cluster.

[DM-25487] Document Route 53 setup for cert-issuer

---

installer/install.sh
science-platform/templates/cert-issuer-application.yaml
services/cert-issuer/templates/cluster-issuer.yaml

When bootstrapping the cluster, sync nginx-ingress, cert-manager,
and cert-issuer first.  Drop all the sync wave annotations, which
appear to just confuse matters and cause the sync of the
science-platform app to hang.

[DM-25487] Fix initial sync ordering

---

science-platform/templates/vault-secrets-operator-application.yaml
science-platform/values-base.yaml
science-platform/values-bleed.yaml
science-platform/values-gold-leader.yaml
science-platform/values-int.yaml
science-platform/values-nts.yaml
science-platform/values-nublado.yaml
science-platform/values-red-five.yaml
science-platform/values-rogue-two.yaml
science-platform/values-stable.yaml
science-platform/values-summit.yaml
science-platform/values-tucson-teststand.yaml
science-platform/values.yaml

The installer script syncs this app separately, but add it to the
app of apps anyway so that we stick with the pattern that
science-platform owns all of the apps.
Add some missing app configuration for the summit science-platform
definition.

[DM-25487] Add vault-secrets-operator to science-platform

---

services/gafaelfawr/requirements.yaml

Fixes some bugs in OpenID Connect support, which will be used for
SQuaSH, EFD, and possibly other things.

[DM-26682] Bump Gafaelfawr version

---

science-platform/templates/vault-secrets-operator-application.yaml

vault-secrets-operator has to be deployable as its own application
for early bootstrapping, so it creates its own namespace.  This then
duplicates the namespace created by science-platform for it.
Drop the latter, since it shouldn't be necessary (Argo CD will sync
the namespace first when syncing vault-secrets-operator).

Drop namespace for vault-secrets-operator

---

services/tap/values-bleed.yaml
services/tap/values-gke.yaml
services/tap/values-gold-leader.yaml
services/tap/values-int.yaml
services/tap/values-minikube.yaml
services/tap/values-nublado.yaml
services/tap/values-red-five.yaml
services/tap/values-rogue-two.yaml
services/tap/values-stable.yaml

First, point stable over to the address of the small qserv.
Next, we need to release a new version of the TAP service to roll
out the proper monkey queries as well.  While we don't theoretically
need to roll this out everywhere (since only stable is running
the monkey) I like to keep the spirit of everything up to date.

[DM-27279] Move stable over to small qserv

---

services/nginx-ingress/values-bleed.yaml

This allows the nginx ingress to talk to the JupyterHub proxy via
its NetworkPolicy.  We will eventually need this configuration
everywhere, but start only on bleed for now.

[DM-27278] Add JupyterHub label to nginx pod on bleed

---

installer/minikube/coredns.yaml
installer/minikube/setup_minikube.sh

Making some helper scripts including one to make the cluster and
set up the appropriate coredns configmap to allow for DNS resolution
of minikube.lsst.codes to work from inside the cluster.
This should be run before the installer script.

[DM-27353] Helper scripts for minikube

---

science-platform/values.yaml

This might be confusing, as Adam will likely attest to.

Don't default the science-platform part to an environment name

---

services/argo-cd/values.yaml

Add the necessary extra level in values.yaml and override the
release name to preserve the naming when Argo CD was manually
installed with Helm.

[DM-26507] Fix configuration for argo-cd

---

installer/argo-cd-values.yaml
services/argocd/values-base.yaml
services/argocd/values-bleed.yaml
services/argocd/values-gold-leader.yaml
services/argocd/values-int.yaml
services/argocd/values-minikube.yaml
services/argocd/values-nts.yaml
services/argocd/values-nublado.yaml
services/argocd/values-red-five.yaml
services/argocd/values-rogue-two.yaml
services/argocd/values-squash-sandbox.yaml
services/argocd/values-stable.yaml
services/argocd/values-summit.yaml
services/argocd/values-tucson-teststand.yaml
services/nginx-ingress/requirements.yaml
services/nginx-ingress/values-bleed.yaml
services/nginx-ingress/values-gold-leader.yaml
services/nginx-ingress/values-minikube.yaml
services/nginx-ingress/values-nublado.yaml
services/nginx-ingress/values-red-five.yaml
services/nginx-ingress/values-rogue-two.yaml
services/nginx-ingress/values-tucson-teststand.yaml

Okay so the previous chart was marked as deprecated and moved to
a new helm chart repo.  So first we update the requirements.yaml
to point to that repository, and the new URL.  The version numbers
have also changed, so pick the latest one there that is published.
Now since the name of the chart has changed from nginx-ingress to
ingress-nginx, this means that the name in the requirements.yaml
changes as well.  And since this is used as the section in the
values files, all of those have to change to match that name.
Otherwise that configuration section will be ignored (which is
all of it).

[DM-27636] Fix nginx-ingress chart dependency

---

services/nginx-ingress/values-minikube.yaml

Get rid of some parts that aren't used by the new chart, and
fix the nodeport which used to work with the old chart, but
hangs with the current settings.

[DM-27636] Fix minikube ingress

---

services/nginx-ingress/Chart.yaml
services/nginx-ingress/requirements.yaml

The upstream chart now only supports Helm v3, so change our chart
to use Helm v3 syntax so that Argo CD will apply it with Helm v3.

Convert nginx-ingress chart to Helm v3 syntax

---

services/vault-secrets-operator/requirements.yaml

Fixes ownership of secrets for Argo CD.

Bump vault-secrets-operator to 1.10.1

---

services/exposurelog/values-nts.yaml

- Set correct values for nfs_path_1, butler_uri_1 and nfs_server at NCSA Test Stand

Fix exposurelog values for the NTS environment

---

services/cert-manager/requirements.yaml

The new version doesn't seem to work correctly with Route 53.

Revert cert-manager version

---

science-platform/values.yaml

This way if someone misconfigures the environment, nothing will
be deployed, which will make it obvious that something is wrong.
The previous failure mode would deploy every application, which
can cause more of a mess.

[DM-26507] Disable all applications by default

---

installer/install.sh

- Now that vault-secrets-operator is parametrized for each environment the install.sh script needs to set the --values option.

Set values file when installing vault-secrets-operator

---

services/cert-manager/requirements.yaml

This reverts commit 5129919c583121a79661872a7db4def3d9433ccb.
The problem appears to have been due to a glue record, so retry
the upgrade and see if things work properly now.

[DM-27867] Revert "Revert cert-manager version"

---

installer/install.sh

- The installer bootstraps Argo CD by installing its Helm chart and then creates the Argo CD app to manage it.
- The version of Argo CD bootstrapped by the installer must be the same as the version synchronized later, otherwise during the synchronization step the argocd-server pod will restart breaking the communication with Argo CD CLI and making the admin password invalid.

Ensure Argo CD chart versions are consistent

---

installer/minikube/coredns.yaml
services/gafaelfawr/values-minikube.yaml
services/mobu/values-minikube.yaml
services/nginx-ingress/values-minikube.yaml
services/nublado/values-minikube.yaml
services/nublado2/values-minikube.yaml
services/portal/values-minikube.yaml

Okay, so first off, this came about by not being able to get to the
gafaelfawr token endpoint, due to the annotations being wrong (no
port), and no way to configure it.
Realizing I'm digging a hole rather than making a pile, I found a
way to configure the nginx-ingress to use the host networking on
80 and 443 (which is actually the VM's host).  This means we can
get rid of port 31337 (picked because NodePorts can only have
ephemeral range).
Using the host network also allows the pod to contact itself,
something it couldn't do previously since it wasn't attached to
the host networking stack.
One downside is that I haven't gotten the admissions webhook
service working yet, and this means that you won't get a warning
if you make an editing goof in your ingress yaml.  But only for
minikube. …

[DM-28043] Fix up minikube networking

---

science-platform/values-nts.yaml
services/exposurelog/values-bleed.yaml
services/exposurelog/values-nts.yaml
services/exposurelog/values-summit.yaml

Add site_id to all existing exposurelog values (bleed, nts, and summit).
Disable deployment at nts because it doesn't have a suitable butler registry.

DM-28135: exposurelog: add site_id and disable nts deployment

---

services/portal/values-int.yaml
services/portal/values-stable.yaml

This is a slightly different way to configure it based on the
helm chart changes on the same ticket.

[DM-28198] Portal: use new way to specify hostpath

---

.github/workflows/ci.yaml
.github/workflows/docs.yaml
.github/workflows/minikube.yaml

Depend on only the major version for the GitHub Actions where this
is supported, to avoid churn on version updates.

Relax version constraints on GitHub Actions

---

services/ingress-nginx/values-idfdev.yaml

Pin the ingress IP to the static IP created via Terraform for the
IDF development environment.

[DM-27979] Pin ingress IP for idfdev

---

installer/generate_secrets.py
installer/install.sh
science-platform/values-minikube.yaml
services/ingress-nginx/templates/vault-certificate.yaml
services/ingress-nginx/values-bleed.yaml
services/ingress-nginx/values-gold-leader.yaml
services/ingress-nginx/values-idfdev.yaml
services/ingress-nginx/values-idfint.yaml
services/ingress-nginx/values-minikube.yaml
services/ingress-nginx/values-nublado.yaml
services/ingress-nginx/values-red-five.yaml
services/ingress-nginx/values-rogue-two.yaml
services/ingress-nginx/values-squash-sandbox.yaml
services/ingress-nginx/values-tucson-teststand.yaml

Load the certificate from a vault secret.
Disable for all environments other than minikube for now, although
forks of this repo may use this feature.  This means that instead
of using let's encrypt, minikube will use the certificate stored
in vault, not stressing our rate limits.

[DM-28256] Vault TLS certificate loading

---

science-platform/templates/rancher-external-ip-webhook-application.yaml
science-platform/values-bleed.yaml
science-platform/values-minikube.yaml
science-platform/values.yaml
services/argocd/values-bleed.yaml
services/rancher-external-ip-webhook/Chart.yaml
services/rancher-external-ip-webhook/values-bleed.yaml
services/rancher-external-ip-webhook/values-minikube.yaml

This admission controller is required to mitigate CVE-2020-8554.
This is a vulnerability in Kubernetes that allows anyone who can
create a pod to claim an IP address via externalIP configuration,
at which point Kubernetes will route all the traffic for that IP
to that pod.  The pod can claim addresses like 8.8.8.8 and run a
rogue DNS server or do other malicious things.
Since we allow users to create pods in the Science Platform, our
Kubernetes environment is effectively multi-tenant and we need to
prohibit this.
Install only in bleed and minikube for now to confirm that it
works.  cert-manager is required for the webhook, so install it
again on minikube (but not the cert issuer that uses Route 53).

[DM-27982] Install rancher-external-ip-webhook in bleed

---

docs/cert-issuer/bootstrapping.rst
docs/cert-issuer/index.rst
docs/cert-issuer/route53-setup.rst
docs/cert-manager/index.rst

Add documentation for setting up Route 53 for a new zone, and be
clearer about the steps for setting up cert-issuer for a new cluster.
Reference the cert-issuer documentation from cert-manager.

[DM-27983] Flesh out cert-issuer documentation

---

installer/generate_secrets.py

This apparently got left out, but is needed if that secret is
pulled from postgres.

[DM-28472] Add exposurelog_password to generate_secrets

---

science-platform/values-base.yaml
science-platform/values-summit.yaml
services/ingress-nginx/values-base.yaml
services/ingress-nginx/values-gold-leader.yaml
services/ingress-nginx/values-idfdev.yaml
services/ingress-nginx/values-idfint.yaml
services/ingress-nginx/values-minikube.yaml
services/ingress-nginx/values-nublado.yaml
services/ingress-nginx/values-red-five.yaml
services/ingress-nginx/values-rogue-two.yaml
services/ingress-nginx/values-squash-sandbox.yaml
services/ingress-nginx/values-summit.yaml
services/ingress-nginx/values-tucson-teststand.yaml

For now, we'll be managing cert-manager and ingress-nginx in the
antu and andes clusters.  Enable them and add the required values
files for ingress-nginx.
Try to pin the IP addresses for base, summit, and tucson-teststand
since we hopefully should be able to request the same IP address as
we're currently using in those clusters.

[DM-28463] Enable cert-manager and ingress-nginx at base and summit

---

services/gafaelfawr/values-idfprod.yaml

Grant access to IDF prod to the members of the Data Management
team in the GitHub LSST organization.

Add lsst/data-management team to IDF prod

---

services/tap/requirements.yaml

This should be wrapped up in the Chart.yaml now for helm 3.
Maybe the existance of this file is causing some kind of strange
error I'm seeing?

[DM-28454] Delete requirements.yaml

---

services/nublado2/values-bleed.yaml
services/nublado2/values-idfdev.yaml
services/nublado2/values-minikube.yaml

Add the base_url parameter required by the new version of the chart
and remove the now-unnecessary auth-url setting.

[DM-28666] Update Nublado 2 configuration

---

services/nublado2/values-idfdev.yaml

Maybe this will work?
Also, since the namespace is nublado2 on the datadev, we need to make these user created resources in the right namespace that nublado2 is also writing to.  I should probably factor this out in the near future to automatically put the namespace in, since that will be a major annoyance.

[DM-28482] Try to run as provisionator

---

services/nublado2/values-idfdev.yaml

The groups here is just a list of groups, but not in the proper
format we need.  That's external_groups

[DM-28482] Nublado2: use proper external_groups

---

services/nublado2/values-idfdev.yaml

Don't use the singleuser uid in the chart, we'll use pod_uid's
default which is in the nublado2 chart now.
Also, we can use the user_namespace template variable now, which
will automatically know and compute the proper namespace for us,
so that means the templating can be more cookie cutter.

[DM-28482] Don't use uid, user_namespace

---

README.md
docs/arch/index.rst
docs/index.rst

Document the very basics about the architecture of lsp-deploy, and
add some more detailed documentation about versioning and the
layering of Helm charts.

[DM-28675] Add a start of an architecture overview

---

services/gafaelfawr/values-bleed.yaml

This reverts commit 33a1585027e6eeea4e7aaac045a491e28d32fd1e.
CILogon has been fixed.

[DM-28845] Revert "Switch bleed environment to Gafaelfawr branch"

---

services/gafaelfawr/values-bleed.yaml

test.cilogon.org still has the broken code that means we don't get
uidNumber, so switch it back to regular CILogon for now.

[DM-28845] Point bleed back to regular CILogon for now

---

services/nublado2/values-int.yaml

Okay, so since int doesn't have automatically provisioning PVs, let's
just use in memory for now.  This won't be production anyway.

[DM-28923] In-memory nublado2 database

---

services/nublado2/values-int.yaml

For some reason on int it doesn't recognize the cluster svc DNS name?

[DM-28923] Nublado2: need to override auth annotation

---

services/cachemachine/Chart.yaml
services/cachemachine/values-bleed.yaml
services/cachemachine/values-idfdev.yaml
services/cachemachine/values-int.yaml
services/cachemachine/values-minikube.yaml
services/mobu/Chart.yaml
services/mobu/values-idfdev.yaml
services/mobu/values-idfint.yaml
services/mobu/values-idfprod.yaml
services/mobu/values-int.yaml
services/mobu/values-minikube.yaml
services/mobu/values-red-five.yaml
services/mobu/values-stable.yaml

Rather than pinning the Docker image tag, pin the version of the
chart for mobu and cachemachine.  The chart now pins the Docker
image.  This works correctly with Renovate's automatic PR
generation: it will now create PRs for new Docker image versions
in the charts repo and then create PRs for new chart versions in
the Phalanx repo.

[DM-28993] Pin mobu and cachemachine charts and remove tags

---

services/argocd/values-idfdev.yaml

Use an OAuth client identity created via the console.
Try restricting logins by Google Group, which may not work given
that we're not using G Suite.

[DM-28900] Enable Google auth to IDF dev Argo CD

---

.github/workflows/ci.yaml

Version 2 requires running the action in a different way.

Fix helm/chart-testing-action CI configuration

---

science-platform/values-base.yaml
science-platform/values-idfint.yaml
science-platform/values-idfprod.yaml
science-platform/values-minikube.yaml
science-platform/values-red-five.yaml
science-platform/values-summit.yaml
science-platform/values-tucson-teststand.yaml
services/moneypenny/values-base.yaml
services/moneypenny/values-idfint.yaml
services/moneypenny/values-idfprod.yaml
services/moneypenny/values-int.yaml
services/moneypenny/values-kueyen.yaml
services/moneypenny/values-minikube.yaml
services/moneypenny/values-nts.yaml
services/moneypenny/values-red-five.yaml
services/moneypenny/values-stable.yaml
services/moneypenny/values-summit.yaml
services/moneypenny/values-tucson-teststand.yaml
services/nublado/values-base.yaml
services/nublado/values-idfint.yaml
services/nublado/values-idfprod.yaml
services/nublado/values-int.yaml
services/nublado/values-kueyen.yaml
services/nublado/values-minikube.yaml
services/nublado/values-red-five.yaml
services/nublado/values-stable.yaml
services/nublado/values-summit.yaml
services/nublado/values-tucson-teststand.yaml

This will install the moneypenny app (namespace and pod).  It does NOT enable any of the hubs other than idfdev to use Moneypenny, although she is configured to do FS provisioning at all the IDF instances, as well as summit, base, and tucson-teststand.
The NCSA-managed instances (int/stable/nts), kueyen, red-five, and minikube all get Moneypenny, but configured to do nothing upon receipt of orders.

Add moneypenny across environments (no caller yet except in idfdev)

---

installer/generate_secrets.py

This is a bit cleaner, and fixes the issue where a new generated
key is present but doesn't exist in the vault.

[DM-28839] Add non existent regeneratable keys

---

installer/generate_secrets.py

This same key is used for both GitHub and Google OAuth.

[DM-28900] Add Argo CD dex.clientSecret to installer

---

docs/argo-cd/authentication.rst
services/argocd/values-base.yaml
services/argocd/values-int.yaml
services/argocd/values-nts.yaml
services/argocd/values-stable.yaml
services/argocd/values-summit.yaml
services/argocd/values-tucson-teststand.yaml

Configure the base, summit, NCSA int and stable, NCSA teststand,
and Tucson teststand environments to use GitHub for Argo CD
authentication.  Use the square team in lsst-sqre for access
control for now.  (More will be added on at least the teststand
environments.)
Add documentation for how to set up GitHub OAuth authentication.

[DM-28900] Add GitHub Argo CD authentication configuration

---

services/argocd/values-idfprod.yaml

Enable Google OAuth authentication for Argo CD in data.lsst.cloud
with an enumerated list of administrators.  This matches the
configuration from data-int with different URLs and a new client
ID corresponding to an OAuth application in the same GCP project.

[DM-28900] Use Google OAuth for Argo CD in prod

---

docs/arch/index.rst
docs/cert-issuer/bootstrapping.rst
docs/cert-issuer/index.rst
docs/cert-issuer/route53-setup.rst
docs/index.rst
docs/ingress-nginx/certificates.rst
docs/ingress-nginx/index.rst

Add some architectural discussion of how TLS is configured.  Stress
that only a commercial certificate or Route 53 with the DNS solver
are supported.  Be clearer about the prerequisites for the Route 53
approach.  Add a link to more information on creating glue records.

[DM-29170] Improve TLS documentation

---

services/mobu/Chart.yaml

At least for now, let's just unpin mobu, and then when we update the
chart we will update the version everywhere.  I'm not worried about
version compatibility right now.

[DM-29321] Unpin mobu

---

services/gafaelfawr/Chart.yaml
services/gafaelfawr/values-int.yaml
services/gafaelfawr/values-nts.yaml
services/gafaelfawr/values-stable.yaml

NCSA's ingress-nginx cannot resolve the internal cluster name for
Gafaelfawr, so use the ingress hostname instead for the Gafaelfawr
token ingress in those deployments.

[DM-29085] Use external hostname for auth-url at NCSA

---

services/gafaelfawr/values-int.yaml

CILogon has announced an update to their service on 2021-04-13.  Test it on -int prior to then by using their test service at test.cilogon.org.

Use test CILogon to verify their update.

---

science-platform/templates/squareone-application.yaml
science-platform/values-base.yaml
science-platform/values-idfdev.yaml
science-platform/values-idfint.yaml
science-platform/values-idfprod.yaml
science-platform/values-int.yaml
science-platform/values-minikube.yaml
science-platform/values-nts.yaml
science-platform/values-red-five.yaml
science-platform/values-squash-sandbox.yaml
science-platform/values-stable.yaml
science-platform/values-summit.yaml
science-platform/values-tucson-teststand.yaml
science-platform/values.yaml
services/squareone/Chart.yaml
services/squareone/values-base.yaml
services/squareone/values-idfdev.yaml
services/squareone/values-idfint.yaml
services/squareone/values-idfprod.yaml
services/squareone/values-int.yaml
services/squareone/values-minikube.yaml
services/squareone/values-nts.yaml
services/squareone/values-red-five.yaml
services/squareone/values-stable.yaml
services/squareone/values-summit.yaml
services/squareone/values-tucson-teststand.yaml

This adds the squareone service and leaves it disabled everywhere except `idfint` (where it replaces the `landing-page` service).

DM-29432: Add squareone service

---

services/squareone/values-idfint.yaml
services/squareone/values-minikube.yaml

Update the squareone image tag to 0.1.1 in idfint and minikube to test a solution to the squareone startup.

DM-29432: Update squareone image to 0.1.1 in idfint

---

services/squareone/values-idfint.yaml
services/squareone/values-minikube.yaml

On idfint and minikube.
This image should further fix the configuration path issue.

DM-29432: Update squareone image to 0.1.2

---

services/gafaelfawr/Chart.yaml

Pick up a fix to ingress configuration on Kubernetes 1.19 or later.

[DM-28120] Bump Gafaelfawr chart version

---

services/cert-issuer/values-idfdev.yaml
services/cert-issuer/values-idfint.yaml
services/cert-issuer/values-idfprod.yaml

The IDF environments were all trying to use the lsst.codes AWS
access key and have been failing since March.  Change the key ID
to the new lsst.cloud key pair.  The Vault secrets have already
been updated.

[DM-28120] Fix AWS access key for IDF

---

services/portal/values-idfdev.yaml
services/portal/values-minikube.yaml

This will make argocd stop showing the portal as out of sync
when it isn't.

[DM-29822] Use vault for portal secret

---

services/cachemachine/values-int.yaml

NCSA int's ingress can't resolve in-cluster names, so we have to
use the external name for auth-url settings.

[DM-28120] Fix auth-url for cachemachine at NCSA int

---

services/squareone/values-idfint.yaml

With the removal of nublado, squareone will be taking over the TLS
configuration for the shared hostname.

[DM-28120] Add TLS configuration to squareone for IDF int

---

services/gafaelfawr/values-idfint.yaml
services/portal/values-idfdev.yaml
services/portal/values-idfint.yaml
services/portal/values-int.yaml

Use the right /auth parameters for the portal and pass more headers
in the environments with Gafaelfawr 2.0.  Enable debug logging in
data-int for Gafaelfawr to try to understand why connections are
timing out.

[DM-28120] Clean up Gafaelfawr configuration

---

services/gafaelfawr/values-idfint.yaml
services/gafaelfawr/values-int.yaml

Add the new admin:provision scope to the int environments.  Remove
the now-unused exec:user scope from NCSA int.

[DM-28120] Add admin:provision to int environments

---

science-platform/values-idfdev.yaml
services/squareone/Chart.yaml
services/squareone/values-idfdev.yaml
services/squareone/values-idfint.yaml
services/squareone/values-minikube.yaml

Also bump the chart version and remove the image tag pinning, since
this is now handled by the chart.

[DM-28120] Deploy squareone on IDF dev

---

services/gafaelfawr/values-idfdev.yaml
services/gafaelfawr/values-idfint.yaml
services/gafaelfawr/values-int.yaml
services/gafaelfawr/values-minikube.yaml

Gafaelfawr 2.0.0 has been released, so we no longer need to pin to
a branch build and can install the official 2.0.0 release.

[DM-28120] Stop pinning Gafaelfawr image to a branch

---

science-platform/values-idfprod.yaml
services/gafaelfawr/values-idfprod.yaml
services/mobu/values-idfprod.yaml
services/moneypenny/values-idfprod.yaml
services/nublado2/values-idfprod.yaml
services/portal/values-idfprod.yaml
services/squareone/values-idfprod.yaml

Upgrade to Gafaelfawr 2.0, replace the landing page with squareone,
upgrade to nublado2 as the default notebook implementation, and
make the necessary changes to the configuration of the other
applications.

[DM-28120] Upgrade data.lsst.cloud to current versions

---

services/gafaelfawr/Chart.yaml

Pick up a fix for constructing the ingress on Kubernetes 1.19 and
later.

[DM-28120] Bump version of Gafaelfawr

---

services/gafaelfawr/Chart.yaml

Pick up hopeful fix to the ingress API selection for older versions
of Kubernetes.

[DM-28120] Bump Gafaelfawr version

---

services/gafaelfawr/Chart.yaml
services/gafaelfawr/values-idfdev.yaml
services/ingress-nginx/values-base.yaml
services/ingress-nginx/values-idfdev.yaml
services/ingress-nginx/values-idfint.yaml
services/ingress-nginx/values-idfprod.yaml
services/ingress-nginx/values-minikube.yaml
services/ingress-nginx/values-red-five.yaml
services/ingress-nginx/values-squash-sandbox.yaml
services/ingress-nginx/values-summit.yaml
services/ingress-nginx/values-tucson-teststand.yaml

Add the Gafaelfawr ingress label to our managed ingress-nginx and
enable the Gafaelfawr network policy that restricts access to the
ingress on IDF dev for testing.

[DM-28120] Enable Gafaelfawr network policy on IDF dev

---

services/gafaelfawr/values-idfdev.yaml
services/gafaelfawr/values-idfint.yaml
services/gafaelfawr/values-idfprod.yaml
services/gafaelfawr/values-int.yaml
services/gafaelfawr/values-nts.yaml
services/gafaelfawr/values-stable.yaml

Enable creation of a frontend NetworkPolicy on IDF int and stable.
Clean up debug logging configuration that's no longer needed.
Remove pre-Gafaelfawr-2.0 ingress configuration from NCSA
deployments.

[DM-28120] Enable Gafaelfawr NetworkPolicy on IDF

---

services/portal/values-idfprod.yaml
services/portal/values-int.yaml

Allows the upgrade to SUIT 2.2.0, which has fixes for Gafaelfawr
2.0 compatibility.

[DM-28120] Unpin SUIT on IDF prod and NCSA int

---

services/squareone/Chart.yaml

chart-only change to mount an emptyDir for .next/cache/images.

Update squareone chart to 0.1.5

---

services/cachemachine/values-int.yaml
services/cachemachine/values-stable.yaml

We weren't setting jupyterlab:ok, so that was running on all the
nodes, and we want to restrict the nodes down to just what jupyterlab
nodes are running on.  This will also restrict what nodes we look
at.

[DM-29799] Restrict cachemachine nodes by label

---

services/tap/values-stable.yaml

TAP wants a token in the Authorization header, so request a delegated
token so that we have a token to put there.

[DM-28120] Ask for a delegated token for TAP

---

services/nublado2/Chart.yaml
services/nublado2/values-base.yaml
services/nublado2/values-idfdev.yaml
services/nublado2/values-idfint.yaml
services/nublado2/values-idfprod.yaml
services/nublado2/values-nts.yaml
services/nublado2/values-red-five.yaml
services/nublado2/values-summit.yaml
services/nublado2/values-tucson-teststand.yaml

- Move the Butler credential environment variables to per-environment configuration
- Set `butler_secret_path` on every environment since it's currently mandatory

[DM-30007] Set Butler environment variables only on IDF

---

services/nublado2/Chart.yaml

Even force refresh isn't picking up the new chart versions for
some reason.  Force upgrading the chart with a pin.

[DM-30007] Pin the nublado2 chart to force an upgrade

---

services/squareone/values-base.yaml
services/squareone/values-red-five.yaml
services/squareone/values-summit.yaml
services/squareone/values-tucson-teststand.yaml

The T&S sites and red-five had .lsst.cloud instead of .lsst.codes.

[DM-28120] Fix TLS configuration for squareone

---

services/nublado2/values-nts.yaml

This was accidentally pointing to NCSA int.

[DM-28120] Fix secret paths on NCSA teststand

---

services/cachemachine/values-nts.yaml

The NCSA cluster doesn't support internal DNS references to services.

[DM-28120] Override the cachemachine ingress annotation

---

services/tap/values-idfdev.yaml
services/tap/values-idfint.yaml
services/tap/values-idfprod.yaml
services/tap/values-int.yaml
services/tap/values-minikube.yaml
services/tap/values-red-five.yaml

The chart doesn't configure authentication, so it needs to be done
in Phalanx, at least for now.  Request a delegated token and lift
it into the Authorization header, since TAP uses that internally.

[DM-28120] Fix authentication annotations for TAP

---

science-platform/values-int.yaml

Enable squareone and rancher-external-ip-webhook on NCSA int and
disable landing-page.

[DM-28120] Enable squareone current applications on NCSA int

---

science-platform/values-int.yaml

This isn't set up with cert-manager, so don't try to install it.

[DM-28120] Disable rancher-external-ip-webhook on NCSA int

---

services/cachemachine/values-base.yaml
services/cachemachine/values-summit.yaml

andes01 and andes04 are apparently cordoned, so use node labels
to stop looking at them for spawning purposes.

Restrict summit and base pods to labeled nodes

---

services/cachemachine/values-summit.yaml
services/nublado2/values-summit.yaml

Go back to using the recommended tag and unpin the release in
nublado2 now that we've fixed which nodes are inspected.

Unpin release on summit

---

services/tap/values-int.yaml
services/tap/values-stable.yaml

The Qserv team has tracked, patched, and tested bug which we could only reproduce on the 'small' cluster.  We would now like to swap 'small' back in to production so we can resume development activities on 'large'.

Configure NCSA -int and -stable to use 'small' Qserv instance

---

services/squareone/Chart.yaml
services/squareone/values-idfdev.yaml

This release includes new documentation, support, AUP, and API aspect pages in preparation for DP0.1. See https://github.com/lsst-sqre/squareone/pull/21

DM-30839: Update squareone to 0.2.0

---

services/squareone/Chart.yaml

Includes a typo fix for the terms of service.
https://github.com/lsst-sqre/squareone/pull/23

DM-30887: Update squareone to 0.2.2

---

services/portal/values-idfprod.yaml

Increase the replica count to four and the memory limit for each
pod to 24GB.  The memory limit matches NCSA stable.  NCSA stable
runs two pods.

[DM-30888] Scale up Portal on IDF production

---

services/portal/values-idfint.yaml
services/portal/values-idfprod.yaml

proxy_read_timeout for NGINX also controls the timeout on web
sockets.  We're seeing what we think is a web socket timeout showing
the results of a query in the Portal.  Try increasing the timeout
to five minutes to see if it resolves that.

[DM-30904] Increase proxy timeout for Portal

---

services/portal/values-idfint.yaml
services/portal/values-idfprod.yaml

This probably isn't necessary, but make them match for the Portal
configuration.

[DM-30904] Set proxy-send-timeout as well as proxy-read-timeout

---

services/portal/values-idfint.yaml
services/portal/values-idfprod.yaml

We have some long-running queries, so increase the proxy timeout to
10m, which is as long as the Portal will keep its web socket open
for.

[DM-30904] Further increase Portal proxy timeout

---

services/tap/Chart.yaml
services/tap/values-idfdev.yaml
services/tap/values-idfint.yaml
services/tap/values-idfprod.yaml
services/tap/values-int.yaml
services/tap/values-minikube.yaml
services/tap/values-red-five.yaml
services/tap/values-stable.yaml

Depend on 0.2.0 and remove the now-unnecessary override of the
address of the TAP schema database.

[DM-30904] Update TAP application for 0.2.0 chart

---

services/gafaelfawr/values-idfprod.yaml

This should fix access for people who have more teams than fit into
the first pagination of GitHub team memberships.

[DM-30971] Install hotfix Gafaelfawr on stable

---

services/cachemachine/Chart.yaml
services/moneypenny/Chart.yaml
services/squareone/Chart.yaml

Roll out a new version of these charts to add the ingress
annotation that was missing and causing some log messages.

[DM-30974] Rollout new versions of charts

---

services/portal/values-idfint.yaml

This should trigger the Portal fallback of showing the username,
which is what we want anyway.

[DM-31056] Stop sending the name to the Portal on IDF int

---

services/squareone/Chart.yaml
services/squareone/values-base.yaml
services/squareone/values-idfdev.yaml
services/squareone/values-idfint.yaml
services/squareone/values-idfprod.yaml
services/squareone/values-int.yaml
services/squareone/values-minikube.yaml
services/squareone/values-nts.yaml
services/squareone/values-red-five.yaml
services/squareone/values-stable.yaml
services/squareone/values-summit.yaml
services/squareone/values-tucson-teststand.yaml

This deploys squareone 0.3.0 with support for config-based notifications (via the Squareone values files). Includes notifications enabled for the idfdev and minikube environments for testing.kj

DM-31034: Squareone 0.3.0 with config-based notifications

---

services/gafaelfawr/Chart.yaml
services/gafaelfawr/values-idfdev.yaml
services/gafaelfawr/values-idfint.yaml
services/gafaelfawr/values-idfprod.yaml
services/portal/values-idfdev.yaml
services/portal/values-idfprod.yaml
services/portal/values-int.yaml
services/portal/values-stable.yaml

Stop passing name to the Portal in headers.  Upgrade Gafaelfawr to
4.2.0, which drops support for name in HTTP headers due to Unicode
issues and checks that the user is a member of a valid group.  Add
an error footer to the IDF environments pointing to the GitHub
project for issues (this is also on int and dev so that we can test
it more easily, not because those users should use that channel).

[DM-31056] Update to Gafaelfawr 4.2.0

---

services/tap-schema/values-int.yaml

Preparation for deploying it everywhere today
This should have no tangible effect on NCSA-int; it's a change only to a schema that isn't deployed there.

DM-30177: Deploy sdm_schemas 1.1.0 to NCSA-int

---

services/portal/Chart.yaml
services/portal/values-idfdev.yaml
services/portal/values-idfint.yaml
services/portal/values-idfprod.yaml

The chart now installs suit-233-7-dev by default.

[DM-30073] Remove Portal version overrides

---

science-platform/templates/semaphore-application.yaml
science-platform/values-base.yaml
science-platform/values-idfdev.yaml
science-platform/values-idfint.yaml
science-platform/values-idfprod.yaml
science-platform/values-int.yaml
science-platform/values-minikube.yaml
science-platform/values-nts.yaml
science-platform/values-red-five.yaml
science-platform/values-squash-sandbox.yaml
science-platform/values-stable.yaml
science-platform/values-summit.yaml
science-platform/values-tucson-teststand.yaml
science-platform/values.yaml
services/semaphore/Chart.yaml
services/semaphore/values-base.yaml
services/semaphore/values-idfdev.yaml
services/semaphore/values-idfint.yaml
services/semaphore/values-idfprod.yaml
services/semaphore/values-int.yaml
services/semaphore/values-minikube.yaml
services/semaphore/values-nts.yaml
services/semaphore/values-red-five.yaml
services/semaphore/values-stable.yaml
services/semaphore/values-summit.yaml
services/semaphore/values-tucson-teststand.yaml

Add the semaphore service (https://github.com/lsst-sqre/semaphore), and enable it for minikube and idf-dev environments for testing (app version 0.1.0).

DM-30725: Add semaphore application for development

---

science-platform/templates/semaphore-application.yaml
services/semaphore/values-base.yaml
services/semaphore/values-idfdev.yaml
services/semaphore/values-idfint.yaml
services/semaphore/values-idfprod.yaml
services/semaphore/values-int.yaml
services/semaphore/values-minikube.yaml
services/semaphore/values-nts.yaml
services/semaphore/values-red-five.yaml
services/semaphore/values-stable.yaml
services/semaphore/values-summit.yaml
services/semaphore/values-tucson-teststand.yaml

Semaphore's application source path was incorrectly left as services/squareone when bootstrapping. This left some errors in the semaphore configuration unchecked. This PR should resolve those issues.

DM-30931: Fix path for semaphore science-platform app

---

services/semaphore/Chart.yaml
services/semaphore/values-base.yaml
services/semaphore/values-idfdev.yaml
services/semaphore/values-idfint.yaml
services/semaphore/values-idfprod.yaml
services/semaphore/values-int.yaml
services/semaphore/values-minikube.yaml
services/semaphore/values-nts.yaml
services/semaphore/values-red-five.yaml
services/semaphore/values-stable.yaml
services/semaphore/values-summit.yaml
services/semaphore/values-tucson-teststand.yaml

- Update chart to 0.2.0-alpha.2 (enable development testing to semaphore (lsst-sqre/semaphore#3)
- Set vaultSecretsPath value

DM-30931: Update semaphore chart to 0.2.0-alpha.2

---

services/semaphore/Chart.yaml
services/semaphore/values-base.yaml
services/semaphore/values-idfdev.yaml
services/semaphore/values-idfint.yaml
services/semaphore/values-idfprod.yaml
services/semaphore/values-int.yaml
services/semaphore/values-minikube.yaml
services/semaphore/values-nts.yaml
services/semaphore/values-red-five.yaml
services/semaphore/values-stable.yaml
services/semaphore/values-summit.yaml
services/semaphore/values-tucson-teststand.yaml

This chart update adds the phalanx_env configuration for semaphore, which is needed for ingesting messages from a shared GitHub repository.

DM-30931: Deploy semaphore chart 0.2.0-alpha.3 onto idfdev

---

services/mobu/values-idfprod.yaml

For now, disable the mobu tutorial notebook runner, since it doesn't
work correctly with a notebook that requires an external file.

[DM-31201] Disable running tutorial notebooks on IDF prod

---

science-platform/values-idfint.yaml
services/semaphore/values-idfint.yaml
services/squareone/Chart.yaml
services/squareone/values-base.yaml
services/squareone/values-idfdev.yaml
services/squareone/values-idfint.yaml
services/squareone/values-idfprod.yaml
services/squareone/values-int.yaml
services/squareone/values-minikube.yaml
services/squareone/values-nts.yaml
services/squareone/values-red-five.yaml
services/squareone/values-stable.yaml
services/squareone/values-summit.yaml
services/squareone/values-tucson-teststand.yaml

This is for the integration of squareone 0.4 and semaphore 0.2 to source broadcast messages and user notifications from semaphore.
Enables semaphore on idfint and idfdev.

DM-30727: Squareone 0.4 and Semaphore 0.2 (idfint and idfdev)

---

services/semaphore/Chart.yaml

This fixes the /v1/broadcasts endpoint, which was showing disabled messages.

DM-31395: Update semaphore to 0.2.1

---

services/mobu/values-idfint.yaml

Add a new flock for doing TAP testing and pin data-int to the
ticket branch with the overhauled TAP support.

[DM-31454] Do TAP testing via mobu on data-int

---

services/mobu/values-idfint.yaml

This reverts commit 87c2fa2dfa89247618f2e2399ce0b3c00e9f814e.
data-int cannot run the TAP queries.

[DM-31454] Revert "Do TAP testing via mobu on data-int"

---

services/mobu/values-int.yaml

Try deploying a TAP testing monkey from the TAP ticket branch in
mobu on int, where hopefully it has all of the data sources required
for the default queries to pass.

[DM-31454] Use mobu for TAP testing on NCSA int

---

.gitignore
installer/install.sh

This has to be set up a bit different since we need this to exist
before vault-secrets-operator is installed.  Use the vault command
line to pull it down and kubectl to add it.

[DM-31518] pull-secret for vault-secrets-operator

---

services/mobu/Chart.yaml
services/mobu/values-idfdev.yaml
services/mobu/values-idfint.yaml
services/mobu/values-idfprod.yaml
services/mobu/values-int.yaml
services/mobu/values-stable.yaml

The next release of mobu will not require specifying all the values
to submit to the options form and will default to a Large image.
It also supports testing the latest weekly instead of the recommended
image, so use that on IDF int to test the latest weekly image before
we promote it.

[DM-31490] Update configuration for mobu 4.0.0

---

services/mobu/values-idfdev.yaml

This cluster doesn't have the resources to run large images.

[DM-31490] Use small images for mobu on IDF dev

---

services/mobu/values-stable.yaml

This is causing serious problems with qserv because it can't
handle one of the queries well.  Ensure it doesn't restart if
mobu is restarted.

Remove TAP monkey for NCSA stable for now

---

services/portal/values-base.yaml
services/portal/values-minikube.yaml
services/portal/values-nts.yaml
services/portal/values-red-five.yaml
services/portal/values-summit.yaml
services/portal/values-tucson-teststand.yaml

Add the delegate_to and delegate_scope params to the auth uri,
which were missing and causing trouble.

[DM-31876] Fix auth-uri setting for portal

---

services/strimzi-registry-operator/Chart.yaml

This update runs v0.3.0 of the underlying application.

DM-32548: strimzi-registry-operator: Update to v1.1.0 of chart

---

installer/generate_secrets.py

This changes the installer/generate_secrets.py script to allow updates of secrets that already exist in Vault, and have a value in 1Password. Previously, the value in Vault was always preserved.
There is some special behavior for ingress-nginx and cert-manager which I don't understand; I'm preserving the old code's behavior (never update those two) just out of caution.

Allow updates of secrets from 1Password

---

services/alert-stream-broker/values-idfint.yaml

This is a first step to deal with full disks - enlarge them so Kafka can start so we can see what's actually going on.

DM-32958: alert-stream-broker: grow disks to 1.5TB

---

docs/arch/secrets.rst
docs/index.rst
docs/service-guide/add-a-onepassword-secret.rst
docs/service-guide/update-a-onepassword-secret.rst
services/vault-secrets-operator/values-base.yaml
services/vault-secrets-operator/values-idfdev.yaml
services/vault-secrets-operator/values-idfint.yaml
services/vault-secrets-operator/values-idfprod.yaml
services/vault-secrets-operator/values-int.yaml
services/vault-secrets-operator/values-minikube.yaml
services/vault-secrets-operator/values-nts.yaml
services/vault-secrets-operator/values-red-five.yaml
services/vault-secrets-operator/values-roe.yaml
services/vault-secrets-operator/values-squash-sandbox.yaml
services/vault-secrets-operator/values-stable.yaml
services/vault-secrets-operator/values-summit.yaml
services/vault-secrets-operator/values-tucson-teststand.yaml

This describes what I had to do to update the alert-stream-broker's VaultSecret's child Secret.
---
Update:
After discussion, this now goes beyond just documentation. It also changes the configuration of Vault Secrets Operator in each environment, enabling automatic reconciliation.

Automatically reconcile VaultSecrets with Vault's state

---

services/alert-stream-broker/Chart.yaml
services/alert-stream-broker/values-idfint.yaml

This version sets a max bytes retention policy on the alerts-simulated topic.

DM-32958: alert-stream-broker: update to alert-stream-simulator 1.6.0

---

services/alert-stream-broker/Chart.yaml
services/alert-stream-broker/values-idfint.yaml

This merely requests `kafka` nodes (and tolerates their taints), it doesn't hard-require them, so it's safe to deploy even before taints are established.

DM-32568: alert-stream-broker: run on kafka node pool

---

services/moneypenny/Chart.yaml
services/moneypenny/values-base.yaml
services/moneypenny/values-idfdev.yaml
services/moneypenny/values-idfint.yaml
services/moneypenny/values-idfprod.yaml
services/moneypenny/values-int.yaml
services/moneypenny/values-minikube.yaml
services/moneypenny/values-nts.yaml
services/moneypenny/values-red-five.yaml
services/moneypenny/values-roe.yaml
services/moneypenny/values-stable.yaml
services/moneypenny/values-summit.yaml
services/moneypenny/values-tucson-teststand.yaml

Use the pull-secret chart to install pull-secret instead of a
separate VaultSecret that came with the old moneypenny chart.
Update values-*.yaml for the new configuration options and remove
boilerplate that's now handled by the chart.  Remove the retire
configuration, since we currently don't use it anywhere.
Enable the network policy on the IDF.

[DM-32811] Update moneypenny configuration

---

services/alert-stream-broker/values-idfint.yaml

This name needs to be synchronized exactly to a value in GCP, set via terraform.

DM-32646: alert-stream-broker: set service account name for db ingester

---

services/alert-stream-broker/Chart.yaml
services/alert-stream-broker/values-idfint.yaml
services/gafaelfawr/values-idfint.yaml

The server is the entrypoint allowing HTTP-based access to archival alert packet and schema data.

alert-stream-broker: add alert-db server

---

services/cachemachine/Chart.yaml
services/datalinker/Chart.yaml
services/gafaelfawr/Chart.yaml
services/noteburst/Chart.yaml
services/portal/Chart.yaml
services/semaphore/Chart.yaml
services/sherlock/Chart.yaml
services/squareone/Chart.yaml
services/squash-api/Chart.yaml
services/vo-cutouts/Chart.yaml

The latest versions of the charts add support for Kubernetes 1.22,
which deprecates the API we were using for ingress definitions.

[DM-32991] Bump chart versions to pick up Kubernetes 1.22 support

---

services/ingress-nginx/Chart.yaml

Now that all of the Ingress resources have been switched to the
new API, we can upgrade to the new version of ingress-nginx that
drops support for the old API version.

[DM-32991] Bump version of ingress-nginx

---

services/obstap/values-idfdev.yaml
services/obstap/values-idfint.yaml
services/obstap/values-idfprod.yaml
services/obstap/values-int.yaml
services/obstap/values-minikube.yaml
services/obstap/values-red-five.yaml
services/obstap/values-roe.yaml
services/obstap/values-stable.yaml

Push the tag to 1.1, apparently the chart doesn't default to the
app version yet, but I'll do that another time.

[DM-33248] Obstap version to 1.1

---

services/gafaelfawr/Chart.yaml

Pick up additional scope, new Google Cloud Proxy version, and new
Gafaelfawr 3.5.0 release with LDAP support and async Kubernetes.

[DM-33121] Bump version of Gafaelfawr

---

services/tap/values-idfprod.yaml
services/tap/values-stable.yaml

Up the memory because we were having issues when running too many
big queries and then running out of memory and kubernetes killing
me.

[DM-33306] TAP memory to 32 GB

---

services/alert-stream-broker/values-idfint.yaml
services/gafaelfawr/values-idfint.yaml

This will be used by the alert database.
Just using some of the traditional GH teams for groups backing it.

Use new read-alertdb scope for alertdb

---

services/moneypenny/Chart.yaml
services/nublado2/Chart.yaml
services/nublado2/values-base.yaml
services/nublado2/values-idfdev.yaml
services/nublado2/values-idfint.yaml
services/nublado2/values-idfprod.yaml
services/nublado2/values-int.yaml
services/nublado2/values-minikube.yaml
services/nublado2/values-nts.yaml
services/nublado2/values-red-five.yaml
services/nublado2/values-roe.yaml
services/nublado2/values-stable.yaml
services/nublado2/values-summit.yaml
services/nublado2/values-tucson-teststand.yaml

Bump the version of moneypenny and nublado2 to pick up the new
Moneypenny API.  Configure pull-secret for nublado2, since our
chart was referencing it but not installing it so far as I could
see.

[DM-33244] Bump moneypenny, nublado2 version, add pull-secret

---

services/noteburst/Chart.yaml
services/noteburst/values-idfdev.yaml
services/noteburst/values-minikube.yaml

This adds support for noteburst's worker queue.

DM-33025: Deploy noteburst 0.2.0-alpha.3 chart on idf-int

---

services/tap/values-idfdev.yaml
services/tap/values-idfint.yaml
services/tap/values-idfprod.yaml
services/tap/values-int.yaml
services/tap/values-minikube.yaml
services/tap/values-red-five.yaml
services/tap/values-roe.yaml
services/tap/values-stable.yaml

Avoid the tap-cadc-tap naming pattern by overriding the name so
that everything will use the simpler cadc-tap base name.

[DM-33241] Override name of TAP objects

---

services/tap/Chart.yaml

Pick up fix for the name of the mock-qserv service.

[DM-33241] Bump version of TAP chart

---

services/tap/values-idfdev.yaml
services/tap/values-idfint.yaml
services/tap/values-idfprod.yaml
services/tap/values-int.yaml
services/tap/values-minikube.yaml
services/tap/values-red-five.yaml
services/tap/values-stable.yaml

async-results.lsst.codes is a CNAME to a GCS bucket, so we cannot
use https for the initial access because the certificate won't
verify.  Use http, which will cause the GCS endpoint to redirect
the user to the https URL with the correct hostname for the
certificate to verify.

[DM-33241] Fix gcsBucketUrl to not use https

---

services/vo-cutouts/Chart.yaml
services/vo-cutouts/values-idfdev.yaml
services/vo-cutouts/values-idfint.yaml

Add configuration for the new version of vo-cutouts and pin to the
current ticket branch.  This will be relaxed later once the new
version is working end to end.

[DM-33513] Update for new vo-cutouts

---

services/vo-cutouts/Chart.yaml

Pick up updated GCE Proxy and the change to the ConfigMap to pass
down the name of the service account.

[DM-33513] Bump version of vo-cutouts

---

services/exposurelog/values-summit.yaml

to use the correct ComCam repo and to include LATISS

DM-33595: exposurelog: update summit configuration

---

services/exposurelog/values-base.yaml

Use the two test butler registries in exposurelog 0.8.0;
the old hsc registry is gone.

exposurelog: update base deployment for 0.8.0

---

science-platform/values-idfprod.yaml
services/vo-cutouts/Chart.yaml
services/vo-cutouts/values-idfdev.yaml
services/vo-cutouts/values-idfprod.yaml

Update to the vo-cutouts 0.3.0 chart and adjust the data-int
configuration accordingly.  Pin to a newer ticket branch.  Add
configuration for IDF prod and enable it.  Update the configuration
for data-dev similarly.

[DM-33720] Update vo-cutouts chart, install in IDF prod

---

services/vo-cutouts/values-idfprod.yaml

IDF prod uses a different Butler repository URL than IDF int.

[DM-33720] Fix Butler repository URL for vo-cutouts IDF prod

---

services/sasquatch/values-idfdev.yaml
services/sasquatch/values-minikube.yaml

By setting GENERIC_API_KEY=sub we use the sub token claim, which corresponds to the user's username, instead of the user's email address as Gafaelfawr does not always have an email address for a user.

Debug Chronograf OIDC authentication

---

services/vo-cutouts/values-idfdev.yaml
services/vo-cutouts/values-idfint.yaml
services/vo-cutouts/values-idfprod.yaml

0.3.0 has been released, so we can now go back to using the
default images.

[DM-33720] Remove container pins for vo-cutouts

---

services/sasquatch/Chart.yaml
services/sasquatch/README.md
services/sasquatch/values.yaml

- Add InfluxData Telegraf chart as a dependency to Sasquatch
- Configure the Telegraf Prometheus input plugin to collect [JupyterHub metrics](https://jupyterhub.readthedocs.io/en/stable/reference/metrics.html) and write them to InfluxDB.

[DM-33804] Add Telegraf to Sasquatch

---

services/sasquatch/values-idfdev.yaml
services/sasquatch/values.yaml

I'm sure this is conceptually correct.  Whether it's `flux-enabled`, `flux-enable`, `flux_enabled`, `fluxEnabled`, or some other permutation isn't totally clear to me, but it'd be flux-enabled in the config file.  I don't quite understand mapping that to the Helm chart to the Phalanx config yet.

tickets/DM-33827: Enable Flux in IDF dev

---

services/sasquatch/README.md
services/sasquatch/values.yaml

The upstream InfluxDB helm chart used in sasquatch does not rewrite the configuration keys replacing "_" with "-" anymore. Glad we found this today, thanks @athornton

[DM-33924] Always use dash in the InfluxDB configuration keys

---

services/times-square/values-idfdev.yaml

This is to debug why access to /times-square/ was not possible.

DM-33930: Use unique path prefix for times-square-ui

---

services/times-square/Chart.yaml
services/times-square/values-idfdev.yaml

- Restores ingress path to /times-square
- Adopts 0.1.0-alpha.2 chart version which fixes the network policy
- Adopt fullnameOverride to make times-square-ui resources easier to work with

DM-33930: Update times-square-ui 0.1.0-alpha.2

---

services/mobu/values-idfint.yaml
services/mobu/values-idfprod.yaml

Remove the image settings for IDF int since the new version of mobu
has been released, and copy the TAP runner configuration to prod.

[DM-33813] Deploy mobu TAP runner on IDF prod

---

services/mobu/templates/deployment.yaml
services/mobu/templates/networkpolicy.yaml

Change the StatefulSet back to a Deployment, but use a Recreate
strategy so that only one will be running at a time.  Remove the
conditional around NetworkPolicy now that there's no boolean
setting whether to create an ingress.

[DM-33813] Update mobu type, enable NetworkPolicy

---

services/exposurelog/Chart.yaml
services/exposurelog/README.md
services/exposurelog/templates/deployment.yaml
services/narrativelog/README.md

in order to make matplotlib happy.
Also tweak existing volumeMount entries to put the name first, for consistency with other deployments.
Also add README files for exposurelog and narrativelog.

DM-33922: exposurelog: add a writable /tmp dir

---

services/times-square/charts/times-square/templates/configmap.yaml

Helm / Argo CD is having trouble resolving the pointer to the port; so we'll hard code it for now.

DM-34090: Times Square: hard code redis port

---

services/times-square/charts/times-square/Chart.yaml
services/times-square/charts/times-square/templates/configmap.yaml

This seems to be the ultimate issue with the times-square chart — that the `/bitnami` chart was left off the Helm repo.

DM-34090: Fix bitnami repo URL in times-square chart

---

services/times-square/Chart.yaml
services/times-square/charts/times-square/Chart.yaml
services/times-square/charts/times-square/templates/configmap.yaml
services/times-square/charts/times-square/values.yaml
services/times-square/values.yaml

Helm was not showing the redis deployment when it was a sub-sub-chart (via the time-square subchart). Moving redis up to the top-level as a normal sub-chart should resolve this problem.
It does mean that the redis URL now needs to be hard-coded, but this shouldn't be a difficulty since the redis deployment is fully under this Helm chart's control.

DM-34090: Move redis dependency to top-level chart

---

science-platform/templates/exposurelog-application.yaml
science-platform/templates/narrativelog-application.yaml
services/exposurelog/Chart.yaml
services/exposurelog/templates/deployment.yaml
services/exposurelog/values-base.yaml
services/exposurelog/values-roe.yaml
services/exposurelog/values-summit.yaml
services/exposurelog/values-tucson-teststand.yaml
services/exposurelog/values.yaml
services/narrativelog/Chart.yaml
services/narrativelog/templates/deployment.yaml
services/narrativelog/values-base.yaml
services/narrativelog/values-summit.yaml
services/narrativelog/values-tucson-teststand.yaml
services/narrativelog/values.yaml

Moving the charts from charts to this package broke value namespaces.
Rather than move the some of the names up a level, I put
application-specific values into namespace "config".
I also removed some values from values.yaml, replacing them with
comments, so that the site-specific file MUST override some values
in order for deployment to work. This is to avoid the current situation
where the service may run with incorrect default values.

DM-33922: exposurelog and narrativelog: fix value namespace

---

docs/service-guide/update-tap-schema.rst
services/tap-schema/Chart.yaml
services/tap-schema/README.md.gotmpl
services/tap-schema/templates/_helpers.tpl
services/tap-schema/templates/tap-schema-db-deployment.yaml
services/tap-schema/templates/tap-schema-db-service.yaml
services/tap-schema/templates/vault-secrets.yaml
services/tap-schema/values-idfdev.yaml
services/tap-schema/values-idfint.yaml
services/tap-schema/values-idfprod.yaml
services/tap-schema/values-int.yaml
services/tap-schema/values-minikube.yaml
services/tap-schema/values-red-five.yaml
services/tap-schema/values-roe.yaml
services/tap-schema/values-stable.yaml
services/tap-schema/values.yaml

Simplify the configuration and update the Helm resources to match
our current standards.  Update the documentation for how to push
out a new TAP schema.

[DM-34180] Move tap-schema chart into Phalanx

---

services/gafaelfawr/Chart.yaml
services/gafaelfawr/README.md
services/gafaelfawr/templates/configmap.yaml
services/gafaelfawr/templates/ingress-rewrite.yaml
services/gafaelfawr/templates/ingress.yaml
services/gafaelfawr/values-idfdev.yaml
services/gafaelfawr/values-minikube.yaml
services/gafaelfawr/values-squash-sandbox.yaml
services/gafaelfawr/values.yaml

- Remove the `key_ids` configuration
- Change configuration structure to reflect the new Gafaelfawr configuration
- Remove the ingress annotations configuration
- Update the version of Gafaelfawr to 4.0.0 but use a branch for IDF dev and minikube

[DM-34097] Update for Gafaelfawr 4.0.0

---

services/gafaelfawr/values-idfdev.yaml
services/gafaelfawr/values-minikube.yaml

The new release is out, so undo the image pinning used for testing.

[DM-34097] Use 4.0.0 of Gafaelfawr everywhere

---

science-platform/templates/mobu-application.yaml

This reverts commit 1abd97379dd2c72fb0b5c18ccb90822685ff3652.
Still not supported by Argo CD.

[DM-34199] Revert "Move the mobu application to a different namespace"

---

services/portal/templates/redis-deployment.yaml

This was accidentally dropped when moving the chart from
charts.

[DM-34285] Add pull-secret for Portal Redis

---

installer/generate_secrets.py

So the vocutouts thing had a keyerror exception when running it,
because postgres was generating it one way, and then we tried pulling
out the wrong key.  So that's the vo-cutouts fix.
Now that we have that working, add the sherlock generated secret
for publishing.

[DM-34317] Add sherlock secrets, fix vo-cutouts

---

services/semaphore/Chart.yaml
services/semaphore/README.md

This release supports the new broadcast message "category" field.
https://github.com/lsst-sqre/semaphore/releases/tag/0.3.0

DM-34437: Update Semaphore to 0.3.0

---

services/squareone/Chart.yaml

This release includes handling for info banners and auto refreshing of broadcast message data.

DM-34437: Update Squareone to 0.6.0

---

science-platform/templates/nublado2-application.yaml

nublado2 does automatic secret rotation, which means that it always
shows as out of date.  Configure Argo CD to ignore the secret changes
and the associated checksum changes on the deployment objects.

[DM-34385] Ignore nublado2 secret differences

---

.github/workflows/ci.yaml
science-platform/templates/vo-cutouts-application.yaml
services/vo-cutouts/Chart.yaml
services/vo-cutouts/README.md
services/vo-cutouts/README.md.gotmpl
services/vo-cutouts/templates/_helpers.tpl
services/vo-cutouts/templates/configmap.yaml
services/vo-cutouts/templates/db-worker-deployment.yaml
services/vo-cutouts/templates/db-worker-networkpolicy.yaml
services/vo-cutouts/templates/deployment.yaml
services/vo-cutouts/templates/ingress.yaml
services/vo-cutouts/templates/networkpolicy.yaml
services/vo-cutouts/templates/redis-networkpolicy.yaml
services/vo-cutouts/templates/redis-service.yml
services/vo-cutouts/templates/redis-statefulset.yaml
services/vo-cutouts/templates/service.yaml
services/vo-cutouts/templates/serviceaccount.yaml
services/vo-cutouts/templates/vault-secrets.yaml
services/vo-cutouts/templates/worker-deployment.yaml
services/vo-cutouts/templates/worker-networkpolicy.yaml
services/vo-cutouts/values-idfdev.yaml
services/vo-cutouts/values-idfint.yaml
services/vo-cutouts/values-idfprod.yaml
services/vo-cutouts/values.yaml

Move the chart from charts, add the global variable settings in
the Argo CD application configuration, and simplify the chart to
make use of them.  Update the version of the GCE Proxy to match
the other applications in Phalanx.

[DM-34385] Move the vo-cutouts chart into Phalanx

---

services/portal/templates/ingress.yaml
services/portal/values-idfdev.yaml
services/portal/values-idfint.yaml

- updates to suit version 2022.1
- _fixes_:  when firefly is proxied, we need to know where it’s proxied from

Added a new suit deployment, fixed the proxy in ingress.yaml

---

services/argocd/values-base.yaml
services/argocd/values-idfdev.yaml
services/argocd/values-idfint.yaml
services/argocd/values-idfprod.yaml
services/argocd/values-int.yaml
services/argocd/values-minikube.yaml
services/argocd/values-roe.yaml
services/argocd/values-stable.yaml
services/argocd/values-summit.yaml
services/argocd/values-tucson-teststand.yaml

This reverts commit bf3547642eef4ae976468ee53ce1e3a0b8bc1ae5.
This has now been fixed by a subsequent Argo CD chart release.

Revert "Fix Argo CD Redis metrics container"

---

docs/conf.py
docs/index.rst
docs/service-guide/linting-and-helm-docs.rst

This adds developer documentation corresponding to #1395. Draft: https://phalanx.lsst.io/v/DM-34595/service-guide/linting-and-helm-docs.html

DM-3495: Add docs for the pre-commit setup

---

installer/generate_secrets.py
services/gafaelfawr/Chart.yaml
services/gafaelfawr/README.md
services/gafaelfawr/README.md.gotmpl
services/gafaelfawr/templates/configmap.yaml
services/gafaelfawr/templates/deployment.yaml
services/gafaelfawr/templates/vault-secrets.yaml
services/gafaelfawr/values-idfdev.yaml
services/gafaelfawr/values-minikube.yaml
services/gafaelfawr/values.yaml

- Add configuration support for getting the UID from LDAP
- Add installer support for generic OpenID Connect
- Switch the Gafaelfawr image to GitHub Container Registry
- Add configuration support for Google Firestore
- Add configuration support for enrollment URLs
- Update Gafaelfawr to 4.1.0

[DM-34335] Update Gafaelfawr chart for 4.1.0 release

---

services/sasquatch/Chart.yaml
services/sasquatch/README.md
services/sasquatch/README.md.gotmpl
services/sasquatch/charts/kafka-connect-manager/Chart.yaml
services/sasquatch/charts/kafka-connect-manager/README.md
services/sasquatch/charts/kafka-connect-manager/README.md.gotmpl
services/sasquatch/charts/kafka-connect-manager/values.yaml
services/sasquatch/charts/strimzi-kafka/Chart.yaml
services/sasquatch/charts/strimzi-kafka/README.md
services/sasquatch/charts/strimzi-kafka/README.md.gotmpl
services/sasquatch/templates/vault-secret.yaml
services/sasquatch/values-tucson-teststand.yaml
services/sasquatch/values.yaml

This PR adds the Test CSC and the Kafka Producer charts from the T&S charts repository as dependencies. The goal is to have data being produced to test new deployments of sasquatch.
Both charts are deployed in the sasquatch namespace.
It assumes the secret to pulling images from `ts-dockerhub.lsst.org` is in Vault under the `pull-secret` key for the deployment environment, and it creates the k8s secret expected by the charts in the sasquatch namespace.

[DM-34430] Add test CSC and Kafka producer in sasquatch

---

services/sasquatch/charts/strimzi-kafka/templates/kafka.yaml
services/sasquatch/charts/strimzi-kafka/templates/tests/test-sasl-authentication.yaml
services/sasquatch/charts/strimzi-kafka/templates/ts-salkafka-user.yaml
services/sasquatch/templates/vault-secret.yaml

- Enable scram-sha-512 authentication for the plain listener used by clients inside the Kubernetes cluster
-  Add the `ts-salkafka` user with operations restricted to topics prefixed by `lsst.sal.*`
- The User Operator uses the `ts-salkafka` secret to set the password for the `ts-salkafka` user, that's needed otherwise the User Operator would set a random password and create the secret himself.
- Add a chart test for SASL authentication

[DM-34611] Secure access to Sasquatch kafka brokers

---

services/gafaelfawr/README.md
services/gafaelfawr/templates/configmap.yaml
services/gafaelfawr/values.yaml

This was previously supported in an earlier iteration of the chart
but was lost.  uidClaim is used at SLAC.  Allow these to be set
for the generic OIDC provider and plumb them through to the
ConfigMap.

Support usernameClaim and uidClaim in Gafaelfawr

---

helm-docs.md.gotmpl
science-platform/README.md
services/alert-stream-broker/README.md
services/cachemachine/README.md
services/cert-manager/README.md
services/exposurelog/README.md
services/gafaelfawr/README.md
services/mobu/README.md
services/narrativelog/README.md
services/noteburst/README.md
services/nublado2/README.md
services/portal/README.md
services/production-tools/README.md
services/sasquatch/README.md
services/sasquatch/charts/kafka-connect-manager/README.md
services/sasquatch/charts/strimzi-kafka/README.md
services/semaphore/README.md
services/squareone/README.md
services/tap-schema/README.md
services/telegraf-ds/README.md
services/telegraf/README.md
services/times-square/README.md
services/times-square/charts/times-square-ui/README.md
services/times-square/charts/times-square/README.md
services/vo-cutouts/README.md

We decided to take out the version badge in order to make it easier for version bumps from edit-on-GitHub workflows (i.e., bumping the version does not trigger a change in the README now).

Drop appVersionBadge from helm-docs template

---

services/portal/templates/ingress.yaml

See if this helps with our 504 issues after restarting the Portal.

Delete the Portal ingress cookie on failure

---

services/datalinker/Chart.yaml

Use the new datalinker released version that has the links endpoint.

[DM-34737] Datalinker 1.1.0 version

---

services/exposurelog/values-tucson-teststand.yaml

DM-34918: exposurelog: update tucson-teststand deployment

---

science-platform/templates/datalinker-application.yaml
science-platform/templates/vo-cutouts-application.yaml
science-platform/values-idfint.yaml
science-platform/values-idfprod.yaml
services/datalinker/README.md
services/datalinker/templates/deployment.yaml
services/datalinker/values.yaml
services/vo-cutouts/README.md
services/vo-cutouts/templates/configmap.yaml
services/vo-cutouts/templates/worker-deployment.yaml
services/vo-cutouts/values-idfdev.yaml
services/vo-cutouts/values-idfint.yaml
services/vo-cutouts/values-idfprod.yaml
services/vo-cutouts/values.yaml

Both vo-cutouts and datalinker need DAF_BUTLER_REPOSITORY_INDEX to
resolve Butler locations.  This is a per-site configuration that
should also eventually be injected into nublado2, so add it to the
deployment values file and inject it via Argo CD.  Adjust datalinker
and vo-cutouts charts accordingly, and set the environment variable
on the relevant deployments.
For vo-cutouts, we can now drop CUTOUT_BUTLER_REPOSITORY, since this
replaces that setting.

[DM-34998] Inject butlerRepositoryIndex

---

services/vo-cutouts/Chart.yaml
services/vo-cutouts/README.md
services/vo-cutouts/templates/db-worker-deployment.yaml
services/vo-cutouts/templates/deployment.yaml
services/vo-cutouts/templates/redis-statefulset.yaml
services/vo-cutouts/templates/vault-secrets.yaml
services/vo-cutouts/templates/worker-deployment.yaml
services/vo-cutouts/values.yaml

Update the version and pull from GitHub Container Registry instead
of Docker Hub.  Drop the pull-secret, since the only remaining image
we pull from Docker Hub is the first-party redis image, which
should be cached and shouldn't cause rate-limiting issues.

[DM-35058] Update vo-cutouts to 0.4.1

---

services/noteburst/values-minikube.yaml

It's possible that noteburst workers can't connect to JupyterLab pods in the minikube environment; setting the worker count to 0 should prevent them from deploying.

Drop noteburst workers from minikube env

---

science-platform/templates/hips-application.yaml
services/hips/Chart.yaml
services/hips/README.md
services/hips/values.yaml

Update the hips service for the new crawlspace release.  Stop
plumbing through vaultSecretsPath for that service, since it has
no secrets (it uses workload identity).

[DM-35029] Bump crawlspace version to 0.1.1

---

services/postgres/Chart.yaml
services/postgres/README.md
services/postgres/templates/deployment.yaml
services/postgres/values-int.yaml
services/postgres/values-roe.yaml
services/postgres/values-stable.yaml
services/postgres/values.yaml

At SLAC, the network connection with the in-cluster PostgreSQL
database is dropped after too long an idle period.  Enable TCP
keep-alive on the PostgreSQL server to prevent this.
This should be harmless everywhere, so do this unconditionally.

[DM-34859] Configure TCP keepalive for postgres

---

services/datalinker/templates/ingress.yaml

All annotations were suppressed if ingress.annotations wasn't set.

[DM-35182] Fix annotations for datalinker

---

services/datalinker/templates/ingress.yaml

The conditional for datalinker ingress annotations was eating too
much whitespace.

[DM-35182] Fix spacing on datalinker annotations

---

services/hips/templates/networkpolicy.yaml

Re-add the NetworkPolicy for the HiPS service, but make an exception
for the Portal so that it can use the internal cluster address.  It
doesn't yet know how to send authentication on HiPS requests.

[DM-35204] Reintroduce HiPS NetworkPolicy

---

services/datalinker/Chart.yaml
services/datalinker/README.md
services/datalinker/templates/ingress.yaml
services/datalinker/templates/service.yaml
services/datalinker/values-idfint.yaml
services/datalinker/values.yaml

Bump version to the latest release.  Require read:image scope for
datalinker access by default and remove the override for IDF int.
Change the pull policy to IfNotPresent to match our other services.
Remove the values.yaml configuration for service type and port,
since we never change those.

[DM-35182] Update datalinker to 1.3.0

---

services/portal/templates/deployment.yaml

The new version of Portal (2022.3 and later) will require setting
individual environment variables instead of FIREFLY_OPTS.  Set
the new variables now so that we can easily move back and forth
between versions solely by changing the image pin.

[DM-35204] Set environment variables required for new Portal

---

services/noteburst/Chart.yaml
services/noteburst/README.md
services/noteburst/templates/worker-configmap.yaml
services/noteburst/templates/worker-deployment.yaml
services/noteburst/values-idfdev.yaml
services/noteburst/values.yaml
services/times-square/templates/worker-deployment.yaml

New configurations for noteburst workers:
- `NOTEBURST_WORKER_TOKEN_LIFETIME`
- `NOTEBURST_WORKER_IMAGE_SELECTOR`
- `NOTEBURST_WORKER_IMAGE_REFERENCE`

DM-35203: Add image noteburst image selection configs

---

services/tap/Chart.yaml
services/tap/templates/tap-deployment.yaml

This will check the availability endpoint every 10 seconds and
restart the pod if it fails.  This should help with our out of
memory issues.  It might supriously restart the pod though, so
we have to make sure it doesn't hit false positives too often.

[DM-35242] Add liveness check

---

services/sasquatch/README.md
services/sasquatch/values.yaml

- We are seeing "ClientPayloadError: Response payload is not completed"  and long async queries being killed. Try to get around that by increasing the write timeout in the query coordinator.

Increase write timeout in the query coordinator

---

services/times-square/Chart.yaml

This adds initial GitHub Checks API support to Times Square.

Deploy DM-35149 version of times-square

---

services/squareone/Chart.yaml

This update to Squareone includes documentation link updates for DP0.2.

DM-35317: Deploy squareone 0.7.1

---

services/noteburst/Chart.yaml

This update to noteburst adds the enable_retry option to noteburst's nbexec function.

DM-35328: Deploy noteburst 0.5.0

---

services/times-square/Chart.yaml

This update adds GitHub checks for notebooks.

DM-35150: Deploy Times Square 0.5.0

---

services/portal/templates/ingress-admin.yaml

The URL pattern is different so we were accidentally dropping the
/admin component of the path.

[DM-35495] Fix Portal admin ingress rewrite

---

services/portal/values-idfdev.yaml
services/portal/values-idfint.yaml

Switch to the same version as data-dev.  Also switch data-dev to
the DP0.2 HiPS service.

[DM-35495] Bump version of Portal on data-int

---

services/sasquatch/values-idfdev.yaml
services/sasquatch/values-summit.yaml
services/sasquatch/values-tucson-teststand.yaml

- JSON feeds for sasquatch are now served from the rsp_broadcast repo.

[DM-35575] Update Sasquatch news feed URLs

---

science-platform/values-tucson-teststand.yaml

- Now that Sasquatch is running at TTS we can tear down the old EFD deployment and deploy telegraf and telegraf-ds as part of the monitoring infrastructure.

Enable telegraf and telegraf-ds at TTS

---

services/gafaelfawr/README.md
services/gafaelfawr/templates/configmap.yaml
services/gafaelfawr/values-idfdev.yaml
services/gafaelfawr/values.yaml

COmanage needed some different LDAP configuration and to change
the username claim attribute in the OpenID Connect token.  Also
suppress the uid_attr config parameter if none is set to avoid
sending the empty string.

[DM-34613] Fix LDAP configuration for IDF dev

---

services/gafaelfawr/README.md
services/gafaelfawr/templates/configmap.yaml
services/gafaelfawr/values-idfdev.yaml
services/gafaelfawr/values-minikube.yaml
services/gafaelfawr/values.yaml

- Drop support for looking up usernames in LDAP
- Fix enrollment URL configuration for OpenID Connect
- Fix CILogon enrollment URL when test CILogon is enabled
- Switch to Gafaelfawr 5.0.0 on IDF dev and minikube

[DM-34613] Gafaelfawr Phalanx configuration cleanup

---

services/mobu/values-idfint.yaml

We need to figure out the problems with the 8 hour timeouts that we're
seeing before any more meaningful results can be figured out.

[DM-35717] Ceasefire on int

---

services/sasquatch/charts/strimzi-kafka/templates/kafka.yaml

Configure an external listener of type loadbalancer with tls encryption and scram-sha-512 authentication used by clients outside the Kubernetes cluster.

[DM-35764] Configure external listener for sasquath kafka brokers

---

services/strimzi/values-idfdev.yaml
services/strimzi/values-idfint.yaml
services/strimzi/values-summit.yaml
services/strimzi/values-tucson-teststand.yaml

It was crashing on the Tucson teststand at 384MiB with out of
memory errors.  Bump it to 512MiB everywhere.

Bump memory limits for strimzi-cluster-operator

---

services/datalinker/Chart.yaml
services/datalinker/README.md
services/datalinker/templates/deployment.yaml
services/datalinker/templates/gafaelfawr-token.yaml
services/datalinker/templates/ingress-anonymous.yaml
services/datalinker/templates/ingress.yaml
services/datalinker/values-idfint.yaml
services/datalinker/values.yaml
services/hips/templates/ingress.yaml

datalinker will be the service that dynamically generates the HiPS
list based on the properties files of the HiPS data sets for a given
Science Platform deployment.

[DM-35482] Serve /api/hips/list from datalinker

---

services/sasquatch/charts/strimzi-kafka/templates/kafka.yaml

In Strimzi operator 0.30.0 Kafka `PersistenVolumeClaim` resources show up as `OutOfSync (requires prune)` in Argo CD, affecting the overall app sync status. 
Strimzi provides a mechanism for [customizing k8s resources](https://strimzi.io/docs/operators/latest/configuring.html#assembly-customizing-kubernetes-resources-str).  Use that to add annotations to [exclude the PVCs from the app sync status](https://argo-cd.readthedocs.io/en/stable/user-guide/compare-options/#ignoring-resources-that-are-extraneous) and to [prevent them from being pruned](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#no-prune-resources).

[DM-35849] Exclude Kafka PVCs from the app sync status

---

services/datalinker/values-idfint.yaml
services/portal/templates/deployment.yaml

Use the in-deployment HiPS list served by datalinker.  Also delete
the old FIREFLY_OPTS setting, which is no longer used by current
Firefly.

[DM-35482] Point Portal at new HiPS list

---

services/argocd/Chart.yaml
services/argocd/README.md

The new version doesn't show the restart menu option. Revert for now until
it's fixed upstream.

Revert Argo CD update that introduced a bug

---

installer/generate_secrets.py
services/gafaelfawr/README.md
services/gafaelfawr/templates/configmap.yaml
services/gafaelfawr/values-idfdev.yaml
services/gafaelfawr/values.yaml

Add support for a general RSP alerts Slack webhook secret, and
configuration for Gafaelfawr to use it via its secret.  Currently
this is only used to report uncaught exceptions.

[DM-35872] Add Gafaelfawr config for Slack webhook

---

services/sasquatch/charts/strimzi-kafka/README.md
services/sasquatch/charts/strimzi-kafka/templates/certificates.yaml
services/sasquatch/charts/strimzi-kafka/templates/kafka.yaml
services/sasquatch/charts/strimzi-kafka/values.yaml
services/sasquatch/values-idfdev.yaml

- If TLS is enabled use cert-manager to issue certificates for the external listener.
- Support annotations added to the Ingress, Route, or Service resource.
- Add configuration for Sasquatch on idfdev

[DM-35764] Add external listener configuration

---

services/mobu/Chart.yaml
services/mobu/values-idfint.yaml
services/mobu/values-idfprod.yaml
services/mobu/values-roe.yaml

Set explicit primary GID numbers for test users on deployments with
mobu enabled and using GitHub for identity.

[DM-35881] Update mobu to 4.5.0

---

installer/install.sh
science-platform/templates/argocd-application.yaml
services/argocd/README.md
services/argocd/templates/vault-secrets.yaml
services/argocd/values-base.yaml
services/argocd/values-idfdev.yaml
services/argocd/values-idfint.yaml
services/argocd/values-idfprod.yaml
services/argocd/values-minikube.yaml
services/argocd/values-roe.yaml
services/argocd/values-summit.yaml
services/argocd/values-tucson-teststand.yaml
services/argocd/values.yaml

Inject the Vault secrets path like we do for other applications,
and modify the installer to also inject it (and correctly pass in
both values.yaml files; I'm not sure how it was working before).
Install the Vault secret unconditionally, since it was enabled for
every environment, and remove the configuration from the individual
values files.

[DM-35977] Improve Argo CD application configuration

---

services/gafaelfawr/values-base.yaml
services/gafaelfawr/values-summit.yaml
services/gafaelfawr/values-tucson-teststand.yaml

I didn't add these when the scope was added for the cutout service,
since it wasn't clear we would have images in the same sense on T&S
deployments, but now the Portal requests this scope, which means users
have to have it when using the Portal to do image display.  It's
simpler to just grant the scope to the same groups as have exec:portal
access than try to change the scope requirements in those environments.
This matches what we did with read:tap, which also isn't directly in
use there.

[DM-35977] Add read:image scopes to T&S deployments

---

science-platform/templates/noteburst-application.yaml
science-platform/templates/tap-schema-application.yaml
services/ingress-nginx/README.md
services/ingress-nginx/templates/vault-secrets.yaml
services/ingress-nginx/values-minikube.yaml
services/ingress-nginx/values-roe.yaml
services/ingress-nginx/values.yaml
services/noteburst/README.md
services/noteburst/values.yaml
services/postgres/README.md
services/postgres/values.yaml
services/tap-schema/README.md
services/tap-schema/values.yaml

Remove Argo CD injected Helm variables that aren't used, and
document the ones that are used.  Rename the vault_certificate
setting for ingress-nginx to vaultCertificate, following the naming
rules for Helm chart parameters.
This leaves some unused injected variables for semaphore on the
grounds that they may be used in the future.

[DM-35977] Clean up unused injected variables

---

services/gafaelfawr/README.md
services/gafaelfawr/templates/cloudsql-deployment.yaml
services/gafaelfawr/templates/cloudsql-networkpolicy.yaml
services/gafaelfawr/templates/cloudsql-service.yaml
services/gafaelfawr/templates/configmap.yaml
services/gafaelfawr/templates/cronjob-maintenance.yaml
services/gafaelfawr/templates/deployment-tokens.yaml
services/gafaelfawr/templates/deployment.yaml
services/gafaelfawr/values-idfdev.yaml
services/gafaelfawr/values-idfint.yaml
services/gafaelfawr/values-idfprod.yaml
services/gafaelfawr/values-summit.yaml
services/gafaelfawr/values-tucson-teststand.yaml
services/gafaelfawr/values.yaml

Using a Cloud SQL Proxy sidecar for CronJob resources is very
annoying, since one has to coordinate stopping the Cloud SQL Proxy
server so that the CronJob can exit, which in turn requires a bunch
of opaque shell gunk.
Since we're about to add another CronJob, add a separate Cloud SQL
Proxy service that can be used by all the non-critical, low-volume
services (the Kubernetes operator and the CronJobs to start).
Continue to use the sidecar for the main Gafaelfawr pods so that
the proxy will scale with the pods and the critical Gafaelfawr
service doesn't have a single point of failure.
Add a NetworkPolicy to keep anything else in the cluster from talking
to the Cloud SQL Proxy pod.  This will only work at Google, but this
service is only used at Google, so that should be sufficient.
This …

[DM-35959] Use separate Cloud SQL Proxy pod

---

services/tap/templates/mock-qserv-deployment.yaml
services/tap/templates/tap-deployment.yaml
services/tap/templates/uws-db-deployment.yaml

I stopped installing it but forgot to clean up the references in
the deployments.

[DM-35982] Delete references to pull-secret in TAP

---

services/gafaelfawr/Chart.yaml
services/gafaelfawr/README.md
services/gafaelfawr/templates/configmap.yaml
services/gafaelfawr/templates/cronjob-audit.yaml
services/gafaelfawr/values.yaml

- Add periodic audit cron job that reports issues to Slack
- Add new configuration options to specify the claims from which to get GID and groups
- The schedule of the maintenance cron job can now be specified in the Helm chart

[DM-35959] Updates for Gafaelfawr 5.2.0

---

services/nublado2/Chart.yaml
services/nublado2/README.md
services/nublado2/values.yaml

- Update to latest nublado2 release
- Expose the user's primary GID in `EXTERNAL_GID` parallel to `EXTERNAL_UID`
- Drop the provisionator user and group, which I believe are no longer used
- Don't add the user as an additional member of the group matching their primary GID, following normal UNIX semantics
- Set the user's GID correctly if it differs from their UID

[DM-36093] Update nublado2 templates for latest Gafaelfawr

---

services/gafaelfawr/values-idfdev.yaml

The LDAP DNs and enrollment URL have changed for the renaming of the environment to id-dev.lsst.cloud.

[DM-35698] Update Gafaelfawr configuration for IDF dev

---

installer/generate_secrets.py

**Description:**
Small typo in generate_secrets script, causes script to fail when trying to regenerate secrets for (roe) environment.
**Fix:**
Change gaelfawr -> gafaelfawr

Fix typo in generate_secrets script

---

services/gafaelfawr/templates/cloudsql-networkpolicy.yaml
services/gafaelfawr/templates/cronjob-audit.yaml
services/gafaelfawr/templates/redis-networkpolicy.yaml
services/gafaelfawr/values-base.yaml
services/gafaelfawr/values-idfint.yaml
services/gafaelfawr/values-idfprod.yaml
services/gafaelfawr/values-summit.yaml
services/gafaelfawr/values-tucson-teststand.yaml

Suppress the audit CronJob if Slack alerts are not enabled, since it will just fail anyway.  Enable Slack alerts for most environments now that Slack webhook secrets are in place.  Add the audit CronJob to the NetworkPolicy for CloudSQL and Redis.

[DM-36152] Fix several issues with Gafaelfawr audits

---

installer/generate_secrets.py

The way that this was checked for would fail if it wasn't set due to missing dicts.  Use the _get_current method instead, since that's what it was intended for.

[DM-36152] Fix optionality of slack-webhook secret

---

services/mobu/values-idfprod.yaml

DP0.2 is out so we should be checking this data set, even though we're currently getting errors.

Enable DP0.2 TAP queries on IDF prod

---

services/tap-schema/values-idfdev.yaml

This has been rolled into the regular tap-schema release process, so it should float with the current appVersion like the other environments.

Stop pinning tap-schema on IDF dev

---

services/nublado2/README.md
services/nublado2/values-base.yaml
services/nublado2/values-ccin2p3.yaml
services/nublado2/values-idfdev.yaml
services/nublado2/values-idfint.yaml
services/nublado2/values-idfprod.yaml
services/nublado2/values-minikube.yaml
services/nublado2/values-roe.yaml
services/nublado2/values-summit.yaml
services/nublado2/values-tucson-teststand.yaml
services/nublado2/values.yaml

We no longer support PAM, sudo, or privilege escalation in labs, so nothing should be reading these files.  Simplify the config by removing the generated ConfigMaps and mounts.
Also delete obsolete settings for vault_secrets_path and pull-secret, which were migrated to use the injected global path.
The sciplat-lab build already deletes /etc/shadow and /etc/gshadow, so with this change those files simply won't exist.

DM-36302: Delete /etc/shadow and /etc/gshadow for labs

---

services/datalinker/README.md
services/datalinker/templates/ingress-image.yaml
services/datalinker/templates/ingress-tap.yaml
services/datalinker/values.yaml

datalinker was using read:image for access control to all of its non-public routes, but all the routes except /api/datalink/links are TAP query helpers.  Require read:tap for those and read:image only for /api/datalink/links.  Remove the conditionals and values.yaml configuration for scopes and hard-code them, as we do for other complex configurations.
Also remove the auth-url setting, since we expect datalinker links to mostly be followed by scripts and the Portal Aspect, for which redirects to a login page are not useful.

DM-36321: Fix authorization for datalinker

---

services/gafaelfawr/Chart.yaml
services/gafaelfawr/README.md
services/gafaelfawr/templates/configmap.yaml
services/gafaelfawr/templates/ingress.yaml
services/gafaelfawr/values.yaml
services/sasquatch/values-idfdev.yaml
services/sasquatch/values-idfint.yaml
services/sasquatch/values-summit.yaml
services/sasquatch/values-tucson-teststand.yaml
services/tap/templates/tap-ingress-authenticated.yaml

- Update version of Gafaelfawr
- Drop support for changing the redirect URL with CILogon or OIDC
- Fix userinfo URL for OpenID Connect integration with Sasquatch
- Drop support for InfluxDB 1.x token generation
- Stop requesting the UID in headers for TAP (which didn't use it)

DM-36247: Update Gafaelfawr configuration for 6.0.0

---

services/sasquatch/Chart.yaml
services/sasquatch/README.md
services/sasquatch/charts/strimzi-kafka/templates/users.yaml
services/sasquatch/charts/telegraf-kafka-consumer/Chart.yaml
services/sasquatch/charts/telegraf-kafka-consumer/README.md
services/sasquatch/charts/telegraf-kafka-consumer/templates/configmap.yaml
services/sasquatch/charts/telegraf-kafka-consumer/templates/deployment.yaml
services/sasquatch/charts/telegraf-kafka-consumer/values.yaml
services/sasquatch/values-idfdev.yaml
services/sasquatch/values-tucson-teststand.yaml
services/sasquatch/values.yaml

- Add a subchart to deploy a list of Telegraf Kafka consumer agents to consumer Kafka topics and write them to InfluxDB
- Enable the Telegraf Kafka consumers and deploy on TTS to compare performance with the Lenses InfluxDB Sink Kafka connector.

[DM-36233] Evaluate Telegraf as replacement for the InlfuxDB Sink connector in Sasquatch

---

services/nublado2/values-summit.yaml

Enable automatic upgrade of the JupyterHub database at the summit for the JupyterHub 3.0 migration.

Upgrade JupyterHub database at summit

---

services/argocd/Chart.yaml
services/argocd/README.md

This reverts commit 1c9af4c6780469cee33ac7e87aa905b8dbf57bf8. This release of Argo CD has a buggy version of Dax that breaks Google authentication.  Hopefully the next release will import the version of Dax with a fix.

Revert "Update Helm release argo-cd to v5.5.16"

---

.github/workflows/ci.yaml
.github/workflows/docs.yaml
.gitignore
LICENSE
Makefile
docs/Makefile
docs/_rst_epilog.rst
docs/about/contributing-docs.rst
docs/about/repository.rst
docs/admin/bootstrapping.rst
docs/admin/update-pull-secret.rst
docs/developers/add-application.rst
docs/requirements.txt
pyproject.toml
src/phalanx/__init__.py
src/phalanx/testing/expandcharts.py
tests/packaging_test.py
tests/requirements.txt
tox.ini

This PR adds a standard Python package to phalanx for the purpose of hosting Python infrastructure for testing, developing, and generating documentation.
Since there is now Python package infrastructure, the docs are now built with tox. The `expand-services` script is also moved into the Python package and installed as an entrypoint along with its GitPython dependency.

DM-36585: Add a Python package to Phalanx

---

services/nublado2/Chart.yaml
services/nublado2/README.md
services/nublado2/values.yaml

Pick up fix for the communication to moneypenny when some groups do not have GIDs.

DM-36624: Bump version of nublado2 to 2.6.1

---

science-platform/templates/sasquatch-application.yaml
services/sasquatch/README.md
services/sasquatch/charts/strimzi-kafka/templates/bridge.yaml
services/sasquatch/values.yaml

- Add Kafka bridge, a REST interface that allows clients to interact with Kafka.
- Enable TLS authentication
- Reach the kafka bridge at <host>/sasquatch-bridge

[DM-36684] Add Kafka bridge to Sasquatch

---

docs/applications/_summary.rst.jinja
docs/developers/chart-overview.rst
services/noteburst/Chart.yaml
services/semaphore/Chart.yaml
services/times-square/Chart.yaml
services/times-square/README.md
src/phalanx/docs/models.py

This adds support for including links to technotes (and other Rubin documents) in a Phalanx app's Chart.yaml file, and including that information on the app's summary table in the Phalanx docs. This feature makes use of the ``annotations`` field in Helm. Annotations are key-value pairs. The key for this feature is `phalanx.lsst.io/docs` and the value is a YAML-formatted string:
```yaml
annotations:
phalanx.lsst.io/docs: |
- id: "SQR-065"
title: "Design of Noteburst, a programatic JupyterLab notebook execution service for the Rubin Science Platform"
url: "https://sqr-065.lsst.io/"
- id: "SQR-062"
title: "The Times Square service for publishing parameterized Jupyter Notebooks in the Rubin Science platform"
url: "https://sqr-062.lsst.io/"
```
Example of the result in the docs: …

DM-36805: Add phalanx.lsst.io/docs annotation support in Chart.yaml

---

.github/workflows/docs.yaml
services/datalinker/Chart.yaml
services/gafaelfawr/Chart.yaml
services/hips/Chart.yaml
services/moneypenny/Chart.yaml
services/nublado2/Chart.yaml
services/sasquatch/Chart.yaml
services/telegraf-ds/Chart.yaml
services/telegraf/Chart.yaml
services/vo-cutouts/Chart.yaml

For services that have associated tech notes, add the references using the new annotation syntax.
Rebuild the documentation if `Chart.yaml` or `values.yaml` for any of the services change, since we pull from those files to generate the application documentation.

DM-36809: Add tech note references to services

---

docs/applications/cachemachine/gar.rst

Fix a stray Markdown link in the GAR documentation.

DM-36809: Fix stray Markdown link

---

services/sasquatch/Chart.yaml
services/sasquatch/templates/bucketmapper.yaml

These components only make sense in environments where influxdb2 is deployed, so make the environments cleaner while transitioning from influxdb to influxdb2.

Deploy bucketmapper and telegraf-kafka-consumer only if influxdb2 is enabled

---

services/cachemachine/values-summit.yaml

FYI, this cannot be pushed to the summit until Thursday after the deployment is completed. 
⚠️  This PR needs to remain unmerged until the appropriate time. I will do the merge when it is time to sync.

Update nublado summit deployment to cycle 27.

---

services/ingress-nginx/values-roe.yaml
services/moneypenny/values-roe.yaml
services/nublado2/values-roe.yaml
services/tap-schema/values-roe.yaml
services/tap/values-roe.yaml

Upgrades include:
- Change Ingress to add an affinity rule & fix a few other params (externalTrafficPolicy, hostNetwork etc..)
- Add Mounts for NFS shares
- Enable Qserv in TAP
- Change TAP_SCHEMA to use a custom image that includes additional databases

Upgrades to ROE environment

---

docs/developers/add-application.rst
docs/developers/local-development.rst
starters/web-service/README.md
starters/web-service/templates/ingress.yaml
starters/web-service/values.yaml

Update the developer documentation and web-service starter to use GafaelfawrIngress instead of a regular Ingress, and move more things into the template and out of values.yaml, following the pattern used with newer services where we try to avoid configuration for things that should never change.

DM-28493: Update Gafaelfawr documentation and starter

---

services/noteburst/README.md
services/noteburst/templates/ingress.yaml
services/noteburst/values.yaml
services/times-square/README.md
services/times-square/templates/ingress-webhooks.yaml
services/times-square/templates/ingress.yaml
services/times-square/values.yaml

Noteburst and times-square were using the ingress path configuraiton in values.yaml. Restore it back to the way they were.

DM-37226: Fix noteburst and times-square ingress paths

---

services/noteburst/templates/ingress.yaml
services/times-square/templates/networkpolicy.yaml

There's no longer an option to not install the ingress, so the conditional has to be removed for the NetworkPolicy.

DM-37226: Make times-square NetworkPolicy unconditional

---

services/plot-navigator/templates/ingress.yaml
services/production-tools/templates/ingress.yaml
services/vo-cutouts/templates/ingress.yaml

This setting isn't used with GafaelfawrIngress.

DM-37226: Remove stray ingressClassName from plot-navigator

---

services/mobu/values-idfdev.yaml
services/tap/values-idfdev.yaml
services/tap/values-idfint.yaml

Turn on mobu TAP queries for data-dev, and up the debug level for data-dev and data-int by using release 1.4.1

[DM-37254] Turn on mobu on data-dev, up debug level

---

services/tap/values-idfdev.yaml

We're running queries from mobu now, and it has restarted about 2 dozen times over night, and I think that is due to the restrictive default resource limits.  Let's make them the same as int since we're expecting what they are expecting, but keep the replica count at 1.

[DM-37254] Add resources for data-dev tap

---

services/tap/values-idfdev.yaml

I set the resource limits for the container, but I forgot to tell java how much memory it can take, so it wasn't expanding the heap.

[DM-37254] Set java heap space correctly

---

services/mobu/values-idfint.yaml

This should at least let us know if we get errors running the old queries, or is it just the new queries?

[DM-27254] Switch mobu -int back to dp0.1

---

services/mobu/values-idfint.yaml

If we're doing async queries, that might get around this connection reset, if the connection reset is between mobu and TAP.  If it is somehow related to qserv, then the problem should persist.

[DM-37254] Go back to dp0.2, but try async

---

services/cachemachine/README.md
services/cachemachine/templates/ingress-anonymous.yaml
services/cachemachine/templates/ingress.yaml
services/cachemachine/values.yaml
services/semaphore/templates/ingress.yaml
services/squareone/templates/ingress.yaml
services/tap/templates/tap-ingress-anonymous.yaml
services/times-square/templates/ingress-webhooks.yaml

Make use of the new anonymous ingress support and convert all remaining Ingress objects in Phalanx to GafaelfawrIngress. This doesn't change the ingresses installed by third-party charts.

DM-37476: Convert remaining Ingress objects to GafaelfawrIngress

---

services/noteburst/Chart.yaml
services/noteburst/README.md
services/noteburst/templates/configmap.yaml
services/noteburst/templates/deployment.yaml
services/noteburst/templates/worker-configmap.yaml
services/noteburst/templates/worker-deployment.yaml
services/noteburst/values-idfdev.yaml
services/noteburst/values.yaml
services/times-square/Chart.yaml
services/times-square/README.md
services/times-square/templates/deployment.yaml
services/times-square/templates/worker-deployment.yaml
services/times-square/values-idfdev.yaml
services/times-square/values.yaml

Use the new internal Redis chart that only creates a single instance, since in practice we were only using the master created by the Bitnami chart.  Use SSD storage for Redis on IDF dev.
Although authentication was enabled in values.yaml for noteburst, Redis authentication was not actually in use so far as I could determine, so do not configure authentication and rely on the NetworkPolicy to control access.  (Ideally we should add a secret, but we can tackle this later after we simplify secret management.)

DM-37390: Convert noteburst and times-square to new Redis chart

---

.github/workflows/ci.yaml
services/gafaelfawr/Chart.yaml
services/ingress-nginx/README.md
services/ingress-nginx/values.yaml
services/nublado2/README.md
services/nublado2/values.yaml

The NGINX support for an auth_request subhandler is very limited. It only allows 401 and 403 returns, and doesn't even include the WWW-Authenticate header on 403 replies.  We want to use it to do many more things, so we need to add some custom configuration.
Use server-snippet to add an autherror block to every server in the NGINX configuration.  This will be used as the target for an error_page directive introduced by Gafaelfawr and will read the actual status and error body out of headers.  It will also always set Cache-Control and WWW-Authenticate.
As is, this block won't be used by anything.  The other half of this change will introduced Ingress annotations that will use the block for Ingresses that are Gafaelfawr-protected.

DM-37480: Add autherror location to each NGINX server

---

services/gafaelfawr/values-base.yaml
services/gafaelfawr/values-ccin2p3.yaml
services/gafaelfawr/values-idfdev.yaml
services/gafaelfawr/values-idfint.yaml
services/gafaelfawr/values-idfprod.yaml
services/gafaelfawr/values-minikube.yaml
services/gafaelfawr/values-roe.yaml
services/gafaelfawr/values-summit.yaml
services/gafaelfawr/values-tucson-teststand.yaml
services/gafaelfawr/values.yaml

- Simplify the group mappings on data-dev and data-int to not duplicate all-user access
- Rename groups on data-dev to match the other environments
- Add the `exec:internal-tools` scope

DM-37583: Update Gafaelfawr group mappings

---

services/ingress-nginx/README.md
services/ingress-nginx/values-base.yaml
services/ingress-nginx/values-ccin2p3.yaml
services/ingress-nginx/values-idfint.yaml
services/ingress-nginx/values-idfprod.yaml
services/ingress-nginx/values-roe.yaml
services/ingress-nginx/values-summit.yaml
services/ingress-nginx/values-tucson-teststand.yaml
services/ingress-nginx/values.yaml

Move the header buffer changes out of values.yaml into the per-environment values files and leave them off of IDF dev and minikube so that we can test whether they're needed.
Clean up some duplicated settings in the values files for ccin2p3 and roe.

DM-37588: Drop NGINX header buffer changes on minikube, IDF dev

---

services/linters/Chart.yaml
services/linters/templates/cronjob-dns-linter.yaml

Since now the vault secret also has the slack webhook, I got rid of the aws part there

[DM-26505] Linter version to 0.1.5

---

services/alert-stream-broker/README.md
services/alert-stream-broker/charts/alert-database/Chart.yaml
services/alert-stream-broker/charts/alert-stream-broker/Chart.yaml
services/alert-stream-broker/charts/alert-stream-broker/README.md
services/alert-stream-broker/charts/alert-stream-broker/values.yaml
services/alert-stream-broker/charts/alert-stream-schema-registry/Chart.yaml
services/alert-stream-broker/charts/alert-stream-simulator/Chart.yaml
services/alert-stream-broker/charts/alert-stream-simulator/README.md
services/alert-stream-broker/charts/alert-stream-simulator/values.yaml
services/alert-stream-broker/values-idfint.yaml
services/alert-stream-broker/values.yaml

Add TLS auth
Added static broker IPs
Reduce kafka retention
Static broker IPs are needed to access the alert-broker from the outside, otherwise every time Kafka is restarted a new is is assigned and the SSL certificates no longer get validated. TLS auth is also needed for the brokers to be able to talk with users.  cluserNamespace is was updated for the strimzi-registry to properly build. Reduced the topic level retention for alert-stream-simulator to 24 GB to prevent the current storage from filling up.

Update IP and add tls in values-idfint.yaml + add clusterNamespace

---

src/phalanx/docs/models.py

It was a practice in the environment values.yaml files to use `_` in place of `-` in app names. e.g.
```yaml
times_square:
enabled: true
```
Instead of using the actual app name:
```yaml
times-square:
enabled: true
```
This change handles that situation so that many missing apps with `-` in their names but that use `_` in the environment values.yaml files now appear in documentation homepages for environments..

DM-37659: Handle apps with names that have _ in values

---

science-platform/values-idfdev.yaml

Allow Butler applications such as vo-cutouts to be deployed on IDF dev using the same Butler as IDF int.

DM-37589: Add Butler configuration for IDF dev

---

docs/admin/bootstrapping.rst
docs/developers/add-a-onepassword-secret.rst
installer/generate_secrets.py
installer/requirements.txt
installer/update_secrets.sh
installer/vault_key.py

Rather than using third-party onepassword Python API, which is not pip-installable and doesn't work on all platforms, use the 1Password Connect API against the new server that we're installing on Roundtable.

DM-37221: Convert to 1Password Connect API

---

installer/generate_secrets.py

Ignore 1Password items with no generate_secrets_key field, since there are several that are used for other purposes.  Warn about items with a generate_secrets_key but no value.

DM-37721: Fix some secret generation bugs

---

applications/telegraf/templates/configmap.yaml

Apps are now named with dashes, not underscores, which requires a fix to the ConfigMap logic for telegraf.

Fix telegraf config for app renaming

---

applications/sasquatch/charts/rest-proxy/README.md
applications/sasquatch/charts/rest-proxy/templates/user.yaml
applications/sasquatch/charts/rest-proxy/values.yaml
applications/sasquatch/values-idfdev.yaml
applications/sasquatch/values-summit.yaml
applications/sasquatch/values-tucson-teststand.yaml

- Use PatternType prefix when associating topics with the rest-proxy user
- Topics created via Strimzi KafaTopic resource or via the REST Proxy v3 API that match that prefix are associated to the rest-proxy user
- Fix the configuration in the environments where the REST Proxy is enabled.

Allow for topic prefixes in REST proxy config

---

.github/workflows/ci.yaml
applications/gafaelfawr/values-minikube.yaml
applications/ingress-nginx/README.md
applications/ingress-nginx/values.yaml
applications/nublado2/values-minikube.yaml
environments/values-minikube.yaml
installer/install.sh

Work around the fact that nothing sets $auth_status as a variable until Gafaelfawr runs and creates its first ingress.  The NGINX documentation seems to indicate that you can set the same variable multiple times, so ensure that $auth_status always has a value, which will be overridden by the custom configuration snippets in the locations that Gafaelfawr is protecting.

DM-37944: Fix bootstrapping of ingress-nginx

---

applications/argocd/values-roundtable-dev.yaml
applications/argocd/values-roundtable-prod.yaml
applications/cert-manager/values-roundtable-dev.yaml
applications/cert-manager/values-roundtable-prod.yaml
applications/gafaelfawr/values-roundtable-dev.yaml
applications/gafaelfawr/values-roundtable-prod.yaml
applications/ingress-nginx/values-roundtable-dev.yaml
applications/ingress-nginx/values-roundtable-prod.yaml
applications/squareone/values-roundtable-dev.yaml
applications/squareone/values-roundtable-prod.yaml
docs/environments/index.rst
docs/environments/roundtable-dev/index.rst
docs/environments/roundtable-prod/index.rst
environments/values-roundtable-dev.yaml
environments/values-roundtable-prod.yaml
installer/update_all_secrets.sh

- Adds roundtable-prod and roundtable-dev values to science-platform/
- Adds service values files for the initial services:
- argocd
- cert-manager
- gafaelfawr
- ingress-nginx
- squareone (to have a landing page, initially)
- vault-secrets-operator
- Documentation homepages for roundtable-prod and roundtable-dev
The ingress-nginx snippet exclusion was needed to prevent a bootstrap sequence issue between ingress-nginx and gafaelfawr.

Add roundtable-prod and roundtable-dev

---

applications/portal/Chart.yaml
applications/portal/values-idfdev.yaml
applications/portal/values-idfint.yaml

Bump the Portal version to the version that had been pinned on IDF dev and IDF int.

Bump Portal version on other environments

---

applications/sasquatch/values-idfint.yaml

Topics prefixed by `lsst.dm` correspond to analysis_tools metrics and are managed by the REST proxy v3 API.

Replicate topics prefixed by lsst.dm

---

applications/noteburst/Chart.yaml
applications/noteburst/templates/gafaelfawrtoken.yaml
applications/noteburst/values-idfdev.yaml

This noteburst update (will be 0.6.0) provides support for JupyterLab Controller.

DM-37857: Update noteburst 0.6.0

---

applications/nublado2/values.yaml

We're seeing a lot of web socket closed errors on data.lsst.cloud that may be ingress-nginx timeouts on cells that take a long time to run. Try increasing the proxy timeout to five minutes.

DM-38103: Increase timeout on nublado ingress

---

applications/gafaelfawr/templates/cloudsql-deployment.yaml
applications/gafaelfawr/templates/deployment.yaml
applications/times-square/templates/deployment.yaml
applications/times-square/templates/worker-deployment.yaml
applications/vo-cutouts/templates/db-worker-deployment.yaml
applications/vo-cutouts/templates/deployment.yaml

Add flags to Cloud SQL Auth Proxy to use structured logging and send info/debug messages to standard output rather than standard error. This should prevent Google from misclassifying them as errors.

DM-38154: Use structured logging for Cloud SQL Auth Proxy

---

applications/squareone/Chart.yaml
applications/squareone/README.md
applications/squareone/templates/configmap.yaml
applications/squareone/values-idfdev.yaml
applications/squareone/values-idfint.yaml
applications/squareone/values-idfprod.yaml
applications/squareone/values.yaml

This value can be set to the COmanage URL for environments that use COmanage (i.e. https://id.lsst.cloud for the IDF).

DM-38116: Add coManageRegistryUrl value (Squareone 0.9.0)

---

.github/workflows/ci.yaml
.github/workflows/docs.yaml
.github/workflows/linkcheck.yaml

GitHub has a new feature called merge queues that allows one to queue up a number of PRs for merging, and each will be properly rebased and merged when their tests pass. In order to use it, it has to be mandatory for merges and GitHub Actions that may block a merge have to trigger on `merge_group`.
Take this opportunity to rework the documentation build a bit:
- Always run the documentation build but skip the work if the documentation hasn't changed. This allows us to block merges on documentation syntax errors or missing metadata for new applications or environments.
- Re-add the documentation link check, which we'd disabled in January, as a separate CI workflow so that it doesn't block merges. Run it on pushes and once a week.
- Update to Python 3.11 for documentation builds.
- Use the …

DM-38208: Prepare Phalanx for using merge queues

---

.github/workflows/docs.yaml
.github/workflows/linkcheck.yaml

The merge queue also does pushes to various branches, which should not run docs or link check CI workflows.

DM-38208: Additional merge queue fixes

---

applications/ingress-nginx/values-roe.yaml
applications/moneypenny/values-roe.yaml
applications/nublado2/values-roe.yaml

A couple of changes to the roe env:
- Modify NGINX ingress controller to user LoadBalancer, also add the floating IP that is used.
- Change IP's for NFS

Upgrade roe env (loadbalancer for nginx ingress / new IP's for NFS)

---

applications/argocd/README.md
applications/argocd/values.yaml

See if this prevents Google Log Explorer from misclassifying the Argo CD log messages.

DM-38154: Enable structured logging for Argo CD

---

applications/sasquatch/charts/strimzi-kafka/README.md
applications/sasquatch/charts/strimzi-kafka/templates/mirrormaker2.yaml
applications/sasquatch/charts/strimzi-kafka/values.yaml

MM2 by default consumes the earliest offsets from the source cluster, for the Summit that means ~72h of data for more than 2000 topics.
When we turned on MM2 at USDF we got the following errors and needed to fine-tune the connector to be able to replicate larger amounts of data. 
```2023-03-10 14:18:56,247 WARN [source->target.MirrorSourceConnector|task-1] [Producer clientId=connector-producer-source->target.MirrorSourceConnector-1] Got error produce response in correlation id 2104 on topic-partition lsst.sal.MTM1M3.forceActuatorData-0, splitting and retrying (2147483647 attempts left). Error: MESSAGE_TOO_LARGE (org.apache.kafka.clients.producer.internals.Sender) [kafka-producer-network-thread | connector-producer-source->target.MirrorSourceConnector-1]```

Fine tune MM2 configuration for Summit->USDF replication

---

applications/sasquatch/charts/strimzi-kafka/templates/users.yaml

- Give read access for the prompt-processing user on the lsst.sal.ScriptQueue.logevent_nextVisit topic

Fix prompt-processing user permissions

---

applications/gafaelfawr/README.md
applications/gafaelfawr/templates/configmap.yaml
applications/gafaelfawr/values-ccin2p3.yaml
applications/gafaelfawr/values.yaml

Add Gafaelfawr configuration support for querying a ForgeRock Identity Management server for group GIDs, and add the needed configuration for the CC-IN2P3 environment.

DM-38058: Add ForgeRock Identity Management support

---

applications/gafaelfawr/values-ccin2p3.yaml
applications/gafaelfawr/values-idfdev.yaml
applications/gafaelfawr/values-minikube.yaml

Gafaelfawr 9.1.0 has been released, so switch to the released version for IDF dev, minikube, and CC-IN2P3.

DM-38058: Use the released version of Gafaelfawr

---

applications/obstap/templates/tap-deployment.yaml

This part is unlike the lsst-tap-service, and I'll have to do additional work to connect to the tap-schema as well as the normal database.  Let's just try to use the mock pg database which should hopefully have a tap schema setup to start.

[DM-38110] Begin trying to configure databases

---

applications/mobu/Chart.yaml
applications/mobu/README.md
applications/mobu/templates/configmap-autostart.yaml
applications/mobu/templates/deployment.yaml
applications/mobu/values-idfdev.yaml
applications/mobu/values-idfint.yaml
applications/mobu/values-idfprod.yaml
applications/mobu/values-minikube.yaml
applications/mobu/values-roe.yaml
applications/mobu/values-usdfdev.yaml
applications/mobu/values-usdfprod.yaml
applications/mobu/values.yaml
environments/templates/nublado-users-application.yaml

Update the mobu configuration for the new 5.0.0 release, which changes the structure of the flock specifications. Pin IDF dev and minikube to the testing branch for right now.
Remove the cachemachineImagePolicy setting, since it didn't actually do anything and cachemachine is going away.
Switch the TAP queries on IDF int back to sync so that we can test the timeout problems that we are seeing in IDF prod.

DM-38339: Update to latest mobu

---

applications/nublado/README.md
applications/nublado/templates/configmap.yaml
applications/nublado/values-idfdev.yaml
applications/nublado/values.yaml
environments/templates/nublado2-application.yaml

Rather than injecting static files into JupyterHub as secrets, construct all of our configuration in a ConfigMap and then mount that into /usr/local/etc/jupyterhub/jupyterhub_config.d. Use that configuration to set the new parameters for RSPRestSpawner. We now no longer need a separate Nublado configuration file or all the parsing code and are uniformly using traitlets.
Mount the Gafaelfawr token for JupyterHub on /etc/gafaelfawr without a subpath so that hopefully we now get dynamic token updates.
Pin the images for IDF dev to my current patch queue branches.
Fix the indentation for YAML lists in the nublado values.yaml to be consistent with the rest of Phalanx.

DM-38279: Redo how nublado configures JupyterHub

---

.pre-commit-config.yaml
applications/nublado/templates/configmap.yaml

JupyterHub no longer uses this file, but we still need it for the lab controller, for which it is the primary configuration file.

DM-38279: Restore config.yaml for the lab controller

---

applications/nublado/templates/configmap.yaml

The new configuration file had a few syntax errors.  Fix those.

DM-38279: Fix typos in Nublado configuration

---

applications/strimzi/values-usdfdev.yaml
applications/strimzi/values-usdfprod.yaml

- Getting `Terminating due to java.lang.OutOfMemoryError: Java heap space` on the strimzi operator pod

Strimzi operator is crashing at usdf

---

applications/semaphore/templates/vaultsecret.yaml

This error was introduced in a chart migration. It likely didn't trigger an error because the secret was pre-existing in all environments, however the VaultSecret resource does show a FetchFailed error.

DM-38488: Fix vault secrets path for semaphore

---

applications/nublado/README.md
applications/nublado/values-idfdev.yaml
applications/nublado/values.yaml

Take a single source key that has a type parameter specifying docker or google and then the necessary configuration for that image source. The previous approach was simpler (somewhat) to document in Helm, but this approach works better with Pydantic.

DM-38279: Change how Nublado image sources are given

---

applications/nublado/README.md
applications/nublado/templates/controller-serviceaccount.yaml
applications/nublado/values-idfdev.yaml
applications/nublado/values.yaml

This is required to be able to access the Google Artifact Registry.

DM-38466: Bind nublado-controller to a Google service account

---

applications/nublado/values.yaml

This was only required for very old images that now are unlikely to work for other reasons.

DM-38554: Remove NO_SUDO from notebook environment

---

applications/nublado/values-idfdev.yaml
applications/nublado/values.yaml

Don't pull the tutorial notebooks on every instance by default since they only work at the IDF (and maybe the USDF). Instead, set that in values-idfdev.yaml.
Pull the Butler configuration environment variables that are specific to the IDF out of values.yaml and into values-idfdev.yaml.

DM-38554: Move auto-repo and Butler out of Nublado values.yaml

---

applications/sasquatch/README.md
applications/sasquatch/values.yaml

Chronograf 1.10.x introduces a regression in the table display for Flux queries and invalidate a few dashnboards. This was noticed at USDF before the Summit upgrade window.

Rollback Chronograf to version 1.9.4

---

applications/gafaelfawr/values-base.yaml
applications/gafaelfawr/values-idfdev.yaml
applications/gafaelfawr/values-idfint.yaml
applications/gafaelfawr/values-summit.yaml
applications/gafaelfawr/values-tucson-teststand.yaml
applications/gafaelfawr/values-usdfdev.yaml
applications/gafaelfawr/values-usdfprod.yaml
applications/gafaelfawr/values.yaml

Add a new distinguished scope for write access to the telemetry service, since we will eventually want to create service tokens that have access only to that service. For now, add that scope only in the environments that deploy Sasquatch and only for administrators.

DM-38654: Add new write:sasquatch scope

---

docs/_rst_epilog.rst
docs/applications/sasquatch/create-write-token.rst
docs/applications/sasquatch/index.rst

Add documentation for how to create a service token for writing to Sasquatch.

DM-38654: Document creating Sasquatch write tokens

---

applications/nublado/README.md
applications/nublado/templates/controller-deployment.yaml
applications/nublado/templates/vault-secrets.yaml
applications/nublado/values-idfdev.yaml
applications/nublado/values.yaml
installer/generate_secrets.py

Add the Slack webhook to the secret for the new Nublado and inject it into the lab controller pod if Slack alerting is enabled. Enable Slack alerting on IDF dev.

DM-38554: Add Slack alerting support to Nublado

---

applications/nublado/Chart.yaml
applications/nublado/README.md
applications/nublado/values.yaml

Update the versions of the images used for Nublado v3 to the 0.2.0 release.

DM-38554: Bump versions of Nublado images

---

applications/gafaelfawr/README.md
applications/gafaelfawr/templates/configmap-kerberos.yaml
applications/gafaelfawr/templates/configmap.yaml
applications/gafaelfawr/templates/cronjob-audit.yaml
applications/gafaelfawr/templates/cronjob-maintenance.yaml
applications/gafaelfawr/templates/deployment-operator.yaml
applications/gafaelfawr/templates/deployment.yaml
applications/gafaelfawr/templates/vault-secrets.yaml
applications/gafaelfawr/values.yaml

Add a new configuration option to set the Kerberos configuration for GSSAPI bind support. If set, create a separate secret for the keytab and mount it in all the containers, and run Gafaelfawr under k5start. Also mount the krb5.conf file and create a /tmp directory, since k5start needs a writable directory to use for ticket caches.

DM-38747: Add Kerberos GSSAPI bind support for Gafaelfawr

---

applications/times-square/Chart.yaml
applications/times-square/templates/deployment.yaml
applications/times-square/templates/worker-deployment.yaml

This version updates Times Square to use safir.redis and safir.github.

DM-38650: Deploy Times Square 0.7.0 Update

---

applications/nublado/values-idfint.yaml

The new Nublado requires explicitly specifying the secrets to mount in the container and uses a different path by default. Adjust the IDF int configuration accordingly.

DM-38795: Add Butler secret to data-int

---

applications/mobu/values-idfint.yaml
applications/nublado/templates/vault-secrets.yaml
applications/nublado/values-idfint.yaml

The secrets that we inject into the lab shouldn't use nublado-secret since it has a complex templating setup. Instead, create a separate lab-secret VaultSecret to collect secrets we're injecting into labs, and reference that in the IDF int configuration.

DM-38795: Add separate lab secret

---

applications/nublado/templates/vault-secrets.yaml

Rather than unconditionally creating the nublado-lab-secret Vault secret, only create it if we have secrets configured in the lab configuration. This avoids having to create an empty Vault secret just to keep vault-secrets-operator happy.
This is not entirely correct since the secret references in the secrets configuration may not point to this secret, but it will be good enough for now. We can do fancier Helm templating later if needed.

DM-38795: Only create nublado-lab-secret if secrets configured

---

applications/nublado/README.md
applications/nublado/templates/hub-configmap.yaml
applications/nublado/values.yaml

For reasons we don't yet understand, JupyterLab startup sometimes takes over 60 seconds. Increase the default timeout to 90 seconds to match what we're currently using in production.
Make the total spawn timeout and the JupyterLab startup timeout easily configurable in values files. Add a new section to the values file for hub configuration that we control rather than that is passed down to Zero to JupyterHub.

DM-38795: Increase JupyterLab startup timeout to 90 seconds

---

applications/sasquatch/values-usdfdev.yaml

This PR adds a new connector for the lsst.rubintv namespace in Sasquatch at USDF dev.

Add a new connector for lsst.rubintv

---

applications/sasquatch/values-usdfdev.yaml

- Configure the REST Proxy to expose topics with the lsst.rubintv prefix

Add lsst.rubintv namespace

---

applications/sasquatch/charts/kafka-connect-manager/README.md
applications/sasquatch/charts/kafka-connect-manager/templates/influxdb_sink.yaml
applications/sasquatch/charts/kafka-connect-manager/values.yaml
applications/sasquatch/values-summit.yaml
applications/sasquatch/values-usdfdev.yaml

- A repairer connector is a new instance of a connector that consumes the earliest offsets and write to InfluxDB at the same time the original connector continue writing the latest offsets.

Deploy a repairer connector

---

applications/sasquatch/values-usdfdev.yaml

- Configure the REST Proxy to expose topics with the lsst.camera prefix
- Configure InfluxDB connector to write these topics to the lsst.camera database

[DM-39135] Add lsst.camera namespace

---

applications/mobu/values-idfdev.yaml

In the mobu image spec, enable debugging for the Jupyter lab tests on IDF dev.

DM-38425: Enable Jupyter lab debugging on IDF dev

---

applications/sasquatch/Chart.yaml
applications/sasquatch/README.md
applications/sasquatch/charts/kafka-connect-manager/README.md
applications/sasquatch/charts/kafka-connect-manager/values.yaml
applications/sasquatch/charts/strimzi-kafka/README.md
applications/sasquatch/charts/strimzi-kafka/templates/connect.yaml
applications/sasquatch/charts/strimzi-kafka/templates/kafka.yaml
applications/sasquatch/charts/strimzi-kafka/templates/tests/test-sasl-authentication.yaml
applications/sasquatch/charts/strimzi-kafka/templates/users.yaml
applications/sasquatch/charts/strimzi-kafka/values.yaml
applications/sasquatch/values-roundtable-dev.yaml
applications/sasquatch/values.yaml
applications/strimzi/values-roundtable-dev.yaml
environments/values-roundtable-dev.yaml

This PR configures a Kafka cluster for Roundtable. We're doing this by configuring Sasquatch so that down the road we can easily add Sasquatch's monitoring capabilities to Roundtable given that Sasquatch itself is also Kafka based.
- ~~[ ] Configures Kafdrop to use TLS authentication~~ May need to be done later.
The Sasquatch deployment on roundtable-dev is here: https://roundtable-dev.lsst.cloud/argo-cd/applications/argocd/sasquatch

DM-39014: Configure Kafka/Sasquatch for Roundtable

---

applications/sasquatch/README.md
applications/sasquatch/values.yaml

- This is due to the annoying ":" bug in the query editor.

Revert Chronograf to version 1.9.4 everywhere

---

applications/nublado/README.md
applications/nublado/values.yaml

Add helm-docs comments to all of the overrides for Zero to JupyterHub configuration so that we get more useful chart documentation.
Delete the creation of a new self role. So far as I can tell, this was never used or assigned to anything, and therefore wasn't doing anything. I think this was an earlier attempt to solve a problem that was solved by setting authenticatePrometheus to false.
Change the default permissions of the server role (for spawned labs) to self rather than inherit. This only affects labs spawned by JupyterHub administrators and ensures that the lab token only inherits their regular user permissions and not their admin permissions.

DM-39232: Improve nublado documentation and roles

---

applications/cert-manager/README.md
applications/cert-manager/templates/cluster-issuer.yaml
applications/cert-manager/templates/vault-secrets.yaml
applications/cert-manager/values.yaml

cert-manager now supports configuring structured logging. Do that, and improve the chart values.yaml documentation. Remove the name overrides, since we don't use them, and simplify the resources we create directly.

Use JSON logging format for cert-manager

---

applications/nublado/values-idfdev.yaml
applications/nublado/values-idfint.yaml
applications/nublado2/values-idfdev.yaml
environments/values-idfdev.yaml
installer/generate_secrets.py

Add the required secrets and configuration for both Nublado v2 and v3 access to DP0.2 from IDF dev using the Cloud SQL Proxy for cross-project access.

DM-38203: Enable DP0.2 access from IDF dev

---

applications/mobu/values-idfdev.yaml

On IDF dev, test both Nublado v2 and v3 with mobu by default, using the new support for configuring cachemachine in the business options.

DM-39325: Test both Nublado v2 and v3 with mobu

---

applications/noteburst/Chart.yaml
applications/noteburst/README.md
applications/noteburst/templates/configmap.yaml
applications/noteburst/templates/worker-configmap.yaml
applications/noteburst/values-idfdev.yaml
applications/noteburst/values.yaml

This adds `config.hubPathPrefix` and `config.nubladoControllerPathPrefix` values to the noteburst chart.

DM-39336: Add JupyterHub URL configurations to Noteburst

---

applications/sqlproxy-cross-project/values-idfdev.yaml

Point the Cloud SQL Proxy in IDF dev at the Butler database used by IDF int (the one in the panda-dev project).

DM-38203: Repoint IDF dev SQL proxy

---

applications/nublado/Chart.yaml
applications/nublado/README.md
applications/nublado/templates/proxy-ingress.yaml
applications/nublado/values-usdfdev.yaml
applications/nublado/values.yaml

Add a new configuration for USDF dev modelled after its nublado2 configuration. USDF overrode the ingress annotations, so add support for setting ingress annotations for the proxy so that it can continue to do this. That uncovered missed annotations that we added to nublado2 and not nublado, which have now been copied over.
Rename the ingress to reflect that it's an ingress for the proxy, not the hub (the proxy routes to either the hub or the lab).

DM-39232: Add Nublado v3 configuration for USDF dev

---

applications/portal/values-roe.yaml
applications/tap/values-roe.yaml

Changes include:
- Modify portal/values-roe.yaml to scale up replicas & set a default hipsUrl
- Modify tap/values-roe.yaml to change QServ IP & setup S3 buckets for async

Updates to roe environment (S3 buckets, default hips url, fixed Qserv)

---

applications/argocd/README.md
applications/argocd/values.yaml

The documentation was a bit unclear, but I found the right place to put this in the new configuration layout. So far as I can tell, explicitly registering the Helm repositories shouldn't be required, so those are still omitted.

Re-add Argo CD configuration for aggregated roles

---

applications/nublado/Chart.yaml
applications/nublado/README.md
applications/nublado/values.yaml

Pick up the 0.3.1 release of the REST spawner and the 0.6.0 release of the Nublado controller.

DM-39400: Use new JupyterHub and Nublado controller images

---

applications/mobu/values-idfdev.yaml
applications/mobu/values-idfint.yaml

Now that the tutorial notebooks should work on the data-dev and data-int environments, start testing them there with mobu using Nublado v3.

DM-39400: Test tutorial notebooks on data-dev and data-int

---

applications/mobu/values-idfdev.yaml
applications/mobu/values-idfint.yaml

The assert that prevents them from running anywhere other than IDF prod has not been removed on any branch or PR that I can find, so turn them off on IDF int and dev for the time being.

DM-39400: Turn the tutorial notebook tests off again

---

applications/portal/README.md
applications/portal/templates/deployment.yaml
applications/portal/values-idfint.yaml
applications/portal/values.yaml

Allows turning on the SSO TAP service in the Portal on a per-instance basis, initially for data-int.

DM-39435: Add values-level support for adding SSO TAP to Portal menu

---

applications/mobu/values-idfdev.yaml
applications/mobu/values-idfint.yaml

This reverts commit 749fa424ae3d421623ba68b89ca3ee77def4a86a. The assert preventing tutorial notebooks to run in other environments has reportedly been removed on main.

DM-39400: Revert "Turn the tutorial notebook tests off again"

---

applications/mobu/values-idfdev.yaml
applications/mobu/values-idfint.yaml

On IDF dev and IDF int, run the tutorial notebooks with latest-weekly since they require the new lsst.rsp package.

DM-39400: Run tutorial notebooks with latest-weekly

---

applications/portal/templates/deployment.yaml

Change order of RSP TAP service entries to keep DP0.2 first, and DP0.3 / SSOTAP as the second.  (Workaround for surprising behavior of Firefly configuration language.)

DM-39435: Restore DP0.2 TAP as the default service

---

applications/portal/templates/deployment.yaml

Required for the final public-facing configuration we want:
* LSST DP0.2 DC2
* LSST DP0.3 SSO

DM-39435: Update to match the new `suit` default TAP service label

---

applications/noteburst/values-usdfdev.yaml
applications/postgres/templates/deployment.yaml
applications/postgres/values-usdfdev.yaml
applications/times-square/values-usdfdev.yaml
environments/values-usdfdev.yaml

This deploys both `times-square` and `noteburst` on usdfdev. Also configures a `timessquare` database in the in-cluster postgres database.
This PR is pending the deployment of Nublado v3 on usdfdev.

DM-38798: Deploy Times Square and Noteburst on usdfdev

---

applications/squareone/values.yaml

This direct link was suggested by the Users Committee via https://github.com/rubin-dp0/Support/issues/41

DM-39579: Add link to DP0.2 tutorials from the Squareone /docs page

---

renovate.json

Enable automated config migration. Disable rebasing of non-conflicted PRs; we use the merge queue, which will rebase them anyway, so these extra rebases are wasted effort and testing cycles. Set the time zone to push weekly updates a bit later into the middle of the night on Monday instead of starting to show up Sunday evening.

DM-39594: Update Renovate configuration

---

applications/sasquatch/values-usdfdev.yaml

- Configure the REST Proxy to expose topics with the lsst.lf prefix
- An an InfluxDB connector to write these topics to the lsst.lf database

Add lsst.lf namespace

---

applications/noteburst/values-usdfdev.yaml

bot-noteburst 01 to 20 were created at usdfdev; for now only configure the first two to run on dev.

DM-38798: Update bot names for usdf-dev

---

applications/sasquatch/Chart.yaml
applications/sasquatch/README.md
applications/sasquatch/charts/kafka-connect-manager/README.md
applications/sasquatch/charts/kafka-connect-manager/templates/influxdb_sink.yaml
applications/sasquatch/charts/kafka-connect-manager/values.yaml
applications/sasquatch/charts/strimzi-kafka/README.md
applications/sasquatch/charts/strimzi-kafka/templates/mirrormaker2.yaml
applications/sasquatch/charts/strimzi-kafka/templates/source-connect.yaml
applications/sasquatch/charts/strimzi-kafka/templates/source-schema-registry.yaml
applications/sasquatch/charts/strimzi-kafka/values.yaml
applications/sasquatch/values-base.yaml
applications/sasquatch/values.yaml
pyproject.toml

Enabled MirrorMaker2 (MM2) at the base for another online copy of the Summit EFD.
MM2 is configured with `DefaultReplicationPolicy`.
Kafka topics are renamed in this mode and have the source cluster alias as a prefix.
A second schema registry is configured to use the `source.registry-schemas` topic as the source for the schemas.
Schema translation is required, so schemas were registered under new subjects that follow the topic name strategy, including the `source.` prefix to the subject name.
A second Kafka Connect cluster was deployed and configured to use the new schema registry.
Finally we use a new version of kafka-connect-manager that adds the --remove-prefix option because we want the measurement names in InfluxDB to preserve the names at the Summit EFD.
kafka-connect-manager is …

[DM-39664] Deploy MirrorMaker 2 for replicating EFD data at the Summit (Yagan) to Base (Manke)

---

applications/nublado/README.md
applications/nublado/values.yaml

Update to version 0.3.2, which has a timeout fix.

DM-39596: Bump version of REST spawner for Nublado v3

---

applications/mobu/values-idfdev.yaml
applications/mobu/values-idfint.yaml
applications/noteburst/values-idfdev.yaml
applications/noteburst/values-usdfdev.yaml
applications/nublado/values-idfdev.yaml
applications/nublado/values-idfint.yaml
applications/nublado/values-usdfdev.yaml
applications/nublado2/values-idfdev.yaml
applications/nublado2/values-idfint.yaml
applications/nublado2/values-usdfdev.yaml

This moves nublado3 to /nb on idf-dev, -int, and usdf-dev, while relocating nublado2 to /n2 on the same environments, as requested by Frossie on 5 July 2023.

idf-dev, idf-int, and usdf-dev -> nublado3 by default

---

applications/mobu/Chart.yaml

Improved error reporting and hopefully a fix for the timeouts when summarizing flocks.

DM-39552: Update to mobu 6.1.1

---

applications/livetap/README.md
applications/livetap/templates/tap-schema-db-deployment.yaml
applications/livetap/values-minikube.yaml
applications/livetap/values-usdfdev.yaml
applications/livetap/values-usdfprod.yaml
applications/livetap/values.yaml
applications/ssotap/README.md
applications/ssotap/templates/tap-schema-db-deployment.yaml
applications/ssotap/values-idfdev.yaml
applications/ssotap/values-idfint.yaml
applications/ssotap/values-idfprod.yaml
applications/ssotap/values-minikube.yaml
applications/ssotap/values-usdfdev.yaml
applications/ssotap/values-usdfprod.yaml
applications/ssotap/values.yaml
applications/tap/README.md
applications/tap/templates/tap-schema-db-deployment.yaml
applications/tap/values-ccin2p3.yaml
applications/tap/values-idfdev.yaml
applications/tap/values-idfint.yaml
applications/tap/values-idfprod.yaml
applications/tap/values-minikube.yaml
applications/tap/values-roe.yaml
applications/tap/values-usdfdev.yaml
applications/tap/values-usdfprod.yaml
applications/tap/values.yaml

Make the TAP schema database pod configuration consistent with other deployments and Helm values style:
* Use tapSchema rather than tap_schema since Helm uses camelCase
* Add and use podAnnotations, nodeSelector, tolerations, and affinity rather than using the ones for the base TAP server
* Add image.pullPolicy configuration
Also set a default image.repository for tapSchema. It would be nice to have Helm force this to be set, but unfortunately it breaks Renovate discovery of the latest image tag version, which we want as a reminder when the image is out of date. Use the same image name that we use for minikube as the default, but document that it must be set for each environment.

Change TAP schema database pod configuration

---

.github/workflows/dependencies.yaml
.pre-commit-config.yaml
tox.ini

Run neophile weekly to update the pre-commit dependencies. Fix the URLs of the existing pre-commit dependencies to use the canonical URLs, since neophile does not yet support fixing those.

DM-39989: Add periodic pre-commit dependency update

---

.pre-commit-config.yaml

neophile can't handle the trailing .git, so remove it so that neophile can properly update the dependency.

DM-39989: Remove .git from the yamllint pre-commit hook

---

.github/workflows/linkcheck.yaml

Don't name the linkcheck workflow docs, because then it becomes a required workflow for merging and the whole point of making it a separate workflow was so that it wouldn't be required.

Give the linkcheck workflow a unique name

---

applications/sasquatch/charts/kafka-connect-manager/README.md
applications/sasquatch/charts/kafka-connect-manager/values.yaml

The connector for M1M3 breaks with the RETRY error policy. Reverting for now.

Revert "Change connector error policy to RETRY"

---

applications/tap/values-roe.yaml

This PR changes the image repository for the roe env to: stvoutsin/tap-schema-roe. At ROE we have a different set of databases/catalogs that do not appear in the idfprod schema image, so for now we've created a new Docker image for TAP_SCHEMA. Perhaps down the road these schema files can be included in the sdm_schemas repo & build scripts.

Update the TAP_SCHEMA repository for the roe environment

---

applications/livetap/values-minikube.yaml
applications/livetap/values-usdfdev.yaml
applications/livetap/values-usdfprod.yaml
applications/ssotap/values-idfdev.yaml
applications/ssotap/values-idfint.yaml
applications/ssotap/values-idfprod.yaml
applications/ssotap/values-minikube.yaml
applications/ssotap/values-usdfdev.yaml
applications/ssotap/values-usdfprod.yaml
applications/tap/values-idfdev.yaml
applications/tap/values-idfint.yaml
applications/tap/values-idfprod.yaml
applications/tap/values-minikube.yaml

Once there is a load balancer set up in front of the bucket, we should use the https URL.  Then if we
really want or need to, we can use an http endpoint, and the loadbalancer will redirect to an https URL.

[DM-39960] Change URL from http to https

---

renovate.json

Renovate is picking up the annoying global pipelines release tags for sdm_schemas. Try to exclude them.

Ignore bogus pipelines releases for tap-schema

---

applications/gafaelfawr/README.md
applications/gafaelfawr/templates/configmap.yaml
applications/gafaelfawr/values-ccin2p3.yaml
applications/gafaelfawr/values-minikube.yaml
applications/gafaelfawr/values-roe.yaml
applications/gafaelfawr/values-usdfdev.yaml
applications/gafaelfawr/values-usdfprod.yaml
applications/gafaelfawr/values.yaml

Add a new Helm configuration option for whether Gafaelfawr should use the cluster-internal PostgreSQL database instead of just using the database URI so that we can trigger optional secrets based on whether that configuration option is set.

DM-40060: Change config for Gafaelfawr internal database

---

applications/noteburst/templates/ingress.yaml
applications/squareone/templates/ingress-times-square.yaml
applications/times-square/templates/gafaelfawrtoken.yaml
applications/times-square/templates/ingress.yaml

- Switch to exec:notebook scope for noteburst
- Add an ingress to Squareone specifically for the `/times-square` path prefix to ensure that users are logged in (and auto-redirect them to log in if not).

DM-40169: Times Square and Noteburst debugging on USDF Dev

---

applications/sasquatch/values-base.yaml

- Kafka at base has two functions now, it stores topics from the teststand and topics replicated from the summit efd.
- Expand Kafka data partition from 500G to 1T

[DM-40165] Increase Kafka data partition size

---

applications/times-square/Chart.yaml
applications/times-square/README.md
applications/times-square/templates/configmap.yaml
applications/times-square/values.yaml

This value configures what GitHub orgs can sync repos to Times Square (provided they've also installed the Times Square GitHub App).

DM-40187: Add githubOrgs config to Times Square

---

applications/ingress-nginx/values-idfdev.yaml

nginx produces a lot of spurious warning messages about spooling large request bodies to disk, which we don't care about.

Change nginx logs to error

---

applications/times-square/Chart.yaml

This deploys the new Times Square behaviour where the first code cell is replaced by Times Square with Python code that sets parameters are variables. No other Python code cells are treated as templates. https://github.com/lsst-sqre/times-square/releases/tag/0.9.0

DM-40188: Deploy Times Square 0.9.0

---

applications/alert-stream-broker/README.md
applications/alert-stream-broker/charts/alert-stream-broker/README.md
applications/alert-stream-broker/charts/alert-stream-broker/values.yaml
applications/alert-stream-broker/values-idfint.yaml

Update alert-stream-broker Kafka version and temporarily remove brokers 3-5.

DM-40174: Update Kafka version

---

applications/gafaelfawr/secrets.yaml
docs/about/introduction.rst
docs/documenteer.toml
src/phalanx/cli.py
src/phalanx/services/secrets.py
src/phalanx/yaml.py
tests/cli/secrets_test.py
tests/data/input/applications/gafaelfawr/secrets.yaml
tests/data/output/idfdev/static-secrets.yaml
tests/support/data.py
tox.ini

Add a phalanx secrets static-template command that generates a YAML template for the static secrets for an environment.

DM-40125: Add support for static secret template

---

applications/sasquatch/values-base.yaml

- This is required for restoring historical EFD data

Expand influxdb-source PV to 10TB at base

---

applications/squareone/values-idfint.yaml
applications/squareone/values.yaml

Keep DP0.2 since we're hosting both releases at the same time.

DM-40298: Add doc links for DP0.3

---

applications/mobu/values-idfdev.yaml

The tutorial notebooks have added DP0.3 notebooks, and DP0.3 isn't available on IDF dev, so disable running tutorial notebooks on IDF dev for now until we can talk about it.

Stop running tutorial notebooks on IDF dev

---

.github/workflows/ci.yaml
applications/vault-secrets-operator/values.yaml
installer/install.sh

Stop setting a default for vault-secrets-operator.vault.address to make it more obvious when science-platform hasn't been correctly updated.

DM-40256: Clear default for Vault address

---

applications/mobu/values-idfdev.yaml
applications/mobu/values-idfint.yaml

Re-enable tutorial notebook testing on IDF dev and switch the IDF int testing to the prod branch from main, since the prod branch is currently broken.

Test prod tutorial branch on IDF dev and int

---

src/phalanx/cli.py
src/phalanx/services/secrets.py
src/phalanx/storage/vault.py
tests/cli/secrets_test.py
tests/data/input/vault/idfdev/unknown.json
tests/data/output/idfdev/secrets-audit
tests/data/output/idfdev/sync-delete-output
tests/support/vault.py

Add support for a `--delete` flag to `phalanx secrets sync` that removes stray secrets in Vault, either ones for unknown or no-longer-enabled applications or individual keys for applications no longer configured to have a key by that name.
Also fix `phalanx secrets vault-secrets` to read all secrets from Vault, not just the ones that correspond to enabled applications.

DM-40256: Add support for cleaning up Vault secrets

---

applications/sasquatch/values-usdfprod.yaml

Enabling the repairer connectors at USDF to help isolate the data corruption events we see.
If both the current and repairer connectors fail to consume the same Kafka message, it indicates that the problem is indeed a corrupted message as opposed to a bug in the connector.

Enable repairer connectors at USDF

---

applications/sasquatch/charts/kafka-connect-manager/templates/influxdb_sink.yaml

- Use tasksMax config parameter when deploying repairer connectors

Use tasksMax config for repairer connectors

---

applications/sasquatch/values-idfdev.yaml

- idfdev cluster does not have enough resources for the default influxdb resources configuration

Decrease influxdb resources at idfdev

---

src/phalanx/cli.py
src/phalanx/constants.py
src/phalanx/models/environments.py
src/phalanx/models/vault.py
src/phalanx/services/vault.py
src/phalanx/storage/vault.py
tests/cli/vault_test.py
tests/data/output/idfdev/audit-approle-extra
tests/data/output/idfdev/audit-approle-policy
tests/data/output/idfdev/audit-both-missing
tests/data/output/idfdev/audit-token-expired
tests/data/output/idfdev/audit-token-multiple
tests/data/output/idfdev/audit-token-policy
tests/support/vault.py

Add a command to check the authentication credentials for a given environment (both the read AppRole and the write token) and report any problems found. Add a display name to write tokens so that they can be more easily found among all of the other accessors.

DM-25701: Add phalanx vault audit command

---

src/phalanx/services/vault.py
src/phalanx/storage/vault.py
tests/cli/vault_test.py
tests/data/output/idfdev/audit-token-multiple
tests/support/vault.py

When creating a new Vault AppRole or write token for an environment, search for any existing AppRole SecretIDs or write tokens and delete them. This more aggressive credential management approach maintains an invariant of only having one active AppRole SecretID and write token at a time, better for both conceptual simplicity and security, and means most problems with an AppRole or write token configuration can be fully resolved by creating a new one.

DM-23487: Delete all other AppRole SecretIDs and write tokens on creation

---

src/phalanx/exceptions.py

The f-string formatting the error message accidentally omitted the f prefix and thus wasn't formatted.

DM-40343: Fix InvalidEnvironmentConfigError error

---

pyproject.toml
src/phalanx/services/secrets.py
tests/cli/secrets_test.py

If no static secret source was provided but all of the required static secrets are already in Vault, successfully sync and retain the secrets in Vault. This is required to support the USDF environments, where static secrets are maintained directly in Vault, and in general will be more convenient since it will mean that 1Password secrets don't have to be provided when one is just syncing new generated secrets.

DM-40256: Support secret sync with no static secrets source

---

src/phalanx/cli.py
src/phalanx/factory.py
src/phalanx/storage/config.py
tests/cli/secrets_test.py
tests/cli/vault_test.py
tests/conftest.py
tests/support/cli.py

Add a flag to every phalanx CLI command that uses the Phalanx configuration specifying its location, and default to searching upwards from the current directory to find the top of the configuration tree (by looking for the applications and environments directories).
Add a wrapper function around Click command-line testing for the test suite that adds the path to the test configuration directory and flips the default for catching exceptions to False.

DM-40343: Detect location of the Phalanx configuration

---

.pre-commit-config.yaml

Change the helm-docs pre-commit hook to only process the environments nad applications directories. This avoids generating unwanted README.md files in other directories that look like they may contain a Helm chart, such as input data for the test suite.

DM-40343: Only process specific directories with helm-docs

---

applications/giftless/templates/ingress.yaml

Turns out we can't share the secret between the two ingresses.

turn on LE for rw endpoint

---

applications/gafaelfawr/values-idfint.yaml
applications/gafaelfawr/values-idfprod.yaml

On IDF int and IDF prod, give admins admin:jupyterhub scope so that they can ask the Nublado lab controller about the status of labs.

Give admins admin:jupyterhub scope

---

docs/.gitignore
docs/_templates/autosummary_core/exception.rst
docs/_templates/autosummary_core/pydantic_model.rst
docs/conf.py
docs/documenteer.toml
docs/index.rst
docs/internals/api.rst
docs/internals/index.rst
docs/internals/json-schema.rst
requirements/dev.in
requirements/dev.txt
src/phalanx/models/secrets.py
src/phalanx/storage/vault.py
tox.ini

Add an internals page that is available only via the top bar from the pull-down menu, since most people will never need to see it. Document the JSON schemas there (currently only one for secrets.yaml but more will come later) and add internal API documentation.
This is of arguable usefulness, but sometimes it can be nice to browse the API documentation when working on new code, and it has the nice benefit of checking all of the docstrings more thoroughly than a linter does.

DM-40343: Add API and schema documentation

---

applications/nublado/values-tucson-teststand.yaml

To track Michael's maintenance work and keep n3 in sync with /nb (still nublado2 at T&S sites)

n3: tts->cycle_32

---

applications/telegraf-ds/templates/configmap.yaml

The changes to adjust for the new format of the enabled applications field omitted blank lines between output definitions. Add that blank line back in.

DM-40448: Fix blank line in telegraf-ds configuration

---

docs/applications/cachemachine/bootstrap.rst

The cachemachine documentation included a link to the IDF prod cachemachine configuration, but we no longer use cachemachine on IDF prod. Remove that sentence.

DM-40495: Remove link to IDF prod cachemachine setup

---

environments/values-roe.yaml

Move from "https://vault.lsst.codes" to locally (UK) managed one: "https://vault.lsst.ac.uk"

Update the Vault URL for the roe environment

---

src/phalanx/models/environments.py
src/phalanx/storage/config.py
tests/data/input/applications/argocd/values-usdfdev-prompt-processing.yaml
tests/data/input/environments/values-usdfdev-prompt-processing.yaml

When generating the documentation, support environments that have Gafaelfawr disabled. We may have Phalanx environments that only run backend processes without any user interface, in which case Gafaelfawr is unnecessary.

DM-40537: Support disabling Gafaelfawr

---

applications/gafaelfawr/values.yaml

The scope description for write:sasquatch had spurious additional quotes because it was quoted two ways in YAML. Remove the surrounding double quotes.

Remove quotes from write:sasquatch description

---

docs/applications/giftless/index.rst
docs/applications/monitoring/index.rst

Fix the title of the monitoring application documentation page and add some additional explanation of what it does. Include links to the telegraf and telegraf-ds applications.

Improve monitoring docs page

---

Makefile
applications/rubintv/Chart.yaml
applications/rubintv/README.md
docs/admin/installation.rst
docs/applications/rubintv/index.rst
docs/documenteer.toml

- Delete automodsumm files before doing a link check
- Update the RubinTV URL and fix the application page style
- Add the new prompt-processing environment to the ignore list
- Document that you need to update the ignore list when adding new environments

Fix some documentation link issues

---

applications/onepassword-connect-dev/.helmignore
applications/onepassword-connect-dev/Chart.yaml
applications/onepassword-connect-dev/README.md
applications/onepassword-connect-dev/secrets.yaml
applications/onepassword-connect-dev/templates/_helpers.tpl
applications/onepassword-connect-dev/templates/idfdev-ingress.yaml
applications/onepassword-connect-dev/templates/idfdev-vault-secrets.yaml
applications/onepassword-connect-dev/values.yaml
docs/applications/index.rst
docs/applications/onepassword-connect-dev/index.rst
docs/applications/onepassword-connect-dev/values.md
environments/README.md
environments/templates/onepassword-connect-dev-application.yaml
environments/values-roundtable-dev.yaml
environments/values.yaml

This application will create the 1Password Connect API servers for all development and test 1Password vaults for SQuaRE-run Phalanx environments.
Because we need to create a separate subchart per 1Password vault and dependencies with aliases can't be templated using values.yaml, unfortunately we'll need to create two Phalanx applications, one that collects the API servers for the development and test vaults and runs on roundtable-dev, and one that collects the API servers for the production vaults and runs on roundtable. This is the one for development and test servers, starting with just IDF dev.

DM-40502: Add onepassword-connect-dev application

---

docs/developers/define-secrets.rst
docs/developers/update-a-onepassword-secret.rst
docs/documenteer.toml
docs/extras/schemas/environment.json
docs/internals/api.rst
environments/values-idfdev.yaml
requirements/dev.txt
requirements/main.in
requirements/main.txt
src/phalanx/cli.py
src/phalanx/exceptions.py
src/phalanx/factory.py
src/phalanx/models/applications.py
src/phalanx/models/environments.py
src/phalanx/models/secrets.py
src/phalanx/services/secrets.py
src/phalanx/storage/onepassword.py
tests/cli/secrets_test.py
tests/conftest.py
tests/data/input/environments/values-minikube.yaml
tests/data/input/environments/values.yaml
tests/data/input/onepassword/minikube.yaml
tests/data/input/vault/minikube/unknown.json
tests/data/output/minikube/sync-output
tests/data/output/minikube/values-after-add.yaml
tests/support/onepassword.py

Add new configuration options for environments that allow specifying a 1Password Connect server and Vault title. If those options are set for an environment, use that, via onepasswordconnectsdk, to retrieve static secrets provided that a separate static secrets YAML file was not given.
The layout used for 1Password is to have one 1Password item per application, with one field (without section nesting) for each secret.

DM-40501: Add 1Password support for static secrets

---

docs/developers/define-secrets.rst

Merge the warning with the note in the same section when describing the new method of adding static secrets for an application to 1Password.

DM-40501: Combine warning for 1Password app setup

---

docs/documenteer.toml

The prompt-processing environment is using k8s.slac.stanford.edu for its Argo CD URL. Phalanx doesn't handle this correctly yet, but we can at least ignore the broken link errors.

DM-40501: Ignore another Argo CD URL pattern

---

applications/strimzi/values-base.yaml
applications/strimzi/values-idfdev.yaml
applications/strimzi/values-idfint.yaml
applications/strimzi/values-minikube.yaml
applications/strimzi/values-tucson-teststand.yaml
applications/strimzi/values-usdfdev.yaml

- Strimzi loglevel was set to DEBUG in some environments, but logs are too chatty.

Change Strimzi loglevel to INFO

---

applications/sasquatch/Chart.yaml
applications/sasquatch/README.md
applications/sasquatch/values-base.yaml
applications/sasquatch/values.yaml

Deploy a second instance of Kapacitor and point it to its corresponding InfluxDB instance.
Enable it at base.

[DM-40662] Fix Kapacitor alerts crosstalk at base

---

applications/nublado/secrets-idfdev.yaml
docs/developers/define-secrets.rst
docs/developers/secrets-spec.rst
docs/extras/schemas/secrets.json
pyproject.toml
src/phalanx/models/applications.py
src/phalanx/models/environments.py
src/phalanx/models/secrets.py
src/phalanx/services/secrets.py
src/phalanx/storage/config.py
tests/cli/secrets_test.py
tests/data/input/applications/mobu/secrets.yaml
tests/data/input/onepassword/minikube.yaml
tests/data/output/minikube/onepassword/argocd.json
tests/data/output/minikube/onepassword/gafaelfawr.json
tests/data/output/minikube/onepassword/mobu.json
tests/support/data.py

Some of our secrets contain significant newlines, such as the AWS credentials and pgpass file for Butler. 1Password unfortunately does not allow embedded newlines in fields. The official solution to this problem is to use files, but files can no longer be attached to Server items and instead need to be separate Document items, which breaks our entire 1Password layout.
Instead, support encoding the secret in base64 when storing it in 1Password and decoding it when retrieving it. This should allow arbitrary values at the cost of some complexity and having to explicitly tag which secrets are encoded in base64.

DM-40501: Support encoding secrets in 1Password

---

applications/gafaelfawr/Chart.yaml

Pick up the Gafaelfawr 9.3.1 release, which has some improvements to error handling.

DM-40567: Bump version of Gafaelfawr

---

applications/sasquatch/values-usdfprod.yaml

We confirmed that the repairer connectors are affected similarly by the data corruption errors seen at usdf, and thus there's no need for them to be running since they don't help to mitigate the problem.

[DM-40723] Disable repairer connectors at USDF

---

applications/sasquatch/charts/strimzi-kafka/templates/mirrormaker2.yaml

- When enabled, the Strimzi Cluster Operator watches the connector and its tasks for failures and if in case of failures it automatically restarts them.

[DM-40741] Enable MM2 auto-restart feature

---

applications/datalinker/Chart.yaml

This will add the 2MASS HiPS tiles into the static list of paths in the bucket to scrape to make a list.

[DM-40761] Datalinker 1.6.2 for hosting 2MASS HiPS

---

applications/sasquatch/charts/strimzi-kafka/templates/users.yaml

In salobj, the ts-salkafka user also needs authorization to perform operations on kafka groups.

Extend ts-salkafka user access control to groups

---

applications/portal/Chart.yaml

The new Portal release broke the plugin to integrate with the Notebook Aspect.

Revert version of Portal

---

charts/cadc-tap/values.yaml

This includes the UWS version and the lsst-tap-service version.

[DM-40477] Update Qserv TAP version to 2.0.1

---

src/phalanx/cli.py
src/phalanx/constants.py
src/phalanx/models/vault.py
tests/cli/vault_test.py

Support outputting the credentials for the read Vault AppRole as a Vault Secret resource suitable for vault-secrets-operator.

DM-40790: Add --as-secret flag to create-read-approle

---

src/phalanx/cli.py
src/phalanx/services/vault.py
src/phalanx/storage/vault.py
tests/cli/vault_test.py
tests/data/input/environments/values-idfdev.yaml
tests/data/output/idfdev/audit-approle-extra
tests/data/output/idfdev/audit-approle-policy
tests/data/output/idfdev/audit-both-missing
tests/data/output/idfdev/audit-token-expired
tests/data/output/idfdev/audit-token-policy
tests/support/vault.py

Add phalanx vault copy-secrets, which copies all application secrets under the specified path into the Vault area for the specified environment, overwriting any existing secrets. This is primarily intended as a migration tool to move our existing secrets to the new Vault paths with the new access control model and active management.

DM-40790: Add a command to copy Vault secrets

---

src/phalanx/cli.py
src/phalanx/services/secrets.py
src/phalanx/services/vault.py
tests/cli/secrets_test.py
tests/cli/vault_test.py

Now that there are a bunch of other vault commands, it makes more sense to move this command, which operates only on Vault, into the vault command list.

DM-40790: Rename secrets vault-secrets to vault export-secrets

---

.github/workflows/docs.yaml

Now that we're generating API and (more importantly) CLI documentation from src/phalanx, regenerate documentation if files under those paths change.

DM-40790: Regenerate documentation if src changes

---

.pre-commit-config.yaml
applications/prompt-proto-service-hsc/Chart.yaml
applications/prompt-proto-service-hsc/README.md
applications/prompt-proto-service-hsc/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-hsc/values.yaml
applications/prompt-proto-service-latiss/Chart.yaml
applications/prompt-proto-service-latiss/README.md
applications/prompt-proto-service-latiss/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-latiss/values.yaml
applications/prompt-proto-service-lsstcam/Chart.yaml
applications/prompt-proto-service-lsstcam/README.md
applications/prompt-proto-service-lsstcam/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-lsstcam/values.yaml
applications/prompt-proto-service-lsstcomcam/Chart.yaml
applications/prompt-proto-service-lsstcomcam/README.md
applications/prompt-proto-service-lsstcomcam/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcam/values.yaml
charts/prompt-proto-service/Chart.yaml
charts/prompt-proto-service/README.md
charts/prompt-proto-service/templates/prompt-proto-service.yaml
charts/prompt-proto-service/values.yaml
docs/about/local-environment-setup.rst

This PR does some refactoring and documentation cleanup of the `prompt-proto-service-*` applications, then rewrites its handling of PostreSQL credentials to mount them as a file instead of through environment variables. This change (with the corresponding code in lsst-dm/prompt_prototype#83) will greatly simplify `prompt-proto-service` configuration in the future.

DM-36772: Migrate PostgreSQL credentials to mounted file

---

applications/prompt-proto-service-latiss/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-lsstcam/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcam/values-usdfdev-prompt-processing.yaml

This PR removes unwanted `vaultSecretsPath` overrides (see #2520) that should have been cleaned up on #2538.

DM-36772: Remove vault path overrides for prompt-proto-service.

---

applications/times-square/Chart.yaml

Deploys https://github.com/lsst-sqre/times-square/releases/tag/0.9.2

DM-40865: Update to Times Square 0.9.2

---

src/phalanx/cli.py
src/phalanx/exceptions.py
src/phalanx/models/environments.py
src/phalanx/models/vault.py
src/phalanx/services/secrets.py
src/phalanx/services/vault.py
src/phalanx/storage/vault.py
tests/cli/vault_test.py
tests/data/output/idfdev/audit-approle-extra
tests/data/output/idfdev/audit-approle-policy
tests/data/output/idfdev/audit-both-missing
tests/data/output/idfdev/audit-token-expired
tests/data/output/idfdev/audit-token-policy
tests/support/vault.py

- Shorten help summary for vault copy-secrets so it isn't truncated
- Allow token expiration to be null when reporting a newly-created token
- Add `token-` to write token display names since Vault forces that prefix
- Improve secrets audit output for unresolved secrets
- Audit pull-secret as well when auditing secrets

DM-40790: Fix secrets tool issues found during IDF dev testing

---

applications/argo-workflows/templates/vault-secrets.yaml
applications/argocd/templates/vault-secrets.yaml
applications/argocd/values-idfdev.yaml

There were stub secrets to allow argo-workflows to do SSO to Argo CD, but we never got that working. Remove those stub secrets and the Argo CD configuration, since they aren't being ported to the new secret management system.

DM-40790: Remove stub for Argo CD SSO for argo-workflows

---

applications/argocd/templates/vault-secrets.yaml

Now that we're including the clear-text admin password in the Vault Argo CD secret, template the Argo CD Kubernetes secret to exclude that key, since we don't want to write the Argo CD password into Kubernetes.

DM-40790: Template the Argo CD secret

---

applications/nublado/README.md
applications/nublado/templates/vault-secrets.yaml
applications/nublado/values-idfdev.yaml
applications/nublado/values.yaml
applications/postgres/values-idfdev.yaml
applications/vault-secrets-operator/values-idfdev.yaml
docs/admin/index.rst
docs/admin/migrating-secrets.rst
environments/values-idfdev.yaml

Convert idfdev to use Vault AppRole authentication instead of a token. Use the defaults for max token lifetime, since we're not imposing any particular limits. Use vault-credentials as the name of the secret instead of vault-secrets-operator so that we don't clash with the default secret name for the service account.
Use the new secrets path for IDF dev.
Remove the nublado2 postgres configuration for IDF dev, since it's no longer used. Add support for generating a nublado-lab-secret from the same Vault secret as the JupyterHub secret, both pulling down only specific fields via the templating supported by Vault Secrets Operator. This required adding a new parameter to the nublado Helm chart.
Add documentation for how to migrate an environment to the new secrets management system.

DM-40790: Convert IDF dev to the new secrets system

---

docs/admin/migrating-secrets.rst

The sphinx-prompt extension automatically adds the prompt character, so don't include it in the text of the command.

DM-40790: Remove prompt from prompt commands

---

applications/sasquatch/README.md
applications/sasquatch/charts/strimzi-kafka/README.md
applications/sasquatch/charts/strimzi-kafka/templates/schema-registry-ingress.yaml
applications/sasquatch/charts/strimzi-kafka/values.yaml
applications/sasquatch/values-idfdev.yaml
applications/sasquatch/values-tucson-teststand.yaml

Add ingress configuration to give external access to the SR API it  can be used in the TTS. 
Authentication will be implemented later.

[DM-40888] Expose Schema Registry API in Sasquatch

---

applications/ingress-nginx/README.md
applications/ingress-nginx/values.yaml

This now defaults to false, but Gafaelfawr support requires it.

Allow snippet annotations in ingress-nginx

---

applications/sasquatch/secrets.yaml

These may or may not be needed, but they seem to be needed on IDF dev for right now, so add them back until they can be reviewed.

DM-40790: Add some more secrets for Sasquatch

---

applications/datalinker/README.md
applications/datalinker/secrets-idfdev.yaml
applications/datalinker/templates/deployment.yaml
applications/datalinker/templates/vault-secrets.yaml
applications/datalinker/values-idfdev.yaml
applications/datalinker/values.yaml

Datalinker was installing a copy of the Butler secret. Switch to copying the secrets from nublado instead. This isn't correct on environments without secrets, so it will require some additional work.

DM-40790: Adjust datalinker secrets for new approach

---

docs/about/local-environment-setup.rst
docs/admin/requirements.rst

Be more explicit about how to find the right version of helm-docs. Point to the general local development environment setup instructions in the admin pages rather than repeating the same requirements.

DM-40889: Improve installation instructions

---

docs/admin/migrating-secrets.rst
docs/admin/troubleshooting.rst
docs/applications/cachemachine/bootstrap.rst
docs/developers/add-application.rst
docs/developers/create-an-application.rst
docs/documenteer.toml
src/phalanx/models/vault.py

- Fix date of new secrets management system
- Do not link directly to a `values.yaml` line number
- Improve the wording of the Safir pointer
- Ignore a bogus cross-reference due to a Sphinx bug
- Fix the link to Vault Secrets Operator documentation
- Remove references to prepulling recommended

DM-40889: Fix a bunch of small documentation issues

---

applications/ingress-nginx/secrets.yaml

The certificates used by ingress-nginx in environments that don't use cert-manager contain newlines and therefore have to be encoded when being stored in 1Password.

DM-40889: Mark ingress-nginx certs as encoded

---

docs/admin/installation.rst

Stop linking to nublado2, since that's no longer the recommended Notebook Aspect. Mention persistent volume claims as a possible source of POSIX home directories.

DM-40889: Tweak the install documentation

---

docs/admin/upgrade-windows.rst

Use links to the environments instead of FQDNs, and separate the Telescope and Site deployments from the weekly schedule of the IDF.

DM-40889: Update maintenance window summary

---

docs/admin/sync-argo-cd.rst

Having to use hard refresh in Argo CD was an artifact of using unpinned chart dependencies, which we have thankfully stopped using in favor of Mend Renovate PRs. This documentation is now therefore obsolete.

DM-40889: Stop telling people about hard refresh

---

docs/developers/add-external-chart.rst

Provide somewhat better naming advice for charts designed to install third-party charts. Tell people they are responsible for merging the Phalanx PRs. Document adding helm-docs comments to anything that Phalanx overrides.

DM-40889: Update external chart documentation

---

docs/developers/local-development.rst

Clean up the documentation for using minikube locally to use the sphinx-prompt extension and refer to other pages on setting up tools that aren't specific to minikube.

DM-40889: Update minikube documentation

---

applications/nublado/templates/vault-secrets.yaml

The change to support the new secret management system accidentally changed the path of the nublado lab secret on older environments. Fix that.

Fix nublado-lab-secret on old secret system

---

applications/exposurelog/secrets.yaml
applications/narrativelog/secrets.yaml
docs/about/repository.rst
docs/applications/_summary.rst.jinja
docs/applications/postgres/add-database.rst
docs/developers/deploy-from-a-branch.rst
docs/developers/upgrade.rst
docs/developers/write-a-helm-chart.rst

Document the trick of adding a checksum annotation to force restarts of the deployment. Stop telling people to add development versions to the Chart.yaml appVersion; for development tags, just use overrides of image.tag. Tell people they can sync their application in the science-platform app to revert development changes. Clarify documentation about Chart.yaml and pull secrets.

DM-40889: Improve developer documentation

---

applications/next-visit-fan-out/Chart.yaml
applications/next-visit-fan-out/README.md
applications/prompt-proto-service-hsc/Chart.yaml
applications/prompt-proto-service-hsc/README.md
applications/prompt-proto-service-latiss/Chart.yaml
applications/prompt-proto-service-latiss/README.md
applications/prompt-proto-service-lsstcam/Chart.yaml
applications/prompt-proto-service-lsstcam/README.md
applications/prompt-proto-service-lsstcomcam/Chart.yaml
applications/prompt-proto-service-lsstcomcam/README.md
charts/prompt-proto-service/Chart.yaml
charts/prompt-proto-service/README.md
docs/applications/next-visit-fan-out/index.rst
docs/applications/prompt-proto-service-hsc/index.rst
docs/applications/prompt-proto-service-latiss/index.rst
docs/applications/prompt-proto-service-lsstcam/index.rst
docs/applications/prompt-proto-service-lsstcomcam/index.rst

Improve the documentation pages, titles, and Chart.yaml descriptions for the prompt processing services. Explicitly note for the prompt processing services that they use a shared chart.

Improve prompt-processing descriptions

---

docs/applications/kubernetes-replicator/index.rst
docs/applications/linters/index.rst
docs/applications/obsloctap/index.rst
docs/applications/onepassword-connect-dev/index.rst
src/phalanx/cli.py
tests/cli/application_test.py
tests/docs/applications_test.py

Check that the application documentation page titles match our standard format and start with a capital letter. This should be handled automatically by the phalanx application create command going forward.

DM-40947: Add test for application descriptions

---

applications/alert-stream-broker/Chart.yaml
applications/giftless/Chart.yaml
applications/moneypenny/Chart.yaml
applications/monitoring/Chart.yaml
applications/plot-navigator/Chart.yaml
applications/strimzi/Chart.yaml
applications/telegraf/Chart.yaml
tests/config_test.py

The application chart version is meaningless in Phalanx because of how we use Helm and those charts, as is the chart version for shared charts in the charts directory. Enforce that it is always 1.0.0, matching the documentation, to ensure that no one gets confused by supposed semantic information in the chart version that doesn't mean anything.

DM-40947: Ensure all application charts use 1.0.0

---

applications/ook/secrets.yaml
applications/squarebot/secrets.yaml
environments/values-roundtable-dev.yaml
environments/values-roundtable-prod.yaml

This adds new `secrets.yaml` file for ook and squarebot that should be sufficient to get the roundtable-dev and roundtable-prod environments running under the new secrets infrastructure and 1Password Connect.

DM-40952: Add secrets.yaml for Ook and Squarebot

---

environments/values-roundtable-prod.yaml

Set up the 1Password Connect server for production environments on roundtable-prod.

DM-40890: Enable onepassword-connect on roundtable-prod

---

tests/config_test.py

Test that every application that installs a VaultSecret resource has a secrets.yaml or secrets-<environment>.yaml file that defines its secrets. Add a whitelist of applications that have not yet done this.

DM-40947: Add test for secrets.yaml files

---

src/phalanx/exceptions.py
src/phalanx/services/secrets.py
src/phalanx/storage/onepassword.py
tests/cli/secrets_test.py
tests/data/output/idfdev/secrets-audit
tests/data/output/minikube/audit-missing-output
tests/support/onepassword.py

Retrieve each 1Password item separately rather than using the bulk API so that we can do proper error reporting of all of the missing secrets we expected to be in 1Password but which weren't found. Throw that as an exception up through sync, but, in audit, catch that exception and properly report the missing secrets.

DM-40947: Better handling of missing 1Password secrets

---

src/phalanx/exceptions.py
src/phalanx/services/secrets.py
tests/cli/secrets_test.py
tests/support/onepassword.py

Report a proper exception including the application and secret key names if the value of a secret in 1Password that is marked as encoded is either invalid base64 or decodes to something that cannot be represented as a Unicode string.

DM-40947: Properly diagnose 1Password encoding errors

---

applications/datalinker/secrets.yaml

Currently, datalinker unconditionally expects the full Butler secret on every environment, so put that directly in secrets.yaml. Eventually that will change, but we'll cross that bridge later.
Change the names of the secrets to match what the application actually expects.

DM-40947: Fix datalinker secrets

---

applications/obsloctap/README.md
applications/obsloctap/secrets.yaml
applications/obsloctap/templates/deployment.yaml
applications/obsloctap/templates/vault-secrets.yaml
applications/obsloctap/values.yaml
applications/plot-navigator/README.md
applications/plot-navigator/secrets.yaml
applications/plot-navigator/templates/deployment.yaml
applications/plot-navigator/templates/vault-secrets.yaml
applications/plot-navigator/values.yaml
applications/production-tools/README.md
applications/production-tools/secrets.yaml
applications/production-tools/templates/deployment.yaml
applications/production-tools/templates/vault-secrets.yaml
applications/production-tools/values.yaml
docs/admin/migrating-secrets.rst
tests/config_test.py

Add configuration for the new secrets management system to obsloctap, plot-navigator, and production-tools. All of these only used the old Butler secret, so copy the secret from Nublado like we do for other uses of the Butler secret. As with datalinker, add a configuration option that determines whether to use the new per-application secret or the old shared Butler secret, and default it to false.
Fix some helm-docs comments around the image tag.

DM-40947: Add secrets config for more applications

---

docs/admin/audit-secrets.rst
docs/admin/migrating-secrets.rst
docs/admin/secrets-setup.rst
docs/admin/sync-secrets.rst

Rename the 1Password items used by SQuaRE to use Phalanx instead of RSP in the titles, since we include roundtable as well. Document where to find the admin token now that it's been moved back into the SQuaRE vault.

DM-40947: Update documentation for where to find tokens

---

src/phalanx/cli.py
src/phalanx/models/secrets.py

Now that we have a proper Pydantic model for static secrets, that class can gain a class method for loading it from a path, which can be used to simplify the CLI code.

DM-40947: Refactor static secret loading

---

docs/admin/installation.rst
docs/admin/secrets-setup.rst
docs/extras/schemas/environment.json
docs/extras/schemas/secrets.json
environments/README.md
environments/values-base.yaml
environments/values-ccin2p3.yaml
environments/values-idfdev.yaml
environments/values-idfint.yaml
environments/values-idfprod.yaml
environments/values-minikube.yaml
environments/values-roundtable-dev.yaml
environments/values-roundtable-prod.yaml
environments/values-summit.yaml
environments/values-tucson-teststand.yaml
environments/values.yaml
installer/install.sh
src/phalanx/models/environments.py
src/phalanx/models/secrets.py
src/phalanx/storage/vault.py

Add more annotations to the Pydantic models so that the generated schemas contain more details. Mark the Vault URL as an HTTP URL for Pydantic validation purposes. Set a default URL pointing to the SQuaRE Vault server so that most environments don't need to set it, and adjust the schema so that this will validate. Drop the now-obsolete onepasswordUuid enviroment setting.

DM-40947: Improve generated schemas

---

src/phalanx/constants.py
src/phalanx/models/secrets.py
src/phalanx/services/secrets.py
tests/data/output/idfdev/static-secrets.yaml

If a secret is marked as base64-encoded in 1Password, add a warning to the static secret template saying so, in case people are using that as a reference to decide what to put into 1Password.
This required some refactoring to export the correct fields from the static secrets model for a template. In the process, I fixed a few places where we may have incorrectly synced an empty pull secret when no pull secret was specified.

DM-40947: Add encoded secret warnings to static templates

---

applications/gafaelfawr/Chart.yaml

Pick up the new Gafaelfawr release, which has support for finding group membership by user DN. This will be required for the new Keycloak and LDAP configuration on T&S sites.

DM-23878: Bump version of Gafaelfawr

---

docs/about/contributing-docs.rst

The tox instructions under contributing documentation were using the legacy syntax (without the run keyword). Switch to the current syntax.

Use tox v4 syntax consistently

---

starters/web-service/templates/ingress.yaml

This is because this part of the yaml will be stripped after the CRD is made, making it look always out of sync.

[DM-40944] Get rid of ingressClass: nginx in the starter

---

applications/gafaelfawr/values-idfdev.yaml
applications/gafaelfawr/values-idfint.yaml

The problem was due to a bad WAF rule in their AWS infrastructure that was blocking connections from Google Cloud. This has now been fixed, so switch those environments back to the test CILogon.

DM-41075: Switch idfdev and idfint back to test CILogon

---

applications/vault-secrets-operator/values-roundtable-prod.yaml
environments/values-roundtable-prod.yaml

This follows the steps at: https://phalanx.lsst.io/admin/migrating-secrets.html
This PR also enables Squarebot on roundtable-prod so it can be a secrets source for Ook.

DM-40952: Migrate roundtable-prod to new secrets infrastructure

---

applications/gafaelfawr/README.md
applications/gafaelfawr/templates/cronjob-audit.yaml
applications/gafaelfawr/templates/cronjob-maintenance.yaml
applications/gafaelfawr/values.yaml

Set a deadline of five minutes for the Gafaelfawr cron jobs to run, and clean them up after a day (although the limit on the number of successful jobs to retain will override this for audits). Increase the CPU limits of these jobs, since they appear to use most of a CPU when running but don't really need it.

DM-41090: Set Gafaelfawr CronJob time limits, tweak resource limits

---

.github/workflows/ci.yaml
requirements/dev.in
requirements/dev.txt
requirements/main.txt
tox.ini

Install pytest-pretty as a dev dependency for better test summary output. Set CI when running pytest to force verbose diffs of data structures, and drop -vv so that pytest will show the shorter summary of tests in progress instead of printing the name of every test function on its own line.
Increase the column width for pytest-pretty output on GitHub Actions so that the table is more useful.

DM-40497: Improve pytest output with pytest-pretty

---

applications/cert-manager/values-usdfdev.yaml

cert-manager is disabled on usdfdev and the values-usdfdev.yaml file was out of date and didn't have the correct spelling of settings. Delete it; we can always make a new one should usdfdev start running cert-manager again.

DM-40497: Remove unused usdfdev cert-manager configuration

---

applications/strimzi/README.md
src/phalanx/storage/config.py

Although this chart does not need a non-environment values file, accounting for the case where it could be missing would require special code in the Phalanx tooling. It's easier to create an empty file and make the chart consistent with other charts.
Fix another warning during documentation generation.

DM-40497: Add empty values file for strimzi

---

.github/workflows/ci.yaml

The current installer script doesn't use any Python at all, so we don't need to install Python or any of its dependencies for minikube testing.

DM-40497: Stop installing Python for minikube testing

---

src/phalanx/cli.py
tests/cli/secrets_test.py

phalanx vault audit returned non-zero if there was audit output, but phalanx secrets audit did not. Make it match, and match the normal expectations of an audit tool.

DM-40497: Exit non-zero on secrets audit failure

---

applications/nublado/Chart.yaml

Install the 0.8.0 release, which has a lot of internal refactoring and better home directory configuration support.

DM-41051: Upgrade Nublado controller

---

applications/gafaelfawr/values.yaml

USDF dev was using 32MiB of memory for Gafaelfawr Redis for reasons that we don't understand, but this limit is low and there's no reason not to make it larger.

Bump Gafaelfawr Redis limit to 40MiB

---

applications/sasquatch/values-base.yaml

Summit EFD replication is not currently working at the base. Disable MM2 and related source deployments for the moment. The need for having two SR deployments will be reviewed when we replace the InfluxDB Sink connectors with the telegraf-based connectors.

Disable Summit EFD replication at the base

---

applications/nublado/values-idfint.yaml

Newer rsp-restspawner image is to give us a psql client; not strictly needed for operations, but vital for debugging why it wouldn't come up.

tickets/DM-41237: move to cloudsql on int

---

applications/gafaelfawr/Chart.yaml
applications/gafaelfawr/README.md
applications/gafaelfawr/templates/configmap.yaml
applications/gafaelfawr/values-idfdev.yaml
applications/gafaelfawr/values-idfint.yaml
applications/gafaelfawr/values-idfprod.yaml
applications/gafaelfawr/values-usdfdev.yaml
applications/gafaelfawr/values-usdfint.yaml
applications/gafaelfawr/values-usdfprod.yaml
applications/gafaelfawr/values.yaml

Update to Gafaelfawr 9.5.0 and add appropriate configuration to enable the CADC-specific user information endpoint on IDF and USDF environments running TAP servers.

DM-41186: Add CADC auth support

---

applications/nublado/Chart.yaml
applications/nublado/values-idfdev.yaml
applications/nublado/values-idfint.yaml

Update all environments to a new version of the Nublado controller, and update IDF dev and IDF int to the latest version of the RSP REST spawner container, which also uses the new JupyterHub.

DM-41350: Update version of Nublado

---

applications/nublado/README.md
applications/nublado/values-idfdev.yaml
applications/nublado/values-idfint.yaml
applications/nublado/values.yaml

This includes the JupyterHub 4.x migration. Remove the override from IDF dev and IDF int.

DM-41350: Switch Nublado to new JupyterHub by default

---

tests/docs/applications_test.py
tests/docs/environments_test.py

Test that all environments are documented and linked in the index file, and that all applications are linked in the index file. These will probably be caught once we can re-enable fatal Sphinx warnings, but for right now PRs were merged failing these tests.

Add more documentation tests

---

applications/alert-stream-broker/Chart.yaml
applications/alert-stream-broker/README.md
applications/alert-stream-broker/charts/alert-stream-broker/Chart.yaml
applications/alert-stream-broker/charts/alert-stream-broker/README.md
applications/alert-stream-broker/charts/alert-stream-broker/templates/kafka-topics.yaml
applications/alert-stream-broker/charts/alert-stream-broker/values.yaml
applications/alert-stream-broker/values-usdfdev-alert-stream-broker.yaml

Adding a test alert topic to use for sending alerts from the pipeline to the broker. This is separate from the current alert stream which is receiving data from the simulator.

DM-40416: Add test alert topic

---

applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml

The `spec-survey` survey is a new survey being run on AuxTel. Register it as a known survey that we _don't_ want to process.

Register spec-survey with Prompt Processing.

---

applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml

This is a partial revert of #2711, which ran afoul of a bug in `prompt_prototype` itself.

Revert "Register spec-survey with Prompt Processing."

---

applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml

This PR restores the configuration added in #2711 and reverted in #2712. It must be merged after lsst-dm/prompt_prototype#94 (which fixes the config parser so that it can actually handle hyphens).

DM-41658: Register spec-survey with Prompt Processing.

---

applications/nublado/Chart.yaml
applications/nublado/README.md
applications/ook/Chart.yaml
applications/ook/README.md
applications/siav2/Chart.yaml
applications/siav2/README.md
applications/squareone/values-idfdev.yaml
applications/squareone/values-idfint.yaml
applications/squareone/values.yaml
applications/tap/values-idfdev.yaml
docs/_rst_epilog.rst
docs/applications/ook/index.rst
docs/index.rst

Change www.lsst.io links to lsst.io, since www.lsst.io is now a redirect. Update the URLs for Nublado. Remove the link for SIAv2, which points to a nonexistent repository. Update the link for Ruff documentation.

Fix broken links

---

applications/prompt-proto-service-hsc/Chart.yaml
applications/prompt-proto-service-hsc/README.md
applications/prompt-proto-service-hsc/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-hsc/values.yaml
applications/prompt-proto-service-latiss/Chart.yaml
applications/prompt-proto-service-latiss/README.md
applications/prompt-proto-service-latiss/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-latiss/values.yaml
applications/prompt-proto-service-lsstcam/Chart.yaml
applications/prompt-proto-service-lsstcam/README.md
applications/prompt-proto-service-lsstcam/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-lsstcam/values.yaml
applications/prompt-proto-service-lsstcomcam/Chart.yaml
applications/prompt-proto-service-lsstcomcam/README.md
applications/prompt-proto-service-lsstcomcam/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcam/values.yaml
charts/prompt-proto-service/Chart.yaml
charts/prompt-proto-service/README.md
charts/prompt-proto-service/values.yaml

This PR updates the Phanalx configuration for `prompt-proto-service-*` to point to the new package name and the new container names. It makes no attempt to rename the service itself (deferred to [DM-41665](https://jira.lsstcorp.org/browse/DM-41665)).
This PR should be merged after lsst-dm/prompt_processing#96, though most of the changes that affect this PR are already visible.

DM-41664: Rename prompt_prototype package and containers

---

applications/sasquatch/README.md
applications/sasquatch/charts/strimzi-kafka/README.md
applications/sasquatch/charts/strimzi-kafka/values.yaml

- Also review log.retention.bytes parameter. log.retention.bytes specifies how much disk space Kafka will ensure is available. The recommendation is to set it to 70% of the data partition size.

Reduce kafka retention to 48h

---

applications/sasquatch/README.md
applications/sasquatch/values.yaml

- Set this limit by default to prevent long queries to use memory excessively and eventually restart the InfluxDB pod.

Add 60s query timeout to InfluxDB

---

applications/sasquatch/values-summit.yaml

- Increase the number of connector tasks to improve latency issues as reported by Petr when TMA/M1M3 tests restarted at the Summit.

Increase number of connector tasks for M1M3 and MTMount

---

applications/sasquatch/README.md
applications/sasquatch/values.yaml

- The 1s refresh option in Chronograf only works with dashboards that take less than 1s to update, most dashboards take longer, and this option is causing some confusion.It also seems unnecessary as human reactions to displays take longer than that. Users agree that a 5s refresh is enough, and the decision is to remove the 1s refresh option.

Remove the 1s refresh option for Chronograf dashboards

---

environments/values-summit.yaml

We've been running Nublado v3 by default for a while.

Disable nublado2 at the summit

---

applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml

This PR updates the release branch of Prompt Processing to use the `d_2023_11_22` tag as its "latest stable" version.

Update prompt processing to use d_2023_11_22.

---

applications/squareone/values-idfdev.yaml
applications/squareone/values-idfint.yaml
applications/squareone/values.yaml
docs/applications/ook/index.rst
docs/index.rst

www.lsst.io is the canonical URL, so use that everywhere.  It's no longer a redirect.

Switch lsst.io back to www.lsst.io

---

applications/sasquatch/values-usdfprod.yaml

- USDF EFD default proxy timeout is 60s. Some queries are taking longer to execute in both Chronograf and the EFD client.
- Increase both proxy timeout and the InfluxDB coordinator query timeout to 300s

Increase query timeout to 300s

---

applications/gafaelfawr/values-base.yaml

exec:admin is used to control Argo Workflows. For now, grant access to everyone with Kubernetes access to the cluster until we have a proper group for this purpose.

DM-23878: Add k8s-manke exec:admin on base

---

Makefile
applications/linters/secrets.yaml

The linters application was missing a secrets configuration. Add one.

DM-41954: Add secrets configuration for linters

---

.github/workflows/docs.yaml

Now on pull requests, only upload the docs if the content in the `docs/` directory itself changes. This saves us CI time for changes that incidentally change the docs; we still CI that the docs will build and the docs themselves will update on the final merge to main.
In re-working the conditional, I've also found that we don't have a good overall strategy for tags; we'd need to generally build the docs for any tag. I've dropped "tags" from the `on` clause. But if we decide to start tagging Phalanx we'd want to revisit that.
This also adds `applications/argocd/values-*.yaml` to the paths considered as sources for docs.

DM-41950: Don't upload docs on PRs that don't modify docs/ itself.

---

applications/sasquatch/README.md
applications/sasquatch/charts/kafka-connect-manager/README.md
applications/sasquatch/charts/kafka-connect-manager/values.yaml

- Rename the connector used in the default configuration of kafka-connect-manager to avoid overriding the test connector configuration.

Fix default connector configuration

---

applications/sasquatch/values-summit.yaml

- Disable InfluxDB v2 in favor of InfluxDB Enterprise

Disable InfluxDB v2 at the summit

---

applications/sasquatch/charts/strimzi-kafka/templates/mirrormaker2.yaml

- This fixes the warning "replication.policy.separator: A null value is not allowed for this key" that's spamming the Strimzi operator logs

Fix default value for replication.policy.separator

---

applications/gafaelfawr/Chart.yaml

Includes a fix for recovery after the Redis server was restarted.

DM-42093: Update Gafaelafwr to 9.6.1

---

applications/prompt-proto-service-hsc/README.md
applications/prompt-proto-service-hsc/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-hsc/values.yaml
applications/prompt-proto-service-latiss/README.md
applications/prompt-proto-service-latiss/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-latiss/values.yaml
applications/prompt-proto-service-lsstcam/README.md
applications/prompt-proto-service-lsstcam/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-lsstcam/values.yaml
applications/prompt-proto-service-lsstcomcam/README.md
applications/prompt-proto-service-lsstcomcam/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcam/values.yaml
charts/prompt-proto-service/README.md
charts/prompt-proto-service/templates/prompt-proto-service.yaml
charts/prompt-proto-service/values.yaml

This PR cleans up environment variables that stopped being used in #2538. We no longer have any containers that assume these variables are defined.

DM-40839: Remove obsolete environment variables from prompt-proto-service

---

applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml

This PR reverses the timeout decrease added on #2784 for LATISS only, as it turns out that some LATISS visits really do have a long delay.

DM-42155: LATISS image timeouts too short for start of imaging sequence

---

.github/workflows/docs.yaml
docs/about/repository.rst
docs/admin/index.rst
docs/admin/infrastructure/google/credentials.rst
docs/admin/infrastructure/google/index.rst
docs/admin/infrastructure/google/terraform.rst
docs/admin/installation.rst
docs/applications/livetap/index.rst
docs/applications/nublado/updating-recommended.rst
docs/applications/semaphore/index.rst
docs/applications/ssotap/index.rst
docs/applications/tap/index.rst
docs/environments/_summary.rst.jinja
docs/extras/schemas/environment.json
environments/values-idfdev.yaml
environments/values-idfint.yaml
environments/values-idfprod.yaml
environments/values-roundtable-dev.yaml
environments/values-roundtable-prod.yaml
src/phalanx/models/environments.py
tests/data/input/environments/values-idfdev.yaml
tests/docs/jinja_test.py

Add a way to fill out GCP hosting information for environments running on GKE, and expose that information in the generated environments documentation along with links to the Google Console and Log Explorer.
Relocate the authentication source information nearer to the top of the environment documentation both to consolidate shorter data and to move it above the application list, which is usually long enough to push it off the first page.
Document how to get Kubernetes credentials for GKE-hosted projects (the goal that started this PR), and add a stub page about Terraform with little useful content as yet.
While working on this, I noticed that bare GitHub links get useful automatic formatting, so did a pass through all the documentation and used that construction in more places where the …

DM-36957: Add GCP information to documentation

---

.github/workflows/ci.yaml
.github/workflows/dependencies.yaml
.github/workflows/docs.yaml
.github/workflows/linkcheck.yaml
.pre-commit-config.yaml
pyproject.toml
tests/support/helm.py

- Update all pre-commit plugins to the latest versions
- Switch to using Ruff to format code instead of Black
- Update the Ruff configuration based on Nublado
- Update the versions of Vault and Argo CD used for minikube CI
- Update Python to 3.12 everywhere in CI except the Python tests
- Test Python code with both 3.11 and 3.12

Update pre-commit and CI dependencies

---

.github/workflows/docs.yaml

The conditional deciding whether to upload changes after a merge to the main branch was using the wrong GitHub variable.
Also unconditionally build documentation and upload if the workflow was triggered with workflow dispatch, instead of checking the documentation filter.

Fix the rule for upload of documentation

---

charts/cadc-tap/README.md
charts/cadc-tap/values.yaml

tap schema release is already there.

[DM-42069] Advance datalink to 2.1.6

---

applications/mobu/Chart.yaml
applications/mobu/templates/deployment.yaml
applications/mobu/values-idfdev.yaml
applications/mobu/values-idfint.yaml
applications/mobu/values-idfprod.yaml
applications/mobu/values-usdfdev.yaml
applications/mobu/values-usdfint.yaml
applications/mobu/values-usdfprod.yaml

Update the Phalanx configuration for the mobu 7.0.0 release, which changes environment variable names, drops support for cachemachine, and renames some monkey businesses.

DM-42225: Upgrade mobu to 7.0.0

---

applications/sasquatch/values-usdfdev.yaml

Add the `lsst.prompt` namespace to Sasquatch, it assumes the messages have a `timestamp` column, and results will be recorded in the `lsst.prompt` database in InfluxDB. To start use the same set of tags used in `lsst.dm`.

Add the lsst.prompt namespace to Sasquatch

---

applications/nublado/README.md
applications/nublado/templates/hub-configmap.yaml
applications/nublado/values.yaml
docs/applications/onepassword-connect/add-new-environment.rst

Clean up various bits of configuration found while working on the Nublado manual.
- Use the Nublado controller lab spawn timeout as the JupyterHub lab spawn timeout as well, rather than having two separate configuration settings.
- Remove possibly-outdated information from the JupyterHub ConfigMap.
- Add default resource limits for the Nublado controller.
- Add affinity, nodeSelector, and tolerations settings for user labs and user file servers to values.yaml.
- Delete the hopefully-now-obsolete singleuser Zero to JupyterHub settings.
- Quote all strings in the Nublado values.yaml.
- Use entry points for JupyterHub plugins.
- Sort and improve descriptions of Nublado Helm values.

DM-38714: General Nublado configuration cleanups

---

applications/nublado/README.md
applications/nublado/values-base.yaml
applications/nublado/values-idfdev.yaml
applications/nublado/values-idfint.yaml
applications/nublado/values-idfprod.yaml
applications/nublado/values-summit.yaml
applications/nublado/values-tucson-teststand.yaml
applications/nublado/values.yaml

The Nublado file servers should not expose every volume mounted in lab containers. Instead, expose only explicitly configured mounts, similiar to init containers, and expose only the home directory mount on idfdev and idfint.

DM-41979: Require explicit volume mounts for Nublado file servers

---

applications/butler/Chart.yaml
applications/butler/README.md
applications/butler/templates/deployment.yaml
applications/butler/templates/ingress-anonymous.yaml
applications/butler/templates/ingress-authenticated.yaml
applications/butler/values-idfdev.yaml
applications/butler/values-idfint.yaml
applications/butler/values-idfprod.yaml
applications/butler/values.yaml
environments/values-idfint.yaml

Butler server is now able to serve multiple repositories from a single service.  Updated configuration to point to a repository index file instead of a single Butler configuration file.  Added ingresses for each of the repositories.
From the client's perspective, the server it is connecting to is "/api/butler/repo/dp02".  The theory is that in the future we may need separate Butler services for each repository, but at the moment it is excessive to have a separate Butler server for each.  
Also went ahead and added Butler to idfint, as well as a disabled configuration for idfprod.

DM-42189: Update Butler for multi-repo server

---

applications/nublado/templates/controller-ingress-hub.yaml

Ensure that JupyterHub only has access to the routes that it needs to use, and block access to the prepuller and fileserver admin routes to anyone other than exec:admin.

DM-42337: More granular permissions for Nublado controller

---

applications/sasquatch/secrets.yaml

This appears to always be referenced by the strimzi-kafka subchart since it is referenced in the values.yaml file. For the time being, make it unconditional, although I think the logic for deciding what secrets are required may still not be correct.

Make telegraf-password unconditional in sasquatch

---

docs/applications/nublado/troubleshoot.rst
docs/applications/nublado/upgrade.rst

Rework the Nublado upgrading documentation and reference new pages in the Nublado manual. Make clear that deleting user sessions from the database should no longer be necessary, and link to the Nublado manual for how to do it instead of reproducing those instructions in Phalanx.

DM-42337: Improve Nublado documentation

---

applications/strimzi/values-idfint.yaml

Tell strimzi to stop watching alert-stream-broker on idfint, since we no longer deploy it there.

Stop watching alert-stream-broker on idfint

---

applications/nublado-fileservers/Chart.yaml
applications/nublado/README.md
applications/nublado/values.yaml
environments/templates/nublado-fileservers-application.yaml
tests/docs/applications_test.py

For consistency with nublado-users, and to ensure that both of the user application buckets sort together, rename fileservers to nublado-fileservers. This is the application and namespace in which Nublado creates user file servers.

DM-42477: Rename fileservers to nublado-fileservers

---

applications/nublado-fileservers/templates/_helpers.tpl
applications/nublado-fileservers/templates/networkpolicy.yaml

Add a NetworkPolicy to the nublado-fileservers namespace that affects all file servers and restricts access to Gafaelfawr. Otherwise, users inside the cluster can connect directly to anyone's file server as them.

DM-42477: Add NetworkPolicy for Nublado file servers

---

applications/nublado/README.md
applications/nublado/values.yaml
environments/templates/nublado-fileservers-application.yaml

Unfortunately, we cannot use nublado-fileservers as the namespace for user file servers since it conflicts with the namespace pattern used by Nublado for labs. Keep the namespace of fileservers but still use nublado-fileservers as the Argo CD application for appropriate sorting in the Argo CD application display.

DM-42477: Switch back to fileservers for user file servers

---

applications/sasquatch/README.md
applications/sasquatch/charts/strimzi-kafka/README.md
applications/sasquatch/charts/strimzi-kafka/values.yaml
applications/sasquatch/secrets-idfint.yaml
applications/sasquatch/secrets.yaml
applications/sasquatch/values-base.yaml
applications/sasquatch/values-idfdev.yaml
applications/sasquatch/values-idfint.yaml
applications/sasquatch/values-summit.yaml
applications/sasquatch/values-tucson-teststand.yaml
applications/sasquatch/values-usdfdev.yaml
applications/sasquatch/values-usdfint.yaml
applications/sasquatch/values-usdfprod.yaml
applications/sasquatch/values.yaml

- Review Sasquatch secret definitions and conditionals. I've noticed that secret conditionals don't work if a component is enabled at the subchart level, for example, in `sasquatch/charts/strimzi-kafka/values.yaml`:
```
users:
replicator:
enabled: true
```
and  `sasquatch/secrets.yaml`:
```
replicator-password:
description: >-
replicator KafkaUser password.
if: strimzi-kafka.users.replicator.enabled
```
A way around this was disabling the component by default at the subchart level and explicitly enabling it at the top level,  in `sasquatch/values-idfdev.yaml` in this case.
This is related to #2839,  where we made the `telegraf-password` secret unconditional in Sasquatch.
- Add ghcr.io write token to Sasquatch secrets, it is required by Strimzi to build custom Kafka Connect images.

[DM-42456] Add the ghcr.io write token to Sasquatch secrets

---

applications/jira-data-proxy/.helmignore
applications/jira-data-proxy/Chart.yaml
applications/jira-data-proxy/README.md
applications/jira-data-proxy/secrets.yaml
applications/jira-data-proxy/templates/_helpers.tpl
applications/jira-data-proxy/templates/configmap.yaml
applications/jira-data-proxy/templates/deployment.yaml
applications/jira-data-proxy/templates/hpa.yaml
applications/jira-data-proxy/templates/ingress.yaml
applications/jira-data-proxy/templates/networkpolicy.yaml
applications/jira-data-proxy/templates/service.yaml
applications/jira-data-proxy/templates/vault-secret.yaml
applications/jira-data-proxy/values-idfdev.yaml
applications/jira-data-proxy/values-usdfdev.yaml
applications/jira-data-proxy/values.yaml
docs/applications/index.rst
docs/applications/jira-data-proxy/index.rst
docs/applications/jira-data-proxy/values.md
environments/README.md
environments/templates/jira-data-proxy-application.yaml
environments/values-idfdev.yaml
environments/values-usdfdev.yaml
environments/values.yaml

Developed at https://github.com/lsst-sqre/jira-data-proxy the jira-data-proxy provides a read-only (only GET methods) proxy to the Jira REST API. A user can access this proxy using their common Gafaelfawr token and send GET requests to the Jira API through the proxy, which uses a built-in LDAP credential.
This service is developed for Times Square reports and intended to be deployed for Rubin staff at USDF.

DM-42460: Add new jira-data-proxy application

---

src/phalanx/services/application.py

If an application that is the target of a phalanx application template command has no dependency Helm repositories, avoid running a helm repo update. Since we added no repositories, helm repo update may fail if the user has no Helm repositories defined.

Avoid helm repo update on application template

---

applications/gafaelfawr/README.md
applications/gafaelfawr/values.yaml

The limits were too tight to run gafaelfawr audit --fix.

Bump limits for gafaelfawr-operator pod

---

applications/datalinker/templates/ingress-image.yaml

In order to work with Butler client/server, Datalinker will need to get a delegated token for making a request to the Butler server on behalf of the caller.

DM-42190: Add delegated token for datalinker links

---

applications/sasquatch/secrets.yaml
applications/sasquatch/templates/vault-secrets.yaml

- Strimzi requires a secret of type `kubernetes.io/dockerconfigjson` to push images to ghcr.io. Add a secret to sasquatch with the `.dockerconfigjson` key and a `VaultSecret` resource to create the `sasquatch-connect-push-secret` secret.

[DM-42596] Add secret to push Strimzi Kafka Connect images to ghcr.io
