lsst-sqre/phalanx

applications/nublado/README.md
applications/nublado/templates/vault-secrets.yaml
applications/nublado/values-tucson-teststand.yaml
applications/nublado/values.yaml

Putting arbitrary new settings into the controller isn't supported. Move the new setting to secrets like the other secret-related flag.

Fix location of T&S Kafka setting in Nublado

---

applications/sasquatch/charts/strimzi-kafka/templates/kafka.yaml

- This addresses the error "Queue length 1024 exceeded, stopping operator. Please increase STRIMZI_MAX_QUEUE_SIZE environment variable." seen in Strimzi entity operator when upgrading to version 0.39.0

Increase STRIMZI_MAX_QUEUE_SIZE

---

applications/next-visit-fan-out/values-usdfdev-prompt-processing.yaml
applications/next-visit-fan-out/values-usdfprod-prompt-processing.yaml

This PR updates `next-visit-fan-out` with bug fixes ahead of the January 29 -- February 2 AuxTel run.

DM-42677: Don't forward visits with instrument=""

---

applications/sasquatch/README.md
applications/sasquatch/charts/influxdb-enterprise/README.md
applications/sasquatch/charts/influxdb-enterprise/templates/data-pdb.yaml
applications/sasquatch/charts/influxdb-enterprise/templates/meta-pdb.yaml
applications/sasquatch/charts/influxdb-enterprise/values.yaml

- Add Pod Disruption Budgets to InfluxDB Enterprise meta and data pods to help protect against some voluntary disruptions, e.g. `kubectl drain`

[DM-42691] Add Pod Disruption Budgets for meta and data pods

---

applications/butler/Chart.yaml
applications/datalinker/Chart.yaml
applications/datalinker/README.md
applications/datalinker/templates/deployment.yaml
applications/datalinker/values-idfdev.yaml
applications/datalinker/values-idfint.yaml
applications/datalinker/values-idfprod.yaml
applications/datalinker/values.yaml
docs/extras/schemas/environment.json
environments/README.md
environments/templates/datalinker-application.yaml
environments/values-idfdev.yaml
environments/values-idfint.yaml
environments/values-idfprod.yaml
environments/values.yaml
src/phalanx/models/environments.py
src/phalanx/services/application.py

Upgraded datalinker and Butler server to versions that are able to work with each other.  Configured datalinker deployments in all IDF environments to use Butler server instead of connecting directly to the Butler database.  Enabled Butler server on idfprod.
Butler repositories for services using Butler server are now configured by putting the list of repositories in an environment variable, instead of a URI pointing to a file containing the list of repositories.  The file is currently hosted on S3, which services will no longer have credentials for in the near future.

DM-42660: Use Butler server for Datalinker on IDF

---

applications/datalinker/README.md
applications/datalinker/secrets.yaml
applications/datalinker/templates/deployment.yaml
applications/datalinker/templates/ingress-anonymous.yaml
applications/datalinker/templates/ingress-image.yaml
applications/datalinker/templates/ingress-tap.yaml
applications/datalinker/values-idfdev.yaml
applications/datalinker/values-idfint.yaml
applications/datalinker/values-idfprod.yaml
applications/datalinker/values-usdfdev.yaml
applications/datalinker/values-usdfprod.yaml
applications/datalinker/values.yaml
applications/nublado/templates/controller-deployment.yaml

Update the names of the environment variables in preparation for the new release. Add pathPrefix, hipsPathPrefix, and logLevel settings that are passed through to the application. Add support for configuring Slack alerts for uncaught exceptions and enable them in the environments where we normally enable them.
Set resource requests and limits for datalinker based on its current production usage.
Fix setting of Nublado controller resources, noticed when looking at it as a template for datalinker.

DM-42689: Update datalinker chart for 1.7.0 changes

---

applications/nublado/values-base.yaml
applications/nublado/values-summit.yaml
applications/nublado/values-tucson-teststand.yaml

The image configuration was specified with underscores instead of camel-case, which hasn't been valid for a while.

Fix incorrect settings for T&S Nublado

---

applications/prompt-proto-service-hsc/README.md
applications/prompt-proto-service-hsc/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-hsc/values.yaml
applications/prompt-proto-service-latiss/README.md
applications/prompt-proto-service-latiss/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-latiss/values.yaml
applications/prompt-proto-service-lsstcam/README.md
applications/prompt-proto-service-lsstcam/values.yaml
applications/prompt-proto-service-lsstcomcam/README.md
applications/prompt-proto-service-lsstcomcam/values.yaml
charts/prompt-proto-service/README.md
charts/prompt-proto-service/templates/prompt-proto-service.yaml
charts/prompt-proto-service/values.yaml

This PR adds configurable Sasquatch support to the Prompt Processing service. At present, it's only possible to upload to Sasquatch on `usdfdev`, not `usdfprod`.
This PR must be merged after lsst-dm/prompt_processing#107.

DM-40823: Explore methods for calculating Prompt Processing preload timing

---

src/phalanx/cli.py
tests/config_test.py

Enforce restrictions on application names. They must start with a lowercase character and consist only of lowercase characters, digits, and hyphen. Enforce this in phalanx application create and with a separate test.

DM-42714: Reject application names containing underscore

---

docs/developers/add-application.rst
docs/developers/deploy-from-a-branch.rst
docs/developers/upgrade.rst
docs/developers/write-a-helm-chart.rst

Add some more explicit documentation for how to test development versions of an application, and reference pullPolicy in that documentation.
Add explicit documentation of the restrictions on application names, and mention blank lines between settings in values.yaml.

DM-42714: Document testing development versions

---

docs/_rst_epilog.rst
docs/developers/write-a-helm-chart.rst

Our default starter does not provide any writable file systems for the application. Document how to mount a writable /tmp, and caution against using it for large files.

DM-42714: Document mounting a writable /tmp

---

docs/admin/installation.rst
docs/admin/requirements.rst
docs/developers/add-application.rst

Tell people not to use the Argo CD command-line client to create applications. Some folks have attempted to do this and gotten into trouble.

DM-42714: Warn against using the Argo CD client

---

applications/ook/Chart.yaml
applications/ook/README.md

This update deals with technotes that are missing update date metadata.

DM-42705: Update ook to 0.9.1

---

applications/cert-manager/values-roe.yaml
applications/nublado/values-roe.yaml
applications/postgres/values-roe.yaml
applications/squareone/values-roe.yaml
applications/tap/values-roe.yaml
applications/vault-secrets-operator/values-roe.yaml

PR contains a set of changes specific to the roe environment for the RSP instance being operated in Edinburgh.
**Changes:**
- Updated vault-secrets-operator, enabling approles to be used instead of tokens.
- Added ROE Notebook GitHub repo for Nublado
- Added ROE-specific content / description for squareone:
- Update Qserv IP in tap application
- Set createIssuer to false in certmanager application:
**Tests:**
- Changes have been tested on a dev environment
- precommit run successfully locally

Updates to ROE env (Notebook repos, Nublado4, Vault approles, New Qserv)

---

applications/butler/Chart.yaml

Upgrade Butler to server-1.0.2, which supports the chained datastore configuration on idfprod.

DM-42660: Bump Butler version

---

charts/cadc-tap/README.md
charts/cadc-tap/values.yaml

For DP0.2, this version adds a number of foreign-key relationships to TAP_SCHEMA and improves UCD and units annotations for keys and times.

DM-41652: Advance to sdm_schemas 2.3.0 for DP0.2/Qserv-backed TAP.

---

docs/applications/filestore-backup/index.rst
docs/applications/filestore-backup/values.md
docs/developers/index.rst
docs/developers/injected-values.rst
docs/developers/write-a-helm-chart.rst
docs/documenteer.toml
docs/extras/schemas/secrets.json
src/phalanx/models/environments.py
src/phalanx/models/secrets.py

Add documentation for Argo CD injection of values into the application and describe the default injected values. Include documentation for how to add new ones.
Fix various problems with the documentation build and incorrect capitalization of filestore-backup.

DM-42714: Document value injection

---

applications/vo-cutouts/Chart.yaml
applications/vo-cutouts/README.md
applications/vo-cutouts/templates/configmap.yaml
applications/vo-cutouts/templates/deployment.yaml
applications/vo-cutouts/templates/ingress.yaml
applications/vo-cutouts/templates/worker-deployment.yaml
applications/vo-cutouts/values.yaml
environments/templates/vo-cutouts-application.yaml

Updated vo-cutouts to use Butler client/server instead of a direct postgres connection.  It now requests a delegated token from Gafaelfawr to pass to Butler server.

DM-42191: Support Butler client-server for vo-cutouts

---

applications/mobu/values-roe.yaml

This PR modifies the mobu chart config for the roe environmnent, to use the TAPQueryRunner to run three TAP Queries for health-checking purposes
Improvement
- Tested in dev environment
- Formatting tested with pre-commit

Modify mobu for the roe environment to test TAP only with list of queries

---

applications/sasquatch/values-usdfdev.yaml
applications/sasquatch/values-usdfint.yaml

This PR registers `pipeline` as a Sasquatch tag in the `lsst.verify` namespace in both the `-dev` and `-int` environments. This PR should have been merged alongside lsst-dm/jenkins-dm-jobs#976, which added `pipeline` to upload metadata.

DM-42419 hotfix: Treat pipeline as tag in Sasquatch metrics.

---

applications/squarebot/Chart.yaml
applications/squarebot/README.md
applications/squarebot/templates/configmap.yaml
applications/squarebot/templates/deployment.yaml
applications/squarebot/values-roundtable-prod.yaml
applications/squarebot/values.yaml

See https://github.com/lsst-sqre/squarebot/pull/28
Squarebot 0.8 no longer uses the schema registry. Some environment variables also changed names with the use of autoprefixing in pydantic-settings.
Merge before #2950

DM-42875: Deploy Squarebot 0.8.0

---

docs/about/secrets.rst
docs/admin/add-new-secret.rst
docs/admin/index.rst
docs/admin/migrating-secrets.rst
docs/admin/update-a-secret.rst
docs/applications/onepassword-connect/add-new-connect-server.rst
docs/applications/onepassword-connect/add-new-environment.rst
docs/developers/define-secrets.rst
docs/developers/index.rst
docs/developers/update-a-secret.rst
docs/developers/write-a-helm-chart.rst
requirements/dev.in
requirements/dev.txt
requirements/main.txt

Several documentation pages about updating secrets were in the developer section, but secrets can generally only be updated by admins. Move the documentation into the appropriate place and tell developers to ask their platform administrators about secrets.
Break down the documentation in a hopefully simpler way with separate pages for adding and updating secrets for administrators to follow.
Note that currently I'm the only person with access to create new 1Password integrations.

DM-42714: Move around secrets documentation

---

applications/jira-data-proxy/values-roundtable-dev.yaml
applications/sasquatch/charts/square-events/templates/unfurlbot-user.yaml
applications/unfurlbot/.helmignore
applications/unfurlbot/Chart.yaml
applications/unfurlbot/README.md
applications/unfurlbot/secrets.yaml
applications/unfurlbot/templates/_helpers.tpl
applications/unfurlbot/templates/configmap.yaml
applications/unfurlbot/templates/deployment.yaml
applications/unfurlbot/templates/gafaelfawrtoken.yaml
applications/unfurlbot/templates/hpa.yaml
applications/unfurlbot/templates/kafkaaccess.yaml
applications/unfurlbot/templates/kafkauser-secret.yaml
applications/unfurlbot/templates/networkpolicy.yaml
applications/unfurlbot/templates/service.yaml
applications/unfurlbot/templates/vaultsecret.yaml
applications/unfurlbot/values-roundtable-dev.yaml
applications/unfurlbot/values.yaml
docs/applications/index.rst
docs/applications/unfurlbot/index.rst
docs/applications/unfurlbot/values.md
environments/README.md
environments/templates/unfurlbot-application.yaml
environments/values-roundtable-dev.yaml
environments/values-roundtable-prod.yaml
environments/values.yaml

This app consumes from Sasquatch/Kafka topics produced by Squarebot for Slack traffic. Currently the app doesn't expose an external endpoint, it's only a Kafka consumer.

DM-42877: Add unfurlbot application for Squarebot

---

docs/developers/add-application.rst
docs/developers/deploy-from-a-branch.rst
docs/developers/index.rst
docs/developers/switch-environment-to-branch.rst

Add a new documentation page on how to switch science-platform itself to a branch to test deployment of a new application. Link to it in the appropriate places.

DM-42714: Document testing a new application

---

docs/_rst_epilog.rst
docs/about/local-environment-setup.rst

Document that Python 3.11 or later is required in local environment setup. Document that helm-docs may be out of date if tox -e lint creates a bunch of spurious changes.

DM-42714: Document the required version of Python

---

charts/cadc-tap/README.md
charts/cadc-tap/values.yaml

Update tap image and datalinkPayloadUrl to 2.4.0 release of sdm_schemas.

Update sdm_schemas to 2.4.0 release

---

applications/sasquatch/values-usdfprod.yaml

- Since we are running InfluxDB Enterprise now we can disable InfluxDB OSS and release the PVs

Disable InfluxDB OSS at USDF

---

docs/about/contributing-docs.rst
docs/about/edit-on-github.rst
docs/about/index.rst
docs/about/local-environment-setup.rst
tox.ini

Also re-enable documentation build failures on syntax errors, and change some code blocks to prompt blocks for better formatting.

DM-42714: Add documentation for editing on GitHub

---

docs/_rst_epilog.rst
docs/admin/infrastructure/google/index.rst
docs/admin/infrastructure/google/workload-identity.rst
docs/developers/write-a-helm-chart.rst

Add documentation for developers about how to set up the Kubernetes service account, and for administrators on how to configure workload identity in Terraform.

DM-42714: Add instructions for workload identity

---

applications/argocd/values-idfdev.yaml
applications/argocd/values-idfint.yaml
applications/argocd/values-idfprod.yaml
applications/argocd/values-roundtable-dev.yaml
applications/argocd/values-roundtable-prod.yaml
applications/argocd/values-usdf-tel-rsp.yaml
applications/argocd/values-usdfdev.yaml
applications/argocd/values-usdfint.yaml
applications/argocd/values-usdfprod.yaml
applications/gafaelfawr/values-base.yaml
applications/gafaelfawr/values-idfdev.yaml
applications/gafaelfawr/values-idfint.yaml
applications/gafaelfawr/values-idfprod.yaml
applications/gafaelfawr/values-minikube.yaml
applications/gafaelfawr/values-roundtable-dev.yaml
applications/gafaelfawr/values-roundtable-prod.yaml
applications/gafaelfawr/values-summit.yaml
applications/gafaelfawr/values-tucson-teststand.yaml
applications/gafaelfawr/values-usdf-tel-rsp.yaml
applications/gafaelfawr/values-usdfdev.yaml
applications/gafaelfawr/values-usdfint.yaml
applications/gafaelfawr/values-usdfprod.yaml
docs/applications/argocd/authentication.rst
tests/data/input/applications/argocd/values-idfdev.yaml
tests/data/input/applications/gafaelfawr/values-idfdev.yaml
tests/data/input/applications/gafaelfawr/values-minikube.yaml
tests/data/output/idfdev/argocd-rbac-rst

Remove obsolete users from Argo CD RBAC and Gafaelfawr's list of initial administrators.

DM-43148: Remove obsolete users

---

applications/prompt-proto-service-hsc/README.md
applications/prompt-proto-service-hsc/values.yaml
applications/prompt-proto-service-latiss/README.md
applications/prompt-proto-service-latiss/values.yaml
applications/prompt-proto-service-lsstcam/README.md
applications/prompt-proto-service-lsstcam/values.yaml
applications/prompt-proto-service-lsstcomcam/README.md
applications/prompt-proto-service-lsstcomcam/values.yaml
charts/prompt-proto-service/README.md
charts/prompt-proto-service/values.yaml

This PR gives each service an instrument-specific namespace (one of the few cases where our config depends on the instrument and not the environment 🙂).
The instrument-specific namespaces are already available on `-dev` (alongside the old one), so this update can be deployed there at any time. On `-prod`, we will need to coordinate deployment carefully with a schema rename in the APDB, so as to not interfere with active observing (aiming for midday PST on Monday).

DM-42997: Separate APDBs for different instruments in Prompt Processing

---

applications/alert-stream-broker/README.md
applications/alert-stream-broker/charts/alert-stream-broker/templates/kafka.yaml
applications/alert-stream-broker/charts/alert-stream-schema-registry/README.md
applications/alert-stream-broker/charts/alert-stream-schema-registry/values.yaml

Updates the alert stream schema registry to point to the new, updated schema image.

DM-40414: Write PipelineTask to transmit alerts to Kafka

---

environments/values-idfdev.yaml

We don't use this package there (it's only for T&S sites), so stop installing it and thus having to upgrade it.

Disable argo-workflows on data-dev

---

charts/cadc-tap/README.md
charts/cadc-tap/values.yaml

Stop hiding the version numbers of components from the generated documentation. Fix some capitalization and markup issues, and remove a stray Vault secrets path setting that isn't used.

Redo documentation for shared cadc-tap chart

---

docs/applications/vault/index.rst
docs/applications/vault/migration.rst
docs/applications/vault/upgrade.rst

Several of the links in the new Vault documentation were incorrect. Stop linking to the UI; we don't want anyone to use it.

Fix broken links in documentation

---

applications/unfurlbot/Chart.yaml
applications/unfurlbot/README.md
applications/unfurlbot/templates/configmap.yaml
applications/unfurlbot/templates/deployment.yaml
applications/unfurlbot/values.yaml
environments/values-roundtable-prod.yaml

This redis instance is used to maintain a memory of issues already unfurled per channel or thread.

DM-43124: Add Redis to Unfurlbot

---

applications/gafaelfawr/values-base.yaml

Rather than using the DNS round-robin, which a running Gafaelfawr doesn't honor properly anyway, point directly to the main replica at the base cluster. This more closely parallels the configuration that we'll use for the summit.

DM-43177: Switch base cluster to named LDAP server

---

applications/gafaelfawr/values-summit.yaml
applications/nublado/values-summit.yaml

Configure the summit for IPA authentication instead of GitHub. Switch to the new home directory NFS server and path, which will have the user files under the new usernames.

DM-43177: Reconfigure the summit authentication

---

applications/sasquatch/README.md
applications/sasquatch/charts/strimzi-kafka/README.md
applications/sasquatch/charts/strimzi-kafka/templates/users.yaml
applications/sasquatch/charts/strimzi-kafka/values.yaml
applications/sasquatch/secrets.yaml
applications/sasquatch/values-base.yaml
applications/sasquatch/values-summit.yaml
applications/sasquatch/values-usdfdev.yaml
applications/sasquatch/values-usdfint.yaml
applications/sasquatch/values-usdfprod.yaml

This user has broad permissions as a Kafka consumer.
The app can authenticate as user "consdb" and password corresponding to the consdb-password from the sasquatch secret / vault item.
The password is automatically provisioned in vault with Phalanx secrets.

DM-43218: Add consdb KafkaUser

---

applications/argocd/Chart.yaml
applications/argocd/README.md
applications/argocd/values-base.yaml
applications/argocd/values-ccin2p3.yaml
applications/argocd/values-idfdev.yaml
applications/argocd/values-idfint.yaml
applications/argocd/values-idfprod.yaml
applications/argocd/values-minikube.yaml
applications/argocd/values-roe.yaml
applications/argocd/values-roundtable-dev.yaml
applications/argocd/values-roundtable-prod.yaml
applications/argocd/values-summit.yaml
applications/argocd/values-tucson-teststand.yaml
applications/argocd/values-usdf-tel-rsp.yaml
applications/argocd/values-usdfdev-alert-stream-broker.yaml
applications/argocd/values-usdfdev-prompt-processing.yaml
applications/argocd/values-usdfdev.yaml
applications/argocd/values-usdfint.yaml
applications/argocd/values-usdfprod-prompt-processing.yaml
applications/argocd/values-usdfprod.yaml
applications/argocd/values.yaml

Restructure the Argo CD configuration for the latest major revision of the Helm chart, which drops a lot of backward compatibility. Clean up the USDF Argo CD configurations by deleting a bunch of unnecessary settings and moving the proxy environment variable settings into the new global.env setting.

DM-43246: Update to latest version of the Argo CD chart

---

applications/argocd/README.md
applications/argocd/values-usdfdev-alert-stream-broker.yaml
applications/argocd/values-usdfdev-prompt-processing.yaml
applications/argocd/values-usdfprod-prompt-processing.yaml
applications/argocd/values.yaml

We can now set the root path for the server and avoid having to do a rewrite in the ingress, so go ahead and do that. This also means we don't have to use a regex for the ingress path.

DM-43246: Further simplify Argo CD configuration

---

applications/gafaelfawr/README.md
applications/gafaelfawr/values.yaml
applications/sqlproxy-cross-project/README.md
applications/sqlproxy-cross-project/values.yaml
applications/times-square/README.md
applications/times-square/values.yaml
applications/vo-cutouts/README.md
applications/vo-cutouts/values.yaml
docs/applications/postgres/index.rst
docs/developers/helm-chart/workload-identity.rst
installer/install.sh
tests/data/input/applications/gafaelfawr/values.yaml

The Google spelling is with a space. Be consistent.
Try a new method of syncing Argo CD during install.sh that hopefully will cope with the Argo CD pods being restarted while syncing.

DM-42714: Change CloudSQL to Cloud SQL, fix CI testing

---

docs/developers/helm-chart/cloud-sql.rst
docs/developers/helm-chart/index.rst

Document how to set up Cloud SQL access for applications. Hopefully the Terraform parts are already adequately covered by the discussion of workload identity.

DM-42714: Add documentation of Cloud SQL

---

applications/times-square/Chart.yaml
applications/times-square/README.md
applications/times-square/secrets.yaml
applications/times-square/templates/deployment.yaml
applications/times-square/templates/worker-deployment.yaml
applications/times-square/values-usdfdev.yaml
applications/times-square/values.yaml

Deploys Times Square 0.10.0: https://github.com/lsst-sqre/phalanx/pull/3051
We've discovered that the arq liveness check is not compatible with the USDF (it runs fine on GKE/IDF). So we're disable it to avoid restarting the workers every 6 minutes.

DM-43264: Update Times Square with Slack error reporting

---

applications/gafaelfawr/templates/deployment.yaml

The Cloud SQL Auth Proxy sidecar containers didn't have resource limits defined. Use the same limits as are used for the standalone Cloud SQL Auth Proxy deployment.

DM-43288: Add Kubernetes resource limits for Cloud SQL

---

applications/gafaelfawr/templates/job-schema-update.yaml

The hook for doing schema updates also needs resources set for its Cloud SQL Auth Proxy sidecar.

DM-43288: Add another missing Gafaelfawr resource setting

---

applications/gafaelfawr/templates/deployment-operator.yaml

Only one Gafaelfawr Kubernetes operator should be running at a time, so use the recreate strategy to ensure that the running pod is terminated before a new one is started.

DM-43288: Use recreate strategy for Gafaelfawr operator

---

applications/prompt-proto-service-hsc/values-usdfdev-prompt-processing.yaml
charts/prompt-proto-service/README.md
charts/prompt-proto-service/templates/prompt-proto-service.yaml
charts/prompt-proto-service/values.yaml

This PR adds a flag to the Prompt Processing service that toggles caching calibs. While this is a useful feature, it causes the DM-41915 workaround to break in certain development environments. The flag is kept out of the published API as much as possible to make it easy to remove once calib handling is properly fixed.

DM-43205: Calibs fail to locally certify in Prompt Processing

---

applications/prompt-proto-service-hsc-gpu/Chart.yaml
applications/prompt-proto-service-hsc-gpu/README.md
applications/prompt-proto-service-hsc-gpu/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-hsc-gpu/values.yaml
applications/prompt-proto-service-hsc/values.yaml
applications/prompt-proto-service-latiss/README.md
applications/prompt-proto-service-latiss/values.yaml
applications/prompt-proto-service-lsstcam/README.md
applications/prompt-proto-service-lsstcam/values.yaml
applications/prompt-proto-service-lsstcomcam/README.md
applications/prompt-proto-service-lsstcomcamsim/README.md
applications/prompt-proto-service-lsstcomcamsim/values.yaml
charts/prompt-proto-service/README.md
charts/prompt-proto-service/templates/prompt-proto-service.yaml
charts/prompt-proto-service/values.yaml
docs/applications/index.rst
docs/applications/prompt-proto-service-hsc-gpu/index.rst
docs/applications/prompt-proto-service-hsc-gpu/values.md
environments/README.md
environments/templates/prompt-proto-service-hsc-gpu-application.yaml
environments/values-usdfdev-prompt-processing.yaml
environments/values.yaml

Add prompt processing GPU application for HSC to perform testing.  Enables GPU support in disabled state on all other prompt processing applications.

DM-43287: HSC GPU Application

---

charts/cadc-tap/README.md
charts/cadc-tap/values.yaml

Reverts lsst-sqre/phalanx#3056
There is a bug in Firefly that needs to be fixed, having to do with `null` units when a column has a `time.epoch` UCD.
Rolling back the change to TAP_SCHEMA that tripped the bug.  Next week we will modify sdm_schemas itself to avoid triggering the bug until a bug-fixed version of Firefly can be deployed to production -- which might be the new-UI version of Firefly, not a patch on 2023.3.x.

Revert "Update sdm_schemas to 2.5.0 release"

---

applications/argocd/values-idfdev.yaml
environments/templates/argocd-application.yaml
environments/templates/cert-manager-application.yaml
environments/templates/gafaelfawr-application.yaml
environments/templates/ingress-nginx-application.yaml
environments/templates/mobu-application.yaml
environments/templates/postgres-application.yaml
environments/templates/projects/infrastructure.yaml
environments/templates/strimzi-access-operator-application.yaml
environments/templates/strimzi-application.yaml
environments/templates/vault-secrets-operator-application.yaml
installer/install.sh

Create an Argo CD project named infrastructure and put the core Phalanx infrastructure applications in it. Use this to write new RBAC rules for idfdev that divide users into admins and developers and block write access to infrastructure applications by developers.

DM-43342: Add new infrastructure Argo CD project

---

applications/gafaelfawr/Chart.yaml
applications/gafaelfawr/templates/deployment-operator.yaml
applications/gafaelfawr/templates/deployment.yaml

Add a liveness problem for both the main Gafaelfawr deployment and the Kubernetes operator. The former uses the new /health endpoint, and the latter uses a newly-configured Kopf-provided /health endpoint. If there is more than one Gafaelfawr replica, switch the readiness probe for the main Gafaelfawr deployment to use the same health check as the liveness probe so that traffic will be routed away when it starts failing.

DM-43288: Add more probes for Gafaelfawr

---

docs/applications/index.rst
docs/applications/infrastructure.rst
docs/applications/monitoring.rst
docs/applications/prompt.rst
docs/applications/roundtable.rst
docs/applications/rsp.rst
docs/applications/rubin.rst
docs/applications/telescope.rst
docs/developers/helm-chart/add-application.rst
docs/developers/helm-chart/create-new-chart.rst
pyproject.toml
src/phalanx/cli.py
src/phalanx/data/application-template.yaml.jinja
src/phalanx/models/applications.py
src/phalanx/services/application.py
src/phalanx/storage/config.py
tests/cli/application_test.py
tests/config_test.py
tests/data/input/environments/templates/nublado-application.yaml
tests/data/input/environments/templates/portal-application.yaml
tests/data/input/environments/templates/tap-application.yaml
tests/docs/applications_test.py

When creating a new application, require an Argo CD project be provided. Break up the list of applications into separate files by project, and tell people to add their new application to the appropriate project. Check that each application is linked in the appropriate place for its project.
Sort all of the projects into the appropriate place in the documentation so that we can look at the resulting documentation build. The Argo CD applications were assigned to projects and the Argo CD projects were added in a separate, mechanical PR.

DM-43342: Require Argo CD projects when making applications

---

environments/templates/projects/prompt.yaml
tests/config_test.py

The prompt Argo CD project wasn't defined. Add it, and add a test making sure all members of the Project enum have project resources defined.

DM-43342: Add missing prompt Argo CD project

---

docs/developers/deploy-from-a-branch.rst
docs/developers/switch-environment-to-branch.rst

Remove the suggestion to restore an application to the main branch by syncing science-platform, since people will normally not have access. Document that switching science-platform to a branch may have to be done by the environment administrator.

DM-43342: Update development docs for RBAC

---

docs/applications/argocd/authentication.rst
docs/applications/argocd/bootstrap.rst

Rework the documentation for configuring Argo CD authentication to reflect the new secrets management system and the new layout of Helm chart parameters. Add documentation for setting up Argo CD RBAC.

DM-43342: Update Argo CD boostrap documentation

---

docs/applications/argocd/bootstrap.rst
docs/applications/argocd/upgrade.rst

The admin password is only in Vault, not in the static secrets store. Remove a spurious blank line from the upgrading instructions.

DM-43342: Fix mistakes in Argo CD documentation

---

applications/argocd/secrets.yaml
applications/consdb/secrets.yaml
docs/applications/onepassword-connect/add-new-environment.rst
environments/values-base.yaml

Fix the documentation for adding a new 1Password environment, and add the 1Password Connect information for tucson-teststand.

DM-43409: Fix 1Password documentation, add tucson-teststand

---

applications/prompt-proto-service-hsc-gpu/README.md
applications/prompt-proto-service-hsc-gpu/values.yaml
applications/prompt-proto-service-hsc/README.md
applications/prompt-proto-service-hsc/values.yaml
applications/prompt-proto-service-latiss/README.md
applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-latiss/values.yaml
applications/prompt-proto-service-lsstcam/README.md
applications/prompt-proto-service-lsstcam/values.yaml
applications/prompt-proto-service-lsstcomcam/README.md
applications/prompt-proto-service-lsstcomcam/values.yaml
applications/prompt-proto-service-lsstcomcamsim/README.md
applications/prompt-proto-service-lsstcomcamsim/values.yaml
charts/prompt-proto-service/templates/prompt-proto-service.yaml

Enable node affinity to avoid scheduling to nodes with Intel NICs at USDF due to issue with Intel NICS dropping packets.

DM-41829: Prompt Processing Add Node Affinity

---

applications/nublado/Chart.yaml

We'd need to do the nublado release first, of course.

Use newer JupyterHub/z2jh charts and images.

---

applications/butler/README.md
applications/butler/templates/deployment.yaml
applications/butler/templates/ingress-anonymous.yaml
applications/butler/templates/ingress-authenticated.yaml
applications/butler/values-idfdev.yaml
applications/butler/values-idfint.yaml
applications/butler/values-idfprod.yaml
applications/butler/values-usdfdev.yaml
applications/butler/values-usdfint.yaml
applications/butler/values-usdfprod.yaml
applications/butler/values.yaml
applications/datalinker/README.md
applications/datalinker/values-idfdev.yaml
applications/datalinker/values-idfint.yaml
applications/datalinker/values-idfprod.yaml
applications/datalinker/values-usdfdev.yaml
applications/datalinker/values-usdfprod.yaml
applications/datalinker/values.yaml
environments/values-usdfdev.yaml
environments/values-usdfint.yaml
environments/values-usdfprod.yaml

Added a Butler server at USDF providing access to the `embargo` Butler repository, and configured datalinker to use it.  This fixes an issue where Firefly would display a 500 server error when trying to load images via datalinker for Live ObsCore TAP searches.
Previously Datalinker was not properly configured at USDF -- it was pointed at a Butler repository index file containing mostly repositories hosted as POSIX filesystems unreachable from the service, and was missing postgres configuration necessary to access the Butler DB.

DM-43430: Add Butler server at USDF

---

applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-latiss/values.yaml

This PR updates the LATISS Prompt Processing configs (mostly in `usdfprod`) to reflect new surveys and more experience working with LATISS.

DM-43462: Update LATISS Prompt Processing configs

---

applications/vault-secrets-operator/README.md
applications/vault-secrets-operator/values-idfdev.yaml
applications/vault-secrets-operator/values-idfint.yaml
applications/vault-secrets-operator/values-idfprod.yaml
applications/vault-secrets-operator/values-minikube.yaml
applications/vault-secrets-operator/values-roe.yaml
applications/vault-secrets-operator/values-roundtable-dev.yaml
applications/vault-secrets-operator/values-roundtable-prod.yaml
applications/vault-secrets-operator/values-usdf-tel-rsp.yaml
applications/vault-secrets-operator/values-usdfdev.yaml
applications/vault-secrets-operator/values-usdfint.yaml
applications/vault-secrets-operator/values-usdfprod.yaml
applications/vault-secrets-operator/values.yaml
docs/admin/secrets-setup.rst
docs/applications/vault-secrets-operator/bootstrap.rst
environments/values-tucson-teststand.yaml
installer/install.sh

We previously were configuring the Vault token duration in the secret, which makes absolutely no sense since its value is not a secret. Move this configuration to the chart, setting the chart default to the same length of time we were previously putting in the secret.
Quote all of the values files for vault-secrets-operator for consistency, and delete pointless environment variable settings that are handled by the chart.
Update the vault-secrets-operator bootstrapping documentation for the new secrets management system.

DM-43409: Move Vault token duration to the chart

---

applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcamsim/values-usdfprod-prompt-processing.yaml

This PR updates both the LATISS and LSSTComCamSim services to [version 2.2.2](https://github.com/lsst-dm/prompt_processing/releases/tag/2.2.2), which fixes a Butler compatibility problem.

Use prompt-service 2.2.2 in Prompt Processing prod.

---

applications/sasquatch/README.md
applications/sasquatch/charts/strimzi-kafka/README.md
applications/sasquatch/charts/strimzi-kafka/values.yaml

Strimzi 0.40.0 and Kafka 3.7.0 are required to migrate to KRaft mode.

Update Kafka to version 3.7.0

---

applications/noteburst/Chart.yaml
applications/noteburst/README.md
applications/noteburst/templates/worker-configmap.yaml
applications/noteburst/values.yaml

This limits the number of concurrent notebook execution jobs run on a noteburst worker to less than the number of CPUs. This should reduce the occurrence of HTTP timeouts from the noteburst execution endpoint in JupyterLab pods.
See https://github.com/lsst-sqre/noteburst/pull/74

DM-43460: Add NOTEBURST_WORKER_MAX_CONCURRENT_JOBS config

---

applications/gafaelfawr/values-idfdev.yaml
applications/gafaelfawr/values-idfint.yaml
applications/gafaelfawr/values-idfprod.yaml
applications/gafaelfawr/values.yaml
applications/nublado/templates/controller-ingress-files.yaml
applications/portal/templates/ingress.yaml

Define a new write:files scope and assign it to all users on the IDF deployments where we plan to run the WebDAV file server. Change the scope used to control access to WebDAV from exec:notebook to write:files, and add this to the list of scopes delegated to the Portal.

DM-43444: Add new write:files scope

---

applications/ingress-nginx/values-idfdev.yaml
applications/ingress-nginx/values-usdfdev.yaml
applications/ingress-nginx/values-usdfprod.yaml
applications/portal/templates/ingress.yaml

Make idfdev match the other IDF environments. Remove ingress-nginx configuration that just replicates configuration already applied at a higher level in the per-environment ingress-nginx configurations and in the Portal ingress.

DM-43444: Remove duplicate ingress-nginx configuration

---

applications/times-square/Chart.yaml

Add HTML cache busting for page renders. See https://github.com/lsst-sqre/times-square/releases/tag/0.11.0

DM-43327: Update Times Square to 0.11.0

---

applications/prompt-proto-service-hsc-gpu/README.md
applications/prompt-proto-service-hsc-gpu/values.yaml
applications/prompt-proto-service-hsc/README.md
applications/prompt-proto-service-hsc/values.yaml
applications/prompt-proto-service-latiss/README.md
applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-latiss/values.yaml
applications/prompt-proto-service-lsstcam/README.md
applications/prompt-proto-service-lsstcam/values.yaml
applications/prompt-proto-service-lsstcomcam/README.md
applications/prompt-proto-service-lsstcomcam/values.yaml
applications/prompt-proto-service-lsstcomcamsim/README.md
applications/prompt-proto-service-lsstcomcamsim/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcamsim/values.yaml
charts/prompt-proto-service/README.md
charts/prompt-proto-service/templates/prompt-proto-service.yaml
charts/prompt-proto-service/values.yaml

This PR allows customization of Prompt Processing's Sasquatch namespace, and configures the production services to upload metrics to a custom namespace.

DM-42739: Configure Prompt Processing production service for Sasquatch upload

---

applications/nublado/Chart.yaml
applications/nublado/README.md
applications/nublado/values-base.yaml
applications/nublado/values-idfdev.yaml
applications/nublado/values-idfint.yaml
applications/nublado/values-roe.yaml
applications/nublado/values-summit.yaml
applications/nublado/values-tucson-teststand.yaml
applications/nublado/values.yaml

Upgrades JupyterHub, adds new routes for the file server, and fixes the path to the DELETE route for admin access to the file server.

DM-43444: Update to Nublado 6.0.0

---

applications/prompt-proto-service-hsc-gpu/README.md
applications/prompt-proto-service-hsc-gpu/values.yaml
applications/prompt-proto-service-hsc/README.md
applications/prompt-proto-service-hsc/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-hsc/values.yaml
applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml
charts/prompt-proto-service/templates/prompt-proto-service.yaml
charts/prompt-proto-service/values.yaml

Refactor tolerations to allow for variable inputs.  Add affinity and toleration to schedule to isolated nodes for latiss prod.  Enable service links.  Remove readiness probe configuration as this is set by knative.

DM-41829: Affinity and tolerations refactor.  Enable isolated nodes for LATISS prod

---

applications/prompt-proto-service-lsstcomcamsim/values-usdfprod-prompt-processing.yaml
charts/prompt-proto-service/README.md
charts/prompt-proto-service/templates/prompt-proto-service.yaml
charts/prompt-proto-service/values.yaml

This PR adds a flag to the Prompt Processing service that toggles caching all inputs. This allows large-scale deployments that won't run out of storage space, but hurts preload performance. The flag is kept out of the published API as much as possible to make it easy to remove once the local repo is self-managing (DM-40193).

DM-43584: Add an option to turn off caching entirely

---

applications/prompt-proto-service-hsc/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml

Remove 50Gb storage request and inherit default 20Gb.  50 Gb is no longer needed and the request is causing issues with not enough nodes with available ephemeral storage.  Remove affinity and tolerations from HSC.

Prompt Processing: LATISS Prod Lower Disk Size

---

applications/prompt-proto-service-hsc/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcamsim/values-usdfprod-prompt-processing.yaml

This PR updates the default release for all `usdfprod` Prompt Processing services to 2.4.0 in preparation for the Ops Rehearsal. It also scales back a limit on the `usdfdev` service that was causing resource shortages.

Deploy Prompt Processing 2.4.0

---

applications/datalinker/values.yaml

datalinker cycles around the 150MiB request, but it regularly comes very close to the 200MiB limit and has gotten OOM-killed a few times on data-dev because it goes over. Increase the limit to 300MiB.

DM-43610: Increase memory limit for datalinker

---

applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcamsim/values-usdfprod-prompt-processing.yaml

I'm turning it off as the dev default too, so it's getting tested by default.

DM-43608: Turn off force source handling in prompt processing default

---

applications/telegraf-ds/values-base.yaml
applications/telegraf-ds/values-tucson-teststand.yaml
applications/telegraf/values-base.yaml
applications/telegraf/values-tucson-teststand.yaml

TTS new-style secret management isn't working, and base hasn't gotten to it yet...so let's postpone repointing for a bit.

Unwind monitoring destination changes for tts/base

---

applications/argocd/values-base.yaml

oidc.config does not use a connectors key.

DM-43356: Fix Keycloak configuration for base

---

applications/sasquatch/README.md
applications/sasquatch/charts/strimzi-kafka/README.md
applications/sasquatch/charts/strimzi-kafka/templates/kafka.yaml
applications/sasquatch/charts/strimzi-kafka/values.yaml
applications/sasquatch/values-idfdev.yaml
applications/sasquatch/values-idfint.yaml
applications/sasquatch/values-tucson-teststand.yaml

Migration to KRaft mode is described in [Deploying and Upgrading (0.40.0)](https://strimzi.io/docs/operators/0.40.0/deploying.html#proc-deploy-migrate-kraft-str)  and with more details in this blog post [Migrate your Strimzi-operated cluster from ZooKeeper to KRaft](https://strimzi.io/blog/2024/03/22/strimzi-kraft-migration/)
It requires Strimzi 0.40.0 and Kafka 3.7.0.
Another requirement for migrating to KRaft mode is to add a `KafkaNodePool` resource for kafka.
In this PR, we practice the migration to KRaft mode on idv-dev, but let it disabled in the other environments for the moment.
Merging this PR will add the KafkaNodePool with resource configuration for Kafka. The plan is to roll out this change first on IDF and Telescope environments and then USDF.

[DM-43491] Migrate Kafka to KRaft mode in Sasquatch

---

applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcamsim/values-usdfprod-prompt-processing.yaml

This PR updates the default release for all usdfprod Prompt Processing services to 2.5.0.

Deploy Prompt Processing 2.5.0

---

.github/workflows/ci.yaml
.github/workflows/docs.yaml
.github/workflows/linkcheck.yaml
.pre-commit-config.yaml
Makefile
requirements/dev.in
requirements/dev.txt
requirements/main.txt

Use tox-uv so that tox will use uv to manage virtual environments. Update GitHub CI configuration to use separate caches for the tox environments, since there is no real benefit to the shared caches. Move more dependencies into requirements/dev.in so that the Makefile can be simpler.

DM-43714: Use tox-uv plugin

---

applications/gafaelfawr/templates/deployment-operator.yaml

We were seeing spurious failures and restarts, probably because pushing the end-to-end check through the queue can take a bit if some other object is already being processed. Make the timeout longer and set an explicit failure threshold.

Relax livenes probe for gafaelfawr-operator

---

applications/sasquatch/values-tucson-teststand.yaml

We added default resource rquests and limits for Kafka in Sasquatch. That doesn’t seem enough for TTS which runs the Control System.
For TTS, we are requesting 80G of memory and 4 CPUs for Kafka.

Adjust resource request and limits fork Kafka at TTS

---

docs/applications/argocd/authentication.rst
docs/applications/argocd/bootstrap.rst

Add documentation for using Keycloak for SSO for Argo CD.

DM-43356: Document Argo CD configuration with Keycloak

---

applications/alert-stream-broker/README.md
applications/alert-stream-broker/charts/alert-stream-broker/README.md
applications/alert-stream-broker/charts/alert-stream-broker/values.yaml
applications/alert-stream-broker/values-usdfdev-alert-stream-broker.yaml

Increase number of partitions for the alert-stream-test topic as well as increase the retention size to 1 Tb. Update the kafka version to match the latest version used by strimzi

DM-43523: Update retention values, increase number of partitions and update Kafka version

---

environments/templates/applications/roundtable/ook.yaml
environments/templates/applications/roundtable/squarebot.yaml
environments/templates/applications/roundtable/unfurlbot.yaml

Several Roundtable apps use generated and copied Kafka secrets, which should not count as meaningful differences for an Argo CD diff. Add the appropriate ignore rules.

DM-43837: Ignore copied Kafka secrets in Argo CD

---

environments/templates/applications/roundtable/ook.yaml
environments/templates/applications/roundtable/squarebot.yaml
environments/templates/applications/roundtable/unfurlbot.yaml

Ignoring the individual elements still leaves a diff between an empty object and no object. Ignore the entire data key of copied secrets.

DM-43837: Ignore more of the copied Kafka secrets

---

.github/workflows/ci.yaml
applications/squareone/values-minikube.yaml
environments/values-minikube.yaml

Now that Argo CD does the TLS setup, stop installing squareone on minikube. It's not part of the core infrastructure that minikube is meant to be testing.

DM-43837: Stop testing squareone on minikube

---

docs/extras/schemas/environment.json
environments/README.md
environments/values-base.yaml
environments/values-ccin2p3.yaml
environments/values-idfdev.yaml
environments/values-idfint.yaml
environments/values-idfprod.yaml
environments/values-minikube.yaml
environments/values-roe.yaml
environments/values-roundtable-dev.yaml
environments/values-roundtable-prod.yaml
environments/values-summit.yaml
environments/values-tucson-teststand.yaml
environments/values-usdfdev.yaml
environments/values-usdfint.yaml
environments/values-usdfprod.yaml
environments/values.yaml
src/phalanx/models/environments.py
src/phalanx/services/environment.py
src/phalanx/storage/helm.py
tests/data/input/environments/values-idfdev.yaml
tests/data/input/environments/values.yaml
tests/data/output/minikube/values-after-add.yaml

Previously, the installer hard-coded science-platform as the name of the top-level app-of-apps, but this is only appropriate for RSP Phalanx environments. Change the default to app-of-apps, allow it to be overridden, keep it as science-platform for RSP environments, and change it to roundtable for Roundtable.

DM-43837: Allow the app-of-apps name to be configured

---

applications/butler/Chart.yaml
applications/datalinker/Chart.yaml
applications/vo-cutouts/Chart.yaml

Update the Butler server to the latest weekly, and update datalinker and vo-cutouts to the latest Butler client release.

DM-43846: Upgrade Butler server and clients

---

src/phalanx/cli.py
src/phalanx/factory.py
src/phalanx/storage/kubernetes.py

When warning the user before doing an install, print the current cluster from kubectl config current-context. This avoids making the user verify the cluster themselves.

DM-43837: Add current cluster to install prompt

---

src/phalanx/github.py
src/phalanx/services/environment.py
src/phalanx/storage/argocd.py

Use the special output commands in GitHub Actions to register and mask the Argo CD password at the start of the installer, since it may otherwise appear in exception error messages if login fails.
Pass the secret through to the login method as a SecretStr instead of a str.

DM-43837: Mask the Argo CD password in GitHub Actions

---

src/phalanx/cli.py
tests/support/helm.py

If an action in the Phalanx CLI requires that a command be available on the user's path (usually helm, but also kubectl and argocd for the installer), check at the start of the command and fail with a clear error message if that command isn't available.

DM-43837: Check for required commands in phalanx CLI

---

applications/vault-secrets-operator/values-minikube.yaml
docs/admin/secrets-setup.rst
src/phalanx/cli.py
src/phalanx/models/vault.py
src/phalanx/services/vault.py
src/phalanx/storage/vault.py
tests/cli/vault_test.py
tests/support/vault.py

The minikube GitHub CI environment performs two AppRole logins for every test, one for the installer and one for vault-secrets-operator. These create Vault tokens, which then have to be examined by other Vault operations such as create-write-token that need to audit the existing tokens.
Support limiting the lifetime of those tokens so that they will expire faster and thus prevent token accumulation that slows down other operations. Limit the token lifetime obtained by vault-secrets-operator for minikube to one hour, since the minikube AppRole now has a maximum token lifetime of two hours.

DM-43837: Support limiting AppRole token lifetime

---

applications/sasquatch/Chart.yaml
applications/sasquatch/README.md
docs/applications/sasquatch/index.rst

Link to the Sasquatch documentation and add references to the sources of various Sasquatch components to its Chart.yaml.

DM-43837: Add more documentation pointers for Sasquatch

---

applications/squareone/Chart.yaml

See https://github.com/lsst-sqre/squareone/pull/164
This deploys Squareone 0.12.0. https://github.com/lsst-sqre/squareone/releases/tag/squareone%400.12.0

DM-43859: Update Squareone

---

src/phalanx/cli.py
tests/cli/secrets_test.py
tests/cli/vault_test.py
tests/conftest.py
tests/support/cli.py
tests/support/onepassword.py

Check for required environment variables in phalanx CLI commands and raise a clear error. Adjust the test suite to set required environment variables to dummy values, and add a global fixture to ensure that any environment variables set in the test runner's environment don't leak.

DM-43837: Diagnose missing environment variables

---

docs/admin/audit-secrets.rst
docs/admin/migrating-secrets.rst
docs/admin/secrets-setup.rst
docs/admin/sync-secrets.rst
docs/admin/update-a-secret.rst
src/phalanx/cli.py
src/phalanx/exceptions.py
src/phalanx/factory.py
src/phalanx/models/secrets.py
src/phalanx/services/secrets.py
src/phalanx/storage/onepassword.py
tests/cli/secrets_test.py
tests/data/input/onepassword/minikube.yaml
tests/data/output/idfdev/static-secrets.yaml
tests/data/output/minikube/onepassword-secrets.yaml
tests/support/onepassword.py

Allow people to put the Vault write token for their environments into the static secrets file or 1Password source, since it's roughly equivalent in power to the other secrets also stored there. This allows environments that use 1Password to set only OP_CONNECT_TOKEN and not worry about the Vault write token.

DM-43923: Get Vault write tokens from static secrets

---

applications/datalinker/secrets.yaml
docs/developers/secrets-spec.rst
docs/extras/schemas/secrets.json
src/phalanx/models/secrets.py

If a secret has an unconditional copy directive, make the description field optional. This allows people to inherit the description from the source of a copied secret if desired.

DM-43965: Make descriptions optional for copied secrets

---

docs/documenteer.toml
src/phalanx/cli.py
src/phalanx/exceptions.py
tests/cli/secrets_test.py

Add a class of usage error exceptions and a decorator that translates them into Click UsageErrors that just display the error message without a stack backtrace.

DM-43966: Standardize error handling in Phalanx CLI

---

src/phalanx/exceptions.py
src/phalanx/services/vault.py
tests/cli/vault_test.py
tests/data/output/idfdev/copy-output

phalanx vault copy-secrets was prone to copying secrets onto themselves if people forgot to update the Vault secrets path in the environment configuration. Catch that case and fail early with an error instead.

DM-43966: Prevent copying Vault secrets onto themselves

---

src/phalanx/cli.py
src/phalanx/services/secrets.py
src/phalanx/storage/vault.py

Do not error out if the Vault path doesn't exist in secrets audit and secrets sync, since otherwise we can't create the tree for a new environment from scratch. Unfortunately, the Vault server returns permission denied for nonexistent paths, so we can't distinguish between this case and using the wrong Vault token until we try to write.

DM-44008: Handle the case of a nonexistent Vault path

---

src/phalanx/cli.py

The warning should have read "if this is not the correct cluster."

DM-44008: Fix typo in install warning

---

src/phalanx/constants.py
src/phalanx/models/vault.py
src/phalanx/services/environment.py
src/phalanx/storage/command.py
src/phalanx/storage/kubernetes.py
tests/cli/vault_test.py

The second time one ran phalanx environment install for the same environment with the same cluster and partial resources, it would fail because it tried to create the vault-secrets-operator secret and could not overwrite it. Change the installer to use kubectl apply instead of kubectl create, similar to the old bash script, which avoids this problem. As a bonus, this will avoid leaking the Vault tokens to error output if the secret creation fails.

DM-44008: Fix repeated environment installs

---

applications/rubintv/README.md
applications/rubintv/templates/deployment-workers.yaml
applications/rubintv/values-usdfdev.yaml
applications/rubintv/values-usdfprod.yaml
applications/rubintv/values.yaml
environments/values-usdfprod.yaml

I added the ability to turn off the worker deployment by setting the number of replicas to zero, since they don't seem to be used right now and I don't want to add non-working config to usdf-prod just to make helm happy.

DM-43581: Add rubintv to usdfprod.

---

applications/gafaelfawr/values-idfdemo.yaml

idfdemo is the bootcamp environment, and our attendees should get to be effectively-root there.

Empower lsst/ops team at idfdemo

---

starters/fastapi-safir/templates/ingress.yaml

I added the setting and then forgot to use it in the GafaelfawrIngress. Plumb it through rather than hard-coding the path.

DM-44129: Use config.pathPrefix in fastapi-safir starter

---

applications/gafaelfawr/templates/deployment-operator.yaml

The liveness probe for gafaelfawr-operator is constantly restarting the pod still. Use a much longer timeout in case this is just due to queued processing inside Kopf.

DM-44136: Use much longer timeout for gafaelfawr-operator

---

applications/prompt-proto-service-hsc-gpu/README.md
applications/prompt-proto-service-hsc-gpu/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-hsc-gpu/values.yaml
applications/prompt-proto-service-hsc/README.md
applications/prompt-proto-service-hsc/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-hsc/values.yaml
applications/prompt-proto-service-latiss/README.md
applications/prompt-proto-service-latiss/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-latiss/values.yaml
applications/prompt-proto-service-lsstcam/README.md
applications/prompt-proto-service-lsstcam/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-lsstcam/values.yaml
applications/prompt-proto-service-lsstcomcam/README.md
applications/prompt-proto-service-lsstcomcam/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcam/values.yaml
applications/prompt-proto-service-lsstcomcamsim/README.md
applications/prompt-proto-service-lsstcomcamsim/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcamsim/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcamsim/values.yaml
charts/prompt-proto-service/README.md
charts/prompt-proto-service/templates/prompt-proto-service.yaml
charts/prompt-proto-service/values.yaml

This PR updates the Prompt Processing service config to use persisted APDB config files instead of specifying all APDB parameters directly. This PR should be merged after lsst-dm/prompt_processing#157.

DM-44096: Migrate Prompt Processing to external APDB configs

---

applications/argocd/values-idfdemo.yaml

We added the lsst:ops group but didn't allow authentication from the lsst org. Add it.

Allow Argo CD auth to idfdemo from lsst org

---

applications/argocd/values-idfdemo.yaml

The Ops team is capitalized, and the capitalization needs to match.

Fix the ACL for idfdemo

---

applications/argocd/values-idfdev.yaml
applications/argocd/values-idfint.yaml
applications/argocd/values-idfprod.yaml
applications/argocd/values-roundtable-dev.yaml
applications/argocd/values-roundtable-prod.yaml

This adds Dan as an admin on the idf and roundtable clusters. I haven't
updated the usdf values in this PR.

Add Dan Fuchs as Argo CD admin on Google envs

---

applications/exposurelog/values-minikube.yaml
applications/narrativelog/values-minikube.yaml
applications/noteburst/values-minikube.yaml
applications/portal/values-minikube.yaml
applications/semaphore/values-minikube.yaml
applications/strimzi/values-minikube.yaml

Remove configurations for the minikube environment that are not used by the GitHub CI testing, which is now the only thing that we use minikube for. These configurations weren't tested and tend to bitrot.

DM-44239: Remove unused minikube configurations

---

applications/livetap/secrets.yaml

livetap uses the PostgreSQL backend for TAP, which requires a password secret. Copy the description from ssotap and update the description.

DM-44239: Add PostgreSQL secret for livetap

---

src/phalanx/services/secrets.py
tests/data/output/idfdev/secrets-audit

Put a blank line before headings in secrets audit output to make it more readable.

DM-44239: Add blank lines to secrets audit output

---

src/phalanx/services/secrets.py
tests/cli/secrets_test.py

If there are no static secrets, and therefore Phalanx should assume the static secrets are already stored in Vault, make sure that audit doesn't complain about and sync doesn't delete a pull-secret.

DM-44238: Handle pull-secret with no static secrets

---

applications/vo-cutouts/values.yaml

The vo-cutout worker was restarted due to being OOM killed and is on average taking up more memory than we're allocating. Bump the requests and limits.

Bump memory request and limit for vo-cutout worker

---

applications/ook/templates/cronjob-audit.yaml
applications/ook/templates/cronjob-ingest-updated.yaml

Now that we no longer replicate the KafkaUser secret, Ook's Job-based resources need to use the new set of secrets from Kafka Access Operator.

DM-44270: Update Ook jobs to use new Kafka info

---

applications/ook/templates/cronjob-ingest-updated.yaml

Fix how the Kafka Access secret is used for the Ook ingest-updated job.

DM-44270: Fix Ook ingest job secrets

---

applications/schedview-snapshot/Chart.yaml
applications/schedview-snapshot/secrets.yaml
applications/schedview-snapshot/templates/_helpers.tpl
applications/schedview-snapshot/templates/deployment.yaml
applications/schedview-snapshot/templates/vault-secrets.yaml
applications/schedview-snapshot/values-usdfdev.yaml
applications/schedview-snapshot/values-usdfint.yaml
environments/values-usdfint.yaml

This change requires not just updating the schedview version, but also requires configuring phalanx to provide it with the secret it needs.
For this, I was guided by a combination of the phalanx documentation, the configuration of plot-navigator (from which some changes were cut-and-pasted), and [this thread on slack](https://lsstc.slack.com/archives/C2JP8GGVC/p1714426470147829).
It seems to work like this, but I'm not 100% sure copying the secret from nublado using the butler's vault is the right thing to do, in that I think it give this app write access it doesn't need (although KT [says this is okay](https://lsstc.slack.com/archives/C2JP8GGVC/p1714580872053049?thread_ts=1714426470.147829&cid=C2JP8GGVC)).

tickets/PREOPS-5118: Update the schedview snapshot dashboard running in phalanx to support access to an S3 bucket

---

applications/prompt-proto-service-hsc-gpu/README.md
applications/prompt-proto-service-hsc-gpu/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-hsc-gpu/values.yaml
applications/prompt-proto-service-hsc/README.md
applications/prompt-proto-service-hsc/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-hsc/values.yaml
applications/prompt-proto-service-latiss/README.md
applications/prompt-proto-service-latiss/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-latiss/values.yaml
applications/prompt-proto-service-lsstcam/README.md
applications/prompt-proto-service-lsstcam/values.yaml
applications/prompt-proto-service-lsstcomcam/README.md
applications/prompt-proto-service-lsstcomcam/values.yaml
applications/prompt-proto-service-lsstcomcamsim/README.md
applications/prompt-proto-service-lsstcomcamsim/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcamsim/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcamsim/values.yaml
charts/prompt-proto-service/README.md
charts/prompt-proto-service/templates/prompt-proto-service.yaml
charts/prompt-proto-service/values.yaml

This PR creates separate config fields for Prompt Processing to specify the main and preprocessing pipeline(s) to run on a given visit. Currently, the preprocessing configs are set to run nothing, as we don't yet have any preprocessing tasks.
This PR makes a breaking change to Prompt Processing's configuration interface, and must be merged together with lsst-dm/prompt_processing#164.

DM-42925: Add support for preprocessing pipeline to Prompt Processing

---

applications/prompt-proto-service-hsc-gpu/README.md
applications/prompt-proto-service-hsc-gpu/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-hsc-gpu/values.yaml
applications/prompt-proto-service-hsc/README.md
applications/prompt-proto-service-hsc/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-hsc/values.yaml
applications/prompt-proto-service-latiss/README.md
applications/prompt-proto-service-latiss/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-latiss/values.yaml
applications/prompt-proto-service-lsstcam/README.md
applications/prompt-proto-service-lsstcam/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-lsstcam/values.yaml
applications/prompt-proto-service-lsstcomcam/README.md
applications/prompt-proto-service-lsstcomcam/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcam/values.yaml
applications/prompt-proto-service-lsstcomcamsim/README.md
applications/prompt-proto-service-lsstcomcamsim/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcamsim/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcamsim/values.yaml
charts/prompt-proto-service/templates/prompt-proto-service.yaml

This PR has Prompt Processing download a `db-auth.yaml` file from the Vault and configure it for use by the service. The deletion of `PGUSER` is conditional on the assumption that `db-auth.yaml` will be used for Butler and Cassandra authentication, with `.pgpass` needed only for connecting to SQL APDBs.
It might be useful to make these blocks conditional on the Vault secret actually containing the `pgpass_file` or `db-auth_file` keys, but I don't know how to do so.

DM-44141: Migrate APDB/Butler credentials from .pgpass to db-auth

---

applications/gafaelfawr/README.md
applications/gafaelfawr/templates/_helpers.tpl
applications/gafaelfawr/templates/cloudsql-deployment.yaml
applications/gafaelfawr/templates/cloudsql-networkpolicy.yaml
applications/gafaelfawr/templates/configmap-kerberos.yaml
applications/gafaelfawr/templates/configmap.yaml
applications/gafaelfawr/templates/cronjob-audit.yaml
applications/gafaelfawr/templates/cronjob-maintenance.yaml
applications/gafaelfawr/templates/deployment-operator.yaml
applications/gafaelfawr/templates/deployment.yaml
applications/gafaelfawr/templates/ingress-rewrite.yaml
applications/gafaelfawr/templates/ingress.yaml
applications/gafaelfawr/templates/job-schema-update.yaml
applications/gafaelfawr/templates/networkpolicy.yaml
applications/gafaelfawr/templates/service.yaml
applications/gafaelfawr/templates/serviceaccount-operator.yaml
applications/gafaelfawr/templates/serviceaccount.yaml
applications/gafaelfawr/templates/vault-secrets.yaml
applications/gafaelfawr/values.yaml

We're moving away from using the standard Helm name manipulation macros and settings, since Phalanx doesn't need them. Drop them from the Gafaelfawr chart.
Add a hook delete policy to the resources created only for the hook in the hope that this will clean them up correctly after hook execution.

DM-44269: Drop name macros from Gafaelfawr chart

---

applications/ingress-nginx/README.md
applications/ingress-nginx/values.yaml
applications/nublado/README.md
applications/nublado/values.yaml
applications/portal/templates/ingress.yaml

Cache authentication for up to five minutes, using a cache key that invalidates the cache if the Cookie or Authorization headers have changed, for Portal and the Nublado proxy ingress. We want to avoid forcing Gafaelfawr to validate every HTTP request for interactive web sites that may load a large number of ancillary resources.

DM-44468: Cache authentication for Portal and Nublado

---

starters/empty/values.yaml
starters/fastapi-safir/values.yaml
starters/web-service/values.yaml

null in YAML is a more accurate representation of an unset value and, for applications that use part of the values file directly as a configuration file for the application, will translate into the more-useful None value in Python.
Fix the documentation comment for image.tag to specify a default.

DM-44481: Use null instead of the empty string in starters

---

docs/developers/helm-chart/add-application.rst
src/phalanx/services/application.py
tests/cli/application_test.py
tests/data/input/docs/applications/infrastructure.rst
tests/data/input/docs/applications/rsp.rst
tests/data/output/docs/infrastructure.rst
tests/data/output/docs/rsp.rst

Now that we know the project for each new application and the documentation indices are separated by project, we can add new applications to the relevant documentation index automatically. Add that support.

DM-44481: Add new applications to the doc index

---

docs/applications/_summary.rst.jinja
tests/config_test.py

Make documentation generation robust against applications not being configured for any environment. Add a test that will fail in this case, and also test that an application is configured for every environment for which it is enabled. This will catch various issues people had during the bootcamp in a more obvious way.

DM-44481: Test for application/environment config issues

---

environments/templates/applications/roundtable/ook.yaml
environments/templates/applications/roundtable/squarebot.yaml
environments/templates/applications/roundtable/unfurlbot.yaml

We had previously added Argo CD comparison exclusions for the copied Kafka secrets for Roundtable applications, but the new Kafka TLS management mechanism no longer requires this. Remove them.

DM-44481: Remove now-unneeded Argo CD exclusions

---

applications/nublado/README.md
applications/nublado/values-base.yaml
applications/nublado/values-ccin2p3.yaml
applications/nublado/values-idfint.yaml
applications/nublado/values-idfprod.yaml
applications/nublado/values-roe.yaml
applications/nublado/values-summit.yaml
applications/nublado/values-tucson-teststand.yaml
applications/nublado/values-usdfdev.yaml
applications/nublado/values-usdfint.yaml
applications/nublado/values-usdfprod.yaml
applications/nublado/values.yaml

Several times in the Nublado configuration related to culling were given in number of seconds with no human-readable equivalent. Add comments with the human-readable time.
Remove some cull override settings that should be safe to keep at the defaults (we don't use named servers, and it should be fine to remove the user on cull), and remove some obsolete settings that should no longer be needed. Change defaults for unset settings to null instead of the empty string.

DM-44481: Document time intervals for Nublado

---

applications/argocd/README.md
applications/argocd/values-minikube.yaml
applications/argocd/values.yaml
applications/cert-manager/README.md
applications/cert-manager/values-minikube.yaml
applications/cert-manager/values.yaml
applications/gafaelfawr/values-minikube.yaml
applications/ingress-nginx/README.md
applications/ingress-nginx/values-minikube.yaml
applications/ingress-nginx/values.yaml
applications/mobu/README.md
applications/mobu/values-minikube.yaml
applications/mobu/values.yaml
applications/postgres/README.md
applications/postgres/values-minikube.yaml
applications/postgres/values.yaml
applications/strimzi-access-operator/README.md
applications/strimzi-access-operator/values.yaml
applications/strimzi/README.md
applications/strimzi/values.yaml
applications/vault-secrets-operator/README.md
applications/vault-secrets-operator/values-minikube.yaml
applications/vault-secrets-operator/values.yaml

For our core applications, add reasonably-sane (but not tight) requests/limits for all of them.
Site-specific overrides to follow eventually.

Add default resource limits/requests to Phalanx core apps

---

applications/nublado/README.md
applications/nublado/templates/proxy-spawn-ingress.yaml
applications/nublado/values-base.yaml
applications/nublado/values-ccin2p3.yaml
applications/nublado/values-idfint.yaml
applications/nublado/values-idfprod.yaml
applications/nublado/values-roe.yaml
applications/nublado/values-summit.yaml
applications/nublado/values-tucson-teststand.yaml
applications/nublado/values-usdfdev.yaml
applications/nublado/values-usdfint.yaml
applications/nublado/values-usdfprod.yaml
applications/nublado/values.yaml

Use the Gafaelfawr functionality we added some time back and require a minimum token lifetime when spawning a lab. This lifetime can be explicitly configured or taken from the maxAge lab culler setting.
Change the culler defaults to match the settings we're using for most environments so that the default maxAge is not longer than the default Gafaelfawr token lifetime.

DM-44537: Enable minimum token lifetime for Nublado

---

.github/workflows/ci.yaml
applications/ssotap/README.md
applications/ssotap/secrets-idfdev.yaml
applications/ssotap/values-idfdev.yaml
applications/ssotap/values.yaml
charts/cadc-tap/README.md
charts/cadc-tap/templates/serviceaccount.yaml
charts/cadc-tap/templates/tap-deployment.yaml
charts/cadc-tap/templates/uws-db-deployment.yaml
charts/cadc-tap/templates/uws-db-networkpolicy.yaml
charts/cadc-tap/templates/uws-db-service.yaml
charts/cadc-tap/tests/mock-db-networkpolicy_test.yaml
charts/cadc-tap/tests/mockdb-deployment_test.yaml
charts/cadc-tap/tests/serviceaccount_test.yaml
charts/cadc-tap/tests/tap-deployment_test.yaml
charts/cadc-tap/tests/uws-db-networkpolicy_test.yaml
charts/cadc-tap/tests/uws-db-service_test.yaml
charts/cadc-tap/tests/uws-deployment_test.yaml
charts/cadc-tap/values.yaml

This PR addresses Jira issue DM-44524: Move the UWS database for SSO-TAP to CloudSQL
A summary of the changes introduced to enable the feature:
- Add optional cloudsql configuration to values
- Add optional UWS database / username configuration to values
- Optional serviceaccount.yaml / Used when cloudsql is enabled
- Make uws optional (add enabled: true | false).
- Make UWS (uws database that get's deployed as part of cadc-tap until now) resources optional, only deployed when uws enabled
- Add cloudsql proxy container option to tap-deployment / Deployed if cloudsql is enabled
- Add Helm unit tests that use: https://github.com/helm-unittest/helm-unittest/
- Set serviceAccount in values to default to "ssotap"
- Enable cloudsql / Disable uws for idfdev. Set parameters so that CloudSQL is …

Enable CloudSQL UWS database for TAP (Initially just for the idfdev SSOTAP service)

---

applications/schedview-snapshot/README.md
applications/schedview-snapshot/secrets.yaml
applications/schedview-snapshot/templates/deployment.yaml
applications/schedview-snapshot/values-usdfint.yaml
applications/schedview-snapshot/values.yaml

There were a few "policy violation" events that got shown by ArgoCD on usdf-int that commits here address (or attempt to address) as well. See the slack thread [here](https://lsstc.slack.com/archives/C027902HL8H/p1717442595254499).

tickets/PREOPS-5192: Update phalanx config for schedview-snapshot to use its own vault secret

---

.github/workflows/ci.yaml
applications/mobu/README.md
applications/mobu/secrets.yaml
applications/mobu/templates/deployment.yaml
applications/mobu/templates/ingress-webhooks.yaml
applications/mobu/tests/github_disabled_test.yaml
applications/mobu/tests/github_enabled_test.yaml
applications/mobu/values-tucson-teststand.yaml
applications/mobu/values.yaml

Taking some cues from @stvoutsin with this PR description and helm unit tests :grinning: 
* Add mobu chart value (`config.githubIntegration`) to conditionally provision resources and secrets to support environments that are behind a VPN and can't get github webhook requests.
* Use latest version of helm unittest plugin ([the repo moved](nittest/blob/254c582c18d52e07541dbe0185eb64befa20a822/README.md?plain=1#L7))
* Run `helm unittest` in all `charts/*` and `applications/*` dirs with tests.
* Set `config.githubIntegration` to `false` for mobu in `idfdev`
* Verified ingress was gone and secrets were not injected into container env
* New helm unit tests

DM 44461: Mobu GitHub resource/secret toggle

---

applications/prompt-proto-service-hsc-gpu/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-hsc/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-latiss/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcamsim/values-usdfdev-prompt-processing.yaml

This PR updates the LATISS-dev and ComCamSim-dev instances of Prompt Processing to use Cassandra-backed APDBs. HSC-dev is left on SQL for test coverage, but the URI has been updated to reflect the config files' reorganization. We are not deploying Cassandra in production just yet.

DM-42924: Test Prompt Processing with Cassandra APDB

---

applications/prompt-proto-service-hsc-gpu/README.md
applications/prompt-proto-service-hsc-gpu/values.yaml
applications/prompt-proto-service-hsc/README.md
applications/prompt-proto-service-hsc/values.yaml
applications/prompt-proto-service-latiss/README.md
applications/prompt-proto-service-latiss/values.yaml
applications/prompt-proto-service-lsstcam/README.md
applications/prompt-proto-service-lsstcam/values.yaml
applications/prompt-proto-service-lsstcomcam/README.md
applications/prompt-proto-service-lsstcomcam/values.yaml
applications/prompt-proto-service-lsstcomcamsim/README.md
applications/prompt-proto-service-lsstcomcamsim/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcamsim/values.yaml
charts/prompt-proto-service/README.md
charts/prompt-proto-service/templates/prompt-proto-service.yaml
charts/prompt-proto-service/values.yaml

This PR adds service configuration options for the caching system introduced in lsst-dm/prompt_processing#169, and cuts ephemeral storage requests to a quarter.

DM-40193: Disk space leak in Prompt Processing

---

applications/next-visit-fan-out/README.md
applications/next-visit-fan-out/templates/deployment.yaml
applications/next-visit-fan-out/values-usdfdev-prompt-processing.yaml
applications/next-visit-fan-out/values.yaml

This PR adds a config option to Prompt Processing for rejecting out-of-date messages. It should be merged before lsst-dm/next_visit_fan_out#13.

DM-43180: Filter out old messages in fan-out service

---

applications/consdb/README.md
applications/consdb/templates/hinfo-deployment.yaml
applications/consdb/templates/pq-deployment.yaml
applications/consdb/values-base.yaml
applications/consdb/values-summit.yaml
applications/consdb/values-usdfdev.yaml
applications/consdb/values-usdfprod.yaml
applications/consdb/values.yaml
docs/applications/consdb/index.rst

One deployment per HeaderService topic; each deployment can support multiple instruments seen on that topic (e.g. LSSTComCamSim and LSSTComCam).  Each deployment can be enabled or disabled separately, and each can use a different tag of the consdb-hinfo container.

DM-44429: Support multiple instruments with separate hinfo deployments.

---

applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcamsim/values-usdfprod-prompt-processing.yaml

This PR reflects the new locations of the SQL APDB files. It does not try to migrate to Cassandra, as that can only be done self-consistently on #3427.

DM-44844: Deploy Cassandra for production Prompt Processing

---

applications/prompt-proto-service-lsstcomcamsim/values-usdfprod-prompt-processing.yaml

Disable autoscaling for OR4 ComCamSim to run static number of pods.  This is due to knative autoscaling issue.

Prompt Processing: Disable autoscaling for OR4 ComCamSim

---

applications/prompt-proto-service-lsstcomcamsim/values-usdfprod-prompt-processing.yaml

This PR switches ComCamSim-prod from pre-OR4 to OR4.

Configure Prompt Processing ComCamSim for OR4 repository

---

applications/prompt-proto-service-lsstcomcamsim/values-usdfprod-prompt-processing.yaml

This PR increases the service size from 100 pods to 150; experience from the first night suggests that 120 is (barely) sufficient, but that we can afford 150.

Increase fixed Prompt Processing size for ComCamSim.

---

charts/cadc-tap/templates/tap-ingress-anonymous.yaml
charts/cadc-tap/templates/tap-ingress-authenticated.yaml

**Description**
Taplint expects to find a "Server" header value in HTTP responses to the /capabilities endpoint, so it will produce a warning if it doesn't find it, which will affect the validation rating of the service: 
```
Section CAP: Check TAP and TAPRegExt content of capabilities document
W-CAP-SVR0-1 No HTTP Server header
I-CAP-SVRI-1 HTTP server header "Server: null"
```
I'm not sure if this is only applicable to the /capabilities endpoint. I've also briefly looked for this in the standard, and all I found is the wording similar to: "service SHOULD add a server header". So even though I'm not sure if this is a requirement or not, probably worth adding the header for now as it shouldn't have any other effect on the system.
**Fix**
Add custom headers to the TAP ingresses.
I've used …

Set custom server header value for TAP ingresses

---

applications/prompt-proto-service-lsstcomcamsim/values-usdfprod-prompt-processing.yaml

Adjust target utilization percentage to attempt to get higher utilization or running pods.  We saw 60% utilization of running pods.

Prompt Processing: ComCamSim Utilization Percentage

---

applications/datalinker/Chart.yaml
applications/vo-cutouts/Chart.yaml

Revert 468b395e5c4dda80b88c35585ac3c656c896e6ed.  These changes should have been deployed at the same time as a new release of Butler server due to a REST API backwards compatibility break.

Revert new version of datalinker and vo-cutouts

---

applications/sasquatch/README.md
applications/sasquatch/charts/strimzi-kafka/README.md
applications/sasquatch/charts/strimzi-kafka/values.yaml

- Make this the default configuration, which means that we allow one Kafka broker to fail and we improve the Kafka consumer's performance requiring that the messages are replicated to at least 2 brokers before being available for consumption.

Change Sasquatch Kafka min.insync.replicas setting to 2

---

applications/squareone/Chart.yaml

For the removal of Reach UI components from Squareone.
See https://github.com/lsst-sqre/squareone/pull/166

DM-44392: Update Squareone

---

applications/prompt-proto-service-hsc-gpu/README.md
applications/prompt-proto-service-hsc-gpu/values.yaml
applications/prompt-proto-service-hsc/README.md
applications/prompt-proto-service-hsc/values.yaml
applications/prompt-proto-service-latiss/README.md
applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-latiss/values.yaml
applications/prompt-proto-service-lsstcam/README.md
applications/prompt-proto-service-lsstcam/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-lsstcam/values.yaml
applications/prompt-proto-service-lsstcomcam/README.md
applications/prompt-proto-service-lsstcomcam/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcam/values.yaml
applications/prompt-proto-service-lsstcomcamsim/README.md
applications/prompt-proto-service-lsstcomcamsim/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcamsim/values.yaml
charts/prompt-proto-service/README.md
charts/prompt-proto-service/templates/prompt-proto-service.yaml
charts/prompt-proto-service/values.yaml

This PR does some Prompt Processing config cleanup and adds worker recycling for LATISS-prod and ComCamSim-prod.

DM-45007: Memory leak in Prompt Processing service

---

applications/sasquatch/README.md
applications/sasquatch/charts/telegraf-kafka-consumer/README.md
applications/sasquatch/charts/telegraf-kafka-consumer/templates/configmap.yaml
applications/sasquatch/charts/telegraf-kafka-consumer/values.yaml
applications/sasquatch/values-usdfprod.yaml

- Replace auxtel, latiss, lasertracker InfluxDB Sink connectors with corresponding Telegraf Kafka connectors
- Add new eas connectors

Telegraf Kafka chart improvements

---

docs/documenteer.toml
src/phalanx/services/vault.py
src/phalanx/storage/vault.py

We have one Vault token accessor that returns Forbidden for all attempted requests. Not sure what's going on with that, but it shouldn't block creating new write tokens, so ignore accessors that raise Forbidden. Hopefully this won't cause too many problems.

DM-45168: Ignore accessors that return forbidden

---

charts/rubintv/templates/deployment-frontend.yaml

The changes for allowing separate secrets accidentally changed behavior without them. Undo that.

DM-45168: Fix a conditional in the rubintv chart

---

applications/noteburst/README.md
applications/noteburst/templates/deployment.yaml
applications/noteburst/templates/worker-deployment.yaml
applications/noteburst/values-usdfdev.yaml
applications/noteburst/values.yaml
applications/times-square/README.md
applications/times-square/templates/deployment.yaml
applications/times-square/templates/worker-deployment.yaml
applications/times-square/values-usdfdev.yaml
applications/times-square/values.yaml

- The resource allocations for FastAPI front ends and arq backend workers are now separately tuneable for Times Square and Noteburst
- Resource allocations for the app pods as well as their redis databases are generally increased to provide better performance and reliability.

DM-45101: Increase and tune resource requirements for Noteburst and Times Square

---

applications/ssotap/secrets-idfprod.yaml
applications/ssotap/values-idfprod.yaml
applications/tap/secrets-idfprod.yaml
applications/tap/values-idfprod.yaml

**Description**
PR to move UWS database to CloudSQL for prod.
These changes have been deployed and tested on dev & int first
**Checklist:**
- Check that databases are available on CloudSQL [Done]
- Create SQL user password for ssotap & tap / Store password in 1pass  [Done]
- Run secrets sync for prod [Done]

Enable CloudSQL UWS db on prod

---

applications/sasquatch/README.md
applications/sasquatch/charts/strimzi-kafka/README.md
applications/sasquatch/charts/strimzi-kafka/templates/kafka.yaml
applications/sasquatch/charts/strimzi-kafka/values.yaml
applications/sasquatch/values-base.yaml
applications/sasquatch/values-usdfprod.yaml

We have three nodes with local storage at the USDF prod cluster that are available for Kafka. This PR adds the configuration necessary to create a new `KafkaNodePool` on those nodes and migrate the brokers to the new node pool using Cruise Control.

[DM-45239] Migrate Kafka brokers on USDF to local storage

---

applications/semaphore/templates/ingress.yaml
applications/squareone/templates/ingress.yaml

This switches Semaphore and Squareone's anonymous GafaelfawrIngress to a regular nginx Ingress. This allows Semaphore to continue serving broadcasts even when
there is a Gafaelfawr/CILogon outage.

DM-45251: Switch Squareone and Semaphore's anonymous ingresses to nginx ingress

---

applications/sasquatch/values-base.yaml

The Kafka brokers at BTS got new external IPs, we need to update the external listeners configuration and the DNS records on Route53.

Update external IPs for the Kafka brokers at BTS

---

applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml

This is a non-canonical config located on the old embargo rack. Once LATISS is switched over to new embargo, the file can be removed. (The S3 URL is the same on both racks.)

Switch Prompt Processing LATISS-prod to Cassandra.

---

applications/unfurlbot/Chart.yaml

Unfurlbot 0.2.2 fixes support for epics. See https://github.com/lsst-sqre/unfurlbot/pull/7

DM-45338: Update unfurlbot to 0.2.2

---

applications/prompt-proto-service-hsc-gpu/README.md
applications/prompt-proto-service-hsc-gpu/values.yaml
applications/prompt-proto-service-hsc/README.md
applications/prompt-proto-service-hsc/values.yaml
applications/prompt-proto-service-latiss/README.md
applications/prompt-proto-service-latiss/values.yaml
applications/prompt-proto-service-lsstcam/README.md
applications/prompt-proto-service-lsstcam/values.yaml
applications/prompt-proto-service-lsstcomcam/README.md
applications/prompt-proto-service-lsstcomcam/values.yaml
applications/prompt-proto-service-lsstcomcamsim/README.md
applications/prompt-proto-service-lsstcomcamsim/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcamsim/values.yaml
charts/prompt-proto-service/README.md
charts/prompt-proto-service/templates/prompt-proto-service.yaml
charts/prompt-proto-service/values.yaml

This PR reworks Prompt Processing's timeout configuration to be worker-centric rather than Knative-centric. It also adds a control for each worker's grace period.

DM-40434: Prompt Processing continues processing after timeout or termination

---

environments/values-idfdemo.yaml

This environment uses roundtable-dev, not roundtable.

Fix URL for 1Password connect for idfdemo

---

applications/prompt-proto-service-hsc-gpu/values.yaml
applications/prompt-proto-service-hsc/values.yaml
applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-latiss/values.yaml
applications/prompt-proto-service-lsstcomcamsim/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcamsim/values.yaml

This PR adds verbose logging to two tasks known to run slowly in Prompt Processing. This activates some logs that were added on lsst/meas_base#280, lsst/meas_transiNet#27, and lsst/ap_association#229. The tasks do not produce verbose logs otherwise.

DM-43599: Add progress logs to slow AP tasks

---

applications/squarebot/Chart.yaml
applications/unfurlbot/Chart.yaml

This version of unfurlbot supports unfurling tokens from bot messaes like Sup standup reports.
See https://github.com/lsst-sqre/unfurlbot/pull/8
Also update squarebot to 0.9.0 to support bot messages and reducing the combined content of slack messages across attachments. https://github.com/lsst-sqre/squarebot/releases/tag/0.9.0

DM-45383: Update to Unfurlbot 0.3.0

---

applications/sasquatch/README.md
applications/sasquatch/charts/strimzi-kafka/Chart.yaml
applications/sasquatch/charts/strimzi-kafka/README.md
applications/sasquatch/charts/strimzi-kafka/values.yaml
applications/sasquatch/values-idfdev.yaml

Alongside with renovate PRs, test these Sasquatch dependencies on data-dev before rolling out to other environments.  
- Strimzi 0.42.0
- Kafka 3.7.1
- Kafka REST Proxy v7.6.2
- Kafdrop v4.0.2
- Kapacitor v1.7.5

[DM-45415] Sasquatch dependency updates

---

docs/applications/_summary.rst.jinja
docs/environments/_summary.rst.jinja
src/phalanx/models/environments.py
src/phalanx/storage/config.py
tests/docs/jinja_test.py

Refactor the `EnvironmentDetails` model to separate the Gafaelfawr and Argo CD information into submodels to make it easier to organize the code. Extract information about the authentication provider used for Argo CD and add it to the environment documentation pages.

DM-45503: Add Argo CD auth provider details to docs

---

applications/tap/secrets-idfint.yaml
applications/tap/values-idfint.yaml
charts/cadc-tap/README.md
charts/cadc-tap/templates/tap-deployment.yaml
charts/cadc-tap/values.yaml

This PR modifies the cadc-tap chart to accept and pass in an optional QServ password. The password is expected and passed in when `config.qserv.passwordEnabled` is set to true otherwise the qserv password env value is empty, which is what it was previously to this change.
The other change is to move idfint to use the new QServ host: "qserv-int.slac.stanford.edu:4040" with passwordEnabled: true.
Additional changes include adding a qserv-password for idfint (secrets-idfint.yaml).
**JIRA issue:**
https://rubinobs.atlassian.net/browse/DM-45466
**Tests:**
The change was tested on dev, by applying the equivalent changes here, and testing with the new Qserv and passwordEnabled, as well as with the previous and without passwordEnabled

DM-45466: Optional QServ pw secret & idfint to point to new pw-protected Qserv

---

applications/butler/Chart.yaml
applications/datalinker/Chart.yaml
applications/vo-cutouts/Chart.yaml
applications/vo-cutouts/README.md
applications/vo-cutouts/templates/configmap.yaml
applications/vo-cutouts/templates/worker-deployment.yaml
applications/vo-cutouts/values.yaml

Update datalinker, vo-cutouts, and butler to their latest releases. These releases have to be updated together due to backwards-incompatible changes to the Butler server API. This release of datalinker drops support for direct Butler and requires client/server Butler.
Update the Phalanx Helm chart for vo-cutouts for the latest release, which changes the format of some time intervals and adds a new grace period configuration option.

DM-45281: Update datalinker, vo-cutouts, and butler

---

docs/developers/helm-chart/create-new-chart.rst
src/phalanx/models/helm.py
src/phalanx/storage/helm.py
starters/README.md
starters/fastapi-safir-uws/Chart.yaml
starters/fastapi-safir-uws/secrets.yaml
starters/fastapi-safir-uws/templates/_helpers.tpl
starters/fastapi-safir-uws/templates/configmap.yaml
starters/fastapi-safir-uws/templates/db-worker-deployment.yaml
starters/fastapi-safir-uws/templates/db-worker-networkpolicy.yaml
starters/fastapi-safir-uws/templates/deployment.yaml
starters/fastapi-safir-uws/templates/ingress.yaml
starters/fastapi-safir-uws/templates/networkpolicy.yaml
starters/fastapi-safir-uws/templates/service.yaml
starters/fastapi-safir-uws/templates/serviceaccount.yaml
starters/fastapi-safir-uws/templates/vault-secrets.yaml
starters/fastapi-safir-uws/templates/worker-deployment.yaml
starters/fastapi-safir-uws/templates/worker-networkpolicy.yaml
starters/fastapi-safir-uws/values.yaml

Add a starter for vo-cutouts-style FastAPI Safir apps that use UWS. Update the code underlying phalanx application create so that it will substitute `<CHARTENVPREFIX>` in every template, not just `configmap.yaml`.

DM-45494: Add fastapi-safir-uws starter

---

applications/sasquatch/values-usdfprod.yaml

Earthquake data from USGS is now replicated over Kafka to USDF, add a connector to write this data to InfluxDB Enterprise at USDF

Add backpack connector at USDF

---

applications/butler/README.md
applications/butler/templates/configmap.yaml
applications/butler/templates/deployment.yaml
applications/butler/values-idfdev.yaml
applications/butler/values-idfint.yaml
applications/butler/values-idfprod.yaml
applications/butler/values.yaml

Butler configuration files on IDF were previously hosted in an S3 bucket, which is difficult to manage and not version controlled.  They are now injected from Phalanx as a ConfigMap instead.

DM-45572: Move Butler server configuration files into Phalanx

---

applications/datalinker/README.md
applications/datalinker/templates/deployment.yaml
applications/datalinker/values.yaml
docs/developers/injected-values.rst
docs/extras/schemas/environment.json
environments/README.md
environments/templates/applications/rsp/datalinker.yaml
environments/templates/applications/rsp/vo-cutouts.yaml
environments/values-idfdemo.yaml
environments/values-idfdev.yaml
environments/values-idfint.yaml
environments/values-idfprod.yaml
environments/values-usdfdev.yaml
environments/values-usdfint.yaml
environments/values-usdfprod.yaml
environments/values.yaml
src/phalanx/models/environments.py
src/phalanx/services/application.py

The environment-global configuration item`butlerRepositoryIndex` appears to be unused now that datalinker and vo-cutouts have dropped support for DirectButler, so it can be removed.  (nublado always separately hardcoded this path in its own configuration, and nothing else is using it.)

DM-45620: Removed unused butlerRepositoryIndex config

---

applications/sasquatch/values-summit.yaml

- In the last Summit window we increased the Kafka retention period to 7 days due to the USDF outage, we are setting this configuration back to its default which is 24h.

[DM-45647] Set Kafka retention period back to its default configuration at the Summit

---

applications/mobu/Chart.yaml
applications/mobu/values-idfdev.yaml
applications/mobu/values-idfint.yaml
applications/mobu/values-idfprod.yaml
applications/mobu/values-usdfdev.yaml
applications/mobu/values-usdfint.yaml
applications/mobu/values-usdfprod.yaml

It's in the [in-repo config](https://mobu.lsst.io/user_guide/in_repo_config.html) in each notebook repo now.

DM-44635: mobu: ditch `exclude_dirs` from autostart config

---

applications/ook/Chart.yaml
applications/ook/README.md
applications/ook/templates/cronjob-audit.yaml
applications/ook/templates/cronjob-ingest-updated.yaml
applications/ook/templates/deployment.yaml
applications/ook/values.yaml

Updates Ook to use faststream for its kafka usage. See https://github.com/lsst-sqre/ook/pull/160

DM-45676: Deploy Ook 0.10.0

---

applications/sasquatch/charts/influxdb-enterprise/values.yaml

nodePorts are currently specified in the InfluxDB Enterprise meta and data services in Sasquatch.
Kubernetes is automatically assigning their values and the Service gets out of sync in ArgoCD from time to time. 
It turns out nodePorts are not required for these services, so just not allocate them.

Do not allocate nodePort for meta and data services

---

applications/ssotap/values-idfdev.yaml
applications/ssotap/values-idfint.yaml
applications/ssotap/values-idfprod.yaml
applications/tap/secrets-idfdev.yaml
applications/tap/values-idfdev.yaml
applications/tap/values-idfint.yaml
applications/tap/values-idfprod.yaml
charts/cadc-tap/README.md
charts/cadc-tap/templates/configmap.yaml
charts/cadc-tap/templates/tap-deployment.yaml
charts/cadc-tap/values.yaml

**Summary:**
Move UWS databases for all idfs to CloudSQL & upgrade TAP images
**Detailed Description:**
This PR includes the following changes to phalanx:
- Enable cloudsql on all the idfs to move the UWS database to CloudSQL for the ssotap & tap applications
- Upgrade TAP to version 2.4.7
- Upgrade tap-postgres to version 1.18.5
- Add -Dpath_prefix param, needed by the upgraded version of TAP (Lets it know what the path is for generating the redirect URLs)
- Move tap config to /config on the tomcat container, needed by the upgraded TAP version (upstream cadc changes)
- Move idfdev to use the new int QServ that is password protected
- Change idfdev & idfint TAP services to use TLSv1.3 for the QServ connection (This is enabled via upgrade to mysql connector in the newer TAP releases)
The …

DM-45307: Move UWS databases for all idfs to CloudSQL & upgrade TAP images

---

applications/sasquatch/charts/telegraf-kafka-consumer/values.yaml
applications/sasquatch/values-usdfprod.yaml

CCS kafka producers are running routinely now and publishing data to Sasquatch at the Summit.
Thought this is still experimental, we are enabling replication to USDF and configuring connectors at USDF to ingest CCS data in the InfluxDB Enterprise.

[DM-45801] Enable CCS data replication to USDF and configure connectors

---

applications/nublado/Chart.yaml
applications/nublado/README.md
applications/nublado/values-base.yaml
applications/nublado/values-idfdemo.yaml
applications/nublado/values-idfdev.yaml
applications/nublado/values-idfint.yaml
applications/nublado/values-idfprod.yaml
applications/nublado/values-roe.yaml
applications/nublado/values-summit.yaml
applications/nublado/values-tucson-teststand.yaml
applications/nublado/values.yaml

Bump versions to the new release of Nublado and take advantage of the new timedelta syntax, except for the spawnTimeout since it is also passed into JupyterHub configuration.
Fix some 6.1.0 versions that weren't increased in previous Nublado releases.

DM-45794: Update to Nublado 6.3.0

---

applications/argocd/values-idfprod.yaml

He needs to see Argo CD status for the Butler server in production.

Add dirving to idfprod Argo CD as a developer

---

applications/squareone/Chart.yaml
applications/squareone/README.md
applications/squareone/templates/configmap.yaml
applications/squareone/values-idfdev.yaml
applications/squareone/values-idfprod.yaml
applications/squareone/values.yaml

See https://github.com/lsst-sqre/squareone/pull/171
Enables Plausible tracking for data-dev and data.lsst.cloud.

DM-45786: Add Plausible.io tracking support to Squareone

---

applications/alert-stream-broker/README.md
applications/alert-stream-broker/charts/alert-stream-schema-registry/README.md
applications/alert-stream-broker/charts/alert-stream-schema-registry/templates/schema-registry-server.yaml
applications/alert-stream-broker/charts/alert-stream-schema-registry/templates/sync-schema-job.yaml
applications/alert-stream-broker/charts/alert-stream-schema-registry/values.yaml

Remakes schema registry every time the broker is fully synced. Keeps versioning consistent in the registry.

DM-42606 Update schema registry sync to load all schemas

---

applications/gafaelfawr/values-roe.yaml

**Summary:**
New version of TAP services expect to find the auth/cadc endpoint which requires setting up a cadcBaseUuid in gafaelfawr. This PR addresses this for the roe environment.

Enable cadcBaseUuid in gafaelfawr for roe environment

---

applications/sasquatch/charts/strimzi-kafka/templates/users.yaml
applications/sasquatch/secrets.yaml
applications/sasquatch/values-idfdev.yaml

Password is in 1pass: `RSP data-dev.lsst.cloud/sasquatch/appmetrics-password`
Secret has been sync'd.
Test:
```
❯ export KAFKA_PASSWORD=$(op read "op://RSP data-dev.lsst.cloud/sasquatch/appmetrics-password")
❯ echo "blah" | kcat -b sasquatch-dev-kafka-bootstrap.lsst.cloud:9094 -X
security.protocol=SASL_SSL -X sasl.mechanism=SCRAM-SHA-512 -X
sasl.username=appmetrics -X sasl.password=$KAFKA_PASSWORD -P -t
lsst.square.metrics.dfuchs-test
❯ kcat -b sasquatch-dev-kafka-bootstrap.lsst.cloud:9094 -X
security.protocol=SASL_SSL -X sasl.mechanism=SCRAM-SHA-512 -X
sasl.username=appmetrics -X sasl.password=$KAFKA_PASSWORD -P -t
lsst.square.metrics.dfuchs-test -C -o 0
blah
```

DM-44635: appmetrics Kafka/Sasquatch user

---

applications/sasquatch/README.md
applications/sasquatch/charts/strimzi-kafka/README.md
applications/sasquatch/charts/strimzi-kafka/values.yaml

More information on this version in this [blog post](https://kafka.apache.org/blog#apache_kafka_380_release_announcement).

[DM-46000] Upgrade Kafka to version 3.8.0

---

applications/butler/values.yaml

Butler server's memory limit was set too low previously -- it could easily result in an out-of-memory kill with just a couple in-flight requests.

DM-45907: Increase Butler memory limit

---

applications/prompt-proto-service-hsc-gpu/README.md
applications/prompt-proto-service-hsc-gpu/values.yaml
applications/prompt-proto-service-hsc/README.md
applications/prompt-proto-service-hsc/values.yaml
applications/prompt-proto-service-latiss/README.md
applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-latiss/values.yaml
applications/prompt-proto-service-lsstcam/README.md
applications/prompt-proto-service-lsstcam/values.yaml
applications/prompt-proto-service-lsstcomcam/README.md
applications/prompt-proto-service-lsstcomcam/values.yaml
applications/prompt-proto-service-lsstcomcamsim/README.md
applications/prompt-proto-service-lsstcomcamsim/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcamsim/values.yaml
charts/prompt-proto-service/README.md
charts/prompt-proto-service/templates/prompt-proto-service.yaml
charts/prompt-proto-service/values.yaml

This PR configures Prompt Processing to use the raw image microservice introduced in DM-39022.

DM-45005: In Prompt Processing, use microservice to check for already-arrived Rubin images

---

applications/sasquatch/charts/telegraf-kafka-consumer/templates/configmap.yaml
applications/sasquatch/charts/telegraf-kafka-consumer/templates/deployment.yaml

Increase default ``flush_interval`` to fix warning and improve labels to select connector instances.

[DM-46075] Fix for ["outputs.influxdb"] did not complete within its flush interval

---

applications/butler/README.md
applications/butler/secrets.yaml
applications/butler/templates/deployment.yaml
applications/butler/values-idfdev.yaml
applications/butler/values.yaml

We want to use the ir2 repo to test the "hybrid model" where the Butler's database is at Google but the data is at USDF.
Added a configuration option to Butler to allow it to use two different sets of S3 credentials simultaneously.  Added the ir2 repo to data-dev.

DM-44544: Add ir2 repo to idfdev Butler server

---

applications/prompt-proto-service-hsc-gpu/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-hsc/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-latiss/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcamsim/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcamsim/values-usdfprod-prompt-processing.yaml

This PR configures Prompt Processing to run a preprocessing pipeline before raw arrival. It must be merged together with lsst-dm/prompt_processing#191.

DM-43418: Divide AP pipeline into preload and prompt subsets

---

applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml

This PR should wait for a future prompt-service release that includes https://github.com/lsst-dm/prompt_processing/pull/181 changes

DM-44605: Enable LATISS Prompt Processing to process BLOCK-T17

---

applications/sasquatch/charts/telegraf-kafka-consumer/templates/configmap.yaml

We need an extra tag to identify the Telegraf instance from which the internal metrics are collected when running multiple instances of Telegraf (e.g. one Telegraf instance per connector).
As a result route the Telegraf internal metrics to its own database to separate them and configure a different retention period for Telegraf database.
Example:

[DM-46176] Add an extra tag for the Telegraf internal metrics 

---

applications/butler/Chart.yaml

Upgrade to a new version of Butler server with support for a `query_collection_info` endpoint that is needed by the new Butler Collections API that will be part of the 2024_37 pipelines stack.

DM-46129: Upgrade Butler server for collections API

---

applications/noteburst/Chart.yaml
applications/noteburst/README.md
applications/noteburst/values.yaml
applications/times-square/Chart.yaml
applications/times-square/README.md
applications/times-square/templates/configmap.yaml
applications/times-square/values-idfdev.yaml
applications/times-square/values.yaml

This version of Times Square adds timeouts for GitHub Check runs to protect against hanging Noteburst executions.
See https://github.com/lsst-sqre/times-square/pull/81 and https://github.com/lsst-sqre/times-square/releases/tag/0.13.0
Also deploys noteburst 0.13.0 with support for timeouts in its jobs. https://github.com/lsst-sqre/noteburst/releases/tag/0.13.0

DM-46137: Deploy Times Square 0.13.0

---

applications/times-square/values.yaml

We're experiencing OOMKilled with 2Gi memory limits for the Times Square redis on usdf-rsp-dev

Increase memory for Times Square redis

---

applications/gafaelfawr/values-idfprod.yaml
docs/applications/gafaelfawr/add-oidc-client.rst
docs/applications/gafaelfawr/index.rst

Enable the Gafaelfawr OpenID Connect server on idfprod and configure it with a data rights mapping. Add documentation for how to add new OpenID Connect clients.

DM-46380: Enable OpenID Connect on idfprod

---

applications/prompt-proto-service-hsc-gpu/README.md
applications/prompt-proto-service-hsc-gpu/values.yaml
applications/prompt-proto-service-hsc/README.md
applications/prompt-proto-service-hsc/values.yaml
applications/prompt-proto-service-latiss/README.md
applications/prompt-proto-service-latiss/values.yaml
applications/prompt-proto-service-lsstcam/README.md
applications/prompt-proto-service-lsstcam/values.yaml
applications/prompt-proto-service-lsstcomcam/README.md
applications/prompt-proto-service-lsstcomcam/values.yaml
applications/prompt-proto-service-lsstcomcamsim/README.md
applications/prompt-proto-service-lsstcomcamsim/values.yaml
charts/prompt-proto-service/README.md
charts/prompt-proto-service/templates/prompt-proto-service.yaml
charts/prompt-proto-service/values.yaml

This PR allows Prompt Processing to be configured with multiple workers per pod. This does not add any configuration fields, since we reuse the old `containerConcurrency` hook.

DM-45199: Support multiple workers per Prompt Processing pod

---

charts/cadc-tap/README.md
charts/cadc-tap/values.yaml

**Summary**
Upgrades the tap-postgres release to 1.18.6
**What has changed?**
- Remove deprecated AuthenticatorImpl class by @stvoutsin in https://github.com/lsst-sqre/tap-postgres/pull/41
- Remove jcenter repo as it is obsolete and no longer used by cadc by @stvoutsin in https://github.com/lsst-sqre/tap-postgres/pull/42
- Switch RubinUploadManagerImpl to use UploadLimits by @stvoutsin in https://github.com/lsst-sqre/tap-postgres/pull/43
- Enable storage of results in non-GCS S3 buckets by @stvoutsin in https://github.com/lsst-sqre/tap-postgres/pull/44
- Prepare release 1.18.6 by @stvoutsin in https://github.com/lsst-sqre/tap-postgres/pull/45
**How was this tested?**
https://github.com/stvoutsin/rspvalidator

Upgrade version of ssotap to 1.18.6

---

applications/sasquatch/charts/square-events/templates/templatebot-user.yaml
applications/templatebot/.helmignore
applications/templatebot/Chart.yaml
applications/templatebot/README.md
applications/templatebot/secrets.yaml
applications/templatebot/templates/_helpers.tpl
applications/templatebot/templates/configmap.yaml
applications/templatebot/templates/deployment.yaml
applications/templatebot/templates/kafkaaccess.yaml
applications/templatebot/templates/networkpolicy.yaml
applications/templatebot/templates/service.yaml
applications/templatebot/templates/vaultsecret.yaml
applications/templatebot/values-roundtable-dev.yaml
applications/templatebot/values.yaml
docs/applications/roundtable.rst
docs/applications/templatebot/index.rst
docs/applications/templatebot/values.md
environments/README.md
environments/templates/applications/roundtable/templatebot.yaml
environments/values-roundtable-dev.yaml
environments/values.yaml

This adds [templatebot](https://github.com/lsst-sqre/templatebot) into Phalanx for deployment with the modern Roundtable clusters.
Templatebot works with the Squarebot message bus, so it works similarly to apps like Unfurlbot.
See https://github.com/lsst-sqre/templatebot/pull/67

DM-43699: Add Phalanx application for Templatebot

---

docs/developers/helm-chart/define-secrets.rst

The new starters no longer define a fullname macro since it's not needed for Phalanx Helm charts. Remove the last reference to it in the documentation.

DM-46396: Stop using fullname macro in docs

---

applications/sasquatch/README.md
applications/sasquatch/charts/telegraf-kafka-consumer/README.md
applications/sasquatch/charts/telegraf-kafka-consumer/templates/configmap.yaml
applications/sasquatch/charts/telegraf-kafka-consumer/values.yaml
applications/sasquatch/values-summit.yaml

The Kafka Consumer input plugin has three configuration parameters that impact throughput, `metric_batch_size`,  `max_undelivered_messages` and `compression_codec`.
When increasing `metric_batch_size` we also need to increase `max_undelivered_messages` to flush the messages from the brokers. 
Based on tests at the Summit tuning these parameters seems enough to increase the connector throughput to handle M1M3 and MTMount throughput and is a better strategy than running multiple replicas of Telegraf to keep up with the telemetry stream.
```
##
```
The other configuration parameter that has an impact is compression.
```
```
This configuration is handling well the high throughput CSCs with only one Telgraf replica:

[DM-46252] Review Telegraf connector configuration for high throughput 

---

docs/environments/_summary.rst.jinja
src/phalanx/models/environments.py
src/phalanx/storage/config.py

If Gafaelfawr is configured with CILogon and there's an enrollment URL, assume that it points to COmanage and extract its hostname. Add a COmanage link to the environment page for this environment.

DM-46396: Add a COmanage link to environment pages

---

docs/admin/troubleshooting.rst

Document that UID/GID assignment is only based on username, and a user can be deleted from COmanage and then recreated with the same username and they will retain the same UID and GID and thus the same file access.

DM-46396: Document restoring user with same UID/GID

---

applications/sasquatch/values-usdfprod.yaml

To alleviate the race condition we are seeing in the Telegraf Avro parser (see DM-46250) we split the topics handled by the auxtel and eas connectors in two instances. 
While this is totally empirical it seems to help if each connector instance processes less topics. 
This change is applied to USDF only for the moment.

[DM-46203] Alleviate race condition in the Telegraf Avro parser

---

applications/sasquatch/charts/influxdb-enterprise/templates/data-statefulset.yaml

- InfluxDB Enterprise needs more time to read the shards from disk when restarting. The readiness probe was killing the data pods too early preventing it to restart.

[DM-46408] Increase readiness probe initial delay

---

docs/applications/gafaelfawr/add-oidc-client.rst

The instructions for setting up a new OpenID Connect client secret didn't match the expected contents of that secret. Fix them to match.

DM-46380: Fix naming of OpenID Connect client secrets

---

applications/sasquatch/values-base.yaml

We optimized the connector configuration for throughput, we can run m1m3 and mtmount connectors with one replica now. Also use a Telegraf version that fixes a race condition bug found in the Telegraf Avro parser.

[DM-46250] Review configuration for the Telegraf connectors at BTS

---

applications/butler/README.md
applications/butler/templates/configmap.yaml
applications/butler/values-idfdev.yaml
applications/butler/values-idfint.yaml
applications/butler/values.yaml

To facilitate testing by the Community Science Team and start getting stability testing from Mobu, switch the default dp02 alias on `idfdev` and `idfint` to point to client/server Butler instead of DirectButler.
`idfprod` will remain on DirectButler until testing has been completed and information about the transition has been communicated to users.

DM-46286: Make Butler client/server default on IDF int/dev dp02

---

applications/sasquatch/values-base.yaml

- Reducing the batch size configuration in Telegraf from 5000 to 2500 messages fixed the problem. It seems that 5000 messages * avg size of M1M3 messages was too large for a request to the InfluxDB API.

[DM-46463] Fix context deadline exceeded error

---

charts/prompt-proto-service/templates/prompt-proto-service.yaml

This PR removes all references to `.pgpass` from Prompt Processing configurations.

DM-46494: Migrate Prompt Processing to pure db-auth authentication

---

applications/sasquatch/values-base.yaml
applications/sasquatch/values-summit.yaml
applications/sasquatch/values-tucson-teststand.yaml
applications/sasquatch/values-usdfprod.yaml

The `lsst.obsenv` namespace was requested in Sasquatch for additional information about the observing environment. 
This PR registers the new namespace with the REST Proxy API, add the connector configuration for the telescope environments and enables replication to USDF.

Add lsst.obsenv namespace for telescope environments

---

charts/cadc-tap/README.md
charts/cadc-tap/values.yaml

Update to [sdm_schemas 3.2.1](https://github.com/lsst/sdm_schemas/releases/tag/v3.2.1), which removes the UWS table metadata from the deployed TAP_SCHEMA image.

Update sdm_schemas to 3.2.1

---

applications/sasquatch/values-summit.yaml
applications/sasquatch/values-usdfprod.yaml

The `lsst.cp` namespace is used to record Calibration Pipeline metrics at the Summit.
This PR registers this namespace with the REST Proxy API, adds the connector configuration and enables replication to USDF.

[DM-46512] Add new lsst.cp namespace to Sasquatch

---

environments/values-idfdev.yaml
environments/values-idfint.yaml
environments/values-idfprod.yaml

**Description**
Since we are rolling out a new SIAv2 application that uses Butler to replace the previous CADC based one, it makes sense to deprecate the previous one. This PR is a first step towards that, by turning off siav2 on the IDF environments. 
I'm keeping the actual app in phalanx for now until we decide whether it will still be supported in the future or not (alongside the new one).

DM-46493: Turn off siav2 app on all IDFs

---

applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml

This PR updates the LATISS production version for Prompt Processing and adds some clarifying comments to the config.

Deploy Prompt Processing 4.5.1 for LATISS

---

applications/alert-stream-broker/README.md
applications/alert-stream-broker/charts/alert-stream-broker/README.md
applications/alert-stream-broker/charts/alert-stream-broker/templates/kafka-topics.yaml
applications/alert-stream-broker/charts/alert-stream-broker/templates/kafka.yaml
applications/alert-stream-broker/charts/alert-stream-broker/values.yaml
applications/alert-stream-broker/charts/alert-stream-schema-registry/README.md
applications/alert-stream-broker/charts/alert-stream-schema-registry/templates/schema-registry-server.yaml
applications/alert-stream-broker/charts/alert-stream-schema-registry/values.yaml
applications/alert-stream-broker/values-usdfdev-alert-stream-broker.yaml

Update the Kafka version to 3.7 and add kraft. The zookeeper has now been removed and we will uses kraft going forward. Add LATISS specific topic for production testing.

DM-46236: Updated Kafka to 3.7/add kraft/add LATISS topic

---

applications/sasquatch/README.md
applications/sasquatch/charts/telegraf-kafka-consumer/README.md
applications/sasquatch/charts/telegraf-kafka-consumer/templates/_helpers.tpl
applications/sasquatch/charts/telegraf-kafka-consumer/values.yaml
applications/sasquatch/values-base.yaml
applications/sasquatch/values-tucson-teststand.yaml
applications/sasquatch/values-usdfprod.yaml

In DM-46463 we reduced the `metric_batch_size` configuration to 2500 to fix the error at BTS. This was seen later at USDF and Summit with the M1M3 connector where we reduced metric_batch_size even further to 1000 messages.
This ticket makes metric_batch_size = 1000 the default configuration in all environments.

[DM-46595] Review metric_batch_size configuration in Sasquatch

---

applications/ppdb-replication/.helmignore
applications/ppdb-replication/Chart.yaml
applications/ppdb-replication/README.md
applications/ppdb-replication/secrets.yaml
applications/ppdb-replication/templates/_helpers.tpl
applications/ppdb-replication/templates/configmap.yaml
applications/ppdb-replication/templates/deployment.yaml
applications/ppdb-replication/templates/ingress.yaml
applications/ppdb-replication/templates/networkpolicy.yaml
applications/ppdb-replication/templates/pvc.yaml
applications/ppdb-replication/templates/service.yaml
applications/ppdb-replication/templates/vault-secrets.yaml
applications/ppdb-replication/values-usdfdev.yaml
applications/ppdb-replication/values.yaml
docs/applications/ppdb-replication/index.rst
docs/applications/ppdb-replication/values.md
docs/applications/rsp.rst
docs/applications/rubin.rst
environments/README.md
environments/templates/applications/rubin/ppdb-replication.yaml
environments/values-usdfdev.yaml
environments/values.yaml

Add initial version of an application which replicates data between the APDB and PPDB using utilities from [dax_ppdb](https://github.com/lsst/dax_ppdb).
This application is only enabled on `usdf-rsp-dev` for now.

DM-46257: Add initial version of ppdb-replication application

---

applications/sasquatch/charts/app-metrics/templates/telegraf-configmap.yaml
applications/sasquatch/charts/telegraf-kafka-consumer/templates/_helpers.tpl

We used the `namepass` filter in the Telegraf configuration to route Telegraf internal metrics to its own database. We also need to exclude them from the default output using the `namedrop` filter.

Exclude telegraf internal metrics from default output

---

applications/alert-stream-broker/README.md
applications/alert-stream-broker/charts/alert-database/README.md
applications/alert-stream-broker/charts/alert-database/templates/ingress.yaml
applications/alert-stream-broker/charts/alert-database/values.yaml
applications/alert-stream-broker/values-usdfdev.yaml

The next release of Gafaelfawr will drop support for manually configuring Kubernetes ingresses to use Gafaelfawr and will require the use of `GafaelfawrIngress` resources. Convert the ingress for the alert-database subchart of alert-stream-broker to use `GafaelfawrIngress`.

DM-46399: Convert manual ingress to GafaelfawrIngress

---

applications/squarebot/secrets.yaml
applications/templatebot/Chart.yaml
applications/templatebot/README.md
applications/templatebot/secrets.yaml
applications/templatebot/templates/configmap.yaml
applications/templatebot/templates/deployment.yaml
applications/templatebot/values.yaml
environments/values-roundtable-prod.yaml

See https://github.com/lsst-sqre/templatebot/pull/67
Deploys templatebot to roundtable-prod and roundtable-dev.

DM-43699: Deploy templatebot 0.3.0

---

applications/sasquatch/values-summit.yaml
applications/sasquatch/values-usdfprod.yaml

Per discussion in[ Slack](https://rubin-obs.slack.com/archives/C07QM71CVQU/p1728406878984569) Brian Stalder and ​Petr Kubanek concluded we should record all MTVS telemetry in the EFD.
The raw telemetry is now downsampled from 1kHz to 200Hz, and we should record it at both Summit and USDF.
On the EFD side we have made improvements that makes this possible now.
- We improved significantly the EFD at USDF with an InfluxDB Enterprise cluster and local (fast) storage. 
- Kafka is also running on local (fast) storage and we are not constrained by disk space as before.
- We have a timeout that would kill queries longer than 5 min to protect the database.

Record MTVMS telemetry at both Summit and USDF

---

applications/sasquatch/charts/telegraf-kafka-consumer/templates/_helpers.tpl
applications/sasquatch/values-usdfprod.yaml

The repair connector functionality is missing in the Telegraf based connectors. 
The idea is to enable a repair connector in the Telegraf connector configuration, for example:
```
maintel:
enabled: true
repair: true
database: "efd"
timestamp_field: "private_efdStamp"
topicRegexps: |
[ "lsst.sal.MTAOS", "lsst.sal.MTDome", "lsst.sal.MTDomeTrajectory", "lsst.sal.MTPtg" ]
debug: true
```  
This will deploy another Kafka consumer with similar configuration but with a  consumer group named `telegraf-kafka-consumer-maintel-repairer` and with offsets set to oldest.
This is the minimal functionality we need to reingest the data in Kafka to InfluxDB.
To have more fine grained control one still can set the offsets for the consumer group manually.
This was used to recover data at USDF between Oct 6 …

[DM-46735] Implement the repair connector functionality for the Telegraf based connectors in Sasquatch

---

applications/sasquatch/README.md
applications/sasquatch/charts/app-metrics/README.md
applications/sasquatch/charts/app-metrics/values.yaml
applications/sasquatch/values-idfdev.yaml

Provision initial app metrics Sasquatch config for mobu, following these instructions:
https://sasquatch.lsst.io/user-guide/app-metrics.html#configuration

DM-45522 mobu: App metrics events config

---

applications/butler/templates/configmap.yaml

In the Butler configuration used for Butler server and DirectButler, add new relative roots that can be used to reference the DP02 raw image files and files from DP01.
Raw images for DP02 and datasets imported from DP01 were stored in a different S3 buckets than the rest of the files, when this repository was first created.  These were previously referenced from the Registry DB as absolute URLs, which are going to break when the data moves to its new home at SLAC.
Initially no datasets will be present in the new datastores -- it will require a separate migration for this change to take effect.

DM-46701: Update Butler configuration in preparation for moving DP02 files to SLAC

---

applications/consdb/Chart.yaml
applications/consdb/README.md
applications/consdb/secrets.yaml
applications/consdb/templates/hinfo-deployment.yaml
applications/consdb/templates/pq-deployment.yaml
applications/consdb/templates/vault-secrets.yaml
applications/consdb/values-base.yaml
applications/consdb/values-summit.yaml
applications/consdb/values-tucson-teststand.yaml
applications/consdb/values-usdfdev.yaml
applications/consdb/values-usdfprod.yaml
applications/sasquatch/values-tucson-teststand.yaml
docs/developers/helm-chart/values-yaml.rst

Add consdb to Sasquatch's kafka users. Reorganize secrets for consdb. This first step was meant to create consdb on TTS, with the same configuration as on Summit as far as we can. The next steps will be to upgrade consdb, hinfo, pqserver to the most recent commits and test that they work as expected with the correct alembic migration already applied. (At TTS then at Summit)

Update consdb secrets in TTS

---

applications/sasquatch/README.md
applications/sasquatch/charts/strimzi-kafka/README.md
applications/sasquatch/charts/strimzi-kafka/values.yaml
applications/sasquatch/values-summit.yaml
applications/sasquatch/values-usdfprod.yaml

We recently moved Kafka to local storage at both Summit and USDF clusters and have more storage available. Increasing the retention period from 3 to 7 days helps to recover data from outages and we can do it now that we have more storage.

[DM-46785] Increase Kafka retention to 7 days at Summit and USDF Sasquatch environments

---

.github/workflows/docs.yaml

We need to test the documentation build if any dependencies have changed, since they may be Sphinx dependencies. We missed a breaking Sphinx change because we didn't have that test.

Force a docs build if dependencies change

---

applications/sasquatch/README.md
applications/sasquatch/charts/app-metrics/README.md
applications/sasquatch/charts/app-metrics/templates/telegraf-configmap.yaml
applications/sasquatch/charts/app-metrics/values.yaml

* `service` -> `app_name` for metrics event app metadata InfluxDB tag
* Change the metrics InfluxDB database name to be consistent with how other Sasquatch DBs are named

DM-45522: sasquatch metrics events tweaks

---

applications/exposurelog/README.md
applications/exposurelog/templates/ingress.yaml
applications/exposurelog/values.yaml
applications/narrativelog/README.md
applications/narrativelog/templates/ingress.yaml
applications/narrativelog/values.yaml
applications/nightreport/README.md
applications/nightreport/templates/ingress.yaml
applications/nightreport/values.yaml

The next release of Gafaelfawr will drop support for manually configuring Kubernetes ingresses to use Gafaelfawr and will require the use of `GafaelfawrIngress` resources. Convert the three remaining relevant usages in Phalanx.
These ingresses previously didn't require any specific scopes for access. I added `exec:internal-tools` for this purpose about a year ago so everyone's tokens should now have that scope. Add that scope restriction as part of this conversion if authentication is enabled.
Currently, the authentication portion was disabled. Preserve that by configuring the ingreses to be anonymous by default, but add a configuration option that can be used to enable authentication when that is ready.

DM-46399: Convert manual ingresses to GafaelfawrIngress

---

applications/sasquatch/charts/influxdb-enterprise/templates/data-statefulset.yaml

- Increase the failureThreshold to ensure that the pod can remain not ready for longer before it is killed by the liveness probe, and thus has enough time to start.

Increase liveness probe failureThreshold for InfluxDB Enterprise

---

applications/vo-cutouts/values-idfint.yaml
applications/vo-cutouts/values-idfprod.yaml

These schema updates have been complete, so disable schema updates to return to the default.

Disable vo-cutouts schema updates

---

applications/gafaelfawr/README.md
applications/gafaelfawr/templates/_helpers.tpl
applications/gafaelfawr/values.yaml

Just in case someone is using a cluster FQDN other than `svc.cluster.local`, allow configuring the Gafaelfawr internal URL.

DM-47011: Allow configuring Gafaelfawr internal URL

---

applications/next-visit-fan-out/values-usdfdev-prompt-processing.yaml
applications/next-visit-fan-out/values-usdfprod-prompt-processing.yaml

This PR updates the fan-out version in both -dev and -prod.

Deploy Next Visit Fan Out 2.4.0.

---

applications/consdb/values-summit.yaml
applications/consdb/values-tucson-teststand.yaml
applications/consdb/values-usdfdev.yaml
applications/consdb/values-usdfprod.yaml

Upon updating ConsDb on the summit, we ran into some issues and those have been fixed and tested in TTS in version 24.10.3 consdb.

Update ConsDb Tag to fix current migration issues

---

applications/butler/values-idfprod.yaml

We are ready to switch over to client-server Butler as the default in production, so switch the `dp02` alias at IDF prod to point to client-server Butler.

DM-47070: Use client-server butler for default dp02 in prod

---

applications/gafaelfawr/README.md
applications/gafaelfawr/templates/_helpers.tpl
applications/gafaelfawr/templates/configmap-kerberos.yaml
applications/gafaelfawr/templates/configmap.yaml
applications/gafaelfawr/templates/cronjob-audit.yaml
applications/gafaelfawr/templates/cronjob-maintenance.yaml
applications/gafaelfawr/templates/deployment-operator.yaml
applications/gafaelfawr/templates/deployment.yaml
applications/gafaelfawr/templates/job-schema-update.yaml
applications/gafaelfawr/templates/serviceaccount.yaml
applications/gafaelfawr/templates/vault-secrets.yaml
applications/gafaelfawr/values-ccin2p3.yaml
applications/gafaelfawr/values.yaml

Use a different method for handling Gafaelfawr schema updates: add the hook metadata to the required supporting resources rather than creating new ones. We tested this approach with vo-cutouts and it worked well, so adopt it here as well. This results in replacing instead of updating the resources on the next sync, but it avoids having duplicate resources that have to be manually deleted.
Remove the -config and -secret endings on the names of the Gafaelfawr VaultSecret and ConfigMap resources, adopting our current conventions. The endings duplicate information already available in Kubernetes in other ways.

DM-47148: Clean up Gafaelfawr Helm chart

---

applications/exposurelog/values-usdfdev.yaml

For the `usdfdev` environment, the S3 endpoint was configured incorrectly.  It was pulling in the config from the old embargo Butler repo instead of the new one.

DM-47220: Update exposurelog to point to new embargo rack

---

applications/sia/Chart.yaml
applications/sia/README.md
applications/sia/secrets.yaml
applications/sia/templates/_helpers.tpl
applications/sia/templates/configmap.yaml
applications/sia/templates/deployment.yaml
applications/sia/templates/ingress-anonymous.yaml
applications/sia/templates/ingress.yaml
applications/sia/templates/networkpolicy.yaml
applications/sia/templates/service.yaml
applications/sia/templates/vault-secrets.yaml
applications/sia/values-idfdev.yaml
applications/sia/values-idfint.yaml
applications/sia/values.yaml
docs/applications/rsp.rst
docs/applications/sia/index.rst
docs/applications/sia/values.md
environments/README.md
environments/templates/applications/rsp/sia.yaml
environments/values-idfdev.yaml
environments/values-idfint.yaml
environments/values-idfprod.yaml
environments/values.yaml
tests/data/input/docs/applications/rsp.rst
tests/data/output/docs/rsp.rst

**Summary**
This PR adds a new application to phalanx called "sia". This is a separate app to the existing CADC "siav2" application, which implements the same IVOA Simple Image Access protocol but using the butler and dax_obscore packages:
The SIAv2 app is another Safir-FastAPI application, and can be deployed on top of a number of Butler Repositories, either Direct or Remote. There is some additional complexity added to enable setting up the pg secrets in case of use with a Postgres database as the Butler repo db server.
The SIA application is developed here:
https://github.com/lsst-sqre/sia
And the relevant butler & obscore packages:
- https://github.com/lsst/daf_butler
- https://github.com/lsst-dm/dax_obscore
**How was this tested?**
- SIA Validators
The app was run through two …

DM-45906: Enable SIA over Butler application in phalanx

---

applications/sia/Chart.yaml
applications/sia/README.md
applications/sia/values-idfdev.yaml
applications/sia/values-idfint.yaml
applications/sia/values.yaml

**Summary**
Removes the default_instrument configuration attribute for Butler Data collections which was a temporary workaround. No longer needed as fix to daf_butler has been released.
Also upgrades requirements & sia chart version with the required fixes to no longer use this field.

DM-47214: Remove default_instrument from sia values

---

applications/sia/values-idfprod.yaml
environments/values-idfprod.yaml

Enables new SIA application on **idfprod**.
- Added sia/values-idfprod.yaml
- Set `sia: true` in environments/values-idfprod.yaml

DM-47298: Enable SIA on idfprod

---

applications/butler/Chart.yaml

Upgrade Butler server to fix an issue where dataset queries were failing with a weekly 44 client, due to extra properties added in the new version that were being rejected by the old server.

Upgrade butler server to fix conflict with weekly 44

---

applications/prompt-proto-service-hsc-gpu/README.md
applications/prompt-proto-service-hsc-gpu/values.yaml
applications/prompt-proto-service-hsc/README.md
applications/prompt-proto-service-hsc/values.yaml
applications/prompt-proto-service-latiss/README.md
applications/prompt-proto-service-latiss/values.yaml
applications/prompt-proto-service-lsstcam/README.md
applications/prompt-proto-service-lsstcam/values.yaml
applications/prompt-proto-service-lsstcomcam/README.md
applications/prompt-proto-service-lsstcomcam/values.yaml
applications/prompt-proto-service-lsstcomcamsim/README.md
applications/prompt-proto-service-lsstcomcamsim/values.yaml
charts/prompt-proto-service/README.md
charts/prompt-proto-service/templates/prompt-proto-service.yaml
charts/prompt-proto-service/values.yaml

This PR adds an extra config parameter to Prompt Processing that guarantees that the local repo can store at least one dataset per filter for all filter-dependent inputs.

DM-47387: Prompt Processing can't handle blank filters in nextVisit message

---

applications/sasquatch/values-idfdev.yaml

We deployed InfluxDB Enterprise on IDF dev to investigate the slow query issue in a new environment.
I'll merge this PR and let it running there. 
I uses the InfluxDB Enterprise cluster license for development.

[DM-46884] Deploy InfluxDB Enterprise on IDF dev

---

applications/sasquatch/README.md
applications/sasquatch/values-usdfdev.yaml
applications/sasquatch/values.yaml

We reached [this limit](https://docs.influxdata.com/influxdb/v1/administration/config/#:~:text=max%2Dseries%2Dper%2Ddatabase,is%201000000%20(one%20million).) in the database which caused the following error:
```
2024-10-23 04:29:08,071 ERROR [influxdb-sink-lsstdm-repairer|task-0] Encountered error [partial write: max-series-per-database limit exceeded: (1000000) dropped=484] (com.datamountaineer.streamreactor.connect.influx.writers.InfluxDbWriter) [task-thread-influxdb-sink-lsstdm-repairer-0]
```
and then some data points were dropped. 
For the moment I disabled the max-series-per-database limit to allow an unlimited number of series per database, and I enabled the repair connector in Sasquatch to reingest the data from Kafka.
That error indicates a cardinality issue in how we are …

Allow an unlimited number of series per database in Sasquatch (InfluxDB OSS)

---

applications/prompt-proto-service-lsstcomcam/values-usdfprod-prompt-processing.yaml

This PR updates the surveys and scalings for ComCam-prod to reflect our current understanding of how ComCam will operate. It does not include short-term surveys or config overrides associated with commissioning the Prompt Processing system itself.

Set baseline config for Prompt Processing ComCam

---

applications/sasquatch/values-summit.yaml
applications/sasquatch/values-usdfprod.yaml

- We notice the M1M3 cannot keep up with the default metric_batch_size of 1000 messages and increased its value to 2500

Increase M1M3 connector metric batch size

---

applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcam/values-usdfprod-prompt-processing.yaml

This PR updates Prompt Processing ComCam-prod from 4.7.1 to 4.7.2. It also synchronizes the unused LATISS-prod configuration to avoid bit-rot.

Deploy Prompt Processing 4.7.2.

---

applications/exposurelog/templates/ingress.yaml
applications/narrativelog/templates/ingress.yaml
applications/nightreport/templates/ingress.yaml

exposurelog, narrativelog, and nightreport incorrectly added the Helm labels to the template for the Ingress, but that's not allowed by the GafaelfawrIngress schema. Remove them.

Remove labels from GafaelfawrIngress tmeplate

---

applications/sasquatch/values-tucson-teststand.yaml

- One of the kafka borkers is not being scheduled in TTS because of lack of resources.

[DM-47528] Adjust Kafka resources requests and limits

---

applications/unfurlbot/README.md
applications/unfurlbot/values.yaml

Also clean up the unfurlbot `values.yaml` documentation a bit. The addition was requested by Eli Rykoff.

Add TAXICAB to unfurlbot Jira topics

---

applications/sasquatch/charts/strimzi-kafka/templates/schema-registry.yaml

We are using the default version of the Schema Registry  deployed by the schema-registry-operator, which is now quite old. 
This was an oversight of my part and we should set the Schema Registry version as part of the Sasquatch configuration.

Update schema registry version to 7.7.1

---

applications/prompt-proto-service-lsstcomcam/README.md
applications/prompt-proto-service-lsstcomcam/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcam/values.yaml

`BLOCK-T248` and `PP-SURVEY` is no longer expected.   `BLOCK-320` 
< performs the observations for the individual visits that are queued up by the Feature Based Scheduler. BLOCK-320 is expected to be the standard json block for taking science images with ComCam going forward

Update the survey to BLOCK-320 for ComCam Prompt Processing

---

applications/gafaelfawr/Chart.yaml

Update the Gafaelfawr relesae to 12.1.1, which fixes doubled slashes in the OpenID Connect configuration endpoint.
Note that this version of Gafaelfawr no longer supports direct upgrades from versions prior to 10.0.0. Upgrade to an earlier version first, complete the schema migration, and then upgrade to the latest version.

DM-47646: Update Gafaelfawr to 12.1.1

---

applications/prompt-proto-service-hsc-gpu/README.md
applications/prompt-proto-service-hsc-gpu/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-hsc-gpu/values.yaml
applications/prompt-proto-service-hsc/README.md
applications/prompt-proto-service-hsc/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-hsc/values.yaml
applications/prompt-proto-service-latiss/README.md
applications/prompt-proto-service-latiss/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-latiss/values.yaml
applications/prompt-proto-service-lsstcam/README.md
applications/prompt-proto-service-lsstcam/values.yaml
applications/prompt-proto-service-lsstcomcam/README.md
applications/prompt-proto-service-lsstcomcam/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcam/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcam/values.yaml
applications/prompt-proto-service-lsstcomcamsim/README.md
applications/prompt-proto-service-lsstcomcamsim/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcamsim/values.yaml
charts/prompt-proto-service/README.md
charts/prompt-proto-service/templates/prompt-proto-service.yaml
charts/prompt-proto-service/values.yaml

This PR replaces the bespoke pipelines config format with an extensible YAML-based format. The YAML-based config is still loaded into an environment variable; while a ConfigMap would be more convenient, we need the config to be fixed for a particular revision and that's hard to guarantee with a mapped file.
This PR must be merged together with lsst-dm/prompt_processing#222, which makes the corresponding changes to the parser.

DM-47529: Migrate Prompt Processing PipelinesConfig to YAML

---

applications/gafaelfawr/Chart.yaml
applications/gafaelfawr/README.md
applications/gafaelfawr/secrets.yaml
applications/gafaelfawr/templates/_helpers.tpl
applications/gafaelfawr/templates/cronjob-audit.yaml
applications/gafaelfawr/templates/cronjob-maintenance.yaml
applications/gafaelfawr/templates/deployment-operator.yaml
applications/gafaelfawr/templates/deployment.yaml
applications/gafaelfawr/templates/job-schema-update.yaml
applications/gafaelfawr/values.yaml

Update Gafaelfawr to the 12.2.0 release, which allows the new CADC authentication code to use the OpenID Connect userinfo route, hopefully allowing us to drop the old CADC-specific route. This release also fixes some performance issues and adds optional Sentry support, which will let us send traces, errors, and other telemetry to Sentry.

DM-47716: Update to Gafaelfawr 12.2.0

---

applications/prompt-proto-service-hsc/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-latiss/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcam/values-usdfdev-prompt-processing.yaml
charts/prompt-proto-service/README.md
charts/prompt-proto-service/templates/prompt-proto-service.yaml
charts/prompt-proto-service/values.yaml

This PR adds a debugging flag to Prompt Processing that prevents it from exporting to the central repo or Sasquatch.

DM-47814: Allow turning off central repo export in Prompt Processing

---

charts/cadc-tap/README.md
charts/cadc-tap/templates/configmap.yaml
charts/cadc-tap/values.yaml

**Summary:**
CADC have modified the way the OIDC discovery works with the newer release of cadc-gms & the `StandardIdentityProvider` that we use. The discovery service will look for the .well-known oidc endpoint at the wrong location (auth/cadc/..)
This update to phalanx changes the OIDC issuer location to the base path. This requires a newer release of Gafaelfawr, and as part of this PR we update the version of tap-postgres and lsst-tap-service to a version that includes the new cadc-gms releases with the OIDC discovery mechanism.
In this PR we:
- Update tap-postgres to 1.19.0
- Update lsst-tap-service to 2.5.0
- Change the ivo://ivoa.net/sso#OpenID setting in cadc-tap
**Jira issue:**
https://rubinobs.atlassian.net/browse/DM-47788
**Tested:**
Tested using …

Change OIDC provider in the cadc-tap config to base path

---

applications/livetap/README.md
applications/livetap/values.yaml
applications/ssotap/README.md
applications/ssotap/values.yaml
applications/tap/README.md
applications/tap/values.yaml

Move the setting of the service name to the correct location so that the GafaelfawrIngress resources are generated correctly for TAP services.

DM-47837: Fix GafaelfawrIngress for TAP services

---

applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcam/README.md
applications/prompt-proto-service-lsstcomcam/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcam/values.yaml

This PR updates our Prompt Processing version, and makes permanent some survey and resource settings that have already been deployed through Argo.

Update Prompt Processing to 4.10.0 and pull in configs from Argo

---

applications/prompt-proto-service-lsstcomcam/values-usdfprod-prompt-processing.yaml

This PR trims long comments, which were causing Argo to try to parse the blocks as >- instead of |- and also inject newlines. The two changes combined corrupted the config.

Hotfix to Prompt Processing ComCam config

---

applications/sasquatch/values-usdfprod.yaml

- At USDF the InfluxDB query timeout is 300s, increase the nginx ingress proxy timeout accordingly.

Increase nginx ingress proxy timeout for Chronograf at USDF

---

applications/butler/templates/deployment.yaml

Under extreme load, it can easily take more than a second for the Butler server to respond to a request.  The previous default value of 1s was causing the Butler server to be restarted unnecessarily.

DM-47889: Increase timeout for Butler server readiness check

---

applications/prompt-proto-service-hsc-gpu/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-hsc-gpu/values.yaml
applications/prompt-proto-service-hsc/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-hsc/values.yaml
applications/prompt-proto-service-latiss/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-latiss/values.yaml
applications/prompt-proto-service-lsstcam/values.yaml
applications/prompt-proto-service-lsstcomcam/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcam/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcam/values.yaml
applications/prompt-proto-service-lsstcomcamsim/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcamsim/values.yaml
charts/prompt-proto-service/values.yaml

This PR clarifies for config editors under which circumstances a pipeline config will get corrupted. This prevents the issue introduced in #3948 and fixed in #3949.

Add a format warning to Prompt Processing values.

---

applications/prompt-proto-service-hsc-gpu/README.md
applications/prompt-proto-service-hsc-gpu/values.yaml
applications/prompt-proto-service-hsc/README.md
applications/prompt-proto-service-hsc/values.yaml
applications/prompt-proto-service-latiss/README.md
applications/prompt-proto-service-latiss/values.yaml
applications/prompt-proto-service-lsstcam/README.md
applications/prompt-proto-service-lsstcam/values.yaml
applications/prompt-proto-service-lsstcomcam/README.md
applications/prompt-proto-service-lsstcomcam/values.yaml
applications/prompt-proto-service-lsstcomcamsim/README.md
applications/prompt-proto-service-lsstcomcamsim/values.yaml
charts/prompt-proto-service/README.md
charts/prompt-proto-service/templates/prompt-proto-service.yaml
charts/prompt-proto-service/values.yaml

This PR reverts #3851 because the feature in question has been removed by Prompt Processing. Should be merged after lsst-dm/prompt_processing#238.

DM-47868: Remove "any filter" Prompt Processing mode

---

applications/sia/values.yaml

Added resources for SIAv2 application. This may need to be revisited after we get a better idea of what these need to be exactly, along with what row limits we will have and pod replicas etc. 
Currently there is a bug or feature which may be redesigned in the client/server butler which currently fetches and caches a lot more data then needed. So the current usage may not represent the actual expected usage in the future. In any case with things as they stand data-int is using 24 Gb of mem,
For this reason to start with I'm with 30 Gb of RAM same as the resource limits for TAP.

DM-48004: Add resource limits for sia deployment

---

applications/gafaelfawr/Chart.yaml

Allows an empty list of scopes in a `GafaelfawrIngress`, which we want to use for Wobbly. Also fixes a harmless error from the Kopf health check.

DM-48088: Bump Gafaelfawr version to 12.3.0

---

applications/sasquatch/Chart.yaml
applications/sasquatch/README.md
applications/sasquatch/charts/backup/.helmignore
applications/sasquatch/charts/backup/Chart.yaml
applications/sasquatch/charts/backup/README.md
applications/sasquatch/charts/backup/templates/_helpers.tpl
applications/sasquatch/charts/backup/templates/backup-cronjob.yaml
applications/sasquatch/charts/backup/templates/backup-pvc.yaml
applications/sasquatch/charts/backup/values.yaml
applications/sasquatch/values-idfdev.yaml
applications/sasquatch/values-usdfprod.yaml
applications/sasquatch/values.yaml

This PR implements the backup sub chart in Sasquatch, with creates a PVC and a CronJob to execute the InfluxDB Enterprise backup tools from the sasquatch-backup pod. 
Chronograf and Kapacitor backups are disabled at the moment until we have the functionality to snapshot PVs at USDF.

[DM-46938] Automate InfluxDB Enterprise application level backups

---

starters/fastapi-safir-uws/secrets.yaml
starters/fastapi-safir-uws/templates/configmap.yaml
starters/fastapi-safir-uws/templates/db-worker-deployment.yaml
starters/fastapi-safir-uws/templates/deployment.yaml
starters/fastapi-safir-uws/templates/serviceaccount.yaml
starters/fastapi-safir-uws/templates/worker-deployment.yaml
starters/fastapi-safir-uws/values.yaml

Simplify the fastapi-safir-uws starter now that each UWS application no longer needs to manage its own database. Make the configuration for the GCS service account unconditional, since currently Safir only supports putting job results in a GCS bucket and using presigned URLs.

DM-48127: Update the fastapi-safir-uws starter

---

starters/fastapi-safir-uws/secrets.yaml
starters/fastapi-safir-uws/templates/db-worker-deployment.yaml
starters/fastapi-safir-uws/templates/deployment.yaml
starters/fastapi-safir-uws/values.yaml
starters/fastapi-safir/secrets.yaml
starters/fastapi-safir/templates/deployment.yaml
starters/fastapi-safir/templates/vault-secrets.yaml
starters/fastapi-safir/values.yaml

Add support for optional Slack alerting, disabled by default, to the fastapi-safir and fastapi-safir-app starters, since otherwise I have to manually add it to each new application and forget.

DM-48127: Add Slack alerting support to safir starters

---

applications/wobbly/README.md
applications/wobbly/templates/deployment.yaml
applications/wobbly/values.yaml

Some of the bits for Slack alerting were present in the Wobbly chart, but it wasn't plumbed through or configured. Do the remaining steps.

DM-47986: Add support for Slack alerting in Wobbly

---

applications/wobbly/templates/ingress-admin.yaml
applications/wobbly/templates/ingress-service.yaml
applications/wobbly/values-idfdev.yaml

Create a separate ingress for services accessing Wobbly under the `/jobs` route and protect the rest of the routes with a conventional ingress that requires the `exec:admin` scope. This includes the OpenAPI schema as well as the `/admin` routes.

DM-48139: Separate Wobbly ingresses

---

docs/developers/index.rst

On the developers documentation page, add a see also section linking to the Confluence page for the SQuaRE bootcamp, which has slides and recordings of presentations.

Add a link to the SQuaRE bootcamp

---

src/phalanx/cli.py
src/phalanx/models/environments.py
src/phalanx/services/secrets.py
src/phalanx/storage/vault.py
tests/cli/secrets_test.py

Sometimes we'll want to perform a secrets sync without affecting a particular application, such as when we're doing experiments with that application or when we want to run `--delete` but not affect that application. Add an `--exclude` flag to both secrets sync and secrets audit.
This currently excludes the application entirely, as if it doesn't exist, and therefore may interfere with copy directives. We can do something more sophisticated later if that ends up being a problem.

DM-48168: Allow excluding applications from secrets sync

---

applications/gafaelfawr/values.yaml

The steady-state for Gafaelfawr now appears to be a bit higher, so increase all of the memory requests. The limits still seem to be fine.

Bump Gafaelfawr memory requests

---

applications/prompt-proto-service-hsc-gpu/README.md
applications/prompt-proto-service-hsc-gpu/values.yaml
applications/prompt-proto-service-hsc/README.md
applications/prompt-proto-service-hsc/values.yaml
applications/prompt-proto-service-latiss/README.md
applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-latiss/values.yaml
applications/prompt-proto-service-lsstcam/README.md
applications/prompt-proto-service-lsstcam/values.yaml
applications/prompt-proto-service-lsstcomcam/README.md
applications/prompt-proto-service-lsstcomcam/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcam/values.yaml
applications/prompt-proto-service-lsstcomcamsim/README.md
applications/prompt-proto-service-lsstcomcamsim/values.yaml

This PR updates the Prompt Processing pipelines config for LATISS to a form that won't get garbled by Argo, and also updates the Kafka config for all instances. No other bitrot was found compared to the (recently active) ComCamSim config.
There are two changes I've avoided making on this PR:
- We expect to migrate to the embargo rack before observations begin, but there's no concrete timeframe for doing so. The migration will be handled on #3815.
- I've not put in a "catch-all" config block until we have a clearer picture of what next season's nextVisit messages will look like. We may not need one at all.

DM-48165: Invalid Prompt Processing config for LATISS-prod

---

applications/sasquatch/values-idfint.yaml

They were already enabled in idfprod

sasquatch: enable mobu app metrics capabilities in idfint

---

applications/nublado/README.md
applications/nublado/values.yaml

We've added several new configuration parameters to Nublado in support of container flexibility and to add the ability to change how `/tmp` is managed, but they weren't documented in the Phalanx `values.yaml` file. Add the new settings with their default values.
Move the configuration of resources for the proxy pod to where it will take effect (previously it was ignored).
Delete some redundant commentary. Shorten some defaults to try to make the web formatting a bit better. Delete a commented-out block that isn't supported by Zero to JupyterHub.

DM-48193: Add remaining Nublado config parameters

---

applications/nublado/README.md
applications/nublado/values.yaml

Set a custom documentation default value for another Nublado setting to reduce the switch of the values table.

DM-48193: Tweak documentation for another Nublado value

---

applications/wobbly/Chart.yaml
applications/wobbly/README.md
applications/wobbly/templates/cronjob-maintenance.yaml
applications/wobbly/templates/deployment.yaml
applications/wobbly/values.yaml

Upgrade Wobbly to 0.2.0 and add a maintenance `CronJob` that runs `wobbly expire` to delete all jobs that have passed their expiration times. Use the same requests and limits as the main Wobbly pod for simplicity.
Delete a stray environment variable from the main Wobbly deployment that was left over from cut and paste.

DM-48184: Bump Wobbly to 0.2.0, add maintenance CronJob

---

applications/wobbly/values-idfint.yaml
environments/values-idfint.yaml

Enable Wobbly on idfint so that the new vo-cutouts can be deployed and switch to using Wobbly as a backing store.

DM-48199: Deploy Wobbly on idfint

---

applications/wobbly/templates/kafka-access.yaml

A cut and paste error put Gafaelfawr in the name instead of Wobbly.

DM-48199: Fix KafkaAccess for Wobbly

---

applications/wobbly/values-idfdev.yaml
applications/wobbly/values-idfint.yaml

Connecting to Kafka fails due to missing information in the Kafka certificates for Sasquatch. Turning off metrics reporting for now until that's fixed.

DM-48199: Disable Wobbly metrics reporting for now

---

applications/wobbly/Chart.yaml
applications/wobbly/values-idfdev.yaml
applications/wobbly/values-idfint.yaml

Update to Wobbly 0.2.1, which disables strict certificate validation when submitting metrics since the current Strimzi certificates for Sasquatch do not pass it. Re-enable metrics on idfdev and idfint.

DM-48199: Update to Wobbly 0.2.1, re-enable metrics

---

applications/gafaelfawr/templates/configmap.yaml
applications/gafaelfawr/templates/kafka-access.yaml
applications/ook/templates/kafkaaccess.yaml
applications/squarebot/templates/kafkaaccess.yaml
applications/templatebot/templates/kafkaaccess.yaml
applications/wobbly/templates/kafka-access.yaml

Be consistent about adding standard labels to all resources and add them to the `KafkaAccess` resources as well.

DM-48199: Add standard labels to KafkaAccess resources

---

applications/argocd/values-ccin2p3.yaml
applications/argocd/values-minikube.yaml
applications/argocd/values-roe.yaml
applications/argocd/values-usdf-tel-rsp.yaml
applications/argocd/values-usdfdev-alert-stream-broker.yaml
applications/argocd/values-usdfdev-prompt-processing.yaml
applications/argocd/values-usdfint.yaml
applications/argocd/values-usdfprod-prompt-processing.yaml
applications/argocd/values-usdfprod.yaml

**Summary**
There was an indentation issue which showed up recently at the roe environment when they tried to synchronize. The symptoms were that argo-cd failed to synchronize, with error referring to ` letsencypt-dns`. Upon further investigation it seems that the `tls: false` was missplaced, and should be under `ingress` rather than `server`.
This PR addresses the issue by fixing the indentation to match the expected nesting of the ingress setting.
**How was this tested**
Tested on the ROE environments (test & prod) and it works, they can now synchronize argo-cd successfully

DM-48116: Fix ingress/tls indentation issue with argo-cd values files

---

applications/sasquatch/values-idfprod.yaml
applications/wobbly/values-idfprod.yaml
environments/values-idfprod.yaml

Install Wobbly, enable its metrics reporting, add it to the Sasquatch configuration, and upgrade vo-cutouts to the version that uses Wobbly on idfprod.

DM-48241: Install Wobbly and update vo-cutouts on idfprod

---

applications/wobbly/templates/job-schema-update.yaml

The Wobbly schema update job didn't have the Kafka configuration and does try to initialize it.

DM-48241: Fix schema update for Wobbly

---

applications/wobbly/values-idfprod.yaml

The database has been deployed, so this is no longer needed.

DM-48241: Disable Wobbly schema updates on idfprod

---

applications/sia/Chart.yaml

Changes include upgrading the dependencies of SIAv2:
https://github.com/lsst-sqre/sia/pull/24
Mainly this is relevant for the `dax_obscore` & `daf_butler` updated versions which includes some performance updates.

DM-48268: Upgrade SIA Chart to version 0.1.5

---

applications/nublado/values-idfdev.yaml
applications/nublado/values-idfint.yaml
applications/nublado/values-idfprod.yaml

tickets/DM-48170: Put user lab workload into its own pool

---

applications/sasquatch/README.md
applications/sasquatch/charts/backup/README.md
applications/sasquatch/charts/backup/templates/backup-cronjob.yaml
applications/sasquatch/charts/backup/templates/role.yaml
applications/sasquatch/charts/backup/templates/rolebiding.yaml
applications/sasquatch/charts/backup/templates/serviceaccount.yaml
applications/sasquatch/charts/backup/values.yaml
applications/sasquatch/values-idfdev.yaml
applications/sasquatch/values-usdfprod.yaml

Chronograf and Kapacitor don’t have an application level backup tool. 
An alternative is to backup their PVs or specifically the  BoltDB file which holds all the application configuration including dashboards in the case of Chronograf and alert rules in the case of kapacitor.
One complication is that we cannot mount their PVs in the `sasquatch-backup` Pod because they are ReadWriteOnce. 
We investigated using kubernetes Volume Snaphots which could be a good option for backups in all our environments, but that's not currently available at USDF and our Telescope environments. Velero could be perhaps the best option but that's a larger project.
A more pragmatic solution is to use the kubectl tool to copy the BoltDB file from the application, and this approach works in all environments. …

[DM-48286] Automate Chronograf and kapacitor backups

---

applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml

Merging of this PR should wait until LATISS is re-configured to send data to Embargo Rack.

DM-46254: Switch LATISS Prompt Processing to the new Embargo Rack buckets

---

docs/admin/installation.rst
docs/admin/requirements.rst

Fix the order of operations to be something more sensible, and move the caution about having a recent version of the Argo CD client up front. Add more details about how to install Argo CD and the Vault client to the prerequisites page.

Improve Phalanx installation instructions

---

applications/times-square/values-usdfdev.yaml

The redis disk cache is 8Gi, so we need to use at least that much memory to be efficient. The limit is set to 3x the disk cache to avoid OOM kills. With the previous defaults redis couldn't start up on usdf-rsp-dev where the redis cache is heavily loaded.

DM-48318: Increase times square redis memory requests/limits

---

applications/ingress-nginx/README.md
applications/ingress-nginx/values.yaml

The new version of ingress-nginx requires setting the annotation risk level to `Critical` to allow arbitrary snippets, which are used by Gafaelfawr.

DM-48326: Allow risky ingress annotations

---

applications/sasquatch/values-usdfprod.yaml

After the USDF outage sdfk8sn005 was cordoned and won'tbe available soon, as a consequence we are running Sasquatch at USDF with only 2 Kafka brokers. 
This PR updates de NodeAffinity to use sdfk8sn003 in the meantime.

[DM-48322] Update NodeAffinity for Kafka at usdfprod

---

applications/sasquatch/values-summit.yaml
applications/sasquatch/values-usdfdev.yaml
applications/sasquatch/values-usdfprod.yaml

Following the implementation of DM-48286 to  Automate Chronograf and kapacitor backups enable backups at Summit and USDF

[DM-48329] Enable Chronograf and Kapacitor backups at USDF and Summit

---

applications/sasquatch/README.md
applications/sasquatch/charts/backup/README.md
applications/sasquatch/charts/backup/values.yaml
applications/sasquatch/values-idfdev.yaml

Add InfluxDB OSS backups to Sasquatch. This is useful for teststands and IDF deployments where Sasquatch uses an InfluxDB OSS instance.

[DM-48357] Add InfluxDB OSS backups to Sasquatch

---

applications/gafaelfawr/Chart.yaml

Includes the Gafaelfawr fix to generate auth-url annotations that comply with the restrictions of the current ingress-nginx.

DM-48326: Bump Gafaelfawr version to 12.3.1

---

applications/gafaelfawr/templates/ingress.yaml

The new ingress-nginx doesn't allow `.` in paths of `pathType` `Exact`. The workaround is to use `ImplementationSpecific`. Do this for `/.well-known` paths for Gafaelfawr.
See https://github.com/kubernetes/ingress-nginx/issues/11176.

DM-48326: Switch some Gafaelfawr routes to another path type

---

charts/cadc-tap/templates/tap-ingress-anonymous.yaml
charts/cadc-tap/templates/tap-ingress-authenticated.yaml

The new version of ingress-nginx now rejects variables in the `proxy-redirect-from` and `proxy-redirect-to` annotations since they contain the invalid character `$`. Instead use the global values setting containing the base hostname.

DM-48326: Avoid variables in proxy-redirect-{from,to}

---

applications/gafaelfawr/Chart.yaml

This release of Gafaelfawr fixes another issue with generating auth-url annotations for `Ingress` resources by avoiding commas in the `delegate_scope` parameter.

DM-48326: Bump Gafaelfawr version to 12.3.2

---

applications/times-square/Chart.yaml
applications/times-square/README.md
applications/times-square/templates/job-schema-update.yaml
applications/times-square/values.yaml
docs/applications/times-square/db-migrations.rst
docs/applications/times-square/index.rst

This job is based on the same one developed for Gafaelfaawr and will be part of a semi-manual process for running Alembic migrations when needed (e.g. following [the Gafaelfawr process](https://phalanx.lsst.io/applications/gafaelfawr/manage-schema.html#updating-the-database-schema)).
See also the Times Square PR: https://github.com/lsst-sqre/times-square/pull/88

DM-48385: Add times-square database migration job

---

applications/sasquatch/README.md
applications/sasquatch/charts/backup/README.md
applications/sasquatch/charts/backup/templates/restore-cronjob.yaml
applications/sasquatch/charts/backup/values.yaml
applications/sasquatch/values-idfdev.yaml
applications/sasquatch/values-summit.yaml
applications/sasquatch/values-usdfdev.yaml
applications/sasquatch/values-usdfprod.yaml

We assume that sasquatch-backup CronJob for `influxdb-oss-full` is enabled and creating backup items following the configured schedule, for example:
``` 
backupItems:
- name: "influxdb-oss-full"
enabled: true
retentionDays: 3
```
The Job logs show the Backup contents,  where we identify the latest backup we want to restore from:
```
Backup contents:
649M	/backup/sasquatch-influxdb-oss-full-20250113T030120Z
```
We add the  restore configuration, and sync the `sasquatch-restore` CronJob in Argo CD
```
restoreItems:
- name: "influxdb-oss-full"
enabled: true
backupTimestamp: "20250113T030120Z"
```
From where we can run a `sasquatch-restore` Job.
The restore script is implemented in this PR https://github.com/lsst-sqre/sasquatch/pull/56

[DM-48369] Automate restore of InfluxDB OSS backups in Sasquatch

---

applications/sasquatch/README.md
applications/sasquatch/values.yaml

- Upgrade InfluxDB OSS to 1.11.8 by default to all Sasquatch instances.
- The 1.11.8 docker image runs with the influxdb user and group, so add securityContext configuration with fsGroup so the PV is mounted with the right permissions.

Upgrade InfluxDB OSS to 1.11.8

---

applications/sasquatch/charts/app-metrics/templates/telegraf-deployment.yaml

- We expect the app.kubernetes.io/name: sasquatch-telegraf label in all Telegraf deployments.

Fix up telegraf-app-metrics label

---

applications/butler/values-idfdev.yaml

A new postgres 16 database instance has been set up for the DP02 butler on data-dev

DM-45901: Update data-dev Butler to point to new DB

---

applications/sia/values-usdfdev.yaml
applications/sia/values-usdfint.yaml
applications/sia/values-usdfprod.yaml
environments/values-usdfdev.yaml

Changes include adding configurations for the usdf environments for the new SIAv2 over Butler application which will replace the previous CADC-based SIAv2 application & change to the usdfdev environment to enable it there.

DM-48143: Enable new SIAv2 over Butler application for usdf

---

applications/uws/values-summit.yaml

This limits spam in the status channel from all the failed jobs.

Set Summit job lifetime to 2 hours.

---

applications/sasquatch/values-base.yaml
applications/sasquatch/values-idfint.yaml
applications/sasquatch/values-idfprod.yaml
applications/sasquatch/values-tucson-teststand.yaml
applications/sasquatch/values-usdfdev.yaml
applications/sasquatch/values-usdfint.yaml

Enable InfluxDB OSS (or Enterprise), Chronograf and Kapacitor backups on TTS, BTS, Summit, IDF and USDF environments.

[DM-48484]  Enable Sasquatch backups in all environments

---

applications/noteburst/values-usdfprod.yaml
applications/postgres/values-usdfprod.yaml
applications/squareone/values-usdfprod.yaml
applications/times-square/values-usdfprod.yaml
environments/values-usdfprod.yaml

This deploys Times Square on the production USDF RSP. This will become the new primary deployment of Times Square. This should be merged after https://github.com/lsst-sqre/phalanx/pull/4083 which will deploy Times Square 0.15.0.
- Adds timessquare to the postgres database
- Adds values for timessquare at usdfprod
- Adds values for noteburst at usdfprod
- Adds the ingress for `/times-square/` to Squareone

DM-48421: Deploy Times Square on usdfprod

---

applications/ingress-nginx/README.md
applications/ingress-nginx/values-base.yaml
applications/ingress-nginx/values-ccin2p3.yaml
applications/ingress-nginx/values-idfdemo.yaml
applications/ingress-nginx/values-idfdev.yaml
applications/ingress-nginx/values-idfint.yaml
applications/ingress-nginx/values-idfprod.yaml
applications/ingress-nginx/values-roe.yaml
applications/ingress-nginx/values-summit.yaml
applications/ingress-nginx/values-tucson-teststand.yaml
applications/ingress-nginx/values-usdfdev.yaml
applications/ingress-nginx/values-usdfprod.yaml
applications/ingress-nginx/values.yaml

Move the `large-client-header-buffers` and `proxy-buffer-size` settings into `values.yaml` from the per-environment settings files, since we generally want those settings everywhere. This only changes configuration for minikube, roundtable-dev, and roundtable.
These settings increase the buffer size used to read client HTTP headers and response HTTP headers from proxied services, including Gafaelfawr. We saw errors without this setting in environments where the user has large cookies exceeding the 4KB default buffer size limit, such as USDF.

DM-48495: Lift some ingress-nginx settings into values.yaml

---

applications/gafaelfawr/Chart.yaml
applications/gafaelfawr/README.md
applications/gafaelfawr/templates/_helpers.tpl
applications/gafaelfawr/templates/cronjob-audit.yaml
applications/gafaelfawr/templates/cronjob-maintenance.yaml
applications/gafaelfawr/templates/deployment-operator.yaml
applications/gafaelfawr/templates/deployment.yaml
applications/gafaelfawr/templates/job-schema-update.yaml
applications/gafaelfawr/values.yaml
applications/ingress-nginx/values.yaml

Update to Gafaelfawr 12.4.0, which includes new support for API rate limiting and therefore new ingress-nginx integration. This release also requires a separate ephemeral Redis for Gafaelfawr.

DM-48495: Update to Gafaelfawr 12.4.0

---

applications/sasquatch/charts/kafdrop/values.yaml
applications/sasquatch/values-base.yaml
applications/sasquatch/values-idfdev.yaml
applications/sasquatch/values-summit.yaml
applications/sasquatch/values-tucson-teststand.yaml

The Control System Kafka topics now have a key that has DEAULT format.
The configuration `--message.keyFormat=DEFAULT` can be used to set this by default when displaying messages in the kafdrop UI. It doesn't take effect for Kafka topics that don't have a key.
This PR use the DEFAULT key format in all Sasquatch environments now.

[DM-48533] Make message key format configuration default

---

applications/sasquatch/values-usdfprod.yaml

- Replicate schemas and lsst.sal.* topics excluding lsst.sal.MTM1M3, lsst.sal.MTMount and lsst.sal.MTMVS topics because those require multiple partitions to scale for high throughput.

Update MM2 topicsPattern

---

applications/squareone/Chart.yaml
applications/squareone/README.md
applications/squareone/templates/configmap.yaml
applications/squareone/values-base.yaml
applications/squareone/values-idfdev.yaml
applications/squareone/values-idfint.yaml
applications/squareone/values-idfprod.yaml
applications/squareone/values-summit.yaml
applications/squareone/values-tucson-teststand.yaml
applications/squareone/values-usdfdev.yaml
applications/squareone/values-usdfint.yaml
applications/squareone/values-usdfprod.yaml
applications/squareone/values.yaml

This PR updates Squareone to 0.15.0, which adds a link in Times Square to the user documentation for that environment. This change also adds a new configuration, `docsBaseUrl` pointing to the base URL in rsp.lsst.io for a given environment's user documentation.

DM-48448: Update Squareone with documentation link for Times Square

---

applications/butler/values-idfdev.yaml

Use a domain name instead of an IP address for Butler on data-dev.

DM-45901: Update data-dev Butler to use postgres DNS name

---

applications/sasquatch/values-base.yaml
applications/sasquatch/values-summit.yaml
applications/sasquatch/values-tucson-teststand.yaml

We disabled topic auto-creation in Kafka, so we need to create the topics managed by the REST Proxy.
Clean up some old configuration we don't need anymore for the REST Proxy.

[DM-48545] REST proxy Kafka topics should now be created in Sasquatch

---

docs/applications/nublado/block-spawns.rst
docs/applications/nublado/index.rst
docs/applications/nublado/major-upgrade.rst
docs/applications/nublado/updating-recommended.rst

Add a documentation page explaining how to block Nublado notebook spawns via quota overrides. Also mention stopping JupyterHub for completeness.

DM-48622: Document how to block notebook spawns

---

applications/unfurlbot/Chart.yaml
applications/unfurlbot/README.md
applications/unfurlbot/templates/configmap.yaml
applications/unfurlbot/values.yaml

This version has improved logging and avoids unfurling based on stale Slack messages.

DM-48614: Deploy Unfurlbot 0.5.0

---

docs/admin/index.rst
docs/admin/set-quotas.rst
docs/applications/gafaelfawr/index.rst
docs/applications/gafaelfawr/quotas.rst

Add general Phalanx documentation for how quotas work and how to set them in the Gafaelfawr configuration. Add a short stub page to the environment administrator documentation pointing to the quota documentation.

DM-48622: Document setting quotas in Gafaelfawr

---

applications/sasquatch/README.md
applications/sasquatch/charts/strimzi-kafka/templates/kafka.yaml
applications/sasquatch/values-base.yaml
applications/sasquatch/values-summit.yaml
applications/sasquatch/values.yaml

After OS and k8s upgrades at the Summit we had problems restarting Kafka, we had to fix the nodeAffinity configuration for the kafka brokers and also pin the Kafka controller node IDs.
Also we had to rollback InfluxDB OSS after what looks like a bug on version 1.11.8

Summit Sasquatch fixes

---

charts/cadc-tap/README.md
charts/cadc-tap/values.yaml

Upgrade TAP service image to version 2.6.0
* Fix Dockerfile warning about Label by @stvoutsin in https://github.com/lsst-sqre/lsst-tap-service/pull/123
* DM-48516: JobDAO class from opencadc adapted to fix issue with LAST param in joblist by @stvoutsin in https://github.com/lsst-sqre/lsst-tap-service/pull/121
* Prepare release 2.6.0 by @stvoutsin in https://github.com/lsst-sqre/lsst-tap-service/pull/124
**Full Changelog**: https://github.com/lsst-sqre/lsst-tap-service/compare/2.5.0...2.6.0

DM-48516: Update TAP image to version 2.6.0

---

applications/prompt-proto-service-hsc/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-latiss/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcam/values-usdfdev-prompt-processing.yaml
charts/prompt-proto-service/README.md
charts/prompt-proto-service/templates/prompt-proto-service.yaml
charts/prompt-proto-service/values.yaml

This PR removes a Prompt Processing debugging flag that was sometimes needed to get correct results with the old calib-handling code removed on lsst-dm/prompt_processing#249.

DM-46178: Use new query system in Prompt Processing

---

applications/mobu/README.md
applications/mobu/templates/deployment.yaml
applications/mobu/tests/termination_grace_period_test.yaml
applications/mobu/values.yaml

Add ability to specify a time for k8s to wait before killing mobu pods in the pod termination lifecycle.
For scale testing, with a lot of Nublado containers started, it can take a while for them all to shut down.

DM-48700: mobu - terminationGracePeriodSeconds

---

applications/sia/Chart.yaml
applications/sia/README.md
applications/sia/secrets.yaml
applications/sia/templates/deployment.yaml
applications/sia/values-idfdev.yaml
applications/sia/values-idfint.yaml
applications/sia/values.yaml

PR to enable Sentry telemetry for the SIAv2 application. Sentry parameters are read from ENV variables, similar to other config values. The approach follows the implementation of other apps, like times-square gafaelfawr and mobu
- Ensure the Sentry DSN is properly added for each environment where we enable sentry

DM-4866: Enable Sentry telemetry in SIAv2 application

---

applications/gafaelfawr/values-minikube.yaml
applications/gafaelfawr/values.yaml

Based on both load testing and on recent graphs from idfint, adjust resource limits and requests for the Gafaelfawr components, primarily to provide more headroom when we start working with much larger numbers of tokens.

DM-48756: Adjust limits and requests for Gafaelfawr

---

docs/applications/nublado/upgrade.rst

Due to a startup race, it's better to sync the rest of nublado separately from nublado-controller. Document this in the nublado application upgrade page.

DM-48781: Document syncing nublado-controller separately

---

docs/applications/nublado/clean-up-labs.rst
docs/applications/nublado/index.rst

Document how to safely clean up Nublado labs, including restarting the controller and JupyterHub if needed.

DM-48781: Add Nublado documentation on lab cleanup

---

charts/cadc-tap/README.md
charts/cadc-tap/values.yaml

- DM-48132: Introduce Binary2 VOTable Serialization and make it default by @stvoutsin in https://github.com/lsst-sqre/lsst-tap-service/pull/120
- Correctly print field metadata

DM-48132: Upgrade TAP to version 2.7.0

---

applications/gafaelfawr/Chart.yaml

This release has various fixes for quota and rate limiting support, including better logging and metrics.

DM-48786: Bump Gafaelfawr version to 12.5.0

---

applications/sia/Chart.yaml
applications/sia/templates/deployment.yaml

Upgrades SIA to version 0.1.6 and fixes issue where SIA_ENVIRONMENT_NAME is now required by the sia application, but in phalanx was dependent on sentryEnabled being set to True

DM-48661: Upgrade SIA to 0.1.6 and fix issue with SIA_ENVIRONMENT_NAME missing

---

applications/nublado/values.yaml

We would have run out of memory in the Nublado controller with a 1,000 pod scale test. Increase both the limits and the requests to give us more breathing room.

DM-48838: Increase resources for Nublado controller

---

applications/gafaelfawr/Chart.yaml

Fixes parsing of the Redis password when constructing URLs, allowing Gafaelfawr to work correctly with passwords containing special characters.

DM-48870: Update to Gafaelfawr 12.5.2

---

applications/noteburst/values-idfint.yaml
applications/noteburst/values-idfprod.yaml
applications/squareone/values-idfint.yaml
applications/squareone/values-idfprod.yaml
environments/values-idfint.yaml
environments/values-idfprod.yaml

* Enable Noteburst in `idfint` and `idfprod`
* Add the times-square URL to Squareone in `idfint` and `idfprod`
Note that the default Times Square scope is `exec:admin`, and the template api scope is `exec:notebook` in both envs already. This means that only admins will be able to execute notebooks. It does allow anyone with `exce:notebook` to render any templates though, until we [change the template render routes in the ingress](https://github.com/lsst-sqre/phalanx/pull/4172)

DM-48733: Noteburst in `idfint` and `idfprod`

---

applications/sasquatch/charts/strimzi-kafka/templates/kafka.yaml
applications/sasquatch/values-base.yaml
applications/sasquatch/values-summit.yaml

This PR fixes the annotation to assign node IDs in the KafkaNodepools and tries to uniformize the IDs across the different Sasquatch environments, the following rule seems to work:
- Always assign IDs 3,4,5 to controllers in all Sasquatch environments. 
- Assign IDs 0,1,2 to brokers deployed on default storage.
- Assign IDs 6,7,8 to brokers deployed on local storage.
The story behind this is that originally we had the broker IDs 0,1,2 and controller IDs 3,4,5 everywhere.
Then we [migrated the Kafka brokers](https://sasquatch.lsst.io/developer-guide/broker-migration.html) in some Sasquatch environmets (BTS, Summit and USDF) to use local storage. 
The broker migration process creates new brokers with IDs 6,7,8 and remove the old brokers with IDs 0,1,2 after the migration.

[DM-48910]  Review Kafka controllers node IDs assignment

---

applications/gafaelfawr/README.md
applications/gafaelfawr/templates/_helpers.tpl
applications/gafaelfawr/templates/deployment.yaml
applications/gafaelfawr/templates/job-schema-update.yaml
applications/gafaelfawr/values.yaml
applications/times-square/README.md
applications/times-square/templates/_helpers.tpl
applications/times-square/templates/deployment.yaml
applications/times-square/templates/job-schema-update.yaml
applications/times-square/templates/worker-deployment.yaml
applications/times-square/values.yaml
applications/wobbly/README.md
applications/wobbly/templates/_helpers.tpl
applications/wobbly/templates/cronjob-maintenance.yaml
applications/wobbly/templates/deployment.yaml
applications/wobbly/templates/job-schema-update.yaml
applications/wobbly/values.yaml
charts/cadc-tap/templates/tap-deployment.yaml
charts/cadc-tap/tests/tap-deployment_test.yaml
docs/developers/helm-chart/cloud-sql.rst

Run the Cloud SQL Auth Proxy as a proper sidecar container using the new feature in Kubernetes 1.29. This avoids having to do coordination between the main container and the Cloud SQL Auth Proxy container to shut down the latter for jobs, and also ensures the correct startup order and shutdown semantics.

DM-48961: Use sidecar containers for Cloud SQL

---

Makefile

Remove the update-deps-no-hashes Makefile target, which is no longer needed now that we're using uv. Delete a stray addition of a lint target to the Makefile that appears to have been added by mistake.

DM-48961: Remove update-deps-no-hashes Makefile target

---

applications/mobu/README.md
applications/mobu/templates/_helpers.tpl
applications/mobu/templates/configmap.yaml
applications/mobu/templates/deployment.yaml
applications/mobu/templates/gafaelfawr-token.yaml
applications/mobu/templates/ingress-github-ci.yaml
applications/mobu/templates/ingress-github-refresh.yaml
applications/mobu/templates/ingress.yaml
applications/mobu/templates/networkpolicy.yaml
applications/mobu/templates/service.yaml
applications/mobu/templates/vault-secrets.yaml
applications/mobu/tests/github_ci_app_enabled_test.yaml
applications/mobu/tests/github_refresh_app_enabled_test.yaml
applications/mobu/values.yaml

Remove the name overrides for the mobu chart, which we no longer use. Rename the `Secret` resource to `mobu` from `mobu-secret`, matching our current style. Alphabetically sort settings in `values.yaml`.

DM-48977: Adapt mobu chart to current style

---

applications/mobu/templates/_helpers.tpl

The `mobu.labels` macro needs to include `mobu.selectorLabels`.

DM-48977: Fix labels for mobu

---

applications/mobu/templates/deployment.yaml

Set a `SENTRY_RELEASE` env var to the mobu deployment which will tag every Sentry event with a release, which will let us see which errors show up in which releases.
We'll set this to the image tag, which is (I think) the best indicator that we have for what a release is available to the template.

DM-49030: mobu - sentry release

---

applications/squareone/Chart.yaml
applications/squareone/README.md
applications/squareone/templates/configmap.yaml
applications/squareone/values-idfdev.yaml
applications/squareone/values-usdfdev.yaml
applications/squareone/values.yaml

This new version of Squareone features a re-engineered primary navigation with a configurable "Apps" menu for linking to apps like Times Square in the project RSPs.
See PR: https://github.com/lsst-sqre/squareone/pull/179

DM-48644: Squareone update with Apps menu

---

docs/documenteer.toml
src/phalanx/models/secrets.py

Use `StrEnum` rather than inheriting from both `str` and `Enum`.

DM-49036: Use StrEnum where appropriate

---

src/phalanx/services/vault.py
tests/cli/secrets_test.py
tests/cli/vault_test.py
tests/support/vault.py

Python now provides `datetime.now(tz=UTC)`, so use that instead of `current_datetime` from Safir since it's more familiar to the average Python programmer.

DM-49036: Avoid using current_datetime

---

docs/extras/schemas/environment.json
src/phalanx/models/environments.py
src/phalanx/models/secrets.py

Move `model_config` settings to the top of the class instead of after the attributes so that they're more apparent. Use the native Pydantic way of supporting camel-case attributes instead of using Safir's `CamelCaseModel`.

DM-49036: Update model configuration to current style

---

charts/cadc-tap/README.md
charts/cadc-tap/templates/configmap.yaml
charts/cadc-tap/templates/tap-ingress-anonymous.yaml
charts/cadc-tap/values.yaml

We recently noticed an issue where all TAP services were misbehaving with what turned out to be a broken web service at cadc: https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/resource-caps. This gets queried by the `RegistryClient` class in the reg package of cadc, which occurs when `/capabilities` is checked. In this case this request was timing out due to an outage at CADC.
To address this we introduce a new '/reg' endpoint which is can be queried and returns an empty file for the `/reg/resource-caps`'endpoint which is what is queried by the `RegistryClient` to collect additional metadata for capabilities. This does not have to contain any content in our case as our capabilities endpoints don't depend on any extra resource-caps.
The changes above required building a new version & image …

DM-49026: Upgrade ssotap & tap versions and remove dependency on external cadc registry service

---

applications/datalinker/templates/deployment.yaml

Removal of direct Butler support was too aggressive and removed the remote Butler configuration. Add it back.

DM-49067: Re-add datalinker Butler configuration

---

applications/vo-cutouts/Chart.yaml

Now uses Butler to parse URIs to support the new URI format and uses a newer image cutout backend incorporated into the stack container.

DM-49075: Update vo-cutouts to 4.1.0

---

applications/giftless/values-roundtable-prod.yaml

The hosts, which we are treating as immutable because they're Container OS devices, have `somaxconn` set to 1024, so we can't go higher there.  So the easiest way to get past the "backlog fills up, git-lfs goes unresponsive" problem is to spread the load among more servers.
The crash seems to happen during builds, when presumably we have a lot of git-lfs pulls happening in a short time.  But once the servers check out, they seem to neither recover nor die.
Other things we could in principle do:
1) front uwsgi with some sort of session-aggregating web server.  Not sure this will help since I think that's what our ingress is, and it may be that these are all different sessions, happening from different processes during the build phase.
2) dive into the giftless code and try to make it …

tickets/DM-49007: horizontally scale git-lfs to 5 from 3

---

applications/livetap/README.md
applications/livetap/values.yaml
applications/ssotap/README.md
applications/ssotap/values.yaml
applications/tap/README.md
applications/tap/secrets-idfdev.yaml
applications/tap/secrets-idfint.yaml
applications/tap/secrets.yaml
applications/tap/values-idfint.yaml
applications/tap/values.yaml
charts/cadc-tap/README.md
charts/cadc-tap/templates/tap-deployment.yaml
charts/cadc-tap/values.yaml

Enable Sentry error logging and tracing for TAP service. 
Enables for idfint & idfdev. If left disabled TAP services for other environments should continue to work without any noticeable change.
https://rubinobs.atlassian.net/browse/DM-48801
https://github.com/lsst-sqre/lsst-tap-service/pull/127
I've tested on an dev & int with SENTRY_DSN enabled, and then the same build with SENTRY_DSN disabled in phalanx to ensure that tracing doesn't get sent in the second case
Set image of TAP service to new release before merging

Enable Sentry for TAP

---

applications/butler/README.md
applications/butler/templates/configmap-public.yaml
applications/butler/values-idfdev.yaml
applications/butler/values-idfint.yaml
applications/butler/values-idfprod.yaml
applications/butler/values.yaml
applications/nublado/values-idfdev.yaml

Configure the `idfdev` Butler server to use Weka S3 at USDF for serving Data Preview 0.2 files.

DM-49125: Use USDF for serving DP02 Butler files

---

applications/butler/values-idfint.yaml
applications/butler/values-idfprod.yaml
applications/nublado/values-idfint.yaml

Configure the Butler on idfint to serve DP02 files from USDF instead of Google Cloud.

DM-49125: Switch idfint to USDF DP02 datastore

---

applications/butler/templates/configmap-public.yaml

The weekly 2022_40 stack version used for some tutorials does not accept a trailing directory name in a datastore root with Weka S3, because it enforces that the root `exists()` which it does not in S3 because it is a directory.
We are moving the directory on the filesystem so the needed files live at the root.

DM-49125: Move DP02 data product Butler root

---

applications/butler/values-idfprod.yaml

In preparation for future changes to switch to the SLAC datastore and roll out DP1 to prod, set up secrets for Butler server that are distinct from the ones provided to users in nublado.

DM-49125: Separate Butler server secrets from nublado on prod

---

applications/sasquatch/README.md
applications/sasquatch/values.yaml

It is taking longer for the database to read the indexes from disk during initialization. This was noticed at USDF but set an initial delay of 60s by default.

Increase initial delay in InfluxDB OSS liveness probe

---

applications/sasquatch/values-summit.yaml

- Disable InfluxDB Enterprise and Telegraf connectors at the Summit to reduce load
- We are waiting on the second InfluxDB Enterprise node to migrate to InfluxDB Enterprise

Disable InfluxDB Enterprise at the Summit

---

applications/prompt-keda-hsc/README.md
applications/prompt-keda-hsc/values.yaml
applications/prompt-keda-latiss/README.md
applications/prompt-keda-latiss/values-usdfprod-prompt-processing.yaml
applications/prompt-keda-latiss/values.yaml
applications/prompt-keda-lsstcamimsim/README.md
applications/prompt-keda-lsstcamimsim/values.yaml
applications/prompt-keda-lsstcomcamsim/README.md
applications/prompt-keda-lsstcomcamsim/values.yaml
charts/prompt-keda/README.md
charts/prompt-keda/templates/scaled-job.yaml
charts/prompt-keda/values.yaml

This PR adds the same worker config hooks to the Keda implementation as already exist for Knative. Only `worker.restart` is actually implemented on this PR; `worker.grace_period` is for future use.

DM-49078: Add support for worker restarts to Keda

---

applications/sasquatch/values-usdfprod.yaml

Telegraf-app-metrics should write to InfluxDB Enterprise at usdfprod. 
Also remove unused KafkaUser in that environment.

Sasquatch fixes for usdfprod

---

applications/butler/values-idfprod.yaml
applications/nublado/values-idfprod.yaml

Configure the Butler on idfprod to serve DP02 files from USDF instead of Google Cloud.

DM-49125: Switch idfprod to USDF DP02 datastore

---

applications/gafaelfawr/Chart.yaml
applications/gafaelfawr/README.md
applications/gafaelfawr/crds/ingress.yaml
applications/gafaelfawr/templates/_helpers.tpl
applications/gafaelfawr/values.yaml
applications/giftless/README.md
applications/giftless/templates/ingress.yaml
applications/giftless/values.yaml
applications/wobbly/templates/ingress-service.yaml

Drop support for the `config.realm` configuration setting, since Gafaelfawr no longer supports configuring it separately. Update the CRD for `GafaelfawrIngress`. Add the new `config.allowSubdomains` setting.
Disable cookie authentication to giftless since it uses a separate hostname anyway and cookies would never have worked (and otherwise the ingress would now be rejected). Clean up its `values.yaml` file a bit and drop the `config.baseUrl` setting in `GafaelfawrIngress` that is now ignored.
Disable cookie authentication for the service endpoint to Wobbly, since services will never have cookies.

DM-49493: Update to Gafaelfawr 13.0.0

---

applications/nublado/Chart.yaml
applications/nublado/README.md
applications/nublado/values-base.yaml
applications/nublado/values-idfdemo.yaml
applications/nublado/values-idfdev.yaml
applications/nublado/values-idfint.yaml
applications/nublado/values-idfprod.yaml
applications/nublado/values-roe.yaml
applications/nublado/values-summit.yaml
applications/nublado/values-tucson-teststand.yaml
applications/nublado/values.yaml

Upgrade the Nublado application to the 8.7.0 release, which includes an additional `GafaelfawrIngress` setting in file server ingresses that is required to work with Gafaelfawr 13.0.0 and later.

DM-49493: Update Nublado to 8.7.0

---

applications/gafaelfawr/values-idfdev.yaml

Set the configuration option that scopes cookies to the domain instead of the host so that Gafaelfawr can authenticate accesses to per-user subdomains for Nublado.

DM-49329: Allow subdomains in Gafaelfawr on idfdev

---

applications/mobu/Chart.yaml
applications/mobu/README.md
applications/mobu/secrets.yaml
applications/mobu/tests/github_ci_app_enabled_test.yaml
applications/mobu/tests/github_disabled_test.yaml
applications/mobu/tests/github_refresh_app_enabled_test.yaml
applications/mobu/values-ccin2p3.yaml
applications/mobu/values-idfdev.yaml
applications/mobu/values-idfint.yaml
applications/mobu/values-idfprod.yaml
applications/mobu/values-usdfdev.yaml
applications/mobu/values-usdfint.yaml
applications/mobu/values-usdfprod.yaml
applications/mobu/values.yaml

This release retires the `NotebookRunner` business name in favor of `NotebookRunnerCounting` and `NotebookRunnerList` and adds support for per-user subdomains in Nublado. It also adds a new configuration option, `gafaelfawrTimeout`, to change the timeout for Gafealfawr requests during flock startup.

DM-49388: Update mobu to version 15.0.0

---

applications/mobu/values-idfdev.yaml

Otherwise, I can't see debug logs from individual monkeys.

DM-49388: Disable logging mobu monkeys to file in idfdev

---

applications/nublado/README.md
applications/nublado/templates/hub-configmap.yaml
applications/nublado/templates/proxy-ingress.yaml
applications/nublado/values-idfdev.yaml
applications/nublado/values.yaml

Add a new optional ingress that handles the subdomain routing if user subdomains are enabled, and enable user subdomains on data-dev.lsst.cloud. For now, do this with two settings because the proxy configuration requires setting a Zero to JupyterHub configuration setting that we otherwise ignore.

DM-49329: Enable user subdomains for Nublado on idfdev

---

applications/noteburst/Chart.yaml

Adds support for per-user subdomains for Nublado-managed JupyterLab instances.

DM-49388: Update noteburst to 0.16.0

---

applications/nublado/templates/hub-configmap.yaml

Configure JupyterHub to update lab activity no more frequently than once every ten minutes. This will hopefully reduce the database load when large numbers of labs are running, since JupyterHub database updates use a single database session and are synchronous. Our idle cull time is long enough that this shouldn't make any real difference.

DM-49546: Decrease JupyterHub activity updates

---

src/phalanx/data/vault-read-policy.hcl.jinja
src/phalanx/data/vault-write-policy.hcl.jinja
src/phalanx/models/environments.py
src/phalanx/services/vault.py
tests/cli/vault_test.py

This PR modifies how we generate the vault policies, to use the mount point from the vault path in the environment configuration rather than a fixed "/secret" path.

DM-49545: Change vault policies to read mount point from configuration

---

applications/nublado/README.md
applications/nublado/values.yaml

We want to grant servers the ability to delete themselves since that's how the logout menu works. This previously was done by giving the server full `self` access, but that provides access to all sorts of other things we don't want the server to be doing, such as creating tokens for the user. Restrict that to only the permissions normally given to servers, plus the ability to delete servers.

DM-49546: Fix default scopes for user servers

---

applications/nublado/values.yaml

Increase the limit for the JupyterHub proxy to a full CPU and double the memory limit. The current requests are accurate for normal usage right now, but under load testing the JupyterHub proxy ran out of memory and was OOM-killed, and we're seeing warnings about it hitting its CPU limits.

DM-49546: Bump limits for JupyterHub proxy

---

applications/ghostwriter/Chart.yaml

This version adds support for per-user subdomains in Nublado.

DM-49388: Update Ghostwriter to 0.2.0

---

src/phalanx/services/secrets.py
tests/cli/secrets_test.py
tests/data/output/idfdev/sync-gafaelfawr-output

Previously, if `phalanx secrets sync --delete` needed to modify a secret key's value and also delete a different secret key, it would inadvertantly undo the first operation when doing the second due to an out-of-date in-memory data structure. Fix this by updating the in-memory copy of the Vault secret when secrets are added or modified so that a subsequent delete uses the correct values.

DM-49563: Fix secrets sync with modify and delete

---

applications/wobbly/README.md
applications/wobbly/values.yaml

Try moving the Wobbly maintenance job off of 10 minutes past the hour to see if the timing is why we constantly get alerts about it but not about the Gafaelfawr maintenance jobs that use the same pattern.

Shift timing of Wobbly maintenance

---

applications/mobu/Chart.yaml
applications/mobu/README.md
applications/mobu/templates/stateful-set.yaml
applications/mobu/tests/github_ci_app_enabled_test.yaml
applications/mobu/tests/github_disabled_test.yaml
applications/mobu/tests/github_refresh_app_enabled_test.yaml
applications/mobu/tests/termination_grace_period_test.yaml
applications/mobu/values.yaml

* The replica count from the helm chart values is templated into the `replicas` value of the Mobu workload, and the `MOBU_REPLICA_COUNT` environment variable.
* The Mobu workload is a `StatefulSet` instead of a `Deployment` so that the [pod index label](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#pod-index-label) can be passed as the value to the `MOBU_REPLICA_INDEX` env var via the Kubernetes [Downward API](https://kubernetes.io/docs/concepts/workloads/pods/downward-api/). This ensures that monkeys can be distributed as evenly as possible among all of the replicas in the `StatefulSet`.
Goes with [this Mobu PR](https://github.com/lsst-sqre/mobu/pull/448).

DM-49361: mobu - multi-instance

---

applications/mobu/templates/stateful-set.yaml
applications/mobu/values.yaml

* Specify mobu memory reqs in Mi instead of Gi because ArgoCD will always show OutOfSync because of a bug in value normalization for certain combinations of attributes in certain resources: https://github.com/argoproj/argo-cd/issues/16400
* Remove the `strategy` key from the `StatefulSet` because it only applies to `Deployments`

DM-49361: mobu - ArgoCD resource consistency issues

---

applications/gafaelfawr/values-idfint.yaml
applications/nublado/values-idfint.yaml

Enable subdomain support in Gafaelfawr for idfint and switch to per-user subdomains for Nublado in idfint.

DM-49602: Convert idfint to per-user notebook domains

---

applications/sia/Chart.yaml
applications/sia/values-idfdev.yaml
applications/sia/values-idfint.yaml

This PR changes the following:
- Upgrade SIA to 0.1.7 (Mainly to pick up latest changes to dax_obscore)
- Enables DP1 for idfint & idfdev
- DM-48938: Capture sia query in sentry tracing by @stvoutsin in https://github.com/lsst-sqre/sia/pull/29
- DM-49503: Update Python and pre-commit dependencies by @rra in https://github.com/lsst-sqre/sia/pull/31
- DM-49531: Update dependencies by @stvoutsin in https://github.com/lsst-sqre/sia/pull/32

DM-49531: Enable dp1 for SIAv2 on idfdev and idfint environments

---

applications/sasquatch/README.md
applications/sasquatch/charts/app-metrics/README.md
applications/sasquatch/charts/app-metrics/values.yaml

We are using a specific nightly build of telegraf for app metrics collection because it has our added support for Avro unions.
[1.34](https://github.com/influxdata/telegraf/releases/tag/v1.34.0) finally has [our Avro union support](https://github.com/influxdata/telegraf/pull/16272).

DM-49610: Get back on upstream telegraf

---

applications/prompt-keda-hsc/values.yaml
applications/prompt-keda-latiss/values-usdfprod-prompt-processing.yaml
applications/prompt-keda-latiss/values.yaml
applications/prompt-keda-lsstcamimsim/values.yaml
applications/prompt-keda-lsstcomcamsim/values.yaml
applications/prompt-proto-service-hsc-gpu/values.yaml
applications/prompt-proto-service-hsc/values.yaml
applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-latiss/values.yaml
applications/prompt-proto-service-lsstcam/values.yaml
applications/prompt-proto-service-lsstcamimsim/values.yaml
applications/prompt-proto-service-lsstcomcam/values.yaml
applications/prompt-proto-service-lsstcomcamsim/values.yaml

This PR standardizes/normalizes the PP log settings, and adds some verbose-level logs that are useful for debugging Middleware problems.

DM-49555: Expand diagnostic logs for Prompt Processing

---

applications/argocd/values.yaml
applications/nublado/values.yaml

Increase memory limits for the Argo CD application controller and the Nublado controller, both of which were OOMKilled when testing scaling Nublado to 3,000 pods.

DM-49662: Increase memory limits we hit during load testing

---

applications/nublado/templates/hub-configmap.yaml

Configure the Nublado `Spawner` class to only poll the Nublado controller for lab status every five minutes. The Nublado controller only checks Kubernetes for issues every five minutes, so there's no point in checking more frequently than this.

DM-49662: Only poll Nublado labs every five minutes

---

applications/consdbtap/README.md
applications/consdbtap/values.yaml

The consdb container wants to allocate 600 MB initially, reflected in the new request limit, and it seems to intermittently
exceed the 1Gi limit when starting up, so this was increased to 2Gi. 
New settings were tested and confirmed to work on `usdf-rsp-dev`.

DM-49665: Adjust resource limits for consdb tapSchema container

---

applications/love/values-summit.yaml

MTMount, MTM2, ATHeaderService, HVAC and MTCamera LOVE producers are being throttled in the Summit. This change is to increase the CPU resources allocated to them accordingly.

DM-49680: Bump resources of Summit LOVE producers

---

applications/nublado/README.md
applications/nublado/templates/hub-configmap.yaml
applications/nublado/values.yaml

Even at once every ten minutes, recording user lab activity is saturating JupyterHub. Increase the storage interval to one hour and also configure JupyterLab to only report activity once an hour. This is still very long compared to our idle cull interval. Also configure the idle culler to only check once every hour for labs to kill.

DM-49662: Increase Nublado activity reporting interval to 1h

---

applications/nublado/Chart.yaml
applications/nublado/README.md
applications/nublado/templates/hub-configmap.yaml
applications/nublado/values-base.yaml
applications/nublado/values-idfdemo.yaml
applications/nublado/values-idfdev.yaml
applications/nublado/values-idfint.yaml
applications/nublado/values-idfprod.yaml
applications/nublado/values-roe.yaml
applications/nublado/values-summit.yaml
applications/nublado/values-tucson-teststand.yaml
applications/nublado/values.yaml

Add configuration for where to redirect the user after a JupyterHub logout so that we send the user to the Gafaelfawr logout handler instead of creating a redirect loop inside JupyterHub.

DM-49624: Update to Nublado 8.8.0

---

applications/nublado/templates/controller-deployment.yaml

If the Nublado controller has to recover a lot of state from Kubernetes, it may take some time to start up. Configure a separate startup probe that gives it up to five minutes.

DM-49662: Define a separate Nublado controller startup probe

---

applications/wobbly/values.yaml

CPU limits lower than 1 have not proven to be that useful compared to allowing burst usage when needed, and this seems to be the cause of spurious monitoring warnings for the maintenance job.

Increase wobbly CPU limit to 1

---

applications/sasquatch/README.md
applications/sasquatch/values.yaml

- The InfluxDB OSS liveness probe is restarting the InfluxDB OSS Pod at USDF dev before it initializes.

Increase liveness probe initialDelaySeconds to 90s

---

charts/cadc-tap/README.md
charts/cadc-tap/values.yaml

Upgrade TAP to version 2.11.0
- DM-49350: Re-enable log4j configuration for cadc-log, keep log4j2 for sentry by @stvoutsin in https://github.com/lsst-sqre/lsst-tap-service/pull/135
- DM-49350: Fix version cadc-tap since upstream changes break our build, until we update our tap_schema image by @stvoutsin in https://github.com/lsst-sqre/lsst-tap-service/pull/136
- DM-49676: Change Sentry logging to not capture user syntax issues by @stvoutsin in https://github.com/lsst-sqre/lsst-tap-service/pull/137

DM-49676: Upgrade TAP to version 2.11.0

---

applications/rubin-rag/.helmignore
applications/rubin-rag/Chart.yaml
applications/rubin-rag/README.md
applications/rubin-rag/secrets.yaml
applications/rubin-rag/templates/_helpers.tpl
applications/rubin-rag/templates/deployment.yaml
applications/rubin-rag/templates/ingress.yaml
applications/rubin-rag/templates/networkpolicy.yaml
applications/rubin-rag/templates/service.yaml
applications/rubin-rag/templates/vault-secrets.yaml
applications/rubin-rag/values-idfint.yaml
applications/rubin-rag/values.yaml
docs/applications/rubin-rag/index.rst
docs/applications/rubin-rag/values.md
docs/applications/rubin.rst
environments/README.md
environments/templates/applications/rubin/rubin-rag.yaml
environments/values-idfint.yaml
environments/values-usdfdev.yaml
environments/values.yaml

Create rubin-rag from gai-helpers and deploy on data-int.

SP-1929: Adding Rubin rag

---

applications/sasquatch/values-usdfprod.yaml

The lsstcam connector in Sasquatch at USDF is showing this error:
```
E! [agent] Error writing to outputs.influxdb: could not write any address
``` 
Looking at the connector dashboard it is exceeding its buffer limit and using way too much memory.
We spot a difference in the Telegraf config at the Summit and USDF, USDF is missing the following:
```
metric_batch_size: 250
max_undelivered_messages: 5000
```
After fixing the configuration the error is gone and we are operating within the buffer limits.

[DM-49812] FIx lsstcam connector configuration

---

applications/sasquatch/charts/strimzi-kafka/templates/users.yaml

- Add permission to retrieve cluster metadata, this is required for producers

Fix acls for tab an qserv users

---

applications/next-visit-fan-out-keda/README.md
applications/next-visit-fan-out-keda/templates/deployment.yaml
applications/next-visit-fan-out-keda/values.yaml
applications/next-visit-fan-out/README.md
applications/next-visit-fan-out/templates/deployment.yaml
applications/next-visit-fan-out/templates/instruments.yaml
applications/next-visit-fan-out/values-usdfdev-prompt-processing.yaml
applications/next-visit-fan-out/values-usdfprod-prompt-processing.yaml
applications/next-visit-fan-out/values.yaml
environments/values-usdfdev-prompt-processing.yaml
environments/values-usdfprod-prompt-processing.yaml
tests/config_test.py

Adds env variables and instrument config for Redis Steams to `next-visit-fan-out` and `next-visit-fan-out-keda` applications for co-existence.

DM-48978: Keda Support on Next Visit Fan Out

---

applications/prompt-keda-hsc/values-usdfdev-prompt-processing.yaml
applications/prompt-keda-latiss/values-usdfdev-prompt-processing.yaml
applications/prompt-keda-latiss/values-usdfprod-prompt-processing.yaml
applications/prompt-keda-lsstcomcam/values-usdfdev-prompt-processing.yaml
applications/prompt-keda-lsstcomcamsim/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-hsc-gpu/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-hsc/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-latiss/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcam/values-usdfdev-prompt-processing.yaml
applications/prompt-proto-service-lsstcomcamsim/values-usdfdev-prompt-processing.yaml

This PR migrates all active APDB configs from the deprecated pex_config (`.py`) format to YAML. The config files have already been converted.

Migrate Prompt Processing to YAML APDB configs

---

environments/values-usdfdev-prompt-processing.yaml
environments/values-usdfprod-prompt-processing.yaml
tests/config_test.py

Disable `prompt-proto-service` in dev and prod due to the move the Keda.  The applications are being kept for now as Keda is evaluated in production.

Prompt Processing:  Disable Prompt Proto Service

---

applications/nublado/values-idfdemo.yaml
applications/nublado/values-idfdev.yaml
applications/nublado/values-idfint.yaml
applications/nublado/values-idfprod.yaml

Pull inithome from Google Artifact Registry at IDF.  Eliminates ghcr.io rate limiting for heavy user load.

Tickets/dm 49869: IDF->pull inithome from GAR

---

applications/sasquatch/charts/tap/templates/kafka-users.yaml
applications/sasquatch/values-idfint.yaml

Now that the Qserv Kafka bridge will be running in the same cluster as Sasquatch, we can use TLS for authentication rather than passwords. Switch the corresponding Kafka user resource.

DM-49993: Switch qserv Sasquatch user to TLS authentication

---

applications/qserv-kafka/.helmignore
applications/qserv-kafka/Chart.yaml
applications/qserv-kafka/README.md
applications/qserv-kafka/secrets.yaml
applications/qserv-kafka/templates/_helpers.tpl
applications/qserv-kafka/templates/configmap.yaml
applications/qserv-kafka/templates/deployment.yaml
applications/qserv-kafka/templates/kafka-access.yaml
applications/qserv-kafka/templates/networkpolicy.yaml
applications/qserv-kafka/templates/vault-secrets.yaml
applications/qserv-kafka/values-idfint.yaml
applications/qserv-kafka/values.yaml
docs/applications/qserv-kafka/index.rst
docs/applications/qserv-kafka/values.md
docs/applications/rsp.rst
environments/README.md
environments/templates/applications/rsp/qserv-kafka.yaml
environments/values-idfint.yaml
environments/values.yaml

Add new Qserv Kafka bridge application. Deploy a test container for now since there has been no formal release. Configure it on idfint, since that's the environment for which we have information about MySQL and REST connect URLs.

DM-49993: Add test version of Qserv Kafka bridge

---

applications/portal/values-idfdev.yaml
applications/portal/values-idfint.yaml
applications/portal/values-idfprod.yaml
applications/portal/values.yaml

The Portal Redis has been repeatedly OOM killed on idfint. Increase its memory limit to 40Mi and add explicit requests as we do with other Redis pods that are a bit lower. Enable persistent storage on the IDF deployments since notebook integration breaks if the Redis contents are removed.

DM-50027: Change resources and storage for Portal Redis

---

applications/portal/values-usdfdev.yaml
applications/portal/values-usdfint.yaml
applications/portal/values-usdfprod.yaml

Following the configuration change for the IDF deployments, also use a persistent volume for the Portal Redis on USDF environments.

DM-50027: Add persistent volumes for Portal Redis on USDF

---

docs/admin/audit-secrets.rst
docs/admin/index.rst
docs/admin/op-run-phalanx-cli.rst
docs/admin/sync-secrets.rst
docs/admin/update-pull-secret.rst
op/README.md
op/base.env
op/idfdemo.env
op/idfdev.env
op/idfint.env
op/idfprod.env
op/minikube.env
op/roundtable-dev.env
op/roundtable-prod.env
op/summit.env
op/tucston-teststand.env

This PR takes advantage of the 1Password CLI's ability to load secrets referenced by their path in a .env file. With this change, admins no longer need to manually load the VAULT_TOKEN and OP_CONNECT_TOKEN into their shell environments to run phalanx commands like `phalanx secrets sync`. An example usage is:
```sh
PHALANX_ENV="idfprod" op run --env-file="op/square.env" -- phalanx secrets audit
```
Note that I've had the user set PHALANX_ENV, which is used to specify secret paths in `square.env` specific to that Phalanx environment. I've also modified the Phalanx CLI to accept `PHALANX_ENV` as an environment variable instead of as a command-line argument.
Note an alternative approach could be to have a separate `.env` file for each Phalanx environment. This would let us set `PHALANX_ENV` …

DM-49929: Load OP_CONNECT_TOKEN and VAULT_TOKEN from 1Password via env file

---

applications/datalinker/Chart.yaml
applications/datalinker/README.md
applications/datalinker/templates/deployment.yaml
applications/datalinker/values.yaml

Adds `Expires` and `Cache-Control` headers to `{links}` responses with a new configuration option to specify the lifetime. Also delete old settings that are no longer used and alphabetize the settings.

DM-50042: Update Datalinker to 3.2.0

---

applications/nvr-control/templates/ingress.yaml
applications/nvr-control/templates/networkpolicy.yaml

We need a fixed header added inbound from the ingress proxy, which the HA header auth provider can use to select a shared account (after upstream authentication with gafaelfawr).

nvr-control: add proxy header for HA auth

---

applications/prompt-keda-lsstcam/values-usdfprod-prompt-processing.yaml

This PR fixes an incorrect scheduling configuration that wasn't caught on #4505.

DM-49664: Schedule Prompt Processing on PP nodes, where possible.

---

applications/consdb/values-usdfdev.yaml
applications/consdb/values-usdfprod.yaml

In consdb, the the database should be changed to point to the logical replica instead of the new physical replica.

Transition consdb to the logical replica at USDF

---

applications/prompt-keda-lsstcam/values-usdfprod-prompt-processing.yaml

This version prevents broken IERS downloads from the Prompt Processing pods.

Update Prompt Processing to 6.4.1.

---

charts/cadc-tap/README.md
charts/cadc-tap/templates/configmap.yaml
charts/cadc-tap/values.yaml

- Change TableServlet to use RestServlet similar to what is done in other upstream packages
- Remove unneeded implementations (Registry implementation, now fixed in cadc-reg 1.4.3). (To address bug where we send out requests to the cadc reg)
- Remove JobDAO and CachingFile implementations (JobDAO bug has been fixed, and these were retained here because of the log4j checkpoint bug, i.e. getting checkpoint logs due to log4j conflicts)
- Fix log4j / log4j2 issues (cadc-util imports the log4j2 apis so we don't need to add the dependency). We just include the log4j2 configuration here
- Change TableServlet to use RestServlet similar to what is done in other upstream packages
- Upgraded cadc dependencies, java to 11 and remove unneeded implementations of Registry, MaxRec 
- The upgrades include …

DM-50058: Upgrade lsst-tap-service to 2.13.1 and tap-postgres to 1.21.1

---

applications/qserv-kafka/templates/configmap.yaml
applications/qserv-kafka/values-idfdev.yaml
applications/qserv-kafka/values-idfint.yaml

Update the test version of the Qserv Kafka bridge to a version that supports URL rewriting of access URLs.

DM-50225: Add URL rewriting to the Qserv Kafka bridge

---

applications/next-visit-fan-out/README.md
applications/next-visit-fan-out/values-usdfdev-prompt-processing.yaml
applications/next-visit-fan-out/values-usdfprod-prompt-processing.yaml
applications/next-visit-fan-out/values.yaml

Change to `SASL_SSL` and Kafka broker IPs after Sasquatch issues with connectivity to Summit through firewall.

DM-50267: Prompt Processing SSL Kafka Consumer Fix

---

applications/noteburst/templates/worker-deployment.yaml

Ensure that noteburst workers start one-at-a-time to help reduce contention of identities when there's an issue acquiring a jupyterlab pod.

DM-50300: Noteburst workers start sequentially

---

applications/prompt-keda-lsstcam/values-usdfprod-prompt-processing.yaml

This version handles nextVisits with no filter spec correctly.

Update Prompt Processing to 6.4.2.

---

applications/qserv-kafka/Chart.yaml
applications/qserv-kafka/README.md
applications/qserv-kafka/secrets.yaml
applications/qserv-kafka/templates/configmap.yaml
applications/qserv-kafka/templates/deployment.yaml
applications/qserv-kafka/values-idfdev.yaml
applications/qserv-kafka/values-idfint.yaml
applications/qserv-kafka/values.yaml

Set up an internal Redis to store query state, allowing the bridge to be restarted without losing track of what queries are running. Ensure only one copy of the bridge is running at a time, since we don't currently have a locking mechanism to prevent multiple copies of the bridge from processing the same Qserv query.

DM-50253: Add Redis support to Qserv Kafka bridge

---

applications/sasquatch/charts/strimzi-kafka/templates/kafka.yaml
applications/sasquatch/charts/strimzi-kafka/templates/mirrormaker2.yaml
applications/sasquatch/values-usdfdev.yaml
applications/sasquatch/values-usdfprod.yaml

Use the right annotation to allocate Kafka IPs on the Pixel Zone. 
Increase number of MM2 tasks to increate throughput.
Disable replication of Summit consumer group offsets as they are not needed at USDF.
Reduce M1M3 batch size to avoid timeout problems when writing to InfluxDB.

Fix EFD replication at USDF

---

applications/prompt-keda-lsstcam/values-usdfprod-prompt-processing.yaml

The Prompt Processing configuration replaced BLOCK-T407 with BLOCK-365 in the main pipeline but not the preprocessing pipeline. This would have made it impossible to run ApPipe has the config been activated.

Use BLOCK-365 for Prompt Processing SV survey.

---

applications/prompt-keda-lsstcam/values-usdfprod-prompt-processing.yaml

This PR cleans up the PP config to exclude stray light tests, explicitly exclude BLOCK-T454 (which is both prolific and unprocessable), and update our SV config for new fields.

Prompt Processing survey updates

---

applications/consdbtap/values-usdfdev.yaml
applications/consdbtap/values-usdfint.yaml
applications/consdbtap/values-usdfprod.yaml

We want `consdbtap` to be versioned independently from the other TAP services. This pins all USDF environments to a known-good tag.

Change consdbtap to use sdm_schemas w.2025.16

---

applications/prompt-keda-lsstcam/values-usdfprod-prompt-processing.yaml

This PR reorients the Prompt Processing config towards SV visits and fixes some minor issues.

Configure Prompt Processing for early Science Verification

---

applications/qserv-kafka/README.md
applications/qserv-kafka/templates/deployment.yaml
applications/qserv-kafka/values-idfdev.yaml
applications/qserv-kafka/values-idfint.yaml
applications/qserv-kafka/values.yaml

Update to a new development branch of the Qserv Kafka bridge and add a shutdown timeout for graceful shutdown of result processing. Set the Kubernetes pod termination grace period to five seconds more than the internal timeout for shutdown processing.

DM-50391: Update Qserv Kafka bridge, add shutdown timeout

---

applications/next-visit-fan-out/values-usdfprod-prompt-processing.yaml

This PR fixes an issue where the Prompt Processing Next Visit Fan-Out service was requesting processing for detectors that were turned off and always produced blank raws.
Despite having `*LSSTCam`, `LSSTCam-imSim` is *not* affected by this patch.

Don't fan-out Prompt Processing messages for turned-off detectors

---

applications/nublado/README.md
applications/nublado/templates/tutorial-cronjob.yaml
applications/nublado/values-idfdev.yaml
applications/nublado/values.yaml

This will keep our tutorial notebooks fresh, initially on IDF-dev so we don't have to do a clone with each lab start.

Add tutorial notebook pull cronjob/idfdev

---

applications/qserv-kafka/README.md
applications/qserv-kafka/templates/configmap.yaml
applications/qserv-kafka/templates/deployment.yaml
applications/qserv-kafka/values-idfdev.yaml
applications/qserv-kafka/values-idfint.yaml
applications/qserv-kafka/values.yaml

Rename `shutdownTimeout` to `resultTimeout` to fit the newer version of Qserv Kafka bridge and update to the new test version of the bridge.

DM-50410: Update the test Qserv Kafka bridge

---

applications/auxtel/values-summit.yaml
applications/envsys/values-summit.yaml
applications/simonyitel/values-summit.yaml

The following components were reaching their memory limits:
- atheaderservice-7pk99 = 80.6 %
- dream-dg44z = 81.7 %
- gcheaderservice101-xh5sj = 88.0 %
- gcheaderservice102-25nqq = 91.6 %
- gcheaderservice103-2tn76 = 89.3 %
Their memory requests/limits have been updated accordingly.

DM-50489: Increase memory for some summit components.

---

applications/nublado/README.md
applications/nublado/values-idfdev.yaml
applications/nublado/values.yaml

Drop support for the `config.realm` configuration setting, since Gafaelfawr no longer supports configuring it separately. Update the CRD for `GafaelfawrIngress`. Add the new `config.allowSubdomains` setting.
Disable cookie authentication to giftless since it uses a separate hostname anyway and cookies would never have worked (and otherwise the ingress would now be rejected). Clean up its `values.yaml` file a bit and drop the `config.baseUrl` setting in `GafaelfawrIngress` that is now ignored.
Disable cookie authentication for the service endpoint to Wobbly, since services will never have cookies.

DM-49593: Move to NetApp Cloud volumes

---

.pre-commit-config.yaml
applications/sasquatch/secrets.yaml

There was a typo in the secret conditional for the `telegraf-password`  as revealed by `phalanx secrets audit`.
Now `phalanx secrets audit` looks correct for both IDF dev and int.
I also removed the unused static secrets from 1password for those environments.

Fix conditional for telegraf-password

---

applications/qserv-kafka/values-idfdev.yaml
applications/qserv-kafka/values-idfint.yaml

There is now a 0.1.0 release. Use that version on idfdev and idfint instead of using a ticket branch build.

DM-50481: Use the released version of qserv-kafka

---

applications/prompt-keda-lsstcam/values-usdfprod-prompt-processing.yaml

This PR updates the Prompt Processing alert topic from `lsst-alerts` to `lsst-alerts-v7.4`. This is for forward-compatibility only; we are not yet running any pipelines that send alerts to this topic.
It also reorganizes the LSSTCam-prod config file so that the Prompt Processing version and alert stream version are easier to update together.

Update Prompt Processing alert stream.

---

applications/sasquatch/README.md
applications/sasquatch/charts/telegraf/README.md
applications/sasquatch/charts/telegraf/values.yaml
applications/sasquatch/values-idfdev.yaml

- Set up lsst.example namespace and connector to write data to the enterprise InfluxDB instance on idfdev

Setup lsst.example connector

---

applications/alert-stream-broker/README.md
applications/alert-stream-broker/charts/alert-stream-broker/README.md
applications/alert-stream-broker/charts/alert-stream-broker/values.yaml

Disable automatic topic creation so typo/unintended topics are not created in the alert stream.

DM-50543: Disable automatic topic creation

---

applications/sasquatch/Chart.yaml
applications/sasquatch/README.md
applications/sasquatch/charts/backup/README.md
applications/sasquatch/charts/backup/templates/restore-deployment.yaml
applications/sasquatch/charts/backup/values.yaml
applications/sasquatch/charts/influxdb-enterprise/templates/data-pdb.yaml
applications/sasquatch/charts/influxdb-enterprise/templates/data-statefulset.yaml
applications/sasquatch/charts/influxdb-enterprise/templates/meta-pdb.yaml
applications/sasquatch/secrets.yaml
applications/sasquatch/values-usdfprod.yaml

Add new  InfluxDB Enterprise instance at USDF `sasquatch-influxdb-enterprise-active` run the data pods on `sdfk8so005` and `sdfk8so006` nodes and provision 100TB local storage PVs on each.
Add a `startupProbe` for the InfluxDB data pods and fix the `PodDisruptionBudget` to work with multiple InfluxDB Enterprise deployments.

[DM-50585] Setup a new active InfluxDB Enterprise instance at USDF

---

applications/butler/templates/configmap-private.yaml

Update the DP1 Butler to the v29_0_0 DRP run from USDF `/repo/dp1`, collection `LSSTComCam/runs/DRP/DP1/v29_0_0/DM-50260`.

DM-50578: Update DP1 Butler to v29_0_0 DRP run

---

applications/alert-stream-broker/charts/alert-stream-broker/templates/kafka-topics.yaml
applications/alert-stream-broker/values-usdfdev-alert-stream-broker.yaml

Fix partition config so `lsst-alerts-v7.4` has 45 partitions and up the partition retention to 300 GB.

DM-50668: Fix partitions and up max byte retention

---

applications/prompt-keda-lsstcam/values-usdfprod-prompt-processing.yaml

This PR updates Prompt Processing and turns off the noisiest logs (in LSSTCam-prod only, for now).

Update Prompt Processing to 6.9.0

---

applications/nvr-control/templates/ingress.yaml

HomeAssistant requires its own domain because it can't run on a path, so add the configuration for it to get its own TLS certificate.

DM-50710: Add TLS for nvr-control

---

applications/sasquatch/README.md
applications/sasquatch/charts/telegraf/README.md
applications/sasquatch/charts/telegraf/templates/_helpers.tpl
applications/sasquatch/charts/telegraf/templates/configmap.yaml
applications/sasquatch/charts/telegraf/values.yaml
applications/sasquatch/values-idfdev.yaml
applications/sasquatch/values-summit.yaml
applications/sasquatch/values-usdfprod.yaml

To add support for writing to multiple InfluxDB v1 instances we repeat the [[outputs.influxdb]] section for each instance (rather than listing multiple URLs in a single key)
Update telegraf configuration for all environments and enable dual write at USDF prod for the current production and to the active instance.

[DM-50709] Add support for writing to multiple InfluxDB v1 instances

---

applications/argocd/values-summit.yaml

Use Keycloak for summit Argo CD authentication instead of GitHub.

DM-50719: Convert summit Argo CD to Keycloak

---

applications/argocd/values-base.yaml
applications/argocd/values-summit.yaml
applications/gafaelfawr/values-base.yaml
applications/gafaelfawr/values-summit.yaml

Add k8s-manke-admins and k8s-yagan-admins to the Gafaelfawr role configuration on base and summit, respectively, and fix the name of the groups for Argo CD access at base and summit.

DM-50719: Fix group access for base and summit

---

applications/s3proxy/templates/ingress.yaml

This allows it to be used to serve images to authenticated users beyond the portal.

Allow direct, non-portal ingress to s3proxy.

---

applications/sasquatch/values-summit.yaml

- Adjust metric_batch_size and max_undelivered_messages configuration to avoid the "context deadline exceeded (Client.Timeout exceeded while awaiting headers)" error in the InfluxDB OSS instance.

Add a separate connector for lsst.sal.MTM1M3TS

---

applications/qserv-kafka/values.yaml

The new release seems to use more memory in the steady state, so increase the memory requests and limits again.

DM-50728: Bump Qserv Kafka bridge memory again

---

applications/butler/Chart.yaml
applications/butler/README.md
applications/butler/secrets.yaml
applications/butler/templates/deployment.yaml
applications/butler/values-idfdev.yaml
applications/butler/values-idfint.yaml
applications/butler/values-idfprod.yaml
applications/butler/values.yaml

To help debug performance issues with the deployed Butler server, set up Sentry trace.

DM-47594: Add Sentry tracing to Butler server

---

applications/qserv-kafka/templates/worker-hpa.yaml
applications/qserv-kafka/values-idfint.yaml

Set a stabilization window of 15 minutes for scaledown, since we were scaling down a bit too quickly. Fix the configuration of the maximum number of replicas on idfint.

DM-50879: Tweak scaling configuration for Qserv Kafka bridge

---

docs/developers/injected-values.rst
src/phalanx/data/application-template.yaml.jinja
src/phalanx/services/application.py
tests/data/output/idfdev/lint-all-calls.json
tests/data/output/idfdev/lint-git-calls.json
tests/data/output/idfdev/lint-set-values.json

Currently this used by some apps to provide the environment name as the `SENTRY_ENVIRONMENT` variable, but it could be useful for other things.

DM-50858: Add global.environmentName to app template

---

src/phalanx/storage/config.py

[`helm repo` commands aren't supported for OCI repos](https://github.com/helm/helm/issues/10565#issuecomment-1015531100).
Without this, I can't `phalanx application template` an app with a helm dependency from an OCI registry, like:
```
- name: "grafana-operator"
repository: "oci://ghcr.io/grafana/helm-charts"
version: "v5.17.1"
```
I'm not sure if there's anywhere else in the Phalanx CLI code we need to modify to account for this.

DM-50846: Support OCI repos in the Phalanx CLI

---

applications/sasquatch/README.md
applications/sasquatch/values-usdfdev.yaml
applications/sasquatch/values.yaml

A query limit of 15s was introduced in a commit in January as an attempt to control a behavior we observed at the Summit dashboards that still use InfluxDB OSS, and it leaked to the USDF dev configuration.
Using the same query timeout as in USDF prod, which is 300s and setting the nginx proxy timeout to the same value.
The database is taking longer to initialize so increasing initialDelaySeconds to 180s.

[DM-50887] Review InfluxDB OSS query limits for the USDF dev environment

---

applications/sasquatch/Chart.yaml
applications/sasquatch/README.md
applications/sasquatch/charts/data-transfer-monitoring/Chart.yaml
applications/sasquatch/charts/data-transfer-monitoring/README.md
applications/sasquatch/charts/data-transfer-monitoring/templates/kafka-users.yaml
applications/sasquatch/charts/data-transfer-monitoring/values.yaml
applications/sasquatch/values-summit.yaml
applications/sasquatch/values-usdfprod.yaml
applications/sasquatch/values.yaml

Add `data-transfer-monitoring` Kafka user to allow read access to the `lsst.sal.MTCamera.logevent_endReadout` topic to view end readout events.  This is used to create metrics of file transfers from the Summit by combining data from the Kafka file notifications.  The `data-transfer-monitoring` user is enabled at Summit and USDF.  Summit will be used for primary connectivity.

DM-50615: Data Transfer Monitoring Kafka User

---

charts/prompt-keda/templates/_service-init.tpl
charts/prompt-keda/templates/scaled-job.yaml

This PR standardizes the Keda Prompt Processing container names to match the service name and each other. This makes the logs much easier to query in Grafana.

DM-50909: Prompt Processing uses inconsistent container names

---

applications/noteburst/Chart.yaml
applications/noteburst/README.md
applications/noteburst/values-idfdev.yaml
applications/noteburst/values.yaml
applications/times-square/Chart.yaml
applications/times-square/README.md
applications/times-square/values-idfdev.yaml
applications/times-square/values.yaml

Deployment of Times Square 0.19.0 and Noteburst 0.19.0. The Times Square deployment includes a schema migration.

DM-46313: Update Times Square

---

applications/qserv-kafka/values.yaml

Significantly increase the memory limit and request for the Redis for the Qserv Kafka bridge because our serialized query jobs are rather larger than I had realized if the queries are very wide, due to the size of the VOTable header and JSON schema.

DM-50878: Increase memory for Qserv Kafka bridge Redis

---

applications/qserv-kafka/Chart.yaml
applications/qserv-kafka/README.md
applications/qserv-kafka/templates/configmap.yaml
applications/qserv-kafka/values-idfdev.yaml
applications/qserv-kafka/values.yaml
applications/sasquatch/charts/app-metrics/values.yaml
applications/sasquatch/charts/tap/templates/kafka-users.yaml
applications/sasquatch/values-idfdev.yaml
applications/sasquatch/values-idfint.yaml
applications/sasquatch/values-idfprod.yaml

Add the Sasquatch configuration to enable metrics events for the Qserv Kafka bridge and add configuration of metrics events to the qserv-kafka application. Enable metrics on idfdev.

DM-50878: Add metrics events for qserv-kafka

---

applications/argocd/values-ukidacdev.yaml
applications/cert-manager/values-ukidacdev.yaml
applications/ingress-nginx/values-ukidacdev.yaml

Update the ukidacdev environment to use Let's Encrypt DNS and Route53 for TLS instead of using an external certificate.

Switch ukidacdev cert-manager to route53

---

applications/qserv-kafka/templates/frontend-deployment.yaml
applications/qserv-kafka/templates/worker-deployment.yaml

Temporarily allow containers to run as root in all the qserv-kafka pods so that we can attach a memory profiler in a debug container, without recreating the pod, when we see them leaking memory.
More info about the debug pod process:
https://rubin-obs.slack.com/docs/T02SVMGU4/F08SVEUKE7M

DM-51004: Relax qserv-kafka pod securityContext

---

applications/qserv-kafka/README.md
applications/qserv-kafka/templates/frontend-deployment.yaml
applications/qserv-kafka/templates/worker-deployment.yaml
applications/qserv-kafka/values-idfdev.yaml
applications/qserv-kafka/values-idfint.yaml
applications/qserv-kafka/values.yaml

Use a development image of the Qserv Kafka bridge on idfdev and idfint. Add a values setting to enable root debugging of the containers, off by default, and enable ot on idfdev and idfint.

DM-51004: Set up Qserv Kafka bridge debugging

---

applications/argocd/values-roundtable-prod.yaml

For eups-distributor. Eventually we want to use RBAC to limit modifications to just that application, but do the easy thing for now.

Grant Ross Roundtable Argo CD access

---

applications/times-square/Chart.yaml
applications/times-square/README.md
applications/times-square/templates/job-html-key-migrate.yaml
applications/times-square/templates/job-nbstripout.yaml
applications/times-square/templates/job-schema-update.yaml
applications/times-square/values-idfdev.yaml
applications/times-square/values.yaml

This version strips notebook outputs and kernel specs from notebooks before storage. This should improve efficiency and prevent errors related to notebooks being saved with kernel info that isn't appropriate to the noteburst context.
See https://github.com/lsst-sqre/times-square/pull/101

DM-51015: Update Times Square to 0.20.0

---

applications/butler/values-idfprod.yaml
environments/values-idfprod.yaml

Set up Butler server for DP1 in the production RSP at IDF.  Access is restricted to staff who are members of the g_developers and g_cst groups.

DM-51042: Set up DP1 Butler server on idfprod

---

applications/prompt-keda-lsstcam/values-usdfprod-prompt-processing.yaml

This PR re-activates logging of individual dataset transfers in `transfer_from`.

Revert "Turn off verbose non-timer logs for daf_butler." for Prompt Processing

---

applications/times-square/README.md
applications/times-square/values.yaml

This migration has been applied to all environments, so we no longer need to trigger this hook.

DM-51015: Disable nbstripout migration

---

applications/qserv-kafka/values.yaml

Adjust the memory requests and limits for the Qserv Kafka bridge now that we think the memory leak has stabilized.

DM-51004: Adjust requests and limits for Qserv bridge

---

applications/datalinker/values.yaml

Lower the datalinker memory limits and requests to reflect current usage. These were raised earlier due to a memory leak that has now been fixed.

Lower memory limits for datalinker

---

applications/sasquatch/values-usdfdev.yaml

- InfluxDB OSS at USDF dev is taking longer to initialize

[DM-51126] Increase liveness probe initial delay

---

applications/qserv-kafka/values-idfdev.yaml

Test a new proxy using NGINX instead of socat.

DM-51121: Switch proxies used for Qserv on idfdev

---

applications/times-square/Chart.yaml

This version of Times Square supports dynamic defaults for date parameters.
https://github.com/lsst-sqre/times-square/pull/104

DM-51083: Update times-square to 0.21.0

---

environments/values-usdfprod.yaml

This allows Times Square notesbooks on usdfprod to read Jira data.

Enable jira-data-proxy at USDF

---

applications/gafaelfawr/values-idfprod.yaml
applications/nublado/values-idfprod.yaml

Enable subdomain isolation for Nublado on idfprod, following the configuration on idfint and idfdev.

DM-51158: Switch idfprod to per-user Nublado subdomains

---

applications/times-square/Chart.yaml

This fixes dynamic default syntax for relative numbers of
weeks/months/years. E.g. +1w, -2m, +5y.
https://github.com/lsst-sqre/times-square/releases/tag/0.21.1

DM-51083: Update Times Square to 0.21.1

---

applications/qserv-kafka/Chart.yaml
applications/qserv-kafka/README.md
applications/qserv-kafka/templates/configmap.yaml
applications/qserv-kafka/values-idfdev.yaml
applications/qserv-kafka/values.yaml

Add one new configuration option, update to 0.5.0, and run the release version on idfdev.

DM-51121: Update the Qserv Kafka bridge to 0.5.0

---

applications/sasquatch/charts/telegraf/templates/_helpers.tpl
applications/sasquatch/charts/telegraf/templates/configmap.yaml
applications/sasquatch/values-usdfprod.yaml

Point Telegraf connectors to a registry deployed on USDF int temporarily where the [actual solution](https://rubinobs.atlassian.net/browse/DM-51143) is being worked out.
Also split M1M3 into M1M3 for the support system and M1M3TS for the thermal system at USDF following the same configuration as the Summit.

[DM-51206] Sasquatch USDF emergential fix for M1M3 replication

---

applications/atlantis/README.md
applications/atlantis/values-roundtable-dev.yaml
applications/atlantis/values.yaml
environments/values-roundtable-dev.yaml

DM-51209: atlantis - disable in roundtable-dev
The GitHub atlantis app must be installed in at least on repo for
atlantis to start. Since the roundtable-prod Atlantis is now serving the
one repo we use Atlantis for (prodromos), there are no repos we can
attach the dev Atlantis app to, so let's disable the dev Atlantis
instance.
* Disable `atlantis` in roundtable-dev
* Get rid of vestigial Helm value

DM-51209: atlantis - allowedRepos is a comma-separated string

---

applications/atlantis/secrets.yaml
applications/atlantis/templates/statefulset.yaml

Add a `google-cloud-monitoring-slack-token` secret, which is a Slack Bot OAuth token to inject into Google Cloud Monitoring Terraform config. This token will be provisioned in Google Cloud Monitoring Notification Channel resources and will be used by Google Cloud to auth to Slack to post notifications from Google Cloud Monitoring alerts.

DM-50932: Support for Atlantis Google Cloud Monitoring provisioning

---

applications/google-cloud-observability/.helmignore
applications/google-cloud-observability/Chart.yaml
applications/google-cloud-observability/README.md
applications/google-cloud-observability/templates/_helpers.tpl
applications/google-cloud-observability/templates/cluster-pod-monitoring.yaml
applications/google-cloud-observability/values.yaml
docs/applications/google-cloud-observability/index.rst
docs/applications/google-cloud-observability/values.md
docs/applications/monitoring.rst
environments/README.md
environments/templates/applications/monitoring/google-cloud-observability.yaml
environments/values-idfdev.yaml
environments/values-idfint.yaml
environments/values-idfprod.yaml
environments/values-roundtable-dev.yaml
environments/values-roundtable-prod.yaml
environments/values.yaml

Google provides a [managed service for Prometheus](https://cloud.google.com/stackdriver/docs/managed-prometheus).
In Phalanx environments provisioned on [GKE](https://cloud.google.com/kubernetes-engine), we'd like to use this for as much as we can to avoid the effort of running our own metrics and monitoring infrastructure.
Unfortunately, the [managed kube-state-metrics](https://cloud.google.com/kubernetes-engine/docs/how-to/kube-state-metrics) package does not provide `kube_pod_container_status_last_terminated_reason` or `kube_pod_container_status_restarts_total`, both of which are needed to alert on container OOM kills in the most reliable way.
This app installs our own [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics)`_ and configures the Google Cloud managed …

DM-50932: Google Cloud Monitoring

---

applications/sasquatch/README.md
applications/sasquatch/charts/telegraf/README.md
applications/sasquatch/charts/telegraf/values.yaml

Missing default value for the Telegraf registry URL in chart configuration.

Add default value for the Telegraf registry URL

---

applications/times-square/Chart.yaml
applications/times-square/values.yaml

This version features scheduled runs of notebooks.
https://github.com/lsst-sqre/times-square/pull/108

DM-51103: Update Times Square to 0.22.0

---

applications/butler/templates/configmap-private.yaml

Switch the DP1 Butler to an updated data release that includes difference images and a few calibration dataset types that were omitted in error.

DM-51058: Switch DP1 Butler to new data release

---

applications/prompt-keda-hsc/README.md
applications/prompt-keda-hsc/values.yaml
applications/prompt-keda-latiss/README.md
applications/prompt-keda-latiss/values-usdfdev-prompt-processing.yaml
applications/prompt-keda-latiss/values.yaml
applications/prompt-keda-lsstcam/README.md
applications/prompt-keda-lsstcam/values-usdfdev-prompt-processing.yaml
applications/prompt-keda-lsstcam/values.yaml
applications/prompt-keda-lsstcamimsim/README.md
applications/prompt-keda-lsstcamimsim/values.yaml
applications/prompt-keda-lsstcomcam/README.md
applications/prompt-keda-lsstcomcam/values.yaml
applications/prompt-keda-lsstcomcamsim/README.md
applications/prompt-keda-lsstcomcamsim/values.yaml
charts/prompt-keda/README.md
charts/prompt-keda/templates/_service-init.tpl
charts/prompt-keda/templates/scaled-job.yaml
charts/prompt-keda/values.yaml

This PR adds config settings for retries to both the Prompt Processing service and its init job.

DM-41738: Make Prompt Processing more robust to Butler connection failures

---

applications/semaphore/values.yaml

In scale testing with 10,000 users, we found that the memory use can increase to 200MB. This extra head room should give us lots of margin.
The request is also increased slightly to better match baseline usage after heavy loads.

DM-51295: Increase memory request and limit for Semaphore

---

applications/sasquatch/values-idfdev.yaml
applications/sasquatch/values-idfint.yaml
applications/sasquatch/values-idfprod.yaml
applications/sasquatch/values-roundtable-dev.yaml
applications/sasquatch/values-roundtable-prod.yaml
applications/sasquatch/values-usdfdev.yaml
applications/sasquatch/values-usdfint.yaml
applications/sasquatch/values-usdfprod.yaml

Strimzi 0.46.0 drops support to Kafka < 3.9.0 move Kafka to version 3.9.0 first.
Since Telescope environments will upgrade Kafka later, we are upgrading Kafka on IDF and USDF environments only and the Strimzi upgrade is temporarily on [this branch](https://github.com/lsst-sqre/phalanx/pull/4648)

[DM-51317] Upgrade Kafka to version 3.9.0 on IDF and USDF environments 

---

applications/butler/Chart.yaml

Update Butler server to add a new `file_transfer` endpoint used by `transfer_from`.

DM-51075: Update Butler server for transfer_from

---

applications/consdb/values-base.yaml
applications/consdb/values-summit.yaml
applications/consdb/values-tucson-teststand.yaml
applications/consdbtap/values-usdfdev.yaml
applications/consdbtap/values-usdfint.yaml
applications/consdbtap/values-usdfprod.yaml

* Updates hinfo in BTS, TTS, and summit
* Updates consdb tap to use ticket branch

DM-51220: Update consdb to add can_see_sky and zernike coefficients

---

applications/vo-cutouts/values.yaml

We were seeing OOM kill problems on idfint.

Bump limits and requests for cutout workers

---

applications/qserv-kafka/Chart.yaml
applications/qserv-kafka/README.md
applications/qserv-kafka/templates/configmap.yaml
applications/qserv-kafka/values-idfdev.yaml
applications/qserv-kafka/values-idfint.yaml
applications/qserv-kafka/values.yaml

Add the new configuration option to disable sending API versions to the Qserv REST API, and enable it for idfdev and idfint.

DM-51358: Update Qserv Kafka bridge to 0.6.0

---

applications/butler/Chart.yaml
applications/butler/templates/configmap-private.yaml

Point the IDF Butler server at a new release of DP1, and update the Butler server to include a new file transfer feature being released in v29.1

DM-51298: Update Butler server for updated release

---

applications/sasquatch/charts/strimzi-kafka/templates/kafka.yaml
applications/sasquatch/charts/strimzi-kafka/templates/mirrormaker2.yaml
applications/sasquatch/values-usdfprod.yaml

When there's network performance degradation between Summit-USDF we typically see timeouts in MM2 and the replication tasks handling more data are the ones that fall behind. 
Even with 128 MM2 tasks we still have 37 topic-partitions per task and we can't control which topic-partitions are assigned to each task. So for example, a high throughput topic-partition like `lsst.sal.MTHexapod.application-0` can be assigned to the same MM2 task along with other high throughput topics.  
Even if this works in normal conditions, with the usual throughput when all topics are synced, this imbalance in MM2 makes some tasks to progress too slowly when there's a back log to replicate.
To fix the imbalance in the distribution of topic-partitions to MM2 tasks the ultimate solution is to add more partitions …

[DM-51366] Investigate replication lag in MM2 at USDF

---

applications/hips/Chart.yaml
applications/hips/README.md
applications/hips/values-idfdev.yaml
applications/hips/values-idfint.yaml
applications/hips/values-idfprod.yaml
applications/hips/values.yaml

~After modifying [DMTN-230](https://dmtn-230.lsst.io), I realized I used "data set" when I should have been using "release" :cry:~
And after talking to @rra, I changed the terminology to not have anything to do with HiPS at all :)
Goes with ~https://github.com/lsst-sqre/crawlspace/pull/94~ https://github.com/lsst-sqre/crawlspace/pull/95
```
curl --fail-with-body -H "Authorization: Bearer $MY_TOKEN" https://data-dev.lsst.cloud/api/hips/images/2MASS/Color/Moc.fits && \
curl --fail-with-body --head -H "Authorization: Bearer $MY_TOKEN" https://data-dev.lsst.cloud/api/hips/images/2MASS/Color/Moc.fits && \
curl --fail-with-body -H "Authorization: Bearer $MY_TOKEN" https://data-dev.lsst.cloud/api/hips/v2/dp02/images/2MASS/Color/Moc.fits && \
curl --head --fail-with-body -H "Authorization: Bearer …
```

DM-51236: hips - update terminology

---

applications/nublado/Chart.yaml
applications/nublado/README.md
applications/nublado/values-base.yaml
applications/nublado/values-idfdemo.yaml
applications/nublado/values-idfdev.yaml
applications/nublado/values-idfint.yaml
applications/nublado/values-idfprod.yaml
applications/nublado/values-summit.yaml
applications/nublado/values-tucson-teststand.yaml
applications/nublado/values-ukidacdev.yaml
applications/nublado/values-ukidacprod.yaml
applications/nublado/values.yaml

Update Nublado to 8.8.8 and the Zero to JupyterHub chart to 4.2.0. Fix the version numbers for the init containers to match the correct release version.

DM-51427: Update Nublado to 8.8.8

---

applications/butler/templates/configmap-private.yaml

Update the DP1 Butler release to remove the original "broken" version of the datasets fixed in DM-51335

DM-51372: Update DP1 Butler data

---

applications/vo-cutouts/Chart.yaml

Updates the backend worker to use the latest stack container.

DM-51420: Update vo-cutouts to 4.1.1

---

applications/prompt-keda-hsc/README.md
applications/prompt-keda-hsc/values.yaml
applications/prompt-keda-latiss/README.md
applications/prompt-keda-latiss/values.yaml
applications/prompt-keda-lsstcam/README.md
applications/prompt-keda-lsstcam/values.yaml
applications/prompt-keda-lsstcamimsim/README.md
applications/prompt-keda-lsstcamimsim/values.yaml
applications/prompt-keda-lsstcomcam/README.md
applications/prompt-keda-lsstcomcam/values.yaml
applications/prompt-keda-lsstcomcamsim/README.md
applications/prompt-keda-lsstcomcamsim/values.yaml
charts/prompt-keda/README.md
charts/prompt-keda/templates/scaled-job.yaml
charts/prompt-keda/values.yaml

This PR adds a config hook for Redis retries and makes documentation for Redis settings visible in the readmes.

DM-51389: Expand use of retry in Prompt Processing

---

applications/argocd/values-idfdemo.yaml
applications/argocd/values-idfdev.yaml
applications/argocd/values-idfint.yaml
applications/argocd/values-idfprod.yaml
applications/argocd/values-tacc-spherex.yaml
applications/argocd/values-usdfdev.yaml
applications/argocd/values-usdfint.yaml
applications/argocd/values-usdfprod.yaml

There now needs to be an explicit wildcard allow rule for logs for developers or they would only be able to see the logs for infrastructure applications.

Fix Argo CD RBAC rules

---

applications/datalinker/Chart.yaml
applications/datalinker/README.md
applications/datalinker/templates/configmap.yaml
applications/datalinker/templates/deployment.yaml
applications/datalinker/templates/ingress-anonymous.yaml
applications/datalinker/values-idfdev.yaml
applications/datalinker/values-idfint.yaml
applications/datalinker/values.yaml

- Enable new helm chart properties to allow datalinker to handle multiple hips lists
- Move datalinker ENV variables to configmap to handle more complex structure
- Update datalinker ingress to handle new /v2 path
**Before merging**: switch datalinker image back to for idfdev & upgrade app version

DM-51412:  Add support for returning hips lists for multiple data releases

---

applications/tap/values-idfdev.yaml
applications/tap/values-idfint.yaml
applications/tap/values-idfprod.yaml
charts/cadc-tap/README.md
charts/cadc-tap/templates/configmap.yaml
charts/cadc-tap/templates/tap-deployment.yaml
charts/cadc-tap/values.yaml

Upgrades TAP service to **3.1.0** which includes:
- DM-51382 Make URL Rewriting optional, read urlRewriteRules from env by @stvoutsin in https://github.com/lsst-sqre/lsst-tap-service/pull/149
- Read URL_REWRITE_RULES from env and use to determine whether a table-column needs to be formatted/rewritten.
- Fix some formatting issues
- Reduce logging
- Remove upstream patch classes
- Upgrade uws uws-server and cadc-rest libraries
Changes in TAP service chart configuration to allow defining list of schema.table:columns to rewrite

DM-51382: Allow multiple rewrite rules for TAP service

---

applications/butler/README.md
applications/butler/values-idfprod.yaml
applications/butler/values.yaml

Switch the dp02 Butler database in idfprod to use AlloyDB, matching idfint and the dp1 deployment.  This will help ensure the Butler server can scale its load in case there is an increased interest in the DP02-based tutorials after the DP1 release.  It will also reduce the number of different databases/database technologies deployed for Butler.

DM-51471: Switch idfprod dp02 Butler to AlloyDB

---

applications/tap/values-idfdev.yaml
applications/tap/values-idfint.yaml
applications/tap/values-idfprod.yaml

Fixes the following issues:
- Bug where any binary2 table upload appeared as an empty table
- Logging issues when sentry was not enabled
- Show correct upload size limit

DM-51463: Upgrade TAP to version 3.2.0

---

applications/sasquatch/README.md
applications/sasquatch/charts/influxdb-enterprise/README.md
applications/sasquatch/charts/influxdb-enterprise/values.yaml
applications/sasquatch/charts/kafdrop/values.yaml
applications/sasquatch/charts/rest-proxy/values.yaml
applications/sasquatch/charts/strimzi-kafka/README.md
applications/sasquatch/charts/strimzi-kafka/values.yaml
applications/sasquatch/values-base.yaml
applications/sasquatch/values-idfdev.yaml
applications/sasquatch/values-idfint.yaml
applications/sasquatch/values-idfprod.yaml
applications/sasquatch/values-roundtable-dev.yaml
applications/sasquatch/values-roundtable-prod.yaml
applications/sasquatch/values-summit.yaml
applications/sasquatch/values-tucson-teststand.yaml
applications/sasquatch/values-usdfdev.yaml
applications/sasquatch/values-usdfint.yaml
applications/sasquatch/values-usdfprod.yaml
applications/sasquatch/values.yaml

We review Sasquatch resources requests and limits based on data from Grafana  (Kubernetes / Compute Resources / Pod) for the Summit environment. The general idea is to set more reasonable defaults that are suitable for most environments and then overwrite prod environments accordingly.

[DM-51457] Review Sasquatch resources requests and limits and set more reasonable defaults

---

applications/qserv-kafka/Chart.yaml
applications/qserv-kafka/README.md
applications/qserv-kafka/templates/configmap.yaml
applications/qserv-kafka/values.yaml

Add configuration parameters for the retry count and delay after Qserv API network failures.

DM-51450: Update to Qserv Kafka bridge 1.0.0

---

applications/sasquatch/charts/backup/values.yaml

The sasquatch backup Job fails intermittently and eventually hits the backoffLimit and k8s gives up retrying.
Since the backup script uses set -e, any command that exits with a non-zero status will immediately terminate the script, causing the container to exit with failure triggering the Kubernetes retries.
This version removes `set -e` and improve error handling to help identify in which step the backup script is failing.

[DM-51517] Update sasquatch backup to version 1.3.1

---

applications/vo-cutouts/templates/ingress.yaml

Similar to datalinker, advertise HTTP Basic Auth so that TOPCAT will work correctly, since it thinks it doesn't support bearer token authentication.

Advertise HTTP Basic Auth for vo-cutouts

---

applications/portal/Chart.yaml
applications/portal/templates/statefulset.yaml
applications/portal/values-idfdev.yaml
applications/portal/values-idfint.yaml
applications/portal/values-idfprod.yaml

- tags:
- appVersion: "portal-2025.3.0-build2"
- firefly: release-3.4
- portal: portal-2025.3.0
- clean and fixed statefulset.yaml for ops
- update uws.history.svcs
- expose showDatalinkTable
- Add global override of base HiPS map for data-int
- Hard-code base URL - no templates in values files
- Queue DP1 HiPS background for dev and prod as well
- Switch default DP1 HiPs coverage map to r band
- We now have single-channel HiPS for DP1.  Frossie made an executive decision to switch to the r band for the default coverage map.  The r band is better than the colors we were using before, because it has fewer edge artifacts and is less confusing as a background for other things.

portal for ops DP1

---

applications/mobu/values-idfdev.yaml
applications/mobu/values-idfint.yaml
applications/mobu/values-idfprod.yaml

I think this should change `TAPQuerySetRunner` to use async. 
Targeting `idfdev` initially, if this works I think we should make this change on the other IDF environments as well now that we've changed TAP to have a 1 minute timeout for sync queries.

DM-51592: Change TAPQuerySetRunner to use async in mobu for idfdev

---

applications/qserv-kafka/Chart.yaml

This release fixes a bug in the query timings reported back to the TAP server.

DM-51594: Update Qserv Kafka bridge to 1.0.1

---

applications/vo-cutouts/templates/db-worker-deployment.yaml
applications/vo-cutouts/templates/worker-deployment.yaml
starters/fastapi-safir-uws/templates/db-worker-deployment.yaml
starters/fastapi-safir-uws/templates/worker-deployment.yaml

In the UWS starter pattern and in vo-cutouts, include the chart name as a prefix of the container name for the worker and database worker. This makes reading logs in Google Log Explorer easier since they're prefixed with the container name in isolation without the pod name or namespace.

Include chart name in container names

---

applications/argocd/values-ukidacprod.yaml
applications/cert-manager/values-ukidacprod.yaml
applications/ingress-nginx/values-ukidacprod.yaml

Update the ukidacprod environment to use Let's Encrypt DNS and Route53 for TLS instead of using an external certificate.
Changes should be identical to commit 138db33 but for the ukidacprod environment.

Switch ukidacprod cert-manager to route53

---

applications/nublado/Chart.yaml
applications/nublado/README.md
applications/nublado/values-base.yaml
applications/nublado/values-idfdemo.yaml
applications/nublado/values-idfdev.yaml
applications/nublado/values-idfint.yaml
applications/nublado/values-idfprod.yaml
applications/nublado/values-summit.yaml
applications/nublado/values-tucson-teststand.yaml
applications/nublado/values-ukidacdev.yaml
applications/nublado/values-ukidacprod.yaml
applications/nublado/values.yaml

Fixes handling of groups starting with a number, such as user-private groups for usernames starting with a number.

DM-51686: Update Nublado to 8.9.2

---

applications/mobu/Chart.yaml
applications/mobu/values-idfdev.yaml

Butler in idfdev is starting to use groups to restrict access to particular data sets. Upgrade mobu to a version that supports adding groups to user tokens and add the `g_users` group to the tutorial and sia monkey users.

DM-51647: Upgrade mobu, add g_users to idfdev monkeys

---

docs/admin/application-branch.rst
docs/admin/index.rst

Document how to configure Phalanx to run a given application from a branch in a particular environment, and add a caution against using this feature.

DM-51704: Add documentation for running from a branch

---

environments/templates/applications/monitoring/flink.yaml

Configure Argo CD to ignore the priority field in the Flink CRDs, since it's not present upstream but is added automatically by Kubernetes, resulting in spurious differences.

Ignore spurious Flink differences

---

applications/portal/README.md
applications/portal/templates/alert-configmap.yaml
applications/portal/templates/statefulset.yaml
applications/portal/values-idfdev.yaml
applications/portal/values.yaml

Mount a `ConfigMap` in the Portal so that we can drop alerts into the place where Firefly looks for them. The outage banner can be added and removed by changing `values-<env>.yaml` to add or remove `config.alertMessage` and syncing the Portal. Syncing should not restart the Portal if all you changed is the `ConfigMap`.

Add alert message support for the Portal

---

applications/sasquatch/secrets.yaml

The data-transfer-monitoring subchart is enabled at both Summit and USDF and create the data-transfer-monitoring KafkaUser.

[DM-51746] Add secret for data-transfer-monitoring KafkaUser

---

applications/sasquatch/values-summit.yaml

We are replacing the standby InfluxDB OSS by InfluxDB Enterprise at the Summit

[DM-49517] Setup a standby InfluxDB Enterprise instance at the Summit

---

applications/sasquatch/charts/strimzi-kafka/templates/kafka.yaml

We use the following annotations in the Strimzi PVCs
`argocd.argoproj.io/compare-options: IgnoreExtraneous` 
`argocd.argoproj.io/sync-options: Prune=false`
to prevent the parent app (Sasquatch in this case) to show as `OutOfSync` and  to prevent the PVCs from being deleted from the ArgoCD UI.
With KRaft, Strimzi introduced the `KafkaNodePool` resource and these annotations previously in `kafka.spec.template. persistentVolumeClaim` need to be moved under `kafkaNodePool.spec.template.persistentVolumeClaim` for both the controller and broker node pools.

[DM-42378] ArgoCD does not recognize Strimzi PVCs

---

applications/prompt-keda-hsc/README.md
applications/prompt-keda-hsc/values.yaml
applications/prompt-keda-latiss/README.md
applications/prompt-keda-latiss/values.yaml
applications/prompt-keda-lsstcam/README.md
applications/prompt-keda-lsstcam/values-usdfprod-prompt-processing.yaml
applications/prompt-keda-lsstcam/values.yaml
applications/prompt-keda-lsstcamimsim/README.md
applications/prompt-keda-lsstcamimsim/values.yaml
applications/prompt-keda-lsstcomcam/README.md
applications/prompt-keda-lsstcomcam/values.yaml
applications/prompt-keda-lsstcomcamsim/README.md
applications/prompt-keda-lsstcomcamsim/values.yaml
charts/prompt-keda/README.md
charts/prompt-keda/templates/scaled-job.yaml
charts/prompt-keda/values.yaml

This PR adds a `dax_apdb` metrics configuration flag to Prompt Processing, and turns it on for the production instance.

DM-51768: Support dax_apdb metrics in Prompt Processing

---

charts/cadc-tap/README.md
charts/cadc-tap/values.yaml

This PR upgrades the QServ TAP service to version 3.4.3 which addresses the issue where users with dashes in their usernames could not run table upload queries.

DM-51808: Upgrade TAP service to 3.4.3 to address issue with user database names with dashes

---

applications/wobbly/templates/deployment.yaml

We need this because it takes ingress-nginx some time to configure itself to stop sending traffic to the pods scheduled for termination. If Uvicorn gets the SIGTERM and starts closing connections, we could end up with a TCP race condition if ingress-nginx still tries to send data over those connections, which would result in the client getting 502 responses.
Before and after the fix:

DM-51817: wobbly - graceful shutdown

---

applications/prompt-keda-hsc/README.md
applications/prompt-keda-hsc/values-usdfdev-prompt-processing.yaml
applications/prompt-keda-hsc/values.yaml
applications/prompt-keda-latiss/README.md
applications/prompt-keda-latiss/values-usdfdev-prompt-processing.yaml
applications/prompt-keda-latiss/values.yaml
applications/prompt-keda-lsstcam/README.md
applications/prompt-keda-lsstcam/values-usdfdev-prompt-processing.yaml
applications/prompt-keda-lsstcam/values-usdfprod-prompt-processing.yaml
applications/prompt-keda-lsstcam/values.yaml
applications/prompt-keda-lsstcamimsim/README.md
applications/prompt-keda-lsstcamimsim/values-usdfdev-prompt-processing.yaml
applications/prompt-keda-lsstcamimsim/values.yaml
applications/prompt-keda-lsstcomcam/README.md
applications/prompt-keda-lsstcomcam/values-usdfdev-prompt-processing.yaml
applications/prompt-keda-lsstcomcam/values.yaml
applications/prompt-keda-lsstcomcamsim/README.md
applications/prompt-keda-lsstcomcamsim/values-usdfdev-prompt-processing.yaml
applications/prompt-keda-lsstcomcamsim/values.yaml
charts/prompt-keda/README.md
charts/prompt-keda/templates/_service-init.tpl
charts/prompt-keda/templates/scaled-job.yaml
charts/prompt-keda/values.yaml

This PR configures manual IERS downloads from a USDF-local cache. This is much faster than downloading directly from the public services.

DM-50087: Preload IERS data in Prompt Processing

---

applications/gafaelfawr/values-idfprod.yaml

We want to use `exec:internal-tools` for Chronograf and related services. Grant that scope on idfprod to `g_rubin`.

Add exec:internal-tools scope to idfprod

---

applications/nublado/README.md
applications/nublado/values.yaml

There were two copies of the resources stanza, one of which was not used.

DM-51899: Fix resources for Nublado Cloud SQL Proxy

---

applications/gafaelfawr/values-idfprod.yaml

The new version of Gafaelfawr expresses API quotas per minute instead of per fifteen minutes. Adjust the API quotas for idfprod accordingly.

Adjust idfprod quotas

---

applications/nublado/README.md
applications/nublado/values.yaml

Make it longer than `ingress-nginx`'s to avoid a TCP race condition that results in intermittent "connection reset by peer" errors from `ingress-nginx`

DM-51817: nublado - bump proxy keep-alive timeout

---

charts/prompt-keda/templates/_service-init.tpl
charts/prompt-keda/templates/scaled-job.yaml

This PR fixes a bug introduced in #5162 where the init job used `SATTLE_URI_BASE` but the main service did not.

DM-50987: Fix inconsistent use of SATTLE_URI_BASE in Prompt Processing

---

applications/squareone/values-idfint.yaml
applications/squareone/values.yaml

DP0 used different categories and GitHub issues for support. This updates the /support page to point to Community forum categories. Not eprfect, but more useful at this moment.

Add link to community forum for support

---

applications/qserv-kafka/Chart.yaml

Includes support for `unicodeChar` and a partial fix for a memory leak.

DM-51603: Bump Qserv Kafka bridge to 1.2.0

---

applications/consdbtap/values-usdfdev.yaml
applications/consdbtap/values-usdfint.yaml
applications/consdbtap/values-usdfprod.yaml

This adds the ConsDB Transformed EFD schemas so they are accessible via the TAP interface.

Update all consdbtap environments to sdm_schemas w.2025.31

---

applications/prompt-keda-hsc/README.md
applications/prompt-keda-hsc/values.yaml
applications/prompt-keda-latiss/README.md
applications/prompt-keda-latiss/values.yaml
applications/prompt-keda-lsstcam/README.md
applications/prompt-keda-lsstcam/values.yaml
charts/prompt-keda/README.md
charts/prompt-keda/templates/scaled-job.yaml
charts/prompt-keda/values.yaml

This PR removes Prompt Processing cache settings associated with spatial datasets, which we will not try to cache in the future.

DM-51735: Stop caching spatial datasets in Prompt Processing

---

applications/vault/Chart.yaml

This reverts commit d1e67700cd0b41e569d15959ffdbddf1a0527498. This release has a serious bug with GCS storage.

Revert "Update Helm release vault to v0.30.1"

---

charts/cadc-tap/README.md
charts/cadc-tap/values.yaml

Changes to TAP service include:
- DM-51834: Add support for unicodeChar for uploaded tables by @stvoutsin in https://github.com/lsst-sqre/lsst-tap-service/pull/164
- DM-52011: Upgrade cadc-gms library to 1.0.17 by @stvoutsin in https://github.com/lsst-sqre/lsst-tap-service/pull/165
- DM-51730: Enable setting the availability via a system property by @stvoutsin in https://github.com/lsst-sqre/lsst-tap-service/pull/158
- DM-51595: Use jobPersist instead of jobUpdater.setPhase to update job by @stvoutsin in https://github.com/lsst-sqre/lsst-tap-service/pull/153

DM-52011: Upgrade QServ TAP service to version 3.5.0

---

charts/cadc-tap/README.md
charts/cadc-tap/values.yaml

This PR upgrades the QServ TAP service to version 3.6.0 which includes a fix to create a temporary database for each upload job, using the UWS job id as a suffix in the database name.
_This should be deployed at the same time as qservkafka 1.3.0
Otherwise we will end-up with temporary databases in QServ that will not be deleted._

DM-52016: Upgrade QServ TAP service to version 3.6.0

---

applications/gafaelfawr/values-base.yaml
applications/gafaelfawr/values-ccin2p3.yaml
applications/gafaelfawr/values-idfdev.yaml
applications/gafaelfawr/values-idfint.yaml
applications/gafaelfawr/values-idfprod.yaml
applications/gafaelfawr/values-summit.yaml
applications/gafaelfawr/values-tacc-spherex.yaml
applications/gafaelfawr/values-tucson-teststand.yaml
applications/gafaelfawr/values-ukidacdev.yaml
applications/gafaelfawr/values-ukidacprod.yaml
applications/gafaelfawr/values-usdfdev.yaml
applications/gafaelfawr/values-usdfint.yaml
applications/gafaelfawr/values-usdfprod.yaml
applications/gafaelfawr/values.yaml
applications/portal/templates/ingress-admin.yaml
docs/applications/gafaelfawr/add-scope.rst
docs/applications/gafaelfawr/github-organizations.rst
docs/applications/gafaelfawr/index.rst
docs/applications/gafaelfawr/recreate-token.rst
docs/applications/gafaelfawr/troubleshoot.rst

Add a new `exec:portal-admin` scope that controls read access to the Portal admin page so that we can grant access to Portal administrators without giving them `exec:admin`.
Document how to add a new Gafaelfawr scope and make some minor edits to the other Gafaelfawr documentation.

DM-52103: Add new Gafaelfawr scope for Portal admin page

---

applications/gafaelfawr/values-idfdev.yaml
applications/gafaelfawr/values-idfint.yaml
applications/gafaelfawr/values-idfprod.yaml

On idfdev and idfint, add `g_admins` to the list of groups that get `exec:portal-admin` scope.

DM-52103: Add g_admins to exec:portal-admin scope

---

applications/squareone/Chart.yaml

https://github.com/lsst-sqre/squareone/releases/tag/squareone%400.22.0

DM-52127: Update squareone to 0.22.0

---

applications/gafaelfawr/Chart.yaml

Fixes a group name validation regression that broke TACC.

DM-52140: Bump Gafaelfawr to 14.0.1

---

applications/squareone/Chart.yaml

This was the migration to Next 13. We're going to hold off on deploying the modernized Squareone to production until we're further along and have done more testing.

Rollback Squareone to 0.22.0

---

applications/livetap/values.yaml

The database hostname is desirable, but this causes mismatches with the database credentials file, so we are reverting the hostname change.
This reverts commit 94b39243c3b388ce04940a9c8f0728c569821e46, reversing changes made to fa7f89f4f3a396605d128ee20282323a3807cc2d.

DM-52257 (hotfix): Revert "Merge pull request #5269"

---

applications/squareone/Chart.yaml

The Next production build broke with the React/Next.js upgrades.

Rollbackk to 0.21.0

---

applications/qserv-kafka/Chart.yaml

This version sends the collation name on table upload, which is a new parameter with the new release of Qserv and is now effectively required if a UTF-8 character set is used. It also switches the character set to support the full UTF-8 range.

DM-52277: Bump Qserv Kafka bridge to 3.0.0

---

applications/vo-cutouts/Chart.yaml

Uses the new Science Pipelines release in the worker backend, which should hopefully fix a memory leak.

DM-52310: Upgrade vo-cutouts to 4.1.3

---

applications/vo-cutouts/templates/deployment.yaml
starters/fastapi-safir-uws/templates/deployment.yaml
starters/fastapi-safir/templates/deployment.yaml

Add the uvicorn keep-alive configuration and the pre-stop wait for vo-cutouts to avoid various issues with ingress-nginx. Alphabetize the settings in the starter templates.

DM-52310: Add uvicorn settings for vo-cutouts

---

applications/qserv-kafka/Chart.yaml
applications/qserv-kafka/README.md
applications/qserv-kafka/templates/configmap.yaml
applications/qserv-kafka/values-idfdev.yaml
applications/qserv-kafka/values.yaml

Parallelize query processing to make better use of the CPU of the frontend under heavy query load.

DM-52282: Upgrade Qserv Kafka bridge to 3.0.1

---

applications/sasquatch/README.md
applications/sasquatch/charts/strimzi-kafka/README.md
applications/sasquatch/charts/strimzi-kafka/templates/kafka.yaml
applications/sasquatch/charts/strimzi-kafka/values.yaml
applications/sasquatch/values-base.yaml
applications/sasquatch/values-idfdev.yaml
applications/sasquatch/values-summit.yaml

Add the  `k8up.io/backup-target: true` label to Sasquatch Kafka PVCs, this needs to be done via the `KafkaNodePool` template, so the labels are added by the Strimzi operator to the corresponding PVCs. 
This is enable at summit and base environments only, where we run k8up backup tool.

[DM-52379] Add k8sup labels to backup Sasquatch kafka PVCs

---

applications/repertoire/values-idfdev.yaml
environments/values-minikube.yaml

Add Repertoire to Minikube for additional testing. Remove the image override now that there is a 0.1.0 release.

DM-52228: Enable Repertoire for minikube, update for release

---

applications/fov-quicklook/.helmignore
applications/fov-quicklook/Chart.yaml
applications/fov-quicklook/README.md
applications/fov-quicklook/secrets.yaml
applications/fov-quicklook/templates/_helpers.tpl
applications/fov-quicklook/templates/butler-config.yaml
applications/fov-quicklook/templates/coordinator.yaml
applications/fov-quicklook/templates/db.yaml
applications/fov-quicklook/templates/debug.yaml
applications/fov-quicklook/templates/frontend.yaml
applications/fov-quicklook/templates/generator.yaml
applications/fov-quicklook/templates/vault-secrets.yaml
applications/fov-quicklook/values-usdfdev.yaml
applications/fov-quicklook/values.schema.json
applications/fov-quicklook/values.yaml
docs/applications/fov-quicklook/index.rst
docs/applications/fov-quicklook/values.md
docs/applications/rsp.rst
environments/README.md
environments/templates/applications/rsp/fov-quicklook.yaml
environments/values-usdfdev.yaml
environments/values.yaml

These changes are for the in-kind contribution JAP-JPG-S3.
I'm discussing the following points with @ktlim :
* The tile generator should be a `deployment` instead of `daemonset`
* Postgres password should be managed within the phalanx secret framework.

Changes for in-kind contribution `JAP-JPG-S3` from NAOJ

---

charts/cadc-tap/README.md
charts/cadc-tap/values.yaml

Currenly after updating `usdf-rsp-dev` to the bridge and changing the result URL generation to be consistent between S3 and GCS, we get an incorrect URL for TAP_SCHEMA queries:
`https://usdf-rsp-dev.slac.stanford.edu/api/tap/results//rubin:rubin-qserv/result_....xml`
This changes this to be consistent with GCS and only include the filename (not the bucket) in this internal result URL, as the bucket gets appended in the `ResultServlet`.

DM-52437: Upgrade cadc-tap chart to use upgraded version to fix issue with TAP_SCHEMA query result URLs

---

applications/gafaelfawr/templates/deployment.yaml
applications/gafaelfawr/values-idfdev.yaml
applications/gafaelfawr/values.yaml
applications/repertoire/Chart.yaml
applications/repertoire/README.md
applications/repertoire/secrets-idfdev.yaml
applications/repertoire/templates/deployment.yaml
applications/repertoire/templates/ingress-influxdb.yaml
applications/repertoire/templates/vault-secrets.yaml
applications/repertoire/values-idfdev.yaml
applications/repertoire/values.yaml

Add a new scope, `read:sasquatch`, that controls the top-level ability to retrieve any InfluxDB connection information with credentials. More fine-grained access control in the future will probably use groups.
Update Repertoire to 0.2.0 and add idfdev InfluxDB configuration information and a secret for the `idfdev_efd` Sasquatch InfluxDB database. Add an authenticated ingress for retrieving InfluxDB connection information with credentials.

DM-52453: Add InfluxDB support to Repertoire

---

applications/sasquatch/charts/backup/templates/backup-cronjob.yaml
applications/sasquatch/charts/backup/templates/backup-pvc.yaml
applications/sasquatch/charts/backup/templates/restore-deployment.yaml

Old versions of vcluster add the `vcluster.loft.sh/fake-pv: "true"` label to PVs and this became  a problem for upgrading the vcluster.
This is affecting two Sasquatch PVs in `sasquatch-backup` at both usdf-rsp-dev and usdf-rsp.
To fix this, we’ll update sasquatch-backup to provision a PV with a different name, run the backup job and when backups are in place we can remove the old PVs.

Rename sasquatch-backup pvc

---

applications/sasquatch/charts/influxdb-enterprise/templates/data-statefulset.yaml
applications/sasquatch/values-usdfprod.yaml

Using the following limits to alleviate the query load on the standby InfluxDB instance at USDF
```
max-concurrent-queries: 150
query-timeout: "90s"
```
this helps up to certain point because the EFD transformation service is retrying killed queries. 
I have asked the users to pause their queries until we fix the compaction problems, otherwise this won't hold.

[DM-52494] Adjust query limits further in the Standby InfluxDB instance at USDF

---

applications/sasquatch/README.md
applications/sasquatch/charts/rest-proxy/README.md
applications/sasquatch/charts/rest-proxy/values.yaml

From the rest-rpxy logs, the Pods are running out of memory. I've increased the rest proxy JVM heap size and Pod memory resources.

Increase rest proxy JVM heap size and Pod memory resources

---

charts/prompt-keda/templates/scaled-job.yaml

This PR removes a test patch in the Prompt Processing Keda implementation that ended up becoming permanent. It should not be merged until all active Prompt Processing builds include lsst-dm/prompt_processing#349.

DM-52568: Remove Dockerfile override from Prompt Processing template.

---

applications/gafaelfawr/values-idfdev.yaml

In theory, the problem with test CILogon for that environment has been fixed.

Switch idfdev back to test CILogon

---

.github/workflows/ci.yaml
.github/workflows/rebasecheck.yaml

Don't run the minikube test if the head reference starts with dependabot, since GitHub dependabot doesn't have access to the repository secrets.

Skip minikube on dependabot changes

---

applications/gafaelfawr/values-base.yaml
applications/gafaelfawr/values-tucson-teststand.yaml

Add Gafaelfawr authorization rules for the `read:sasquatch` scope to base and tuscon-teststand. This scope will be used for Repertoire access.

DM-52623: Add read:sasquatch rules for base and TTS

---

applications/datalinker/Chart.yaml
applications/datalinker/README.md
applications/datalinker/templates/deployment.yaml
applications/datalinker/values.yaml
environments/templates/applications/rsp/datalinker.yaml

Add the Phalanx configuration required to enable Sentry support for datalinker. This is not tested since it's not clear that we want to use it, but at least the basics will be in place.

DM-52622: Add Sentry support for datalinker

---

applications/sia/Chart.yaml

Upgrades SIA to version 1.1.0
This includes upgrades to dax_obscore and fixes to SIA to enable data origin metadata in the query VOTable output.

DM-51656: Enable Data Origin metadata in SIA

---

applications/sasquatch/values-usdfdev.yaml

After upgrading Kafka Connect at USDF dev cluster to 3.9.0 it is failing to upload the lsst.dm connector with the error
```
appuser@sasquatch-influxdb-sink-lsstdm-dd74f8d4-cs98l:~$ kafkaconnect status influxdb-sink-lsstdm
{
"connector": {
"state": "FAILED",
"trace": "java.lang.IllegalArgumentException: Invalid syntax.failed to parse at line 1 due to extraneous input 'object' expecting SELECT\n\tat com.datamountaineer.kcql.Kcql.parse(Kcql.java:951)\n\tat com.datamountaineer.streamreactor.common.config.Helpers$.$anonfun$checkInputTopics$2(Helpers.scala:102)\n\tat scala.collection.ArrayOps$.map$extension(ArrayOps.scala:924)\n\tat com.datamountaineer.streamreactor.common.config.Helpers$.checkInputTopics(Helpers.scala:102)\n\tat com.datamountaineer.streamreactor.connect.influx.InfluxSinkConnect …
```

[DM-52656] Exclude topic lsst.dm.object from connector configuration

---

applications/sasquatch/charts/influxdb-enterprise/templates/data-pdb.yaml
applications/sasquatch/charts/influxdb-enterprise/templates/meta-pdb.yaml

We want both active and standby instances with min availability of 1 and  allowed disruptions of 0 to  block voluntary evictions (node drains). The PodDisruptionBudget was in place but there was a mismatch between Pod and PodDisruptionBudget labels.

[DM-52665] Fix PodDisruptionBudget for InfluxDB Enterprise

---

applications/nightlydigest/values-base.yaml
applications/nightlydigest/values-usdfdev.yaml

We have a new cycle build for T&S, and so we update the image tag to get the new image and its revisions.

Update nightly digest image tag to cycle 42

---

applications/sasquatch/README.md
applications/sasquatch/charts/strimzi-kafka/README.md
applications/sasquatch/charts/strimzi-kafka/values.yaml
applications/sasquatch/values-idfdev.yaml
applications/sasquatch/values-idfint.yaml
applications/sasquatch/values-idfprod.yaml
applications/sasquatch/values-roundtable-dev.yaml
applications/sasquatch/values-roundtable-prod.yaml
applications/sasquatch/values-summit.yaml
environments/values-usdfdev.yaml

We can run kafka 4.0.0 (Strimzi 0.47.0) in most of the Sasquatch environmets now so that can be set as the default.
Exceptions are:
- Summit that still requires Kafka 3.8.0 with Strimzi pinned to 0.45.0 (will move soon to Kafka 3.9.1 and Strimzi 0.47.0)
- BTS and TTS that require Kafka 3.9.1 with default Strimzi 0.47.0
- USDF environments are still on 3.9.0 waiting for testing MM2 with Kafka 4.0.0 before upgrading.

[DM-52710] Default Sasquatch to Kafka 4.0.0

---

applications/repertoire/Chart.yaml
applications/repertoire/README.md
applications/repertoire/templates/deployment.yaml
applications/repertoire/templates/kafka-access.yaml
applications/repertoire/values-idfdev.yaml
applications/repertoire/values-idfint.yaml
applications/repertoire/values-idfprod.yaml
applications/repertoire/values.yaml
applications/sasquatch/charts/app-metrics/values.yaml
applications/sasquatch/values-idfdev.yaml
applications/sasquatch/values-idfint.yaml
applications/sasquatch/values-idfprod.yaml

Update Repertoire to the 0.5.0 release and add support for publishing app metrics. Initially this will be used to record when people request credentials for an InfluxDB database.

DM-52751: Update Repertoire, add app metrics support

---

applications/repertoire/values.yaml

In the Repertoire configuration, add URLs for each dataset, required by Repertoire 0.5.0.

DM-52751: Add dataset documentation URLs

---

applications/ssotap/values-ukidacdev.yaml
applications/ssotap/values-ukidacprod.yaml
applications/tap/values-ukidacdev.yaml
applications/tap/values-ukidacprod.yaml

Tap scheme images are now (from Docker Hub):
- lsstuk/tap-schema-ukidacdev
- lsstuk/tap-schema-ukidacdev-sso
- lsstuk/tap-schema-ukidacprod
- lsstuk/tap-schema-ukidacprod-sso

Updating tap_schema image versions

---

applications/butler-writer-service/README.md
applications/butler-writer-service/templates/butler-writer-service.yaml
applications/butler-writer-service/values.yaml

This PR configures a single, global logging level for the Butler Writer service. The implementation of the logging level is in lsst-dm/prompt_processing_butler_writer#6.

DM-52580: Make the logging level for the Butler Writer Service configurable

---

applications/fov-quicklook/Chart.yaml
applications/fov-quicklook/README.md

The repository has been moved under lsst-sqre, so the older path is producing a permanent redirect.

Fix URL for fov-quicklook repository
