logging/fluentd-es-values.yaml
configMaps to extraConfigMaps.
=> [DM-21178] Updated values to respect new interface.

logging/fluentd-es-values.yaml
This has to be deployed when PDAC starts running new qserv version, coordination with qserv people is needed.
=> Update fluentd config for new qserv logging format

lsst-lsp-int/cadc-tap.yaml
Check in these values, which were used to deploy the lsst-lsp-int
TAP service.
=> [DM-22013] Commit lsst-lsp-int tap values

lsst-lsp-stable/cadc-tap.yaml
These are the helm values.yaml for the TAP chart for
stable.
=> [DM-22013] Add stable TAP values

lsst-lsp-int/nublado.yaml
These are the values that Adam and I have deployed on -int and are currently working.
=> [DM-22297] Working nublado -int values

lsst-lsp-int/portal.yaml
These are the values for the firefly helm chart to install the portal using the SUIT image on lsst-lsp-int.
=> [DM-22463] Portal values for -int

science-platform-int/templates/portal-application.yaml
Add in the portal application to use the helm chart to create
the portal application with the values.yaml for int.
=> [DM-22463] Add portal to argocd control of -int

lsst-lsp-stable/portal.yaml, science-platform-stable/templates/portal-application.yaml
Add in the portal.yaml for stable, and add in an argocd app in the
stable application to make the portal.
=> [DM-22501] Deploy portal to lsst-lsp-stable for first time

services/tap/values-int.yaml
Add the resource limits/requests block here.
=> [DM-20496] Add resource limits for TAP on -int

services/tap/values-stable.yaml
Same change as was rolled out on -int.
=> [DM-20496] TAP resource limits on stable

science-platform-stable/templates/landing-page-application.yaml, science-platform-stable/templates/nublado-application.yaml, science-platform-stable/templates/portal-application.yaml, science-platform-stable/templates/tap-application.yaml, science-platform/templates/landing-page-application.yaml, science-platform/templates/nublado-application.yaml, science-platform/templates/portal-application.yaml, science-platform/templates/tap-application.yaml
That worked well, let's do manual everywhere else now.
=> [DM-22666] Argocd to manual everywhere

services/landing-page/values-stable.yaml
=> [DM-22473] landing-page 3.0.1 on stable

argo-cd/argo-cd-values.yaml, services/vault-secrets-operator/Chart.yaml, services/vault-secrets-operator/requirements.yaml, services/vault-secrets-operator/values.yaml
=> Pin argo version to 1.2.4

science-platform-int/templates/logging-application.yaml, services/logging/Chart.yaml, services/logging/requirements.yaml, services/logging/values-int.yaml
Make an app in the services directory, and make the logging
application for int.  The values files are copies from the
logging directory in this repo, but indented because now
they are helm subcharts.
=> [DM-22775] Bring logging under argocd

services/logging/values-int.yaml
Ingress wanted to be a list of hosts, so made that a list, and fixed
some indentation problems.
=> [DM-22775] Logging YAML fixes

services/logging/values-int.yaml
Two small fixes:
1. The chart is splitting up the URL looking for the /, so I need to
take out the https:// part, which was making an error in how the
YAML was produced.
2. The format of env has changed and it is now directly injecting
each of those items right into the daemonset.  So put it in the
format of a k8s environment variable YAML.
=> [DM-22775] Fix logging values

science-platform-stable/templates/logging-application.yaml, services/logging/values-stable.yaml
This adds the application for stable, and a values file based on -int.
Before this is rolled out, argocd will need to be updated on stable.
=> [DM-22775] Logging for stable

services/tap/values-gke.yaml, services/tap/values-int.yaml, services/tap/values-stable.yaml
=> [DM-18557] TAP to 1.0.4 everywhere

services/tap/values-int.yaml
This will help me test out the whitelist of users who can modify
the log level properties.
=> [DM-22959] TAP on int to 1.0.5

services/tap/values-int.yaml
I need to turn on the debug info to start to see why I can't seem
to change it.
=> [DM-22959] Switch over to debug build

services/logging/values-int.yaml
Qserv logs at NCSA recently moved (/qserv/log/ -> /qserv/qserv-prod/log/)
=> [DM-23006] Update qserv logging config

services/logging/values-roundtable.yaml
This way we can login after a port-forward.
=> [DM-23217] Turn off ingress, and turn off security

services/logging/values-roundtable.yaml
This one seems shinier and should have more tools in the UI for
managing the different UIs.
=> [DM-23217] Let's try version 1.1.0

science-platform-int/templates/obstap-application.yaml, services/obstap/Chart.yaml, services/obstap/requirements.yaml, services/obstap/values-gke.yaml, services/obstap/values-int.yaml, services/obstap/values-stable.yaml
Add the application to the int environment, and add a services/obstap folder.
=> [DM-23190] Deploy prototype obstap service on -int

services/nublado/values-int.yaml, services/nublado/values-nublado.yaml, services/nublado/values-stable.yaml, services/nublado/values-summit.yaml
=> Add (readonly) butler mount at summit

services/authnz/values-nublado.yaml
We want to use the wildcard virtual host.
=> [DM-23775] Remove the host setting for authnz

services/authnz/values-nublado.yaml
Deploy a branch version to see if this fixes the coding error.
=> [DM-23646] Deploy fixed jwt_authorizer

services/authnz/values-nublado.yaml
The fix has now been included in the 0.2.1 release, so stop using
a ticket branch.
=> [DM-23646] Deploy released jwt_authorizer

services/authnz/values-nublado.yaml
Fixes a session date parsing bug.
=> [DM-23646] Switch authnz back to a ticket branch

services/gafaelfawr/requirements.yaml, services/gafaelfawr/values-nublado.yaml, services/nublado/values-nublado.yaml
Update for the renaming and reorganization of its values.yaml.
Point to the new secret path that contains only the Gafaelfawr
configuration.
=> [DM-23877] Update Gafaelfawr

science-platform-int/templates/gafaelfawr-application.yaml, services/gafaelfawr/values-int.yaml, services/logging/values-int.yaml, services/nublado/values-int.yaml, services/obstap/values-int.yaml, services/portal/values-int.yaml, services/tap/values-int.yaml
Replace authnz with Gafaelfawr on int.  Update the nginx ingress
annotations to point to the new URLs and remove the 403 handling
since we don't want to redirect those to the login handler.
=> [DM-24595] Convert int to Gafaelfawr

services/obstap/values-int.yaml, services/tap/values-int.yaml
These are API services that should return 401.
=> [DM-24595] Don't redirect TAP on auth failure

services/tap/values-int.yaml
Try again with a better database name this time.
=> [DM-24632] TAP int to 1.0.7

services/gafaelfawr/requirements.yaml, services/obstap/values-int.yaml, services/tap/values-int.yaml
Use the new feature of Gafaelfawr 1.1.0 to request Basic auth
challenges for tap and obstap services.
=> [DM-24635] Use Basic auth for TAP

services/nublado/values-int.yaml, services/nublado/values-nts.yaml
The chart has the value for int, but duplicate it in the int values
file since I otherwise keep forgetting that it needs to be set for
all other environments.
=> [DM-24597] Add JWT public key for int and NCSA test stand

science-platform-stable/templates/gafaelfawr-application.yaml, services/gafaelfawr/values-stable.yaml, services/logging/values-stable.yaml, services/nublado/values-stable.yaml, services/obstap/values-stable.yaml, services/portal/values-stable.yaml, services/tap/values-stable.yaml
Replace authnz with Gafaelfawr on the stable environment.
=> [DM-24598] Switch stable to Gafaelfawr

services/nublado/values-stable.yaml
=> [DM-24598] Stable nublado point to internal firefly not demo

services/gafaelfawr/requirements.yaml, services/gafaelfawr/values-int.yaml, services/gafaelfawr/values-nts.yaml, services/gafaelfawr/values-stable.yaml
Picks up support for logging the true client IP address and configure
the IP ranges for the NCSA clusters.
=> [DM-24810] Bump version of Gafaelfawr

services/gafaelfawr/requirements.yaml
Pick up fix to lowercase GitHub usernames and organization names.
=> [DM-24964] Bump Gafaelfawr version

bleed/argo-cd-values.yaml, bleed/initial-resources.yaml, bleed/install.sh, science-platform-bleed/Chart.yaml, science-platform-bleed/templates/argo.yaml, science-platform-bleed/templates/gafaelfawr-application.yaml, science-platform-bleed/templates/landing-page-application.yaml, science-platform-bleed/templates/nublado-application.yaml, science-platform-bleed/templates/nublado-users-application.yaml, science-platform-bleed/templates/portal-application.yaml, science-platform-bleed/templates/postgres-application.yaml, science-platform-bleed/templates/tap-application.yaml, services/gafaelfawr/values-bleed.yaml, services/nublado/values-bleed.yaml, services/postgres/values-bleed.yaml, services/tap/values-bleed.yaml
Okay set up a new bleed environment with a script that does everything!
=> [DM-24367] Create a bleed environment

science-platform/values-bleed.yaml
So complicated with all these branches!
=> [DM-24973] Move bleed off branch

services/gafaelfawr/requirements.yaml, services/gafaelfawr/values-summit.yaml
- Upgrade Gafaelfawr to 1.3.1
- Add lsst-sqre-friends to summit access
=> [DM-24930] Bump Gafaelfawr version, fix summit access

services/nginx-ingress/requirements.yaml
This will allow debugging of Gafaelfawr IP address logging issues.
=> [DM-24810] Upgrade NGINX ingress to latest version

services/gafaelfawr/requirements.yaml
Work around a bug in the latest NGINX ingress.
=> [DM-24810] Bump Gafaelfawr to 1.3.2

services/mobu/values-bleed.yaml, services/mobu/values-nublado.yaml
Now that I'm actually using these values and not relying on ones
that are defaults accidentally checked into the chart, I realize
that I haven't indented these.  Joy.
=> [DM-24246] Now fix the values files

services/mobu/values-int.yaml, services/mobu/values-stable.yaml
Hide mobu behind the admin proxy priv.
=> [DM-24246] Add auth headers for mobu

services/nginx-ingress/values-bleed.yaml, services/nginx-ingress/values-nublado.yaml
Following nublado.lsst.codes. Also add some missing Gafaelfawr configuration to nublado.lsst.codes now that the nginx ingress is managed in Argo CD.
=> [DM-25487] Switch bleed.lsst.codes to Let's Encrypt

services/portal/values-bleed.yaml, services/portal/values-nublado.yaml
On this one, having the hosts set breaks things.
=> [DM-25653] Get rid of hosts for portal on bleed and nublado

services/tap/values-bleed.yaml, services/tap/values-gke.yaml, services/tap/values-int.yaml, services/tap/values-nublado.yaml
Move everyone but stable up to the latest version.
=> [DM-25428] TAP to 1.0.10

science-platform/values-gold-leader.yaml, science-platform/values-red-five.yaml, science-platform/values-rogue-two.yaml
Not ready to take this part on yet, we'll just use normal certs.
=> [DM-25730] Turn off cert manager for new environments

.gitignore, installer/generate_secrets.py, installer/push_secrets.sh
generate_secrets.py will ask for the values and generate random
values as well as generate RSA keys.  These are written into a
directory called secrets, which push_secrets.sh will then use
to write all the keys and their values to vault.  You must
run the push_secrets.sh script with the VAULT_TOKEN appropriately
set for the environment you are trying to setup.
=> [DM-25412] Script to generate secrets and push to vault

installer/generate_secrets.py, services/mobu/values-bleed.yaml, services/mobu/values-gold-leader.yaml, services/mobu/values-int.yaml, services/mobu/values-nublado.yaml, services/mobu/values-red-five.yaml, services/mobu/values-rogue-two.yaml, services/mobu/values-stable.yaml
Add mobu secrets to the generator, and the path of all the keys in vault to all the values files.
=> [DM-25835] Add mobu secrets

science-platform/values-stable.yaml, services/mobu/values-int.yaml, services/mobu/values-stable.yaml
Also pin the versions to 1.0.0 for both int and stable.
=> [DM-25886] Turn on mobu on stable

services/mobu/values-int.yaml, services/mobu/values-stable.yaml
Fixes alerting so we should see some alerts if they happen.
=> [DM-25835] Mobu to 1.0.1

docs/cert-manager/index.rst, docs/index.rst
Includes documentation of the new DNS solver and the necessary
secrets for it.
=> [DM-25487] Add operational docs for cert-manager

installer/generate_secrets.py, services/gafaelfawr/requirements.yaml, services/gafaelfawr/values-bleed.yaml
Add a Redis password secret for Gafaelfawr to the installer script.
Move bleed to a ticket branch so that I can test Redis password
authentication.
=> [DM-26078] Add Redis password secret, bump Gafaelfawr on bleed

services/mobu/values-int.yaml, services/mobu/values-stable.yaml
Roll it out to int and stable.  This has a critical bug fix for
finding more issues.
=> [DM-26303] Roll out mobu 1.0.2

services/gafaelfawr/requirements.yaml
Pick up hardening configuration.
=> [DM-26412] Bump version of Gafaelfawr

services/gafaelfawr/requirements.yaml
Pick up a resource request fix.
=> [DM-26412] Bump Gafaelfawr version

science-platform/values-gold-leader.yaml, science-platform/values-red-five.yaml, science-platform/values-rogue-two.yaml, services/nginx-ingress/values-gold-leader.yaml, services/nginx-ingress/values-red-five.yaml, services/nginx-ingress/values-rogue-two.yaml
Turn these all on and set the default certificate to the one
generated by cert manager.
=> [DM-26528] Turn on cert-manager for star wars environments

docs/index.rst, docs/logging/index.rst
Mostly copied from Roundtable with modifications for the Science
Platform deployment.
=> [DM-26508] Add operational documentation for logging

installer/install.sh, services/postgres/values-gold-leader.yaml, services/postgres/values-red-five.yaml, services/postgres/values-rogue-two.yaml
Postgres wasn't working, and the vault keys were also broken and needed to be regenerated.  With this, hopefully everything should work using the script.
=> [DM-26528] Get nublado working on star wars environments

services/gafaelfawr/values-bleed.yaml, services/nublado/values-bleed.yaml
See if the wildcard nginx handling is what's preventing us from
getting a certificate correctly.
=> [DM-25487] Try specifying the ingress host

services/nublado/values-int.yaml, services/nublado/values-stable.yaml
self-merging.  Don't worry, we were running wfdispatcher for a week or more on int before yesterday.  It's fine.
=> Bump hub and wfdispatcher stable/int

services/portal/values-int.yaml, services/portal/values-nublado.yaml
This reverts commit 611e2ce9d1025607160b9166a74c6a91a166e3af.
=> Revert "update int/nublado to new rc version"

services/portal/values-int.yaml
This reverts commit 2a885c91641d29e81fd1182c2ec31be14eb6c722.
=> Revert "replicaCount 2 for int"

README.md
This will help people at the bootcamp.
=> [DM-27146] Add a thorough README.md

science-platform/values-minikube.yaml, services/cert-issuer/values-minikube.yaml, services/cert-manager/values.yaml, services/gafaelfawr/values-minikube.yaml, services/landing-page/values-minikube.yaml, services/mobu/values-minikube.yaml, services/nginx-ingress/values-minikube.yaml, services/nublado/values-minikube.yaml, services/obstap/values-minikube.yaml, services/portal/values-minikube.yaml, services/postgres/values-minikube.yaml, services/tap/values-minikube.yaml
Add an environment that uses minikube for helping development.
=> [DM-27044] Add minikube environment

science-platform/values-minikube.yaml
Okay now that we've merged the PR, we can get rid of these
revision: branch lines.
=> [DM-27044] Get rid of branches for minikube

services/tap/values-int.yaml
This is the address of the new "small" Qserv backend.
=> [DM-27279] Point -int TAP to lsst-qserv-master03

services/nublado/values-base.yaml, services/nublado/values-bleed.yaml, services/nublado/values-gold-leader.yaml, services/nublado/values-int.yaml, services/nublado/values-minikube.yaml, services/nublado/values-nts.yaml, services/nublado/values-nublado.yaml, services/nublado/values-red-five.yaml, services/nublado/values-rogue-two.yaml, services/nublado/values-stable.yaml, services/nublado/values-summit.yaml, services/nublado/values-tucson-teststand.yaml
I've already updated vault with the password in all environments.
=> Add pull user to deployments

services/nublado/values-kueyen.yaml
It's a copy of base, with "base-lsp" replaced by "kueyen-lsp" and the comcam mount disabled.
=> Add kueyen environment

services/nginx-ingress/values-bleed.yaml, services/nginx-ingress/values-gold-leader.yaml, services/nginx-ingress/values-nublado.yaml, services/nginx-ingress/values-red-five.yaml, services/nginx-ingress/values-rogue-two.yaml, services/nginx-ingress/values-tucson-teststand.yaml
These should all be unused values that aren't used in the new
chart.
=> [DM-27636] Clean up other ingress values

science-platform/templates/exposurelog-application.yaml, science-platform/values-base.yaml, science-platform/values-bleed.yaml, science-platform/values-gold-leader.yaml, science-platform/values-int.yaml, science-platform/values-minikube.yaml, science-platform/values-nts.yaml, science-platform/values-nublado.yaml, science-platform/values-red-five.yaml, science-platform/values-rogue-two.yaml, science-platform/values-squash-sandbox.yaml, science-platform/values-stable.yaml, science-platform/values-summit.yaml, science-platform/values-tucson-teststand.yaml, science-platform/values.yaml, services/exposurelog/Chart.yaml, services/exposurelog/requirements.yaml, services/exposurelog/templates/vault-secrets.yaml, services/exposurelog/values-bleed.yaml
- Add exposurelog service and argo-cd app
=> [DM-27452] Add exposurelog service to lsp-deploy

services/exposurelog/values-bleed.yaml, services/exposurelog/values-nts.yaml
and standardize value formatting a bit
=> exposurelog: fix vault path for nts

services/cert-issuer/values-squash-sandbox.yaml, services/nginx-ingress/values-squash-sandbox.yaml
Add values for missing environment
=> [DM-27846] Deploy squash-sandbox.lsst.codes using the lsp-deploy install script

installer/generate_secrets.py, science-platform/templates/cachemachine-application.yaml, science-platform/templates/nublado2-application.yaml, science-platform/values-bleed.yaml, science-platform/values-minikube.yaml, science-platform/values.yaml, services/cachemachine/Chart.yaml, services/cachemachine/requirements.yaml, services/cachemachine/values-bleed.yaml, services/cachemachine/values-minikube.yaml, services/nublado2/Chart.yaml, services/nublado2/requirements.yaml, services/nublado2/values-bleed.yaml, services/nublado2/values-minikube.yaml
Also adding values for bleed and minikube, which are the only
enabled environments.
=> [DM-27441] Add cachemachine and nublado2 to science-platform

science-platform/values.yaml
Forgot this when doing the last PR, and that caused a syncing error
since the revision couldn't be sourced.
=> [DM-27441] science-platform: add in nublado2

services/nublado2/requirements.yaml
We're not yet to 0.1.0!  But that's okay, just take whatever for now.
=> [DM-27441] Nublado2: fix requirements file

services/squash-api/values-squash-sandbox.yaml
- Will use the squash-sandbox environment to rehearsal DM-18060
=> Clone current squash-prod database to squash-sandbox-2

services/nublado/values-nublado.yaml
This reverts commit e81f4be1f61acf2570c920e7ccd43d8694e155fb.
=> Revert "add filestore /projects for performance comparison"

docs/index.rst, docs/rancher-external-ip-webhook/index.rst, science-platform/values-base.yaml, science-platform/values-gold-leader.yaml, science-platform/values-idfdev.yaml, science-platform/values-idfint.yaml, science-platform/values-int.yaml, science-platform/values-nts.yaml, science-platform/values-nublado.yaml, science-platform/values-red-five.yaml, science-platform/values-rogue-two.yaml, science-platform/values-squash-sandbox.yaml, science-platform/values-stable.yaml, science-platform/values-summit.yaml, science-platform/values-tucson-teststand.yaml, services/rancher-external-ip-webhook/values-gold-leader.yaml, services/rancher-external-ip-webhook/values-idfdev.yaml, services/rancher-external-ip-webhook/values-idfint.yaml, services/rancher-external-ip-webhook/values-nublado.yaml, services/rancher-external-ip-webhook/values-red-five.yaml, services/rancher-external-ip-webhook/values-rogue-two.yaml, services/rancher-external-ip-webhook/values-tucson-teststand.yaml
Enable this on all the environemnts where we run cert-manager.
Add some documentation about the problem it solves and how to test
whether it's working.
=> [DM-27982] Enable rancher-external-ip-webhook

services/gafaelfawr/Chart.yaml
Pick up fix to the auth-url ingress annotation for /auth/tokens.
=> [DM-28227] Bump version of Gafaelfawr

services/cachemachine/values-bleed.yaml, services/cachemachine/values-idfdev.yaml, services/cachemachine/values-minikube.yaml
=> [DM-28601] Cachemachine 1.0.3

services/nublado2/values-idfdev.yaml
This might not work, but then again, it might?
=> [DM-28482] Test out nublado2 on data-dev

services/nublado2/values-idfdev.yaml
Let's break it and try to edit our way to victory.
=> [DM-28725] Turn on network policy on data-dev

services/gafaelfawr/values-bleed.yaml
=> [DM-28845] Switch bleed environment to Gafaelfawr branch

README.md, docs/arch/index.rst, docs/argo-cd/index.rst, docs/bootstrapping.rst, docs/cert-issuer/index.rst, docs/cert-manager/index.rst, docs/conf.py, docs/gafaelfawr/index.rst, docs/index.rst, docs/logging/index.rst, docs/rancher-external-ip-webhook/index.rst, docs/squash-api/index.rst, docs/vault-secrets-operator/index.rst, science-platform/values.yaml, tools/addpullsecret/add-pull-secrets.bash
- Finish the renaming from lsp-deploy to phalans
- Add documentation for bootstrapping a new environment
- Add Gafaelfawr app and debugging documentation
=> [DM-28899] Finish renaming, add bootstrap and Gafaelfawr docs

science-platform/values-int.yaml, services/cachemachine/values-int.yaml, services/nublado2/values-int.yaml
=> [DM-28923] Enable nublado2 on int

renovate.json
See if I can get Renovate to catch up with missing updates by
removing the weekly schedule.
=> Remove Renovate weekly schedule

services/nublado2/values-int.yaml
This will make recommended show up in the list, even if cachemachine
doesn't think it is pulled.
=> [DM-28950] Nublado2: force recommended in the list

services/nublado2/values-int.yaml
Oops, this needs to be under options_form section.
=> [DM-28950] Nublado2: move config

services/nublado2/values-int.yaml
This sets up the work needed to run dask in int, on the PR branch
so I can test it there before merging.
=> [DM-28950] Nublado2: have int run experimental PR

services/argocd/values-idfdev.yaml
- Restore correct ingress configuration
- Fix syntax of Dex configuration
- Add the mandatory URL parameter
- Specify the scope to use for group mappings for users (we're using the email address)
=> [DM-28900] Fix bugs in Google auth setup

services/cachemachine/values-idfint.yaml, services/cachemachine/values-idfprod.yaml, services/nublado2/values-idfint.yaml, services/nublado2/values-idfprod.yaml
This is for idf related environments, as requested.
=> [DM-29112] Turn on cachemachine / nublado2

.github/workflows/minikube.yaml, services/cachemachine/Chart.yaml, services/nublado2/values-bleed.yaml, services/nublado2/values-idfdev.yaml, services/nublado2/values-idfint.yaml, services/nublado2/values-idfprod.yaml, services/nublado2/values-int.yaml, services/nublado2/values-minikube.yaml
This will hopefully reduce the number of changes required.
=> [DM-29112] Use the chart default for version and image

installer/generate_secrets.py
This was because I was using the generated stuff for something that
was generated, but was based on a not generated thing (that came
from the vault).  This meant that the key wasn't getting generated.
=> [DM-28839] generate_secrets not generating argocd secret

services/gafaelfawr/Chart.yaml, services/gafaelfawr/values-base.yaml, services/gafaelfawr/values-idfdev.yaml, services/gafaelfawr/values-idfint.yaml, services/gafaelfawr/values-idfprod.yaml, services/gafaelfawr/values-int.yaml, services/gafaelfawr/values-minikube.yaml, services/gafaelfawr/values-nts.yaml, services/gafaelfawr/values-red-five.yaml, services/gafaelfawr/values-squash-sandbox.yaml, services/gafaelfawr/values-stable.yaml, services/gafaelfawr/values-summit.yaml, services/gafaelfawr/values-tucson-teststand.yaml
- Update Gafaelfawr configuration for the new 2.0.0 chart
- Use the GCE PD CSI driver storage classes on IDF environments
=> [DM-29085] Update Gafaelfawr configuration

services/gafaelfawr/Chart.yaml
Fix various problems with the /auth/tokens ingress.
=> [DM-29085] Bump version of Gafaelfawr chart

services/squareone/values-idfint.yaml, services/squareone/values-minikube.yaml
=> DM-29432: Update squareone image to 0.1.3

services/nublado2/values-idfdev.yaml
Accidentally left a pinned version here.
=> [DM-29619] Get rid of pinned version on data-dev

services/gafaelfawr/Chart.yaml, services/gafaelfawr/values-nts.yaml
Pick up a fix to the OpenID Connect configuration.
=> Bump version of Gafaelfawr chart

science-platform/values-idfdev.yaml, services/moneypenny/Chart.yaml, services/nublado2/Chart.yaml
For iterating on the Gafaelfawr 2.0 rollout.
=> [DM-28120] Point IDF dev at the DM-28120 branch

services/portal/values-base.yaml, services/portal/values-idfint.yaml, services/portal/values-idfprod.yaml, services/portal/values-red-five.yaml, services/portal/values-summit.yaml
This gets us consistent at least.
=> [DM-29822] Use portal vault secret everywhere

installer/generate_secrets.py, installer/install.sh, science-platform/values-idfdev.yaml, services/gafaelfawr/Chart.yaml, services/gafaelfawr/values-idfdev.yaml, services/gafaelfawr/values-idfint.yaml, services/gafaelfawr/values-int.yaml, services/gafaelfawr/values-minikube.yaml, services/landing-page/Chart.yaml, services/landing-page/values-idfdev.yaml, services/mobu/Chart.yaml, services/mobu/values-idfdev.yaml, services/mobu/values-idfint.yaml, services/mobu/values-int.yaml, services/mobu/values-minikube.yaml, services/moneypenny/values-idfdev.yaml, services/moneypenny/values-idfint.yaml, services/moneypenny/values-int.yaml, services/moneypenny/values-minikube.yaml, services/nublado2/Chart.yaml, services/nublado2/values-idfdev.yaml, services/nublado2/values-idfint.yaml, services/nublado2/values-int.yaml, services/nublado2/values-minikube.yaml, services/portal/values-idfdev.yaml, services/postgres/Chart.yaml, services/postgres/values-int.yaml, services/postgres/values-minikube.yaml
- Add configuration for Gafaelfawr 2.0
- Move TLS configuration to the landing-page application
- Update mobu, nublado2, postgres, and moneypenny with necessary changes for Gafaelfawr 2.0
=> [DM-28120] Configure Gafaelfawr 2.0

services/gafaelfawr/Chart.yaml
Pick up a fix for CILogon configurations.
=> [DM-28120] Bump Gafaelfawr chart version

services/gafaelfawr/Chart.yaml
Pick up a new Google Cloud SQL Auth Proxy version.
=> Bump version of Gafaelfawr

science-platform/templates/nublado-users-application.yaml
Otherwise if we disable nublado, we'll stop creating this.
=> [DM-29799] Create nublado-users depending on nublado2 or nublado

services/gafaelfawr/Chart.yaml
Pick up fix to the number of workers spawned in each pod so that
we don't overrun the Cloud SQL connection limit.
=> [DM-28120] Bump version of Gafaelfawr

installer/generate_secrets.py
This will be helpful if some rogue metadata or something changes.
=> [DM-29903] Add debug logging to generate_secrets

services/mobu/values-idfdev.yaml, services/mobu/values-idfint.yaml, services/mobu/values-idfprod.yaml, services/mobu/values-red-five.yaml
I accidentally omitted the Gafaelfawr port.
=> [DM-28120] Fix auth-url annotation for mobu

services/nublado2/values-stable.yaml, services/portal/values-stable.yaml
- Fix Portal configuration for Gafaelfawr 2.0
- Update Portal to the latest release with user display fixes
- Configure the butler-secret path on stable
=> [DM-28120] Fix configuration on stable

services/nublado2/values-stable.yaml
Now we'll use what cachemachine says
=> [DM-29799] Stop pinning recommended on stable

services/cert-issuer/Chart.yaml
Fix for the CluserIssuer key capitalization.
=> [DM-29926] Bump version of cert-issuer

services/gafaelfawr/Chart.yaml
=> [DM-29365] Bump Gafaelfawr version

services/nublado2/Chart.yaml, services/nublado2/values-int.yaml, services/nublado2/values-stable.yaml
Use the internal postgres db instead of the one in the pod.
=> NCSA to postgres instead of on the pod

services/nublado2/Chart.yaml
Pick up improvement to the Gafaelfawr auth-url.
=> [DM-30064] Bump nublado2 version

services/gafaelfawr/Chart.yaml
Pick up new release with UI and database initialization fixes.
=> [DM-30369] Bump version of Gafaelfawr chart

services/gafaelfawr/Chart.yaml
Pick up fix for display of expired tokens and timestamps in logs.
=> [DM-30706] Bump version of Gafaelfawr

services/portal/values-idfdev.yaml, services/portal/values-idfint.yaml
This is a test fix for the authentication issues when retrieving
error messages, plus some other new development.
=> [DM-30073] Install test release of SUIT on data-dev, data-int

services/gafaelfawr/Chart.yaml
Pick up fix to issuing internal and notebook tokens.
=> [DM-30789] Bump version of Gafaelfawr

services/portal/values-idfdev.yaml, services/portal/values-idfint.yaml
Use the new hotfix branch with fixed retrieval of error messages.
=> [DM-30073] Update Portal version tag

services/portal/values-idfdev.yaml, services/portal/values-idfint.yaml
Another test build in preparation for a new release.
=> [DM-30073] Deploy new SUIT version on data-dev and data-int

services/squareone/values-idfdev.yaml
Test out the changes in https://github.com/lsst-sqre/squareone/pull/21
=> DM-30839: Use squareone DM-30839 image on idfdev

science-platform/templates/tap-schema-application.yaml, science-platform/values-base.yaml, science-platform/values-idfdev.yaml, science-platform/values-idfint.yaml, science-platform/values-idfprod.yaml, science-platform/values-int.yaml, science-platform/values-minikube.yaml, science-platform/values-nts.yaml, science-platform/values-red-five.yaml, science-platform/values-squash-sandbox.yaml, science-platform/values-stable.yaml, science-platform/values-summit.yaml, science-platform/values-tucson-teststand.yaml, science-platform/values.yaml, services/tap-schema/Chart.yaml, services/tap-schema/values-idfdev.yaml, services/tap-schema/values-idfint.yaml, services/tap-schema/values-idfprod.yaml, services/tap-schema/values-int.yaml, services/tap-schema/values-minikube.yaml, services/tap-schema/values-red-five.yaml, services/tap-schema/values-stable.yaml
Basic start, uses the version set in the chart
for all the different environments.
=> [DM-30753] Create tap-schema application

services/tap/values-idfprod.yaml
Maybe this will fix our JVM heap issues.
=> [DM-30753] Make idfprod memory limits the same as stable

services/portal/values-idfint.yaml, services/portal/values-idfprod.yaml
This has to be done with an annotation.
=> [DM-30904] Fix specification of the Portal proxy timeout

services/tap-schema/values-int.yaml
Includes other cleanups, notably removing DP0.1 and SDSS.
=> DM-30193: Pre-flight test of updated WISE (wise_01) schema on NCSA -int

services/tap-schema/values-idfint.yaml
Uses sdm_schemas release 1.1.0.
=> DM-31077: Pre-flight changes to "principal" for DP0.1 on data-int

services/cachemachine/Chart.yaml
Pick up fix for the service port.
=> [DM-31082] Bump version of cachemachine

services/tap-schema/values-idfint.yaml, services/tap-schema/values-int.yaml
The version has now been increased in the chart.
=> Remove tap-schema tag overrides

services/semaphore/values-base.yaml
- Always pull images for quicker debugging
- Configure the GitHub app for data-dev
=> DM-30931: Configure semaphore for webhooks on data-dev

services/mobu/Chart.yaml, services/mobu/values-idfdev.yaml, services/mobu/values-idfint.yaml, services/mobu/values-idfprod.yaml, services/mobu/values-int.yaml, services/mobu/values-minikube.yaml, services/mobu/values-red-five.yaml, services/mobu/values-stable.yaml
- Update for new mobu chart
- Add autostart configuration
=> [DM-31083] Add mobu autostart configuration

services/mobu/values-idfdev.yaml, services/mobu/values-idfint.yaml, services/mobu/values-idfprod.yaml
IDF dev doesn't have the data required to run the notebooks.
=> [DM-31083] Go back to JupyterPythonRunner on IDF dev

services/tap/values-idfint.yaml, services/tap/values-idfprod.yaml
This will give us some more signal into how it's working
and other issues that may come up.
=> [DM-17872] Roll out parser improvements to int and prod

services/mobu/values-int.yaml, services/mobu/values-stable.yaml
Run one firefighter monkey on int and five on stable, using a
similar configuration as IDF but use notebook-demo and the
robo-simon branch.
=> [DM-31201] Reconfigure the monkeys for NCSA

services/mobu/values-idfint.yaml
Try to reproduce our cachemachine failure.
=> [DM-31201] Run five firefighter monkeys on IDF int

services/mobu/values-idfprod.yaml
Deploy from a mobu branch on data.lsst.cloud and start the tutorial
notebook now that there is support for setting a working directory.
Rename the buddhist monkey.
=> [DM-31406] Run tutorial notebooks on data.lsst.cloud

services/mobu/values-idfprod.yaml
There is a new release with support for running the tutorial
notebooks and therefore a new chart.
=> [DM-31406] Unpin mobu version

services/gafaelfawr/Chart.yaml
Pick up fixes to the token management deployment.
=> [DM-31387] Bump version of Gafaelfawr

services/nublado2/Chart.yaml
Pick up fixes to deleting namespaces on lab shutdown.
=> [DM-31504] Bump version of nublado2

services/nublado2/values-base.yaml, services/nublado2/values-idfdev.yaml, services/nublado2/values-idfint.yaml, services/nublado2/values-idfprod.yaml, services/nublado2/values-int.yaml, services/nublado2/values-minikube.yaml, services/nublado2/values-nts.yaml, services/nublado2/values-red-five.yaml, services/nublado2/values-stable.yaml, services/nublado2/values-summit.yaml, services/nublado2/values-tucson-teststand.yaml
WARNING: this should be merged immediately upon Simon's renaming repos and branches.  NOT before, and NOT long after.
=> auto repo specs ; repo/branch renaming

.github/workflows/docs.yaml, docs/.gitignore, docs/Makefile, docs/_static/notebook-tap.py, docs/_static/portal-tap.py, docs/conf.py, docs/index.rst, docs/ops/bootstrapping.rst, docs/ops/gafaelfawr/index.rst, docs/ops/tap/index.rst, docs/requirements.txt, services/mobu/values-idfdev.yaml, services/mobu/values-idfint.yaml, services/mobu/values-int.yaml
Capture some diagrams that I made a while back for Frossie.  Add a
new TAP operations page to hold them.
=> [DM-31020] Add diagrams for the TAP service

science-platform/templates/noteburst-application.yaml, science-platform/values-base.yaml, science-platform/values-idfdev.yaml, science-platform/values-idfint.yaml, science-platform/values-idfprod.yaml, science-platform/values-int.yaml, science-platform/values-minikube.yaml, science-platform/values-nts.yaml, science-platform/values-red-five.yaml, science-platform/values-squash-sandbox.yaml, science-platform/values-stable.yaml, science-platform/values-summit.yaml, science-platform/values-tucson-teststand.yaml, science-platform/values.yaml, services/noteburst/Chart.yaml, services/noteburst/values-base.yaml, services/noteburst/values-idfdev.yaml, services/noteburst/values-idfint.yaml, services/noteburst/values-idfprod.yaml, services/noteburst/values-int.yaml, services/noteburst/values-minikube.yaml, services/noteburst/values-nts.yaml, services/noteburst/values-red-five.yaml, services/noteburst/values-stable.yaml, services/noteburst/values-summit.yaml, services/noteburst/values-tucson-teststand.yaml
- Adds the noteburst service
- Enables noteburst in the idfdev and minikube environments
=> DM-31910: Initialize the noteburst service

services/cert-issuer/Chart.yaml
Pick up API update for the new cert-manager release.
=> [DM-32422] Bump version of cert-issuer chart

services/gafaelfawr/values-idfint.yaml
Folks in that group are using int to test things that may be useful
for having Firefly and TAP for.
=> Grant exec:notebook and read:tap to lsst-ops:panda

science-platform/templates/alert-stream-broker-application.yaml, science-platform/values-base.yaml, science-platform/values-idfdev.yaml, science-platform/values-idfint.yaml, science-platform/values-idfprod.yaml, science-platform/values-int.yaml, science-platform/values-minikube.yaml, science-platform/values-nts.yaml, science-platform/values-red-five.yaml, science-platform/values-roe.yaml, science-platform/values-squash-sandbox.yaml, science-platform/values-stable.yaml, science-platform/values-summit.yaml, science-platform/values-tucson-teststand.yaml, science-platform/values.yaml, services/alert-stream-broker/Chart.yaml, services/alert-stream-broker/values-idfint.yaml, services/alert-stream-broker/values.yaml, services/strimzi/values.yaml
This application runs a Kafka broker for the alert stream.
Everything is left with the defaults in https://github.com/lsst-sqre/charts/tree/master/charts/alert-stream-broker.
=> DM-32356: Add alert-stream-broker application

services/strimzi/values.yaml
Debugging an issue in the cluster operator. Seeing errors when it tries to create a cluster. Maybe this will illuminate things.
=> strimzi: Enable debug logging

services/strimzi/values.yaml
Continuation of #1043 - going all the way to trace to try to see the specs that are being created.
=> strimzi: Raise log level to TRACE

science-platform/templates/strimzi-registry-operator-application.yaml, science-platform/values-base.yaml, science-platform/values-idfdev.yaml, science-platform/values-idfint.yaml, science-platform/values-idfprod.yaml, science-platform/values-int.yaml, science-platform/values-minikube.yaml, science-platform/values-nts.yaml, science-platform/values-red-five.yaml, science-platform/values-roe.yaml, science-platform/values-squash-sandbox.yaml, science-platform/values-stable.yaml, science-platform/values-summit.yaml, science-platform/values-tucson-teststand.yaml, science-platform/values.yaml, services/alert-stream-broker/Chart.yaml, services/alert-stream-broker/values-idfint.yaml, services/strimzi-registry-operator/Chart.yaml, services/strimzi-registry-operator/values-idfint.yaml, services/strimzi-registry-operator/values.yaml
Adds the Schema Registry Operator as a new application. Also adds a Schema Registry instance to the alert-stream-broker application.
=> DM-32548: Add Schema Registry

services/nublado2/Chart.yaml
Pick up fix for hanging on to old authentication tokens.
=> [DM-32551] Bump version of nublado2

services/gafaelfawr/Chart.yaml, services/gafaelfawr/values-idfprod.yaml, services/gafaelfawr/values-stable.yaml, services/moneypenny/Chart.yaml, services/portal/values-minikube.yaml
Also remove references to the old gafaelfawr-service service.
=> [DM-32520] Update to Gafaelfawr 3.3.0

services/plot-navigator/values-idfint.yaml
Add missing config parameters.
=> PREOPS-858 Config fixup.

services/nublado2/Chart.yaml
Pick up fix to internal auth from lab to hub.
=> [DM-32755] Bump version of nublado2

services/alert-stream-broker/Chart.yaml
Version 2.0.0 includes a job which injects a schema into the registry
=> alert-stream-broker: update schema registry

docs/index.rst, docs/ops/bootstrapping.rst, docs/ops/cachemachine/updating-recommended.rst, docs/ops/gafaelfawr/recreate-token.rst, docs/ops/nublado2/database.rst, docs/ops/troubleshooting.rst, docs/service-guide/mobu-manage-flocks.rst
- Reformat some documentation
- Move per-service bootstrapping notes into their own sections
- Add some requirements to the bootstrapping page
=> [DM-32775] Documentation updates

services/alert-stream-broker/Chart.yaml
Set the cert issuer by name correctly
=> DM-32360: alert-stream-broker: bump version

services/alert-stream-broker/Chart.yaml
new version fixes reference to admin password
=> DM-32839: alert-stream-broker: bump version

services/cachemachine/values-idfdev.yaml, services/cachemachine/values-idfint.yaml, services/cachemachine/values-int.yaml, services/cachemachine/values-stable.yaml
We're going to make recommended weekly 49 today.
=> [DM-32896] Update all non-TS sites pins to weekly 49

services/gafaelfawr/Chart.yaml
Pick up a fix for database initialization.
=> [DM-32899] Bump version of Gafaelfawr

services/alert-stream-broker/Chart.yaml
Fixes a very large integer getting cast to a float.
=> DM-32958:: alert-stream-broker: bump alert-stream-simulator version

services/alert-stream-broker/Chart.yaml
Maybe this time I got the types correct. Sure wish I could run this locally.
=> DM-32958: alert-stream-broker: bump alert-stream-simulator version again

services/alert-stream-broker/Chart.yaml
Fixes specification of pod affinities and tolerations
=> alert-stream-broker: bump alert-stream-brokerversion

services/moneypenny/Chart.yaml
Handle a race condition between starting the pod and checking its
status.
=> [DM-32811] Bump Moneypenny version

services/moneypenny/Chart.yaml
Pick up a fix for changing the scheme of redirects.
=> [DM-32811] Bump version of moneypenny

services/sherlock/values-idfdev.yaml, services/sherlock/values-idfint.yaml, services/sherlock/values-idfprod.yaml
Should have been .cloud, not .codes.
=> [DM-32751] Fix hostnames for sherlock

services/alert-stream-broker/Chart.yaml
=> DM-32646: alert-stream-broker: bump alert DB version

services/alert-stream-broker/values-idfint.yaml
debug is pretty extreme, with many lines per message. Reduce it to verbose.
=> DM-33003: alert-stream-broker: reduce alert DB ingester log level

services/alert-stream-broker/Chart.yaml
one of these days this will work
=> DM-32647: alert-stream-broker: bump alert db version

services/gafaelfawr/Chart.yaml
Pick up fix for Kubernetes object creation.
=> [DM-33121] Bump Gafaelfawr version

services/noteburst/values-idfdev.yaml, services/noteburst/values-minikube.yaml
- fix environmentUrl value
- update image tag for noteburst
=> DM-33025: Additional noteburst 0.2 integration

services/cachemachine/Chart.yaml, services/datalinker/Chart.yaml, services/moneypenny/Chart.yaml, services/sherlock/Chart.yaml
The NetworkPolicy objects were pointing at the wrong ports.
=> [DM-26506] Bump chart versions for NetworkPolicy fixes

services/tap/Chart.yaml
Pick up security fixes for the database services.
=> [DM-33241] Bump version of TAP chart

services/tap/Chart.yaml
Drop yet more security hardening.
=> [DM-33241] Bump TAP chart version

.gitignore, docs/arch/secrets.rst, docs/service-guide/local-development.rst
I was able to get Minikube running locally thanks to the docs. There were just a couple of areas where I got caught out, so this PR should help with that.
=> DM-33025: Iterate on minikube docs

science-platform/templates/narrativelog-application.yaml, science-platform/values-base.yaml, science-platform/values-idfdev.yaml, science-platform/values-idfint.yaml, science-platform/values-idfprod.yaml, science-platform/values-int.yaml, science-platform/values-minikube.yaml, science-platform/values-red-five.yaml, science-platform/values-roe.yaml, science-platform/values-squash-sandbox.yaml, science-platform/values-stable.yaml, science-platform/values-summit.yaml, science-platform/values-tucson-teststand.yaml, science-platform/values.yaml, services/exposurelog/values-roe.yaml, services/narrativelog/Chart.yaml, services/narrativelog/templates/vault-secrets.yaml, services/narrativelog/values-base.yaml, services/narrativelog/values-summit.yaml, services/narrativelog/values-tucson-teststand.yaml, services/postgres/values-base.yaml, services/postgres/values-minikube.yaml, services/postgres/values-summit.yaml, services/postgres/values-tucson-teststand.yaml, tools/addpullsecret/add-pull-secrets.bash
including configuration for summit, base, and Tucson test stand.
Also tweak a few exposurelog settings.
=> DM-33661: narrativelog: add support

services/vo-cutouts/Chart.yaml
=> [DM-33720] Bump version of vo-cutouts chart

science-platform/templates/times-square-application.yaml, science-platform/values-base.yaml, science-platform/values-idfdev.yaml, science-platform/values-idfint.yaml, science-platform/values-idfprod.yaml, science-platform/values-int.yaml, science-platform/values-minikube.yaml, science-platform/values-red-five.yaml, science-platform/values-roe.yaml, science-platform/values-squash-sandbox.yaml, science-platform/values-stable.yaml, science-platform/values-summit.yaml, science-platform/values-tucson-teststand.yaml, science-platform/values.yaml, services/times-square/Chart.yaml, services/times-square/values-idfdev.yaml
This adds the times-square app, based on chart version 0.1.7.
=> DM-33627: Add times-square application

services/mobu/values-idfint.yaml
Switch to the new build from GitHub Container Registry and start a
TAP runner.
=> [DM-33813] Test new mobu on data-int

services/portal/Chart.yaml, services/portal/values-base.yaml, services/portal/values-idfdev.yaml, services/portal/values-idfint.yaml, services/portal/values-idfprod.yaml, services/portal/values-int.yaml, services/portal/values-minikube.yaml, services/portal/values-red-five.yaml, services/portal/values-roe.yaml, services/portal/values-stable.yaml, services/portal/values-summit.yaml, services/portal/values-tucson-teststand.yaml
Rewrite the local configuration for each environment for the new
Portal chart.
=> [DM-26506] Update to new Portal chart

services/obstap/Chart.yaml, services/obstap/values-idfdev.yaml, services/obstap/values-idfint.yaml, services/obstap/values-idfprod.yaml, services/obstap/values-int.yaml, services/obstap/values-minikube.yaml, services/obstap/values-red-five.yaml, services/obstap/values-roe.yaml, services/obstap/values-stable.yaml, services/tap/Chart.yaml
This requires changes to the environment-specific values files
(and allows deleting some things now handled by the chart).
=> [DM-26506] Update to the new obstap chart

services/obstap/Chart.yaml
=> [DM-26506] Bump version of obstap chart

services/obstap/Chart.yaml
=> [DM-26506] Bump obstap chart version

science-platform/values-int.yaml, services/gafaelfawr/values-int.yaml, services/sasquatch/charts/strimzi-kafka/templates/connect.yaml, services/sasquatch/charts/strimzi-kafka/values.yaml, services/sasquatch/values-int.yaml, services/strimzi/values-idfint.yaml, services/strimzi/values-int.yaml, services/strimzi/values.yaml
This PR enables sasquatch on int and adds specific configuration for this environment.
=> [DM-33846] Deploy sasquatch on NCSA int

science-platform/values-stable.yaml, services/gafaelfawr/values-stable.yaml, services/sasquatch/values-stable.yaml, services/strimzi/values-stable.yaml
- Enable sasquatch on stable and add specific configuration for this environment.
=> [DM-33847] Deploy sasquatch on NCSA stable

services/exposurelog/Chart.yaml, services/exposurelog/templates/_helpers.tpl, services/exposurelog/templates/deployment.yaml, services/exposurelog/templates/hpa.yaml, services/exposurelog/templates/ingress.yaml, services/exposurelog/templates/service.yaml, services/exposurelog/templates/tests/test-connection.yaml, services/exposurelog/values-base.yaml, services/exposurelog/values-summit.yaml, services/exposurelog/values-tucson-teststand.yaml, services/exposurelog/values.yaml, services/narrativelog/Chart.yaml, services/narrativelog/templates/_helpers.tpl, services/narrativelog/templates/deployment.yaml, services/narrativelog/templates/hpa.yaml, services/narrativelog/templates/ingress.yaml, services/narrativelog/templates/networkpolicy.yaml, services/narrativelog/templates/service.yaml, services/narrativelog/templates/tests/test-connection.yaml, services/narrativelog/values.yaml
Update for new versions of both packages.
Move chart and template files from the charts package to this package.
=> DM-33922: Update exposurelog and narrativelog

services/gafaelfawr/templates/configmap.yaml
Missed some renamings of parameters to the OIDC server.
=> [DM-34097] Fix Gafaelfawr OIDC server configuration settings

services/sherlock/values-idfdev.yaml, services/sherlock/values-idfint.yaml, services/sherlock/values-idfprod.yaml
Oops forgot the /api part of the URL.
=> [DM-34074] Fix sherlock publish url

services/nublado2/values-idfdev.yaml
Changes to test culling in rsp dev
=> values for idf dev culling

services/gafaelfawr/values-idfint.yaml
Since it's now the DP0.2 staging environment
=> Add lsst ops team to IDF-int

services/cachemachine/values-idfdev.yaml
deploying cachemachine gar to idf dev
=> deploying new cachemachine gar image to dev

science-platform/values-tucson-teststand.yaml, services/gafaelfawr/values-tucson-teststand.yaml, services/sasquatch/values-tucson-teststand.yaml, services/strimzi/values-tucson-teststand.yaml
- Add values for tucson teststand
- Enable sasquatch and strimzi services
=> [DM-33845] Deploy sasquatch at Tucson Teststand

science-platform/templates/nublado2-application.yaml, services/nublado2/Chart.yaml, services/nublado2/templates/_helpers.tpl, services/nublado2/templates/clusterrole.yml, services/nublado2/templates/clusterrolebinding.yml, services/nublado2/templates/gafaelfawr-token.yaml, services/nublado2/templates/netpol.yaml, services/nublado2/templates/nublado-config.yaml, services/nublado2/templates/nublado2-vault-secret.yaml, services/nublado2/values-base.yaml, services/nublado2/values-idfdev.yaml, services/nublado2/values-idfint.yaml, services/nublado2/values-idfprod.yaml, services/nublado2/values-int.yaml, services/nublado2/values-minikube.yaml, services/nublado2/values-red-five.yaml, services/nublado2/values-roe.yaml, services/nublado2/values-stable.yaml, services/nublado2/values-summit.yaml, services/nublado2/values-tucson-teststand.yaml, services/nublado2/values.yaml, services/telegraf-ds/Chart.yaml
And while I'm in there, modernize nublado2 helm chart (pull chart into Phalanx).
=> tickets/DM-34218: expand "clear .local"

services/portal/values-idfdev.yaml, services/portal/values-idfint.yaml
second try to update `data-int`
=> dm-34469: update int to suit version 2022.1, based on firefly version 2022.1.1

services/argocd/values-minikube.yaml
Work around https://github.com/argoproj/argo-helm/issues/1234.
=> Fix repository for Argo CD redis-exporter

services/argocd/values-base.yaml, services/argocd/values-idfdev.yaml, services/argocd/values-idfint.yaml, services/argocd/values-idfprod.yaml, services/argocd/values-int.yaml, services/argocd/values-roe.yaml, services/argocd/values-stable.yaml, services/argocd/values-summit.yaml, services/argocd/values-tucson-teststand.yaml
Push out the change tested on minikube to all other environments.
=> Fix Argo CD Redis metrics container

services/portal/values-idfprod.yaml
See if this clears up our problems integrating the portal with
Nublado notebooks.
=> Run one portal node on IDF prod

services/portal/values-idfprod.yaml
Continuing to track Portal issues.
=> Go back to four Portal nodes on IDF prod

services/gafaelfawr/templates/configmap.yaml, services/gafaelfawr/templates/deployment-tokens.yaml, services/gafaelfawr/templates/deployment.yaml
- Move remaining secrets from environment variables to files
- Drop remaining pull-secret references
=> [DM-34335] Further Gafaelfawr 4.1.0 updates

services/telegraf-ds/templates/configmap.yaml, services/telegraf/templates/configmap.yaml
- Also increased metric_batch_size and metric_buffer_limit
=> Increase telegraf polling interval

services/noteburst/templates/worker-deployment.yaml, services/times-square/README.md, services/times-square/charts/times-square/README.md, services/times-square/charts/times-square/templates/ingress-webhooks.yaml, services/times-square/charts/times-square/templates/worker-deployment.yaml, services/times-square/charts/times-square/values.yaml, services/times-square/values-idfdev.yaml, services/times-square/values.yaml
Deploy Times Square 0.4.0b1 (see https://github.com/lsst-sqre/times-square/pull/30)
=> DM-34458: Set values for the redis URLs

services/portal/Chart.yaml, services/sasquatch/README.md, services/sasquatch/values.yaml
=> updates for suit 2022.2

services/plot-navigator/templates/deployment.yaml, services/squareone/README.md, services/squareone/templates/vault-secrets.yaml, services/squareone/values.yaml
- Use the right variable for squareone's Vault secret
- Fix the command-line parameters to plot-navigator
=> Fix Phalanx configuration bugs from the DRY changes

services/nublado2/values-idfdev.yaml
adding cull settings into master for idf dev
=> added in server side cull values

services/noteburst/Chart.yaml, services/noteburst/README.md, services/noteburst/templates/worker-configmap.yaml, services/noteburst/values-idfdev.yaml, services/noteburst/values.yaml
Deploys noteburst from PR https://github.com/lsst-sqre/noteburst/pull/33
=> DM-34864: Update noteburst

science-platform/values-int.yaml, science-platform/values-stable.yaml
- There's a problem deploying strimzi on that evironment
=> Disable sasquatch at ncsa deployments

services/datalinker/Chart.yaml, services/datalinker/README.md, services/datalinker/templates/deployment.yaml, services/datalinker/templates/vault-secrets.yaml, services/datalinker/values.yaml
Update the datalinker appVersion to the about-to-be-released
version, and set DATALINKER_CUTOUT_SYNC_URL so that it knows where
the cutout service is.
=> [DM-35001] Add configuration for new datalinker

services/hips/Chart.yaml, services/hips/README.md, services/hips/values-idfdev.yaml, services/hips/values-minikube.yaml
Add the service account, GCS project, and GCS bucket for a test
HiPS data set.  Update Chart.yaml to flesh out the description and
sources link.
=> [DM-35029] Point IDF dev HiPS service at test data

services/strimzi/values-int.yaml, services/strimzi/values-stable.yaml
Forgot these when disabling the applications.
=> [DM-35096] Remove obsolete values files for NCSA

services/datalinker/Chart.yaml, services/datalinker/README.md
Pick up a typing fix from GPDF.
=> [DM-35182] Bump datalinker to 1.2.2

services/portal/values-idfdev.yaml
=> trying suit-2022.3

services/datalinker/values-idfint.yaml, services/portal/values-idfint.yaml
On IDF int, enable auth for datalinker and bump the Portal version.
=> [DM-35182] Add auth for datalinker, bump Portal

services/tap/values-idfint.yaml
Forgot this when I upped the limits.
=> [DM-34891] Set max java heap size for tap

services/portal/Chart.yaml, services/portal/README.md, services/portal/templates/deployment.yaml, services/portal/values-idfdev.yaml, services/portal/values.yaml
Update Portal to 2022.3 and change the deployment to pass Firefly
parameters via individual environment variables rather than via
FIREFLY_OPTS.
=> [DM-35204] Bump version of parameters and update Portal

services/mobu/values-idfint.yaml
=> [DM-35242] TAP volume 5

services/mobu/values-idfint.yaml
Also use legit users, or at least users that I think are legit.
I think if you use the same user it might not actually spawn multiple.
=> [DM-35242] Turn it up to 15

services/mobu/Chart.yaml
Pick up change to TAP query annotations.
=> [DM-35246] Bump mobu version to 4.3.1

services/gafaelfawr/values-stable.yaml
shot in the dark, trying to figure out why portal is 403
=> add read:image token scope

services/sasquatch/README.md, services/sasquatch/values.yaml
- Need to debug the execution of a long running query used to restore a backup shard
=> Enable debug log level in InfluxDB

services/sasquatch/README.md, services/sasquatch/values.yaml
- Try python code that launches async queries to copy data from one database to another, one query per measurement.
=> Allows for an unlimited number of queries

services/hips/Chart.yaml, services/hips/README.md, services/hips/templates/deployment.yaml, services/hips/values-idfint.yaml, services/hips/values-idfprod.yaml, services/hips/values.yaml
Use version 0.2.0 of crawlspace and increase the replicas to 4 in
IDF int and IDF prod.  Add a configuration to set the log level.
=> [DM-35350] Update HiPS service

services/portal/values-idfint.yaml
Updates default coverage HiPS image and ADQL examples.
=> DM-35385: Update Portal version for testing

services/hips/values-idfdev.yaml
Use the same data release in all three environments to make testing
easier.
=> Point IDF dev HiPS service at DP0.2 release

services/portal/README.md, services/portal/templates/deployment.yaml, services/portal/values-idfdev.yaml, services/portal/values.yaml
- Update SUIT to support firefly 2022.2-PRE-3
- Update deployment.yaml with example support PROPS_FIREFLY_OPTIONS
_note:_ - I tried to make the work with the values architecture but it seems to have trouble with block scalars so I can figure it out, but this would be the next step
=> Dm-35468 trey update suit

services/sasquatch/charts/strimzi-kafka/Chart.yaml, services/sasquatch/charts/strimzi-kafka/README.md, services/sasquatch/charts/strimzi-kafka/values.yaml
- Also update Kafka Connect image to tag strimzi-0.29.0-kafka-3.1.1
=> [DM-35512] Update Kafka to version 3.1.1

services/sherlock/Chart.yaml
=> [DM-35542] Sherlock 0.1.8

services/mobu/values-idfint.yaml
Let's see how we handle this one.
=> [DM-35577] Data-int mobu to 60 TAP users

services/gafaelfawr/README.md, services/gafaelfawr/values.yaml
We now have a tech note that explains how scopes are used, so link
to it.
=> [DM-35550] Add DMTN-235 links to Gafaelfawr values.yaml

services/gafaelfawr/templates/configmap.yaml, services/gafaelfawr/values-idfdev.yaml
Change log level to DEBUG for now.  Remove the dot from Simon's
username.  Fix the username claim configuration for CILogon sites.
=> [DM-34613] More IDF dev Gafaelfawr fixes

services/mobu/values-idfint.yaml
Thanks Russ for changing the user thing.
=> [DM-35577] Turn knob to 120

services/mobu/values-idfint.yaml
Pull in the user info section.
=> [DM-35577] Fix mobu config

services/argocd/values-base.yaml, services/argocd/values-summit.yaml, services/argocd/values-tucson-teststand.yaml
This will allow Chilean IT to access Argo CD.
=> Give SQuaRE Friends access to Argo CD on T&S sites

services/plot-navigator/templates/service.yaml
Currently all requests return a 503 from nginx, and don't seem to ever reach panel. No messages in the logs.
=> Fix plot-navigator.

services/tap/Chart.yaml, services/tap/templates/tap-deployment.yaml
Set up default values for connection pools based on what they were
back in the xml.
=> [DM-35704] Tap to 1.3.0

services/portal/templates/deployment.yaml, services/portal/values-idfdev.yaml, services/portal/values-idfint.yaml
suit-2022.5 on `dev` and `int`
- update hips 360
- testing on int
- fixed json syntax error
- removed trailing slash on hips
=> suit-2022.5

services/nublado2/Chart.yaml, services/nublado2/README.md, services/nublado2/values.yaml
Adds support for primary GIDs.
=> [DM-35881] Update nublado2 to 2.4.0

services/gafaelfawr/Chart.yaml, services/gafaelfawr/README.md, services/gafaelfawr/templates/configmap.yaml, services/gafaelfawr/values-idfdev.yaml, services/gafaelfawr/values.yaml
Add new configuration for the upcoming Gafaelfawr release for user
private groups and primary GIDs.
=> [DM-35881] Add support for user private groups and primary GIDs

services/gafaelfawr/README.md, services/gafaelfawr/templates/cronjob-maintenance.yaml, services/gafaelfawr/templates/deployment-tokens.yaml, services/gafaelfawr/templates/deployment.yaml, services/gafaelfawr/templates/redis-networkpolicy.yaml, services/gafaelfawr/values.yaml
Also fix a bug in adding pod annotations to the Kubernetes operator
pod, noticed when copying configuration from it to the new CronJob.
=> [DM-28121] Add Gafaelfawr maintenance CronJob

services/squareone/Chart.yaml, services/times-square/Chart.yaml
Development of Times Square corresponding to https://github.com/lsst-sqre/times-square/pull/42 and https://github.com/lsst-sqre/squareone/pull/84
=> DM-35816: Times Square development

docs/index.rst, docs/ops/mobu/configuring.rst, docs/ops/mobu/index.rst
Add some basic documentation for mobu including examples of some
typical testing patterns.
=> [DM-35881] Add basic mobu documentation

science-platform/values-idfint.yaml, services/gafaelfawr/values-idfint.yaml, services/sasquatch/values-idfint.yaml, services/strimzi/values-idfint.yaml
- Add values for the idfint environment
- Enable support to oicd clients in gafaelfawr (Chronograf)
- Enable sasquatch and strimzi services
=> Enable sasquatch on idfint

services/squareone/Chart.yaml
This deploys Squareone based on https://github.com/lsst-sqre/squareone/pull/93
=> DM-35954: Develop Squareone

services/nublado2/Chart.yaml, services/nublado2/README.md, services/nublado2/values.yaml
Stop waiting for creation of Secrets from ServiceAccounts, since
Kubernetes 1.24 doesn't work this way.
=> [DM-36022] Bump version of nublado2

services/tap/Chart.yaml, services/tap/README.md, services/tap/templates/vault-secrets.yaml, services/tap/values.yaml
Pick up support for S3 from IN2P3.
=> [DM-35982] Bump version of TAP service

docs/ops/troubleshooting.rst
This is usually a storage problem, so just say that.
=> [DM-35977] Clarify the "bad verification code" Gafaelfawr error

services/moneypenny/values-ccin2p3.yaml, services/tap/templates/tap-deployment.yaml
The secrets are not set correctly when S3 is used instead of GCS
=>  [DM-36074] Fix template for S3 

services/tap-schema/Chart.yaml
Pick up annotations of the ForcedSource table.
=> [DM-35254] Bump version of tap-schema

services/nublado2/values-idfint.yaml, services/nublado2/values-idfprod.yaml
IDF int and IDF prod override values.yaml, so had to be updated separately.
=> [DM-36093] Also update nublado2 ConfigMaps for IDF

services/gafaelfawr/templates/cloudsql-networkpolicy.yaml
If CloudSQL is not enabled, also don't install the NetworkPolicy.
=> [DM-35959] Maybe suppress CloudSQL NetworkPolicy for Gafaelfawr

services/tap-schema/Chart.yaml, services/tap/README.md, services/tap/values.yaml
Update the version of the datalink snippets in TAP, and the version of tap-schema.
=> [DM-35254] Bump tap-schema and datalink snippets

services/portal/values-idfdev.yaml, services/portal/values-idfint.yaml
new release base on firefly 2022.2.4
=> release suit-2022.5.5

services/portal/Chart.yaml, services/portal/values-idfdev.yaml, services/portal/values-idfint.yaml
This is the update that had been planned for yesterday, 2022-09-29, and discussed in RSP Ops.
=> Deploy latest Firefly to production

services/nublado2/values-ccin2p3.yaml, services/portal/values-ccin2p3.yaml, services/tap/values-ccin2p3.yaml
I update our RSP config recently, it should be great if the modification will be merged in master
=> DM-36451 merge ccin2p3 branch to master

services/gafaelfawr/Chart.yaml
Pick up `--fix` flag to `gafaelfawr audit`, plus some other bug fixes.
=> DM-36447: Bump version of Gafaelfawr

services/nublado2/values-idfdev.yaml, services/nublado2/values-summit.yaml, services/nublado2/values-tucson-teststand.yaml
Remove the flag from the summit and add it to the Tucson test stand and IDF dev.
=> Move database update flag

services/gafaelfawr/Chart.yaml, services/gafaelfawr/templates/configmap.yaml, services/gafaelfawr/values-base.yaml, services/gafaelfawr/values-ccin2p3.yaml, services/gafaelfawr/values-idfint.yaml, services/gafaelfawr/values-idfprod.yaml, services/gafaelfawr/values-minikube.yaml, services/gafaelfawr/values-roe.yaml, services/gafaelfawr/values-summit.yaml, services/gafaelfawr/values-tucson-teststand.yaml
Use the new syntax for restricting access by GitHub organization and team.
=> DM-36605: Update to Gafaelfawr 6.2.0

services/alert-stream-broker/charts/alert-stream-broker/README.md, services/alert-stream-broker/charts/alert-stream-broker/values.yaml
Update the values.yaml to the latest supported version of Kafka.
=> DM-36041: Update alert-stream-broker Kafka version

services/gafaelfawr/Chart.yaml, services/gafaelfawr/README.md, services/gafaelfawr/crds/ingress.yaml, services/gafaelfawr/crds/service-token.yaml, services/gafaelfawr/templates/cloudsql-networkpolicy.yaml, services/gafaelfawr/templates/deployment-operator.yaml, services/gafaelfawr/templates/serviceaccount-operator.yaml, services/gafaelfawr/templates/serviceaccount-tokens.yaml, services/gafaelfawr/values.yaml, services/portal/README.md, services/portal/templates/deployment.yaml, services/portal/templates/ingress-admin.yaml, services/portal/templates/ingress.yaml, services/portal/values.yaml
- Add support for the new `GafaelfawrIngress` custom resource
- Update the custom resource definition for `GafaelfawrServiceToken`
- Convert the Portal ingresses to use `GafaelfawrIngress`
=> DM-28493: Update to Gafaelfawr 7.1.0

services/datalinker/templates/ingress-anonymous.yaml, services/gafaelfawr/Chart.yaml, services/gafaelfawr/crds/ingress.yaml, services/tap/templates/tap-ingress-authenticated.yaml
New version with support for anonymous ingresses and passing tokens in `Authorization`.
=> DM-37291: Update to Gafaelfawr 8.0.0

services/portal/README.md, services/portal/values.yaml
Spell persistence correctly so that the setting takes effect.
=> DM-37390: Really disable persistence for Portal Redis

services/gafaelfawr/templates/redis-networkpolicy.yaml
tokens was renamed to operator.
=> DM-37390: Fix Gafaelfawr Redis NetworkPolicy

.github/workflows/docs.yaml, docs/applications/index.rst, docs/applications/linters/index.rst, docs/applications/linters/values.md, science-platform/README.md, science-platform/values-idfint.yaml, science-platform/values.yaml, services/linters/Chart.yaml, services/linters/README.md, services/linters/templates/_helpers.tpl, services/linters/templates/cronjob-dns-linter.yaml, services/linters/values.yaml
Have it only run on data-int for now, since we only need it to run in one place since it's checking global state.
=> [DM-26505] Add in a service for the linters

science-platform/templates/linters-application.yaml
This part creates the namespace and uses the stuff in the services directory.
=> [DM-26505] Add in linters application

services/linters/README.md, services/linters/values.yaml
This should change the permissions to make them match the repo, or at least that's what I'm hoping.
=> [DM-26505] Use repository name for images

services/sasquatch/charts/strimzi-kafka/README.md, services/sasquatch/charts/strimzi-kafka/templates/mirrormaker2.yaml, services/sasquatch/charts/strimzi-kafka/values.yaml
- Strimzi operator 0.32.0 requires new Kafka version
=> Update Kafka to 3.3.1

services/datalinker/Chart.yaml
=> DM-37637: Bump version of datalinker

science-platform/values-idfdev.yaml
We should now have access to Butler, so this will hopefully work properly.
=> DM-37589: Deploy cutout service on IDF dev

services/mobu/values-idfint.yaml
Use the same repository that we use everywhere else.
=> DM-37716: Fix URL for mobu system-test on data-int

services/sasquatch/charts/rest-proxy/README.md, services/sasquatch/charts/rest-proxy/templates/topics.yaml, services/sasquatch/charts/rest-proxy/templates/user.yaml, services/sasquatch/charts/rest-proxy/values.yaml, services/sasquatch/charts/strimzi-kafka/templates/users.yaml, services/sasquatch/values-idfdev.yaml
Add `prompt-processing` Kafka user and the `test.next-visit` topic for testing the prompt processing infrastructure.
=> [DM-37685] Create prompt-processing Kafka user in Sasquatch

.github/workflows/ci.yaml, environments/README.md, environments/values.yaml
- Explicitly use the main branch for environments
- Update the versions used for CI
=> DM-37484: Further Argo CD cleanups

applications/telegraf-ds/README.md, applications/telegraf-ds/templates/configmap.yaml, applications/telegraf-ds/values.yaml, applications/telegraf/README.md, applications/telegraf/templates/configmap.yaml, applications/telegraf/values.yaml
These were renamed in earlier Phalanx work but telegraf was not updated properly.
=> Fix name of telegraph variables

applications/ingress-nginx/values-usdfprod.yaml, docs/applications/nublado2/index.rst, docs/documenteer.toml, docs/environments/index.rst, docs/environments/usdfdev/index.rst, docs/environments/usdfprod/index.rst, environments/values-usdfdev.yaml, environments/values-usdfprod.yaml
- Add the documentation configuration for the new environments
- Add missing empty values files
- Add an ingress-nginx configuration for USDF prod
- Disable sherlock and vo-cutouts, since they weren't configured
- Fix a redirect in the nublado2 documentation
=> DM-37885: Cleanups of USDF environment

applications/ingress-nginx/values-base.yaml
This is the new load balancer IP address that gets provisioned in BTS (manke)
=> Update BTS loadbalancer IP address

applications/gafaelfawr/values-idfprod.yaml, applications/mobu/values-idfprod.yaml
Change the Gafaelfawr configuration for data.lsst.cloud to use COmanage.
=> DM-37389: Switch data.lsst.cloud to COmanage

applications/gafaelfawr/values-idfprod.yaml
=> DM-37389: Fix group DN for production

.github/workflows/ci.yaml, .github/workflows/docs.yaml
Trigger a doc build if a Gafaelfawr values-<env>.yaml file has changed, and also add workflow_dispatch so that we can run it manually.
=> DM-37389: Add additional triggers for docs build

environments/values-summit.yaml
- It is now disabled in all the T&S environments.
=> Disable sherlock at the summit environment

.github/workflows/ci.yaml, .github/workflows/docs.yaml
Try to simplify the conditional and always skip merge_group events.
=> DM-38208: Change criteria for doc uploads

applications/gafaelfawr/Chart.yaml, applications/gafaelfawr/README.md, applications/gafaelfawr/templates/configmap.yaml, applications/gafaelfawr/values-idfdev.yaml, applications/gafaelfawr/values-idfint.yaml, applications/gafaelfawr/values-idfprod.yaml, applications/gafaelfawr/values-minikube.yaml, applications/gafaelfawr/values.yaml
Add Helm chart support for quota settings and add quota settings for the Notebook Aspect to the IDF environments. Switch to camel case settings so that the Gafaelfawr configuration file looks closer to the documentation of the Helm chart parameters, and use with in more places. Reorganize configuration settings to match the order inside Gafaelfawr for less confusion (although all the environment settings have not been updated).
=> DM-37833: Update to Gafaelfawr 9.1.0

applications/gafaelfawr/README.md, applications/gafaelfawr/values-idfdev.yaml, applications/gafaelfawr/values-idfint.yaml, applications/gafaelfawr/values-idfprod.yaml, applications/gafaelfawr/values.yaml
=> DM-37833: Fix Gafaelfawr quota settings

environments/values-usdfdev.yaml
Need to have these enabled on main before I can use branch deploys for testing.
=> Enable plot-navigator on usdf dev.

applications/sasquatch/charts/strimzi-kafka/README.md, applications/sasquatch/charts/strimzi-kafka/templates/connect.yaml, applications/sasquatch/charts/strimzi-kafka/templates/mirrormaker2.yaml, applications/sasquatch/charts/strimzi-kafka/values.yaml
Increase request timeout for slower connections (USDF-Summit)
=> [DM-38462] Investigate MirrorMakerSource connector task failures

applications/sasquatch/charts/strimzi-kafka/templates/users.yaml
Add permissions for test next visit topic for prompt processing user
=> Prompt processing user test next visit topic permissions

applications/noteburst/Chart.yaml, applications/noteburst/templates/deployment.yaml, applications/noteburst/templates/worker-deployment.yaml, applications/noteburst/values-idfdev.yaml
Deploy noteburst 0.6.2 from https://github.com/lsst-sqre/noteburst/pull/52
=> DM-38629: Debug noteburst worker shutdowns

applications/gafaelfawr/Chart.yaml, applications/gafaelfawr/README.md, applications/gafaelfawr/templates/configmap.yaml, applications/gafaelfawr/values-ccin2p3.yaml, applications/gafaelfawr/values-idfdev.yaml, applications/gafaelfawr/values.yaml
Add backward compatibility for the loglevel setting (now logLevel).
=> DM-38414: Switch to Gafaelfawr 9.2.0

applications/noteburst/Chart.yaml
App PR: https://github.com/lsst-sqre/noteburst/pull/53
=> DM-38735 Develop noteburst

applications/sasquatch/README.md, applications/sasquatch/values.yaml
Upgrade Chronograf to version 1.10.1 in all environments.
=> Update Chronograf to version 1.10.1

applications/tap/Chart.yaml
=> GPDF-Upload: stop advertising upload capabilitiy

applications/mobu/README.md, applications/mobu/templates/deployment.yaml, applications/mobu/templates/ingress.yaml, applications/mobu/values-idfdev.yaml, applications/mobu/values-idfint.yaml, applications/mobu/values.yaml
Add support for configuring the path prefix and switch IDF dev and IDF int to the test version of mobu.
=> DM-38425: Update IDF dev/int to test version of mobu

applications/plot-navigator/Chart.yaml, applications/plot-navigator/values-usdfdev.yaml, applications/plot-navigator/values-usdfprod.yaml
Automatically determines available skymaps/instruments.
=> DM-39144: Plot navigator version bump.

applications/sasquatch/charts/kafka-connect-manager/README.md, applications/sasquatch/charts/kafka-connect-manager/values.yaml, applications/sasquatch/charts/strimzi-kafka/README.md, applications/sasquatch/charts/strimzi-kafka/values.yaml
- A couple of images used by Sasquatch were still being pulled from docker hub.
=> Pull images from ghcr.io

applications/sasquatch/values-usdfdev.yaml
- Make the example work as documented
=> Fix tags in the lsstexample connector config

applications/gafaelfawr/Chart.yaml
Should fix Redis connection timeout issues.
=> DM-39186: Upgrade Gafaelfawr to 9.2.1

applications/alert-stream-broker/values-idfint.yaml, applications/alert-stream-broker/values-usdfdev.yaml, environments/values-usdfdev.yaml
Enable Alert Stream Broker in USDF Dev.   Some settings commented out for now until values determined.
=> Enable Alert Stream Broker in USDF Dev

applications/mobu/Chart.yaml, applications/mobu/README.md, applications/mobu/templates/deployment.yaml, applications/mobu/values-idfdev.yaml, applications/mobu/values-idfint.yaml, applications/mobu/values.yaml
Adjust for the new configuration, and test both Nublado v2 and v3 on IDF int.
=> DM-39325: Update to mobu 6.0.0

applications/nublado/Chart.yaml, applications/nublado/README.md, applications/nublado/values.yaml
Update the version of the Nublado controller and the REST spawner.
=> DM-39249: Update to latest Nublado v3 releases

applications/mobu/values-idfdev.yaml, applications/mobu/values-idfint.yaml
The assert still hasn't been fixed on prod, but it looks like it's been fixed on main, so run the main branch for now.
=> DM-39400: Run tutorial notebooks from main on IDF dev and int

applications/gafaelfawr/Chart.yaml
Hopefully fix the various Redis pool issues.
=> DM-39486: Update Gafaelfawr to 9.2.2

applications/sasquatch/Chart.yaml, applications/sasquatch/README.md, applications/sasquatch/values-base.yaml, applications/sasquatch/values.yaml
- Enable it on the base environment.
=> Add InfluxDB staging deployment

applications/portal/templates/deployment.yaml
Depends on latest version of Firefly, to be released as release-2023.1.4
=> DM-39435: Return to desired "insert SSO" behavior

installer/install.sh
This PR is aimed to extend the install.sh script of phalanx, to allow instances to be created with Vault services other than https://vault.lsst.codes
An additional (optional) parameter is introduce for the VAULT_TOKEN_LEASE_DURATION, as Vault services may require shorter durations.
One more minor change (remove one empty space) to make the empty spaces consistent 
Tested on a local dev version of the RSP with a UK(ROE) hosted VAULT service.
=> Extend install.sh to make Vault address & token lease duration optional parameters 

applications/sasquatch/README.md, applications/sasquatch/values.yaml
- Increase requests to guarantee that the influxdb pod has the resources it needs reserved to it.
=> Review influxdb requests configuration

applications/ssotap/Chart.yaml
This has an attempt at getting tap upload to work
=> [DM-39825] tap-postgres 1.12

applications/livetap/Chart.yaml
This will allow for temporary uploading of tables
for livetap.
=> [DM-39825] Livetap to tap-postgres 1.12

applications/sasquatch/charts/kafka-connect-manager/README.md, applications/sasquatch/charts/kafka-connect-manager/values.yaml
- Change max number of retries to 20 (default).
=> Change connector error policy to RETRY

.github/workflows/ci.yaml, environments/values-minikube.yaml
Try to use the latest minikube and Kubernetes, and also bump the verisons of Vault and Argo CD.
=> Update versions for minikube testing

docs/applications/giftless/index.rst
Use the name — description format for app titles.
=> Update title for Giftless docs

applications/gafaelfawr/Chart.yaml
=> Bump Gafaelfawr to 9.3.0

applications/monitoring/Chart.yaml, applications/monitoring/README.md, applications/monitoring/templates/_helpers.tpl, applications/monitoring/templates/cronjobs.yaml, applications/monitoring/templates/ingress.yaml, applications/monitoring/templates/vault-secret.yaml, applications/monitoring/values-roundtable-dev.yaml, applications/monitoring/values.yaml, docs/applications/index.rst, docs/applications/monitoring/index.rst, docs/applications/monitoring/values.md, environments/README.md, environments/templates/monitoring-application.yaml, environments/values-base.yaml, environments/values-ccin2p3.yaml, environments/values-idfdev.yaml, environments/values-idfint.yaml, environments/values-idfprod.yaml, environments/values-minikube.yaml, environments/values-roe.yaml, environments/values-roundtable-dev.yaml, environments/values-roundtable-prod.yaml, environments/values-summit.yaml, environments/values-tucson-teststand.yaml, environments/values-usdf-tel-rsp.yaml, environments/values-usdfdev.yaml, environments/values-usdfprod.yaml, environments/values.yaml
Chronograf UI and cronjobs only, so far.
We will want to coordinate pouring the data into Sasquatch (rather than our standalone InfluxDB) with Angelo when he's back.
=> tickets/DM-40204: move "monitoring" into Phalanx

applications/times-square/Chart.yaml
See https://github.com/lsst-sqre/times-square/pull/56
=> DM-40250: Deploy Times Square 0.9.1

applications/datalinker/README.md, applications/datalinker/templates/deployment.yaml, applications/datalinker/values-usdfdev.yaml, applications/datalinker/values-usdfprod.yaml, applications/datalinker/values.yaml
Be explicit about the S3_ENDPOINT_URL which we need to be because we're not using AWS.  Be explicit about the PGUSER so butler can figure out which address
to contact in the PGPASSFILE.
=> [DM-40192] Changes to chart for on prem S3 @ USDF

applications/portal/README.md, applications/portal/templates/deployment.yaml, applications/portal/values-usdfdev.yaml, applications/portal/values-usdfprod.yaml, applications/portal/values.yaml, environments/values-idfdev.yaml, environments/values-idfint.yaml, environments/values-idfprod.yaml, environments/values-usdfdev.yaml, environments/values-usdfprod.yaml, environments/values.yaml
This is because the livetap service has all the datalinks
=> [DM-40192] Expose livetap tap service in portal

applications/nublado/values-base.yaml, applications/nublado/values-summit.yaml, applications/nublado/values-tucson-teststand.yaml
I had specified "path" everywhere I meant "serverPath"
=> tickets/DM-40454: Correct path to serverPath for T&S site n3 volume defs

applications/sasquatch/README.md, applications/sasquatch/charts/strimzi-kafka/README.md, applications/sasquatch/charts/strimzi-kafka/values.yaml
- Make sure Kafka pods run on different nodes, same for zookeeper pods
=> [DM-40510] Add podAntiAffinity for kafka and zookeeper

applications/rubintv/Chart.yaml, applications/rubintv/README.md, applications/rubintv/secrets-usdfdev.yaml, applications/rubintv/secrets.yaml, applications/rubintv/templates/_helpers.tpl, applications/rubintv/templates/deployment-frontend.yaml, applications/rubintv/templates/deployment-workers.yaml, applications/rubintv/templates/ingress.yaml, applications/rubintv/templates/pvc.yaml, applications/rubintv/templates/service.yaml, applications/rubintv/templates/vault-secrets.yaml, applications/rubintv/values-tucson-teststand.yaml, applications/rubintv/values-usdfdev.yaml, applications/rubintv/values.yaml, docs/applications/index.rst, docs/applications/rubintv/index.rst, docs/applications/rubintv/values.md, environments/README.md, environments/templates/rubintv-application.yaml, environments/values-usdfdev.yaml, environments/values.yaml
Create rubintv app and get it running at usdf-dev
=> tickets/DM-40149: Add RubinTV

applications/kubernetes-replicator/README.md, applications/kubernetes-replicator/values.yaml, applications/ook/Chart.yaml, applications/ook/README.md, applications/ook/templates/configmap.yaml, applications/ook/templates/cronjob-audit.yaml, applications/ook/values-roundtable-dev.yaml, applications/ook/values-roundtable-prod.yaml, applications/ook/values.yaml, applications/sasquatch/values-roundtable-prod.yaml, applications/strimzi/values-roundtable-prod.yaml, environments/values-roundtable-prod.yaml
This enables a Ook audit CronJob on roundtable-dev, see https://github.com/lsst-sqre/ook/pull/142
=> DM-40505: Add ook audit CronJob

applications/sasquatch/README.md, applications/sasquatch/charts/strimzi-kafka/Chart.yaml, applications/sasquatch/charts/strimzi-kafka/README.md, applications/sasquatch/charts/strimzi-kafka/values.yaml
- Update appVersion to 0.36.1 which is the version of the Strimzi operator
- Update Helm docs
=> [DM-40655] Update Kafka to version 3.5.1

environments/values-usdfdev-prompt-processing.yaml
Installed by USDF as part of their vcluster provisioning.
=> prompt processing disable vault secrets operator

applications/ook/Chart.yaml, applications/ook/README.md, applications/ook/templates/cronjob-ingest-updated.yaml, applications/ook/values-roundtable-prod.yaml, applications/ook/values.yaml
This cron job runs the ook ingest-updated job to ingest updated documents from LTD. See https://github.com/lsst-sqre/ook/pull/146
=> DM-40649: Ook ingest-updated cron job

applications/prompt-proto-service-hsc/values-usdfdev-prompt-processing.yaml, applications/prompt-proto-service-latiss/values-usdfdev-prompt-processing.yaml, applications/prompt-proto-service-lsstcam/values-usdfdev-prompt-processing.yaml, applications/prompt-proto-service-lsstcomcam/values-usdfdev-prompt-processing.yaml, charts/prompt-proto-service/templates/prompt-proto-service.yaml
Add name suffix for logs and set image pull policy to always in dev
=> prompt processing add name suffix

requirements/dev.txt, requirements/main.in, src/phalanx/cli.py
Replace the code for phalanx help with an invocation of the new Safir display_help function.
=> DM-40697: Use the new Safir display_help function

applications/prompt-proto-service-hsc/values-usdfdev-prompt-processing.yaml, applications/prompt-proto-service-hsc/values.yaml, applications/prompt-proto-service-latiss/values-usdfdev-prompt-processing.yaml, applications/prompt-proto-service-latiss/values.yaml, applications/prompt-proto-service-lsstcam/values-usdfdev-prompt-processing.yaml, applications/prompt-proto-service-lsstcam/values.yaml, applications/prompt-proto-service-lsstcomcam/values-usdfdev-prompt-processing.yaml, applications/prompt-proto-service-lsstcomcam/values.yaml
add revision annotation to dev and update associated comment
=> prompt processing add revision annotation

applications/gafaelfawr/values-tucson-teststand.yaml
Change TTS access groups
Add new group lsst-ts/tts-access
Remove base and summit access groups
=> Tickets/DM-40717 Change TTS access groups

applications/argocd/values-usdfprod-prompt-processing.yaml, applications/prompt-proto-service-latiss/README.md, applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml, applications/prompt-proto-service-latiss/values.yaml, charts/prompt-proto-service/templates/prompt-proto-service.yaml, charts/prompt-proto-service/templates/vault-secret.yaml, charts/prompt-proto-service/values.yaml, docs/environments/index.rst, docs/environments/usdfprod-prompt-processing/index.rst, environments/templates/prompt-proto-service-latiss-application.yaml, environments/values-usdfprod-prompt-processing.yaml
Add production environment and enable prompt proto service for latiss
=> prompt processing: add production environment

applications/next-visit-fan-out/values-usdfprod-prompt-processing.yaml, environments/values-usdfprod-prompt-processing.yaml
Enable fan out in production and add values
=> prompt processing enable fan out in prod

applications/prompt-proto-service-hsc/README.md, applications/prompt-proto-service-hsc/values-usdfdev-prompt-processing.yaml, applications/prompt-proto-service-hsc/values.yaml, applications/prompt-proto-service-latiss/README.md, applications/prompt-proto-service-latiss/values.yaml, charts/prompt-proto-service/values.yaml, environments/templates/prompt-proto-service-hsc-application.yaml, environments/templates/prompt-proto-service-lsstcam-application.yaml, environments/templates/prompt-proto-service-lsstcomcam-application.yaml
Update path for vault to use global values
=> prompt processing - update vault to use global values

applications/next-visit-fan-out/values-usdfprod-prompt-processing.yaml
=> prompt processing: update schema registry address

applications/nublado/templates/controller-deployment.yaml
Add namespace to the projected metadata, which will be used in a future release. Remove labels and annotations, which we never used.
=> DM-40813: Update downward API for Nublado controller

docs/applications/mobu/configuring.rst
**Pull Request: Mobu Documentation Update**
**Description:**
This pull request updates the documentation pages for mobu ([docs/applications/mobu/configuring.rst]), to update to the latest versions of the models in the Mobu application.
**Changes Made:**
- Change examples to match new schema
- Change some of the descriptive text accordingly
=> Mobu documentation update

applications/portal/Chart.yaml
=> appVersion: "suit-2023.2.2"

applications/portal/Chart.yaml
=> appVersion: "suit-2023.2.3"

applications/livetap/Chart.yaml, applications/ssotap/Chart.yaml, charts/cadc-tap/README.md, charts/cadc-tap/values.yaml
Roll out:
tap schema 2.1.1
tap postgres 1.13.0
tap qserv 2.1.0
=> [DM-40764] Fix access_url hosts to use local environment

applications/gafaelfawr/secrets.yaml, applications/sasquatch/secrets.yaml, applications/semaphore/secrets.yaml, applications/times-square/secrets.yaml
- Add configuration for Gafaelfawr oidc-server-secrets
- Add basic secret configurations for semaphore, times-square, and sasquatch with mostly empty descriptions
=> DM-40790: Add more secrets configuration

applications/alert-stream-broker/README.md, applications/alert-stream-broker/charts/alert-stream-broker/README.md, applications/alert-stream-broker/charts/alert-stream-broker/templates/kafka.yaml, applications/alert-stream-broker/charts/alert-stream-broker/values.yaml, applications/alert-stream-broker/values-usdfdev-alert-stream-broker.yaml
Add prometheus monitoring and JMX exporter in helm chart.
=> alert stream broker: prometheus monitoring

applications/ook/Chart.yaml, applications/ook/values-roundtable-dev.yaml
This version adds support for technote.lsst.io-based technotes.
=> DM-40847: Update ook to 0.9.0

docs/applications/_summary.rst.jinja, docs/environments/_summary.rst.jinja
Suppress more whitespace in the documentation templates to make debug output a bit easier to read.
=> DM-40947: Improve whitespace handling in doc templates

applications/giftless/secrets.yaml, applications/monitoring/secrets.yaml, applications/ook/secrets.yaml, applications/sasquatch/secrets.yaml, applications/squarebot/secrets.yaml, applications/vault-secrets-operator/values-roundtable-dev.yaml, environments/values-roundtable-dev.yaml
- Add secrets.yaml for giftless
- Add secrets.yaml for monitoring
- Add app role for vault-secrets-operator
- Migrate vaultPathPrefix
=> DM-40952: Secrets migration for roundtable-dev

applications/gafaelfawr/values-idfdev.yaml, applications/gafaelfawr/values-idfint.yaml
Test CILogon is returning invalid JSON from the token endpoint, so switch to production CILogon for now.
=> Switch idfdev and idfint to prod CILogon

applications/gafaelfawr/README.md, applications/gafaelfawr/values.yaml
Add resource requests and limits based on the Google console statistics and some educated guesses.
=> DM-41090: Add resource requests and limits for Gafaelfawr

src/phalanx/services/application.py, tests/cli/application_test.py
If we didn't configure any external Helm repositories, also don't run helm update. Not only does this save some time, helm update has the obnoxious behavior of failing if no remote repositories are configured, causing CI tests of charts with no dependencies to always fail.
=> Avoid helm update if there are no dependencies

charts/cadc-tap/README.md, charts/cadc-tap/values.yaml
This contains a foreign key in the tap schema tables.
=> [DM-41251] Bump tap schema image to 2.1.2

applications/argocd/values-usdfint.yaml, applications/gafaelfawr/values-usdfint.yaml, applications/livetap/values-usdfint.yaml, applications/mobu/values-usdfint.yaml, applications/nublado/values-usdfint.yaml, applications/plot-navigator/values-usdfint.yaml, applications/postgres/values-usdfint.yaml, applications/sasquatch/values-usdfint.yaml, applications/semaphore/values-usdfint.yaml, applications/squareone/values-usdfint.yaml, applications/ssotap/values-usdfint.yaml, applications/strimzi/values-usdfint.yaml, applications/tap/values-usdfint.yaml, applications/vault-secrets-operator/values-usdfint.yaml, environments/values-usdfint.yaml
- rest-proxy disabled in sasquatch
- livetap/ssotap image repo set to usdf-prod
- nublado proxy-connect timeouts set high to test web socket timeouts
=> deploy usdfint environment

applications/gafaelfawr/Chart.yaml
Will hopefully recover more smoothly from Redis outages.
=> DM-41424: Bump version of Gafaelfawr

docs/applications/index.rst, docs/documenteer.toml, docs/environments/index.rst, docs/environments/usdfint/index.rst, docs/extras/schemas/environment.json, src/phalanx/models/environments.py, src/phalanx/services/application.py
- Inject `global.butlerRepositoryIndex` if appropriate during linting
- Add documentation for the usdfint environment
- Add siav2 to the application index
=> Fix various minor Phalanx issues

applications/gafaelfawr/README.md, applications/gafaelfawr/templates/configmap.yaml, applications/gafaelfawr/values-base.yaml, applications/gafaelfawr/values.yaml, applications/nublado/values-base.yaml
Point Gafaelfawr at local Keycloak on base-lsp.lsst.codes instead of using GitHub. Get user metadata from the IPA LDAP  server.
Add values.yaml documentation for the new groupSearchByDn setting.
=> DM-23878: Use Keycloak on base-lsp.lsst.codes

applications/sasquatch/values-idfint.yaml, applications/sasquatch/values-tucson-teststand.yaml, applications/sasquatch/values-usdfdev.yaml, applications/sasquatch/values-usdfint.yaml
- Make sure we are filtering the Test CSC topics correctly
=> Fix lsst.sal.Test topic regexp elsewhere

applications/sasquatch/charts/strimzi-kafka/templates/mirrormaker2.yaml
- Seeing timeouts and DisconnectException errors in USDF -> Summit connection over the LHN
=> Increase MM2 request timeouts

applications/mobu/values-idfdev.yaml, applications/mobu/values-idfint.yaml
system-test is broken with the latest weekly image. Switch idfdev over to using recommended, switch idfint to recommended for tutorial notebooks, and turn off its latest weekly run with system-test for now.
=> Switch target container for mobu on idfdev, idfint

applications/mobu/values-idfint.yaml, applications/mobu/values-idfprod.yaml
Test latest-weekly against system-test on IDF int, and test the tutorial notebooks against latest-weekly on IDF prod. Do the latter on prod because there is more data there.
=> Re-add mobu tests against latest weekly

charts/cadc-tap/templates/tap-deployment.yaml
This seems to confuse the mysql proxy and not return results although it looks like the query is executing.
=> [DM-41951] Disable useCursorFetch for QServ

docs/about/local-environment-setup.rst, docs/admin/infrastructure/google/credentials.rst, docs/admin/troubleshooting.rst, docs/documenteer.toml
- Fix a permanent redirect of a GitHub link
- Fix formatting errors in the troubleshooting page
- Do not check the validity of console.cloud.google.com links
- Add empty values-base.yaml file for rubintv
=> Fix documentation errors

applications/noteburst/Chart.yaml, applications/noteburst/README.md, applications/noteburst/values.yaml
Release notes: https://github.com/lsst-sqre/noteburst/releases/tag/0.8.0
=> DM-40143: Update to noteburst 0.8.0

applications/next-visit-fan-out/values-usdfdev-prompt-processing.yaml
Update kafka and schema registry IPs after sasquatch maintenance.
=> Prompt Processing Next Visit Fan Out Dev IP Change

applications/nublado/Chart.yaml, applications/nublado/README.md, applications/nublado/values-base.yaml, applications/nublado/values-ccin2p3.yaml, applications/nublado/values-idfdev.yaml, applications/nublado/values-idfint.yaml, applications/nublado/values-idfprod.yaml, applications/nublado/values-roe.yaml, applications/nublado/values-summit.yaml, applications/nublado/values-tucson-teststand.yaml, applications/nublado/values.yaml
Fixes some security issues for user file servers.
=> DM-42477: Deploy Nublado version 4.0.1

applications/jira-data-proxy/README.md, applications/jira-data-proxy/templates/vault-secret.yaml, applications/jira-data-proxy/values.yaml
This matches the global variable set by the Application template.
=> DM-42460: jira-data-proxy change global variable to vaultSecretsPath

applications/nublado/Chart.yaml, applications/nublado/README.md, applications/nublado/values-base.yaml, applications/nublado/values-ccin2p3.yaml, applications/nublado/values-idfdev.yaml, applications/nublado/values-idfint.yaml, applications/nublado/values-idfprod.yaml, applications/nublado/values-roe.yaml, applications/nublado/values-summit.yaml, applications/nublado/values-tucson-teststand.yaml, applications/nublado/values.yaml
Hopefully improves error reporting by switching to pure ASGI middleware.
=> DM-42527: Update to Nublado release 4.0.2

applications/jira-data-proxy/Chart.yaml, applications/jira-data-proxy/README.md, applications/jira-data-proxy/values-usdfdev.yaml, applications/jira-data-proxy/values.yaml
Deploy the first full release of Jira Data Proxy to both idf-dev and usdf-dev.
=> DM-42460: Deploy Jira Data Proxy 1.0.0

applications/gafaelfawr/templates/configmap.yaml, applications/gafaelfawr/values-ccin2p3.yaml, applications/nublado/values-ccin2p3.yaml, applications/postgres/values-ccin2p3.yaml, applications/semaphore/values-base.yaml, applications/semaphore/values-ccin2p3.yaml, applications/semaphore/values-idfdev.yaml, applications/semaphore/values-idfint.yaml, applications/semaphore/values-idfprod.yaml, applications/semaphore/values-minikube.yaml, applications/semaphore/values-roe.yaml, applications/semaphore/values-summit.yaml, applications/semaphore/values-tucson-teststand.yaml, applications/squareone/values-ccin2p3.yaml, applications/tap/values-ccin2p3.yaml, environments/values-ccin2p3.yaml
Merge with the current CC-IN2P3 configuration and clean up some now-unneeded configuration options.
=> DM-42652: Update CC-IN2P3 configuration

applications/filestore-backup/README.md, applications/filestore-backup/values-idfdev.yaml, applications/filestore-backup/values-idfint.yaml, applications/filestore-backup/values.yaml, environments/values-idfint.yaml
Enable filestore-backup:int and refactor its default zone to 'b'
=> Enable filestore-backup:int and refactor its default zone to 'b'

applications/argocd/values-idfint.yaml
Add @JeremyMcCormick to argo-cd
=> Add Jeremy McCormick to Argo CD

applications/checkerboard/README.md, applications/checkerboard/secrets.yaml, applications/checkerboard/templates/deployment.yaml, applications/checkerboard/templates/ingress-anonymous.yaml, applications/checkerboard/templates/ingress.yaml, applications/checkerboard/values-roundtable-dev.yaml, applications/checkerboard/values-roundtable-prod.yaml, applications/checkerboard/values.yaml, applications/gafaelfawr/values-roundtable-dev.yaml, applications/gafaelfawr/values-roundtable-prod.yaml, environments/values-roundtable-prod.yaml
also accomodate post-review checkerboard tightening (remove internal auth and settings in config for it)
=> tickets/DM-42730: add Checkerboard to roundtable-prod

environments/values-roundtable-dev.yaml
=> tickets/DM-42885: Turn off sqrbot-sr and checkerboard on roundtable-dev

docs/developers/local-development.rst, installer/install.sh
This pull request introduces the capability to run the installation script using either approle, or token-based authentication.
It also introduces various refinements a summary of which follows:
**Modified argument parsing:**
- Added capability to the script to be run using named arguments, while maintaing backwards compatibility, where the script defaults to using the existing approle authentication method if run the way it was before
- For example install can be now run with the following ways:
./install.sh myenv VAULT_ROLE_ID=your-vault-id VAULT_SECRET_ID=your-secret
./install.sh myenv your-vault-id your-secret # Uses VAULT_ROLE_ID and VAULT_SECRET_ID
./install.sh myenv VAULT_TOKEN=your-vault-token
./install.sh myenv VAULT_TOKEN=your-vault-token VAULT_TOKEN_LEASE_DURATION=31536000 …
=> Added vault token authentication capability to install script

applications/gafaelfawr/Chart.yaml
This version fixes a bug in checking the database schema during startup.
=> DM-42384: Upgrade Gafaelfawr to 10.0.1

applications/gafaelfawr/values-idfdev.yaml, applications/gafaelfawr/values-idfint.yaml, applications/gafaelfawr/values-idfprod.yaml, applications/gafaelfawr/values-roundtable-dev.yaml, applications/gafaelfawr/values-roundtable-prod.yaml
Disable schema updates on data-dev, data-int, and data. Add schema updates for roundtable-dev and roundtable.
=> DM-42384: Change Gafaelfawr schema update configuration

docs/applications/checkerboard/index.rst, docs/applications/checkerboard/values.md, docs/applications/gafaelfawr/bootstrap.rst, docs/applications/gafaelfawr/index.rst, docs/applications/gafaelfawr/manage-schema.rst, docs/applications/sqrbot-sr/index.rst, docs/applications/sqrbot-sr/values.md
Document how to update the Gafaelfawr schema, and document how to initialize the database when bootstrapping a new environment.
=> DM-42627: Document Gafaelfawr schema updates

applications/mobu/values-idfint.yaml, applications/mobu/values-idfprod.yaml
We don't want noise from failures with the latest weekly to show up in the production alert channel.
=> Move tutorial weekly testing to data-int

applications/next-visit-fan-out/README.md, applications/next-visit-fan-out/templates/deployment.yaml, applications/next-visit-fan-out/values-usdfdev-prompt-processing.yaml, applications/next-visit-fan-out/values-usdfprod-prompt-processing.yaml, applications/next-visit-fan-out/values.yaml
Some were started in https://github.com/lsst-sqre/phalanx/pull/2987  but I'm now separating out the next-visit-fan-out part to here.
=> DM-43090: next-visit-fan-out for LSSTComCamSim for dev

docs/about/introduction.rst, docs/about/secrets.rst, docs/applications/vault/upgrade.rst, environments/README.md, environments/values.yaml, tests/data/input/environments/values-idfdev.yaml, tests/data/input/environments/values-minikube.yaml
(also fix a couple of broken doc links in the Vault documentation)
=> Move from vault.lsst.codes to vault.lsst.cloud

applications/gafaelfawr/values-base.yaml, applications/gafaelfawr/values-summit.yaml
The next Gafaelfawr sync will require a schema update.
=> DM-43177: Enable schema updates on base and summit

applications/gafaelfawr/values-base.yaml, applications/gafaelfawr/values-summit.yaml
The Gafaelfawr schema has been successfully updated and we want to go back to manual updates.
=> DM-43177: Turn off schema updates on base and summit

applications/prompt-proto-service-lsstcomcamsim/Chart.yaml, applications/prompt-proto-service-lsstcomcamsim/README.md, applications/prompt-proto-service-lsstcomcamsim/values-usdfdev-prompt-processing.yaml, applications/prompt-proto-service-lsstcomcamsim/values.yaml, docs/applications/index.rst, docs/applications/prompt-proto-service-lsstcomcamsim/index.rst, docs/applications/prompt-proto-service-lsstcomcamsim/values.md, environments/README.md, environments/templates/prompt-proto-service-lsstcomcamsim-application.yaml, environments/values-usdfdev-prompt-processing.yaml, environments/values-usdfprod-prompt-processing.yaml, environments/values.yaml
This will be the Prompt Processing service for LSSTComCamSim data.
=> DM-42712: Create Prompt Processing service for Ops Rehearsal

applications/telegraf-ds/README.md, applications/telegraf-ds/templates/configmap.yaml, applications/telegraf-ds/values.yaml, applications/telegraf/README.md, applications/telegraf/templates/configmap.yaml, applications/telegraf/values.yaml
=> Parameterize telegraf influxdbv2 endpoint so we can test new server

applications/noteburst/Chart.yaml, applications/noteburst/README.md, applications/noteburst/secrets.yaml, applications/noteburst/templates/deployment.yaml, applications/noteburst/templates/vault-secret.yaml, applications/noteburst/templates/worker-deployment.yaml, applications/noteburst/values-usdfdev.yaml, applications/noteburst/values.yaml, environments/templates/noteburst-application.yaml
See https://github.com/lsst-sqre/noteburst/pull/70
=> DM-43226: Update Noteburst with Slack error reporting

charts/cadc-tap/README.md, charts/cadc-tap/values.yaml
Update sdm_schemas from 2.4.0 to 2.5.0
=> Update sdm_schemas to 2.5.0 release

applications/argocd/values-usdfdev-prompt-processing.yaml, applications/argocd/values-usdfprod-prompt-processing.yaml
Add users to argocd admin for prompt processing.
=> DM-43336: Prompt Processing Add Users

environments/templates/prompt-proto-service-hsc-application.yaml, environments/templates/prompt-proto-service-latiss-application.yaml, environments/templates/prompt-proto-service-lsstcam-application.yaml, environments/templates/prompt-proto-service-lsstcomcam-application.yaml, environments/templates/prompt-proto-service-lsstcomcamsim-application.yaml
Ignore resource limits and requests in ArgoCD reconciliation sync due to ArgoCD bug.
=> DM-43337: Prompt Processing ArgoCD Reconciliation Bug

applications/argocd/values-idfint.yaml, applications/argocd/values-idfprod.yaml
Define a developer role and move non-SQuaRE members to that role on idfint and idfprod.
=> DM-43342: Add Argo CD RBAC on idfint, idfprod

docs/applications/_summary.rst.jinja, src/phalanx/models/applications.py, src/phalanx/storage/config.py, tests/data/input/environments/templates/argocd-application.yaml, tests/data/input/environments/templates/gafaelfawr-application.yaml, tests/data/input/environments/templates/mobu-application.yaml, tests/data/input/environments/templates/postgres-application.yaml
Get the application project from its Argo CD Application Kubernetes resource and include that information on the generated application documentation page.
=> DM-43342: Collect and show application projects

applications/consdb/Chart.yaml, applications/consdb/README.md, applications/consdb/templates/deployment.yaml, applications/consdb/values-base.yaml, applications/consdb/values-summit.yaml, applications/consdb/values-usdfdev.yaml, applications/consdb/values.yaml
Also resolved a number of concerns identified on DM-37511.
=> DM-43240: Fix problems in ConsDB hinfo deployment.

applications/mobu/Chart.yaml
Pick up fixes for the new XSRF handling in the latest version of JupyterLab and JupyterHub, as well as the new git-lfs business.
=> DM-43423: Bump version of mobu

applications/noteburst/Chart.yaml
See https://github.com/lsst-sqre/noteburst/pull/73
=> DM-43393: Update Noteburst

applications/prompt-proto-service-hsc-gpu/README.md, applications/prompt-proto-service-hsc-gpu/values.yaml, applications/prompt-proto-service-hsc/README.md, applications/prompt-proto-service-hsc/values.yaml, applications/prompt-proto-service-latiss/README.md, applications/prompt-proto-service-latiss/values.yaml, applications/prompt-proto-service-lsstcam/README.md, applications/prompt-proto-service-lsstcam/values.yaml, applications/prompt-proto-service-lsstcomcam/README.md, applications/prompt-proto-service-lsstcomcam/values.yaml, applications/prompt-proto-service-lsstcomcamsim/README.md, applications/prompt-proto-service-lsstcomcamsim/values.yaml, charts/prompt-proto-service/README.md, charts/prompt-proto-service/templates/prompt-proto-service.yaml, charts/prompt-proto-service/values.yaml
Add alert stream credentials to prompt processing environment.
=> DM-40415: Add the alert distribution pipelineTask to Prompt Processing

applications/mobu/values-idfint.yaml
Fix the configuration of the latest-weekly system-test runner on idfint to actually use latest-weekly.
=> DM-43573: Fix latest-weekly system-test runner

applications/mobu/Chart.yaml
Fixes an interoperability issue with labs based on jupyterhub 4.1.3.
=> DM-43573: Update to mobu 7.1.1

applications/nublado/values-base.yaml
BTS: Update nublado to Cycle 36.
=> tickets/DM-43529: Cycle 36 upgrade for BTS

applications/nublado/Chart.yaml, applications/nublado/README.md, applications/nublado/values-base.yaml, applications/nublado/values-idfdev.yaml, applications/nublado/values-idfint.yaml, applications/nublado/values-roe.yaml, applications/nublado/values-summit.yaml, applications/nublado/values-tucson-teststand.yaml, applications/nublado/values.yaml
Picks up more fixes for XSRF cookies.
=> DM-43611: Update to Nublado 6.0.1

applications/unfurlbot/Chart.yaml
See https://github.com/lsst-sqre/unfurlbot/pull/5
=> DM-43675: Update to unfurlbot 0.2.1

applications/sasquatch/README.md, applications/sasquatch/charts/strimzi-kafka/README.md, applications/sasquatch/charts/strimzi-kafka/templates/connect.yaml, applications/sasquatch/charts/strimzi-kafka/values.yaml, applications/sasquatch/values-usdfprod.yaml
@mareuter planning on rolling this out today at USDF during patch
=> [DM-43580] Change Sasquatch Kafka min.insync.replicas setting to 2 at USDF

applications/sasquatch/values-usdfdev.yaml, applications/sasquatch/values-usdfprod.yaml
Applying #3133  to USDF during patch Thursday.
=> [DM-43688] Migrate Kafka to Kraft mode at USDF

applications/next-visit-fan-out/values-usdfprod-prompt-processing.yaml
Update address for sasquatch schema registry as IP changed.
=> Prompt Processing: Sasquatch schema registry as IP change

applications/nublado/values-usdfdev.yaml, applications/nublado/values-usdfint.yaml, applications/nublado/values-usdfprod.yaml
Adds DAX_APDB_INDEX_URI environment variable pointing to APDB index file.
=> DM-43760: Enable use of APDB index in nublado

applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml
Remove taint and toleration for LATISS as isolated node testing is completed.
=> Prompt Processing: Isolated Node Scheduling Removal

applications/squareone/Chart.yaml, applications/squareone/templates/deployment.yaml
This update affects the Times Square UI and adds a "recalculate" button.
https://github.com/lsst-sqre/squareone/pull/163
=> DM-43461: Update Squareone to 0.11.0

applications/auxtel/secrets.yaml, applications/calsys/secrets.yaml, applications/control-system-test/secrets.yaml, applications/eas/secrets.yaml, applications/love/secrets.yaml, applications/obssys/secrets.yaml, applications/simonyitel/secrets.yaml, applications/uws/secrets.yaml
=> tickets/SITCOM-1300: Add secrets config files to TTS control system apps in phalanx

applications/control-system-test/charts/integration-testing/templates/controller-configmap.yaml, applications/control-system-test/values-tucson-teststand.yaml, applications/eas/values-tucson-teststand.yaml
The meteoblue API key secret name wasn't updated properly.
=> DM-43409: Fix secret names for eas

applications/nublado/Chart.yaml
=> tickets/DM-43944: Adopt newer Hub/Controller

applications/nublado/README.md, applications/nublado/values-base.yaml, applications/nublado/values-idfdev.yaml, applications/nublado/values-idfint.yaml, applications/nublado/values-roe.yaml, applications/nublado/values-summit.yaml, applications/nublado/values-tucson-teststand.yaml, applications/nublado/values.yaml
The Hub and inithome versions weren't updated.
=> Finish updating Nublado version to 6.0.2

applications/tap/values-idfdev.yaml
qserv-int has been turned off.
=> Point to production qserv on idfdev

charts/cadc-tap/README.md, charts/cadc-tap/values.yaml
Reverts lsst-sqre/phalanx#3272
This release broke data-int. Reverting until this can be resolved.
=> Revert "Update sdm_schemas to 2.6.1"

applications/sasquatch/README.md, applications/sasquatch/values.yaml
This reverts commit c58f025ee28497b5d8b9803a36cc80c7ae6deaeb.
=> Revert "chore(deps): update kapacitor docker tag to v1.7.4"

applications/gafaelfawr/templates/deployment-operator.yaml, applications/gafaelfawr/templates/deployment.yaml
Increase the timeouts and period for Gafaelfawr liveness and readiness probes.
=> DM-44136: Further tweak Gafaelfawr probes

applications/fastapi-bootcamp/Chart.yaml, applications/fastapi-bootcamp/templates/deployment.yaml
See https://github.com/lsst-sqre/fastapi-bootcamp/pull/5
=> DM-44230: Update fastapi-bootcamp

applications/alert-stream-broker/README.md, applications/alert-stream-broker/charts/alert-stream-schema-registry/README.md, applications/alert-stream-broker/charts/alert-stream-schema-registry/values.yaml
DM-41530 has changed the alert schema. Updating chart to point to the newest schema version.
=> DM-44277: Update schema version in alert stream

applications/dfuchs-test/.helmignore, applications/dfuchs-test/Chart.yaml, applications/dfuchs-test/README.md, applications/dfuchs-test/templates/_helpers.tpl, applications/dfuchs-test/templates/configmap.yaml, applications/dfuchs-test/templates/deployment.yaml, applications/dfuchs-test/templates/ingress.yaml, applications/dfuchs-test/templates/networkpolicy.yaml, applications/dfuchs-test/templates/service.yaml, applications/dfuchs-test/values.yaml, docs/applications/dfuchs-test/index.rst, docs/applications/dfuchs-test/values.md, docs/applications/rubin.rst, environments/README.md, environments/templates/applications/rubin/dfuchs-test.yaml, environments/values-idfdemo.yaml, environments/values.yaml
Dummy app generated from `phalanx application create`. If I understand this, once this gets merged to the demo branch, I'll be able to iterate my app from a branch of my own.
Same as https://github.com/lsst-sqre/phalanx/pull/3321, but using the [User Branch](https://developer.lsst.io/work/flow.html#user-branches) convention
=> Dan Fuchs's bootcamp catch-up dummy app

applications/noteburst/Chart.yaml
https://github.com/lsst-sqre/noteburst/pull/77
=> DM-43852: Update noteburst

docs/environments/_summary.rst.jinja
=> Fix typo in generated environment pages

applications/squareone/values-roe.yaml
This PR adds some new content to the roe environment, and fixes an different issue with the existing content for it (missing newline causing rendering issues)
Bugfix & New content
Tested in dev environment
Formatting tested with pre-commit
=> Update / Fix Squareone md content for roe environment

applications/sasquatch/values-idfint.yaml
This adds new namespaces in Sasquatch for camera data and configures the connectors with the provided tags.
=> [DM-44413] Add new namespaces in Sasquatch for lsst.ATCamera, lsst.MTCamera and lsst.CCCamera

applications/gafaelfawr/Chart.yaml, applications/gafaelfawr/crds/ingress.yaml, applications/nublado/README.md, applications/nublado/templates/proxy-ingress.yaml, applications/nublado/values.yaml, applications/portal/templates/ingress.yaml
Switch to the GafaelfawrIngress handling of authentication caching.
=> DM-44468: Update to Gafaelfawr 11.1.0

applications/gafaelfawr/Chart.yaml
Fixes enrollment flow handling for CILogon authentication providers, plus some other bug fixes.
=> DM-44541: Update Gafaelfawr to 11.1.1

applications/alert-stream-broker/charts/alert-stream-broker/templates/kafka-topics.yaml, applications/alert-stream-broker/values-usdfdev-alert-stream-broker.yaml
Also update partitions in the simulated topic to 400.
=> DM-24304: Add dev topic to alert stream to test compression

applications/sasquatch/README.md, applications/sasquatch/charts/strimzi-kafka/README.md, applications/sasquatch/charts/strimzi-kafka/templates/schema-registry.yaml, applications/sasquatch/charts/strimzi-kafka/templates/source-schema-registry.yaml, applications/sasquatch/charts/strimzi-kafka/values.yaml, applications/sasquatch/charts/telegraf-kafka-consumer/README.md, applications/sasquatch/charts/telegraf-kafka-consumer/values.yaml
Add requests and limits for Sasquatch components lacking them.
=> tickets/DM-35106-sasquatch: add sasquatch requests and limits where missing

applications/argocd/values-usdf-cm-dev.yaml, applications/argocd/values-usdf-cm.yaml, docs/documenteer.toml, docs/environments/index.rst, docs/environments/usdf-cm-dev/index.rst, docs/environments/usdf-cm/index.rst, environments/values-usdf-cm-dev.yaml, environments/values-usdf-cm.yaml, src/phalanx/storage/helm.py, tests/cli/application_test.py, tests/data/output/idfdev/lint-all-calls.json, tests/data/output/idfdev/lint-git-calls.json
adjust helm command to not timeout if charts exist.
=> deploy phalanx to usdf-cm and usdf-cm-dev vclusters.

applications/unfurlbot/README.md, applications/unfurlbot/values.yaml
Adds detection of SUMMIT- Jira issue keys to unfurlbot's configuration.
=> Add SUMMIT Jira project to unfurlbot

applications/argocd/values-idfdev.yaml, applications/argocd/values-idfint.yaml
Andy will be helping with Butler server and needs to be able to use Argo CD on idfdev and idfint.
=> Add Andy Salnikov to IDF RBAC

applications/tap/values-idfint.yaml, applications/tap/values-usdfdev.yaml, applications/tap/values-usdfint.yaml, applications/tap/values-usdfprod.yaml, charts/cadc-tap/README.md, charts/cadc-tap/templates/tap-deployment.yaml, charts/cadc-tap/values.yaml
Repoint data-int tap to usdf-prod. Enable SSL connections for idf-int and USDF instances.
=> DM-44525: Repoint data-int tap to usdf-prod.

applications/alert-stream-broker/charts/alert-stream-broker/templates/kafka-topics.yaml
Update all topics to use log append time
=> DM-44779: Change the default timestamp to LogAppendtime

applications/ingress-nginx/values-roe.yaml, applications/squareone/values-roe.yaml
**Description**
- Bring in changes to squareone from lsst-uk repo
- Make ingress-controller a daemonset to address issues with Openstack load balancer
=> Make ingress-nginx-controller a daemonset / add squareone content

applications/sasquatch/values-summit.yaml
Summit: Add EPM to sasquatch connectors.
=> tickets/DM-45029: Add EPM to summit sasquatch connectors

applications/sasquatch/charts/telegraf-kafka-consumer/templates/configmap.yaml, applications/sasquatch/values-idfint.yaml
- Deploy the Camera connectors on data-int for the work Max Turri is doing with Sasquatch REST Proxy.
- Deploy the Sasquatch backpack connectors on data-int for Kai.
=> [DM-45167] Deploy Telegraf-based connectors on data-int

applications/sasquatch/values-usdfprod.yaml
Database name needs to be specified at the connector level
=> Fix up database name

applications/squareone/Chart.yaml
This fixes the "Account settings" label in the user menu.
=> DM-44392: Update Squareone to 0.13.1

applications/mobu/values-usdfdev.yaml, applications/mobu/values-usdfint.yaml
Vault secrets have been added.
=> DM-44635 mobu: enable GitHub refresh app in usdfdev and usdfint

applications/auxtel/secrets-base.yaml, applications/simonyitel/secrets-base.yaml
BTS: Fix auxtel and simonyitel secrets.
=> tickets/DM-45304: Fix secrets for auxtel and simonyitel base apps

applications/uws/secrets.yaml
Point uws PG secret at nublado.
=> tickets/DM-45310: Point uws PG secret to nublado in phalanx

applications/sasquatch/README.md, applications/sasquatch/charts/strimzi-kafka/README.md, applications/sasquatch/charts/strimzi-kafka/templates/kafka.yaml, applications/sasquatch/charts/strimzi-kafka/values.yaml, applications/sasquatch/values-base.yaml, applications/sasquatch/values-tucson-teststand.yaml, applications/sasquatch/values-usdfprod.yaml
Set min.insync.replicas via parameter.
=> tickets/DM-45305: Set min.insync.replicas directly in sasquatch chart

applications/squareone/README.md, applications/squareone/templates/ingress-times-square.yaml, applications/squareone/values-idfdemo.yaml, applications/squareone/values-idfdev.yaml, applications/squareone/values-idfint.yaml, applications/squareone/values-idfprod.yaml, applications/squareone/values-usdfdev.yaml, applications/squareone/values.yaml, applications/times-square/README.md, applications/times-square/templates/ingress-templates.yaml, applications/times-square/templates/ingress.yaml, applications/times-square/values-idfdev.yaml, applications/times-square/values-usdfdev.yaml, applications/times-square/values.yaml
Split template-api and default scopes for times-square
=> Split template-api and default scopes for times-square

applications/tap/values-idfint.yaml
Still pointing to USDF Qserv prod but now using DNS
=> Switch to using FDQN for Qserv - no op

applications/gafaelfawr/values-tucson-teststand.yaml
TTS: Add rsp-access team to gafaelfawr.
=> tickets/DM-45271: Add rsp-access team to gafaelfawr TTS config

applications/sasquatch/values-base.yaml, applications/sasquatch/values-tucson-teststand.yaml
TTS/BTS: Add LOVE k8s URL to sasquatch rest-proxy.
=> tickets/DM-45451: Add k8s LOVE URLs to TTS and BTS sasquatch rest-proxy

applications/sasquatch-backpack/README.md, applications/sasquatch-backpack/templates/configmap.yaml, applications/sasquatch-backpack/templates/cronjob.yaml, applications/sasquatch-backpack/values-idfint.yaml, applications/sasquatch-backpack/values-summit.yaml, applications/sasquatch-backpack/values.yaml, applications/sasquatch/values-summit.yaml, applications/sasquatch/values-usdfprod.yaml, environments/values-summit.yaml
Configure Sasquatch REST Proy URL, enable sasquatch-backpack at the summit and replication to USDF.
=> [DM-45537] Deploy sasquatch-backpack at the summit

applications/noteburst/Chart.yaml
Provides improved XRSF token handling when logging into JupyterHub.
See https://github.com/lsst-sqre/noteburst/pull/98
=> DM-45563: Deploy noteburst 0.12.1

applications/prompt-proto-service-latiss/values-usdfprod-prompt-processing.yaml
This PR updates Prompt Processing LATISS-prod from 4.2.0 to 4.3.0.
=> Update LATISS Prompt Processing to 4.3.0.

src/phalanx/services/environment.py
**Description:**
Upgrading to argo-helm version 7.4.1 causes minikube deploy to fail with an error. This PR addresses the issue, by re-syncing the infrastructure apps after the first fail. For context the actual error is:
`InvalidSpecError: Application referencing project infrastructure which does not exist
`
A similar fix is used when syncing the argocd app.
**Additional change**
Because the fix causes the install method to be too complex for ruff's linting checks, for now I've added a noqa.
I think it may be worth breaking out the functionality into smaller private methods, which I can do in a separate PR if that makes sense.
**Jira Issue:**
https://rubinobs.atlassian.net/browse/DM-45675
**Tested:**
This fix was tested by a PR to trigger the deploy which can be seen here: …
=> DM-45675: Fix error with minikube test deploy (Re-sync infrastructure apps after fail)

pyproject.toml, ruff-shared.toml, src/phalanx/services/environment.py, src/phalanx/storage/argocd.py
Use the new shared Ruff configuration from the SQuaRE templates.
=> DM-45759: Switch to shared Ruff configuration

applications/gafaelfawr/values-base.yaml
BTS: Change group for exec:admin related to Argo Workflows.
=> tickets/DM-45989: Change exec:admin group in gafaelfawr for Argo Workflows access

applications/sasquatch/values-base.yaml
Remove kafka-connect-manager configuration and switch over to Telegraf.
=> [DM-40858] Deploy the Telegraf-based connectors on the base cluster

applications/times-square/Chart.yaml
Improves Times Square's user feedback in GitHub Check Runs.
See https://github.com/lsst-sqre/times-square/pull/80
=> DM-46095: Deploy Times Square 0.12.0

applications/nublado/values-summit.yaml
Summit: Add LSSTCam butler directories to nublado.
=> tickets/DM-46156: Add LSSTCam butler directories to nublado on the summit

applications/nublado/values-tucson-teststand.yaml
TTS: Update nublado to Cycle 39.
=> tickets/DM-46113: Update nublado for Cycle 39

applications/gafaelfawr/templates/serviceaccount.yaml, applications/vo-cutouts/Chart.yaml, applications/vo-cutouts/README.md, applications/vo-cutouts/templates/configmap.yaml, applications/vo-cutouts/templates/job-schea-update.yaml, applications/vo-cutouts/templates/serviceaccount.yaml, applications/vo-cutouts/values-idfdev.yaml, applications/vo-cutouts/values-idfint.yaml, applications/vo-cutouts/values-idfprod.yaml, applications/vo-cutouts/values.yaml
Update vo-cutouts to 3.2.0 and add support for schema migrations.
=> DM-46034: Update vo-cutouts, add schema migration support

applications/sasquatch/README.md, applications/sasquatch/charts/strimzi-kafka/README.md, applications/sasquatch/charts/strimzi-kafka/values.yaml
Merged a commit that reverted Sasquatch Kafka to 3.7.1 by mistake.
=> Update Kafka version to 3.8.0

applications/sasquatch/values-usdfdev.yaml
Add additional test topic for testing job based processing with keda.
=> Sasquatch USDF-DEV additional next visit test topic

applications/sasquatch/values-tucson-teststand.yaml
This PR deploys the Telegraf-based connectors at TTS using same configuration we tested at BTS.
=> Deploy the Telegraf-based connectors at TTS

applications/sasquatch/charts/square-events/templates/squarebot-topics.yaml, applications/sasquatch/charts/square-events/templates/squarebot-user.yaml, applications/sasquatch/charts/square-events/templates/templatebot-user.yaml, applications/squarebot/Chart.yaml, applications/squarebot/README.md, applications/squarebot/templates/configmap.yaml, applications/squarebot/values.yaml, applications/templatebot/README.md, applications/templatebot/templates/configmap.yaml, applications/templatebot/values.yaml
This adds support for parsing block_actions and view_submission interaction events from Slack. See https://github.com/lsst-sqre/squarebot/pull/33
=> DM-46427: Deploy Squarebot with interaction support

applications/nublado/values-summit.yaml
Summit: Update nublado mounts for LSSTComCam.
=> tickets/DM-46488: Update ComCam NFS mounts

applications/sasquatch/values-tucson-teststand.yaml
These changes adjust resources requests and limits and connector configuration on TTS.
For the Telegraf connector configuration reducing max_batch_size and increasing flush_interval fixed the issues we were seeing.
I also added the Connectors dashboard there.
=> [DM-46593] Summit maintenance window Oct 04

applications/squareone/values.yaml
See https://rubinobs.atlassian.net/browse/SP-1621
=> DM-46696: Relabel the "Portal" docs as "Firefly"

applications/sasquatch/README.md, applications/sasquatch/charts/telegraf-kafka-consumer/Chart.yaml, applications/sasquatch/charts/telegraf-kafka-consumer/README.md, applications/sasquatch/charts/telegraf-kafka-consumer/values.yaml
- This version releases the fix for the race condition bug found in the Avro parser.
=> Upgrade Telegraf to version 1.32.1

applications/unfurlbot/Chart.yaml
Pick up the fix for expanding Jira ticket references in bot messages.
=> DM-46782: Bump version of unfurlbot

applications/sasquatch/values-summit.yaml, applications/sasquatch/values-tucson-teststand.yaml, applications/sasquatch/values-usdfprod.yaml
Add ATBuilding and DREAM to sasquatch connectors/consumers.
=> tickets/DM-46973: Add new CSCs to sasquatch telegraf consumers

applications/uws/secrets-tucson-teststand.yaml
=> tickets/DM-46988: Add rubintv secrets to UWS namespace on TTS

applications/gafaelfawr/Chart.yaml, applications/gafaelfawr/README.md, applications/gafaelfawr/crds/ingress.yaml, applications/gafaelfawr/templates/_helpers.tpl, applications/gafaelfawr/templates/cronjob-audit.yaml, applications/gafaelfawr/templates/cronjob-maintenance.yaml, applications/gafaelfawr/templates/deployment-operator.yaml, applications/gafaelfawr/templates/deployment.yaml, applications/gafaelfawr/templates/kafka-access.yaml, applications/gafaelfawr/values-ccin2p3.yaml, applications/gafaelfawr/values-idfdev.yaml, applications/gafaelfawr/values-idfint.yaml, applications/gafaelfawr/values-idfprod.yaml, applications/gafaelfawr/values-roe.yaml, applications/gafaelfawr/values-usdfdev.yaml, applications/gafaelfawr/values-usdfint.yaml, applications/gafaelfawr/values-usdfprod.yaml, applications/gafaelfawr/values.yaml, applications/sasquatch/README.md, applications/sasquatch/charts/app-metrics/README.md, applications/sasquatch/charts/app-metrics/templates/kafka-topics.yaml, applications/sasquatch/charts/app-metrics/templates/kafka-users.yaml, applications/sasquatch/charts/app-metrics/templates/telegraf-configmap.yaml, applications/sasquatch/charts/app-metrics/values.yaml, applications/sasquatch/values-idfdev.yaml
Pass the base URL and base internal URL into Gafaelfawr as environment variables and update the deployed version to 12.0.0. Add metrics configuration and adjust the Sasquatch app-metrics configuration based on testing and further discussion.
This does not yet add service values to every GafaelfawrIngress or remove the now-unneeded baseUrl parameters. Those changes will be made after Gafaelfawr is upgraded.
=> DM-46399: Update for Gafaelfawr 12.0.0

applications/gafaelfawr/Chart.yaml
Fixes configuration handling when metrics are disabled.
=> DM-47011: Update to Gafaelfawr 12.0.1

applications/argocd/values-usdf-cm-dev.yaml
So that I can help debug Gafaelfawr issues.
=> DM-47011: Add rra to Argo CD for usdf-cm-dev

applications/sasquatch/values-summit.yaml, applications/sasquatch/values-usdfprod.yaml
Add MTM1M3TS to summit and USDF prod sasquatch configs.
=> tickets/DM-47114: Add MTM1M3TS to sasquatch config

environments/templates/applications/prompt/prompt-proto-service-lsstcomcam.yaml
Update conditional naming to lsstcomcam.
=> DM-46885: Fix ComCam App conditional to enable

applications/gafaelfawr/values-idfint.yaml, applications/sasquatch/values-idfint.yaml, environments/values-idfint.yaml
Enable app-metrics for Sasquatch on idfint, and enable metrics reporting for Gafaelfawr.
=> DM-47212: Enable Gafaelfawr metrics on idfint

applications/gafaelfawr/Chart.yaml
New features for ingress labeling, better authentication metrics, and more OpenID Connect client support.
=> DM-47148: Update Gafaelfawr to 12.1.0

applications/butler/Chart.yaml
Upgrade butler for a bugfix needed by Stelios' sia service.
=> Upgrade butler server

applications/portal/Chart.yaml
Upgrade to version based on firefly 2024.3.1
=> appVersion: "portal-2024.3.1-final"

applications/obsenv-management/values-base.yaml, applications/obsenv-management/values-summit.yaml, environments/values-base.yaml, environments/values-summit.yaml
Add obsenv-management to BTS and summit.
=> tickets/DM-47312: Deploy obs-env management app to other sites

applications/mobu/Chart.yaml
Bump mobu version to pick up newer nublado client
=> Bump mobu version to pick up newer nublado client

applications/prompt-proto-service-lsstcomcam/values-usdfprod-prompt-processing.yaml
This PR updates Prompt Processing ComCam-prod from 4.7.0 to 4.7.1.
=> Deploy Prompt Processing 4.7.1 for ComCam.

applications/sasquatch/values-summit.yaml, applications/sasquatch/values-usdfprod.yaml
Add LEDProjector to summit and USDF-prod connectors/sinks.
=> tickets/DM-47432: Add LEDProjector to sasquatch

applications/prompt-proto-service-hsc-gpu/values-usdfdev-prompt-processing.yaml, applications/prompt-proto-service-hsc/values-usdfdev-prompt-processing.yaml, applications/prompt-proto-service-latiss/values-usdfdev-prompt-processing.yaml, applications/prompt-proto-service-lsstcam/values-usdfdev-prompt-processing.yaml, applications/prompt-proto-service-lsstcomcam/values-usdfdev-prompt-processing.yaml, applications/prompt-proto-service-lsstcomcamsim/values-usdfdev-prompt-processing.yaml
This PR updates all development Prompt Processing configs to use the Kafka service's new address.
=> Update Kafka server for Prompt Processing dev.

applications/sasquatch/README.md, applications/sasquatch/charts/influxdb-enterprise/README.md, applications/sasquatch/charts/influxdb-enterprise/values.yaml
- As recommended by InfluxData becuase AE  might compete with compaction processes.
=> [DM-46884] Turn off AE service

applications/sasquatch/values-base.yaml, applications/sasquatch/values-summit.yaml, applications/sasquatch/values-tucson-teststand.yaml, applications/sasquatch/values-usdfprod.yaml
Add EAS to TTS, BTS, summit and USDF-prod sasquatch consumers.
=> tickets/DM-47761: Add EAS to sasquatch connectors/sinks

applications/next-visit-fan-out/values-usdfdev-prompt-processing.yaml, applications/next-visit-fan-out/values-usdfprod-prompt-processing.yaml
Updated IP addresses for schema registry as they changed during sasquatch maintenance.
=> Prompt Processing: Update Sasquatch Schema Registry Addresses

applications/prompt-proto-service-hsc-gpu/README.md, applications/prompt-proto-service-hsc-gpu/values.yaml, applications/prompt-proto-service-hsc/README.md, applications/prompt-proto-service-hsc/values.yaml, applications/prompt-proto-service-latiss/README.md, applications/prompt-proto-service-latiss/values.yaml, applications/prompt-proto-service-lsstcam/README.md, applications/prompt-proto-service-lsstcam/values.yaml, applications/prompt-proto-service-lsstcomcam/README.md, applications/prompt-proto-service-lsstcomcam/values.yaml, applications/prompt-proto-service-lsstcomcamsim/README.md, applications/prompt-proto-service-lsstcomcamsim/values.yaml, charts/prompt-proto-service/README.md, charts/prompt-proto-service/templates/prompt-proto-service.yaml, charts/prompt-proto-service/values.yaml
Adds knative platform and image notification kafka consumer offset.
=> DM-43082: Knative

applications/sasquatch/values-base.yaml
Base: Update sasquatch telegraf sinks with new CSCs.
=> tickets/DM-48056: Add ATBuilding, DREAM and Calibration Systems to base telegraf sinks

applications/flink/.helmignore, applications/flink/Chart.yaml, applications/flink/README.md, applications/flink/templates/_helpers.tpl, applications/flink/values.yaml, docs/applications/flink/index.rst, docs/applications/flink/values.md, docs/applications/monitoring.rst, environments/README.md, environments/templates/applications/monitoring/flink.yaml, environments/values-idfdev.yaml, environments/values.yaml
Flink is a stream processing tool I'm evaluating to use with Sasquatch, this PR deploys the Flink operator and enables it in idfdev. Next step is to create a Flink application which will be done in another PR.
=> [DM-46796] Deploy Flink operator

applications/wobbly/values.yaml
Now that Wobbly has been running for a while in idfdev, add limits and requests.
=> DM-48139: Add limits and requests for Wobbly

applications/wobbly/values-idfint.yaml
Required for the initial deployment.
=> DM-48199: Enable schema updates for Wobbly on idfint

applications/sasquatch/values-idfint.yaml, applications/wobbly/values-idfdev.yaml, applications/wobbly/values-idfint.yaml
Also disable schema updates on idfint, since it's been deployed.
=> DM-48199: Enable Wobbly metrics on idfdev and idfint

applications/argocd/values-idfint.yaml
He will be working on a PSF service.
=> Give erfan@lsst.cloud developer access

applications/sia/Chart.yaml
**Changes in sia version 0.1.4**
- DM-47811: Fix FAST001 and FAST002 ruff rules and update-deps by @stvoutsin in https://github.com/lsst-sqre/sia/pull/19
- Add type=results to Resource in Error VOTable by @stvoutsin in https://github.com/lsst-sqre/sia/pull/21
=> DM-48121: Upgrade SIA application to v0.1.4

applications/argocd/values-usdfint.yaml, applications/argocd/values-usdfprod.yaml
Add svoutsin as argocd admin, to help debug TAP issues
=> Added svoutsin as argocd admin on usdfint and usdfprod

docs/admin/installation.rst
Apparently attention isn't supported as a directive?
=> Switch from attention to warning

applications/next-visit-fan-out/values-usdfdev-prompt-processing.yaml
Update address for sasquatch schema registry after network outage.
=> Next Visit Fan Out Schema Registry IP Change

applications/postgres/secrets.yaml, applications/postgres/templates/deployment.yaml, applications/postgres/values-usdf-cm-dev.yaml
Updates the Postgres application with a cmservice database option. Applies the cmservice database to the usdf-dev cluster.
=> DM-48099 : Add cmservice database option to postgres

environments/templates/_helpers.tpl, environments/templates/applications/infrastructure/mobu.yaml
=> DM-48365: mobu - Inject availableServices in the ArgoCD Application

applications/butler/Chart.yaml, applications/butler/README.md, applications/butler/templates/hpa.yaml, applications/butler/values-idfint.yaml, applications/butler/values-idfprod.yaml, applications/butler/values.yaml
Enable pod auto-scaling for Butler server to allow for more concurrent requests.
=> DM-48403: Set up autoscaling for Butler server

applications/sasquatch/values-base.yaml, applications/sasquatch/values-summit.yaml, applications/sasquatch/values-tucson-teststand.yaml, applications/sasquatch/values-usdfprod.yaml
=> Rename EAS connector to envsys

applications/next-visit-fan-out/values-usdfprod-prompt-processing.yaml
Updated IP in fan out after Sasquatch schema registry IP changed.
=> Prompt Processing Fan Out: Sasquatch Schema Registry IP change

applications/times-square/Chart.yaml, applications/times-square/README.md, applications/times-square/secrets.yaml, applications/times-square/templates/configmap.yaml, applications/times-square/templates/deployment.yaml, applications/times-square/templates/worker-deployment.yaml, applications/times-square/values-idfdev.yaml, applications/times-square/values-idfint.yaml, applications/times-square/values-idfprod.yaml, applications/times-square/values-usdfdev.yaml, applications/times-square/values-usdfprod.yaml, applications/times-square/values.yaml, environments/templates/applications/rsp/times-square.yaml
Support for https://github.com/lsst-sqre/times-square/pull/90
=> DM-48476: times-square Sentry

applications/nublado/Chart.yaml, applications/nublado/README.md, applications/nublado/values-base.yaml, applications/nublado/values-idfdemo.yaml, applications/nublado/values-idfdev.yaml, applications/nublado/values-idfint.yaml, applications/nublado/values-idfprod.yaml, applications/nublado/values-roe.yaml, applications/nublado/values-summit.yaml, applications/nublado/values-tucson-teststand.yaml, applications/nublado/values.yaml
Update the Nublado application to 8.3.0 and Zero to JupyterHub 4.1.0.
=> DM-48546: Update to Nublado 8.3.0

applications/sasquatch/values-usdfint.yaml
I've used initially the wrong storage class on usdf-rsp-int.
=> [DM-48571] Fix up sc for Sasquatch backup volume

applications/squareone/Chart.yaml, applications/squareone/README.md, applications/squareone/secrets.yaml, applications/squareone/templates/configmap.yaml, applications/squareone/templates/deployment.yaml, applications/squareone/templates/vault-secrets.yaml, applications/squareone/values-idfdev.yaml, applications/squareone/values-idfint.yaml, applications/squareone/values-idfprod.yaml, applications/squareone/values-roundtable-dev.yaml, applications/squareone/values-roundtable-prod.yaml, applications/squareone/values-usdfdev.yaml, applications/squareone/values-usdfint.yaml, applications/squareone/values-usdfprod.yaml, applications/squareone/values.yaml, environments/templates/applications/rsp/squareone.yaml
Support for Sentry in Squareone, goes with [this Squareone PR](https://github.com/lsst-sqre/squareone/pull/176)
=> DM-48618: squareone sentry

applications/squareone/Chart.yaml
See https://github.com/lsst-sqre/squareone/pull/175
=> DM-48557: Improve Squareone's use of the Times Square events endpoint

applications/nublado/Chart.yaml, applications/nublado/README.md, applications/nublado/templates/controller-deployment.yaml, applications/nublado/templates/kafka-access.yaml, applications/nublado/values-base.yaml, applications/nublado/values-idfdemo.yaml, applications/nublado/values-idfdev.yaml, applications/nublado/values-idfint.yaml, applications/nublado/values-idfprod.yaml, applications/nublado/values-roe.yaml, applications/nublado/values-summit.yaml, applications/nublado/values-tucson-teststand.yaml, applications/nublado/values.yaml, applications/sasquatch/charts/app-metrics/values.yaml, applications/sasquatch/values-idfdev.yaml
This release includes changes to hopefully improve scaling under load, most notably not checking Kubernetes status of pods on every JupyterHub request and increasing the frequency of background reconciliation. It also adds support for event metrics.
=> DM-48714: Update Nublado to version 8.4.0

applications/auxtel/values-summit.yaml, applications/calsys/values-summit.yaml, applications/obssys/values-summit.yaml, applications/simonyitel/values-summit.yaml, applications/uws/values-summit.yaml, environments/values-summit.yaml
- Add AWS_REQUEST_CHECKSUM_CALCULATION env var to components that connect to the LFA.
- Pinned revision to 0 for oods and ocps
- changed cycle tag to k0004
=> DM-48943 Summit config files update

src/phalanx/models/vault.py
Decorate overriden methods with `@override` to get additional checking from type checkers.
=> DM-49036: Add override decorators where appropriate

applications/datalinker/Chart.yaml
Support the new format of Butler data IDs.
=> DM-49067: Update datalinker to 3.1.0

charts/cadc-tap/README.md, charts/cadc-tap/values.yaml
Upgrades TAP to version 2.10.0
Changes to 2.10.0 include:
- Upgrading to JRE 11
- Upgrading cadc-adql to version 1.1.14
=> DM-49187: Update TAP to version 2.10.0

applications/noteburst/Chart.yaml, applications/noteburst/README.md, applications/noteburst/templates/configmap.yaml, applications/noteburst/templates/deployment.yaml, applications/noteburst/templates/kafka-access.yaml, applications/noteburst/templates/worker-configmap.yaml, applications/noteburst/templates/worker-deployment.yaml, applications/noteburst/values-idfdev.yaml, applications/noteburst/values-idfint.yaml, applications/noteburst/values-idfprod.yaml, applications/noteburst/values-usdfdev.yaml, applications/noteburst/values-usdfprod.yaml, applications/noteburst/values.yaml, applications/sasquatch/charts/app-metrics/values.yaml, applications/sasquatch/values-idfdev.yaml, applications/sasquatch/values-idfint.yaml, applications/sasquatch/values-idfprod.yaml, applications/sasquatch/values-usdfdev.yaml, applications/sasquatch/values-usdfprod.yaml
Scaffolding to allow Noteburst to emit [app metrics](https://safir.lsst.io/user-guide/metrics/index.html).
Goes with https://github.com/lsst-sqre/noteburst/pull/106.
=> DM-49148: noteburst - app metrics

applications/sasquatch/values-usdfprod.yaml
Resume MTM1M3, MTMount and MTVMS telemetry replication after Kafka topic repartitioning at the Summit
=> [DM-49242] Resume M1M3, Mount and VMS telemetry replication

applications/sasquatch/values-usdfprod.yaml
- It was misplaced and removed some Chronograf env variables
=> Fix up noteburst metrics app

applications/prompt-keda-hsc/values.yaml, applications/prompt-keda-latiss/values.yaml, applications/prompt-keda-lsstcamimsim/values.yaml, applications/prompt-keda-lsstcomcamsim/values.yaml, charts/prompt-keda/templates/scaled-job.yaml
This PR fixes a Kubernetes bug in the Prompt Processing Keda service.
=> DM-49223: Prompt Processing Keda service can't load S3 credentials files

applications/prompt-keda-lsstcamimsim/README.md, applications/prompt-keda-lsstcamimsim/values.yaml, applications/prompt-proto-service-lsstcamimsim/README.md, applications/prompt-proto-service-lsstcamimsim/values.yaml
This PR increases resource allocations and reduces cache size for Prompt Processing imSim. This change eliminates ephemeral storage errors, but merely reduces the rate of memory errors.
=> DM-49255: Prompt Processing runs out of memory/storage with imSim

applications/squareone/Chart.yaml, applications/squareone/values-usdfprod.yaml, applications/times-square/Chart.yaml, applications/times-square/README.md, applications/times-square/templates/job-html-key-migrate.yaml, applications/times-square/values-idfdev.yaml, applications/times-square/values-usdfdev.yaml, applications/times-square/values-usdfprod.yaml, applications/times-square/values.yaml
This version of Times Square and Squareone provides new support for date and datetime parameters.
See pull request: https://github.com/lsst-sqre/times-square/pull/94
=> DM-48924: Update Times Square

applications/times-square/values-idfdev.yaml, applications/times-square/values-usdfdev.yaml, applications/times-square/values-usdfprod.yaml
=> DM-48924: Disable Times Square HTML key migration

environments/values-idfint.yaml, tests/config_test.py
This hasn't started successfully in a while and I believe the intent is to remove it from this environment.
=> Disable production-tools on idfint

applications/argocd/values-idfint.yaml
They will be working on the rubin-rag application.
=> Add Meisner and Yablonski to idfint Argo CD

applications/love/values-summit.yaml
=> DM-49487: Add LOVE producers to FiberSpectrograph 101 and 102 to summit.

applications/prompt-kafka/charts/strimzi-kafka/templates/users.yaml
Update authorization to butler writer topic to correct name.
=> Prompt Processing Kafka Fix Butler Writer Authorization

applications/nublado/Chart.yaml, applications/nublado/README.md, applications/nublado/values-base.yaml, applications/nublado/values-idfdemo.yaml, applications/nublado/values-idfdev.yaml, applications/nublado/values-idfint.yaml, applications/nublado/values-idfprod.yaml, applications/nublado/values-roe.yaml, applications/nublado/values-summit.yaml, applications/nublado/values-tucson-teststand.yaml, applications/nublado/values.yaml
This release fixes the `NetworkPolicy` rules for user labs.
=> DM-49558: Update Nublado to 8.7.1

applications/rapid-analysis/README.md, applications/rapid-analysis/templates/_helpers.tpl, applications/rapid-analysis/templates/comcam-gather-rollup-set.yaml, applications/rapid-analysis/templates/comcam-gather2a-set.yaml, applications/rapid-analysis/templates/comcam-gather2aAos-set.yaml, applications/rapid-analysis/templates/comcam-worker-set.yaml, applications/rapid-analysis/templates/comcam-workerAos-set.yaml, applications/rapid-analysis/templates/comcamsim-gather-rollup-set.yaml, applications/rapid-analysis/templates/comcamsim-gather2a-set.yaml, applications/rapid-analysis/templates/comcamsim-worker-set.yaml, applications/rapid-analysis/templates/deployment.yaml, applications/rapid-analysis/templates/latiss-worker-set.yaml, applications/rapid-analysis/templates/lsstcam-gather-rollup-set.yaml, applications/rapid-analysis/templates/lsstcam-gather2a-set.yaml, applications/rapid-analysis/templates/lsstcam-worker-set.yaml, applications/rapid-analysis/templates/squid-configmap.yaml, applications/rapid-analysis/templates/squid-deployment.yaml, applications/rapid-analysis/templates/squid-pvc.yaml, applications/rapid-analysis/templates/squid-service.yaml, applications/rapid-analysis/values-summit.yaml, applications/rapid-analysis/values-tucson-teststand.yaml, applications/rapid-analysis/values.yaml
This PR originally was created to add a squid proxy to `rapid-analysis`, however other configurations were also added to support summit work.
=> DM-46612: Add squid proxy to rapid-analysis and other configurations.

applications/sasquatch/values.yaml
- Set INACTIVITY_DURATION to 1h
=> Avoid Chronograf frequent logouts

applications/sasquatch/charts/app-metrics/values.yaml, applications/sasquatch/values-idfdev.yaml, applications/sasquatch/values-idfint.yaml, applications/sia/Chart.yaml, applications/sia/README.md, applications/sia/templates/configmap.yaml, applications/sia/templates/deployment.yaml, applications/sia/templates/kafka-access.yaml, applications/sia/values-idfdev.yaml, applications/sia/values-idfint.yaml, applications/sia/values.yaml
Enables initial metrics for the SIAv2 application in Sentry
=> DM-49297: Enable metrics for SIAv2 application on idfint

applications/butler/templates/configmap-private.yaml
Update the preliminary data preview 1 Butler to point at a new DRP run from LSSTComCam/runs/DRP/DP1/w_2025_11/DM-49472
=> DM-49669: Update DP1 butler for new DRP run

applications/sasquatch/README.md, applications/sasquatch/charts/strimzi-kafka/README.md, applications/sasquatch/charts/strimzi-kafka/templates/users.yaml, applications/sasquatch/charts/strimzi-kafka/values.yaml, applications/sasquatch/secrets.yaml, applications/sasquatch/values-idfdev.yaml
PR to add a new "tap" user in Sasquatch. Plan is to use this for the event-based TAP service that is in development.
=> DM-49704: Enable new TAP user in Sasquatch

applications/sasquatch/README.md, applications/sasquatch/charts/strimzi-kafka/README.md, applications/sasquatch/charts/strimzi-kafka/templates/users.yaml, applications/sasquatch/charts/strimzi-kafka/values.yaml, applications/sasquatch/secrets.yaml, applications/sasquatch/values-idfdev.yaml
Add the qserv KafkaUser and create initial KafkaTopics in the `lsst.tap` namespace.
=> [DM-49723] Initial configuration for the TAP service in Sasquatch 

applications/prompt-keda-lsstcomcam/.helmignore, applications/prompt-keda-lsstcomcam/Chart.yaml, applications/prompt-keda-lsstcomcam/README.md, applications/prompt-keda-lsstcomcam/values-usdfdev-prompt-processing.yaml, applications/prompt-keda-lsstcomcam/values.yaml, docs/applications/prompt-keda-lsstcomcam/index.rst, docs/applications/prompt-keda-lsstcomcam/values.md, docs/applications/prompt.rst, environments/README.md, environments/templates/applications/prompt/prompt-keda-lsstcomcam.yaml, environments/values-usdfdev-prompt-processing.yaml, environments/values.yaml
=> DM-49752: ComCam Keda Application

applications/sasquatch/values-idfdev.yaml
- Fixed mismatch with DNS records and pin bootstrap server and broker IPs
=> Pin loadbalancer IPs for kafka on IDF dev

applications/rubin-rag/Chart.yaml
this is part of Jira ticket SP-2095
=> update release -- part of SP-2095

applications/qserv-kafka/values-idfdev.yaml, environments/values-idfdev.yaml
This was already deployed on idfint. Deploy it on idfdev as well.
=> DM-50174: Add Qserv Kafka bridge to idfdev

applications/exposure-checker/Chart.yaml, applications/exposure-checker/README.md, applications/exposure-checker/secrets.yaml, applications/exposure-checker/templates/_helpers.tpl, applications/exposure-checker/templates/deployment.yaml, applications/exposure-checker/templates/ingress.yaml, applications/exposure-checker/templates/pvc.yaml, applications/exposure-checker/templates/service.yaml, applications/exposure-checker/templates/vault-secrets.yaml, applications/exposure-checker/values-usdfdev.yaml, applications/exposure-checker/values.yaml, applications/postgres/secrets.yaml, applications/postgres/templates/deployment.yaml, applications/postgres/values-usdfdev.yaml, docs/applications/exposure-checker/index.rst, docs/applications/exposure-checker/values.md, docs/applications/rubin.rst, environments/README.md, environments/templates/applications/rubin/exposure-checker.yaml, environments/values-usdfdev.yaml, environments/values.yaml
This is meant to run on the USDF RSP, using a database in the phalanx Postgres server for storing state.
=> SP-2009: Add exposure-checker to Phalanx.

applications/ook/Chart.yaml
This version of Ook provides pagination for the Links API.
https://github.com/lsst-sqre/ook/pull/177
=> DM-50016: Update Ook to 0.12.0

applications/sasquatch/Chart.yaml, applications/sasquatch/README.md, applications/sasquatch/charts/kafka-connect-manager/README.md, applications/sasquatch/charts/kafka-connect-manager/values.yaml
- Also remove old dependency kafka-connect-manager-enterprise
=> Disable subchart by default

applications/hoverdrive/.helmignore, applications/hoverdrive/Chart.yaml, applications/hoverdrive/README.md, applications/hoverdrive/secrets.yaml, applications/hoverdrive/templates/_helpers.tpl, applications/hoverdrive/templates/configmap.yaml, applications/hoverdrive/templates/deployment.yaml, applications/hoverdrive/templates/ingress.yaml, applications/hoverdrive/templates/networkpolicy.yaml, applications/hoverdrive/templates/service.yaml, applications/hoverdrive/templates/vault-secrets.yaml, applications/hoverdrive/values-idfdev.yaml, applications/hoverdrive/values.yaml, docs/applications/hoverdrive/index.rst, docs/applications/hoverdrive/values.md, docs/applications/rsp.rst, environments/README.md, environments/templates/applications/rsp/hoverdrive.yaml, environments/values-idfdev.yaml, environments/values-idfint.yaml, environments/values.yaml
This creates the hoverdrive application. See https://github.com/lsst-sqre/hoverdrive/pull/1
=> DM-49938: Initialize the hoverdrive application

applications/cm-service/README.md, applications/cm-service/secrets.yaml, applications/cm-service/templates/api-deployment.yaml, applications/cm-service/templates/configmap.yaml, applications/cm-service/templates/daemon-deployment.yaml, applications/cm-service/templates/pre-install-hooks.yaml, applications/cm-service/values-usdf-cm-dev.yaml, applications/cm-service/values.yaml
Updates CM-Service in usdf-cm-dev
- Use service release 0.3.0
- Add panda configs
- Add butler auth
- Parameterize postgres db auth secret
=> DM-49324 : Update CM Service

applications/mobu/values-idfdev.yaml
Add mobu latest-daily to idfdev.
=> Add Mobu daily support in idfdev

applications/alert-stream-broker/values-usdfdev-alert-stream-broker.yaml
Switch the ingester from reading alerts-simulated to lsst-alerts-v7.4
=> DM-50564: Change ingester read topic from alerts-simulated to lsst-alerts-v7.4

applications/argocd/values-usdfdev-alert-stream-broker.yaml, applications/argocd/values-usdfdev-prompt-processing.yaml, applications/argocd/values-usdfprod-prompt-processing.yaml
Add Stanford domains to `NO_PROXY` env variables to bypass proxy.
=> Prompt Processing and Alert Stream Broker Argo No Proxy

applications/noteburst/Chart.yaml, applications/noteburst/README.md, applications/noteburst/secrets.yaml, applications/noteburst/templates/configmap.yaml, applications/noteburst/templates/deployment.yaml, applications/noteburst/templates/worker-configmap.yaml, applications/noteburst/templates/worker-deployment.yaml, applications/noteburst/values-idfdev.yaml, applications/noteburst/values-idfint.yaml, applications/noteburst/values-idfprod.yaml, applications/noteburst/values-usdfdev.yaml, applications/noteburst/values-usdfprod.yaml, applications/noteburst/values.yaml, environments/templates/applications/rsp/noteburst.yaml
Goes with [this noteburst PR](https://github.com/lsst-sqre/noteburst/pull/115)
=> DM-49664: noteburst - Sentry

applications/ook/Chart.yaml, applications/ook/README.md, applications/ook/templates/cronjob-ingest-texmf.yaml, applications/ook/values-roundtable-dev.yaml, applications/ook/values-roundtable-prod.yaml, applications/ook/values.yaml
See https://github.com/lsst-sqre/ook/pull/180
Includes database migrations to add glossary and author information tables.
=> DM-50331: Update Ook to 0.13.0

applications/prompt-keda-hsc/values.yaml, applications/prompt-keda-latiss/values.yaml, applications/prompt-keda-lsstcam/values-usdfprod-prompt-processing.yaml, applications/prompt-keda-lsstcam/values.yaml, applications/prompt-keda-lsstcamimsim/values.yaml, applications/prompt-keda-lsstcomcam/values.yaml, applications/prompt-keda-lsstcomcamsim/values.yaml, applications/prompt-proto-service-hsc-gpu/values.yaml, applications/prompt-proto-service-hsc/values.yaml, applications/prompt-proto-service-latiss/values.yaml, applications/prompt-proto-service-lsstcam/values.yaml, applications/prompt-proto-service-lsstcamimsim/values.yaml, applications/prompt-proto-service-lsstcomcam/values.yaml, applications/prompt-proto-service-lsstcomcamsim/values.yaml
This PR modernizes the task names used in Prompt Processing configs.
=> Update task references in Prompt Processing configs

applications/sasquatch/charts/prompt-processing/templates/kafka-topics.yaml, applications/sasquatch/charts/prompt-processing/templates/kafka-users.yaml, applications/sasquatch/values-summit.yaml, applications/sasquatch/values-usdfdev.yaml
Enable prompt processing Kafka user on the Summit.
=> DM-50571: Enable prompt-processing Kafka User on Summit

applications/hoverdrive/Chart.yaml
See https://github.com/lsst-sqre/hoverdrive/pull/5
=> DM-50405: Update hoverdrive for dedicated redirect endpoints

applications/noteburst/Chart.yaml, applications/noteburst/values-idfdev.yaml
See https://github.com/lsst-sqre/noteburst/pull/118
=> DM-50663: Update Noteburst

applications/prompt-keda-lsstcam/values-usdfprod-prompt-processing.yaml
This PR removes some debug hooks that were added for first photon but were never needed.
=> Remove unnecessary debug settings from Prompt Processing.

applications/sia/Chart.yaml
Breakdown of changes in 0.4.0 found here:
https://github.com/lsst-sqre/sia/releases/tag/0.4.0
=> DM-50637: Upgrade SIA Chart to version 0.4.0

applications/nublado/values-idfdev.yaml, applications/nublado/values.yaml
=> Shorten idle culling time for lab in IDF-dev

applications/prompt-keda-lsstcomcamsim/README.md, applications/prompt-keda-lsstcomcamsim/values.yaml
Lower job history limit to 5 for comcamsim.
=> Prompt Processing: Lower ComCamSim Job History

docs/_rst_epilog.rst, docs/applications/atlantis/index.rst, docs/applications/vault/upgrade.rst, docs/documenteer.toml
Add another RSP environment to the exclusion list and fix a few permanent redirects.
=> Fix Phalanx broken links

docs/applications/cert-manager/bootstrap.rst
Add section headings to break up the documentation a bit. Add a warning that this approach means requests for different hostnames will conflict with each other. Remove the AWS key ID from the example Vault secret.
=> Improve cert-manager bootstrapping docs

applications/eups-distributor/.helmignore, applications/eups-distributor/Chart.yaml, applications/eups-distributor/README.md, applications/eups-distributor/templates/_helpers.tpl, applications/eups-distributor/templates/deployment.yaml, applications/eups-distributor/templates/ingress.yaml, applications/eups-distributor/templates/networkpolicy.yaml, applications/eups-distributor/templates/service.yaml, applications/eups-distributor/values-roundtable-dev.yaml, applications/eups-distributor/values-roundtable-prod.yaml, applications/eups-distributor/values.yaml, docs/applications/eups-distributor/index.rst, docs/applications/eups-distributor/values.md, docs/applications/roundtable.rst, environments/README.md, environments/templates/applications/roundtable/eups-distributor.yaml, environments/values-idfdev.yaml, environments/values-roundtable-dev.yaml, environments/values-roundtable-prod.yaml, environments/values.yaml
Create a nginx app that allows for the sharing of eups tarballs.
=> Tickets/DM-49936: enable Eups-distributor

applications/noteburst/Chart.yaml, applications/noteburst/values-idfdev.yaml, applications/noteburst/values-idfint.yaml, applications/noteburst/values-idfprod.yaml
Related PRs:
- https://github.com/lsst-sqre/rsp-jupyter-extensions/pull/48
- https://github.com/lsst-sqre/noteburst/pull/121
=> DM-51011: Update Noteburst to send X-Kernel-Name header

applications/sasquatch/README.md, applications/sasquatch/values.yaml
- Need a flag in values.yaml to disable this subchart elsewhere
=> Disable scimma subchart by default

applications/hips/values-idfprod.yaml
We'll enable it when DP1 is officially released.
=> DM-51236: hips - Don't enable DP1 in prod

applications/squareone/Chart.yaml, applications/squareone/README.md, applications/squareone/templates/configmap.yaml, applications/squareone/values-usdfdev.yaml, applications/squareone/values-usdfint.yaml, applications/squareone/values-usdfprod.yaml, applications/squareone/values.yaml
See https://github.com/lsst-sqre/squareone/pull/186
=> DM-51334: Update Squareone with new branding and preview badge

applications/cm-service/README.md, applications/cm-service/templates/api-deployment.yaml, applications/cm-service/templates/configmap.yaml, applications/cm-service/templates/daemon-deployment.yaml, applications/cm-service/templates/pre-install-hooks.yaml, applications/cm-service/values-usdf-cm-dev.yaml, applications/cm-service/values-usdf-cm.yaml, applications/cm-service/values.yaml
Upgrades cm-service deployment to use application version 0.4.0. Extends helm template to support new feature release.
=> DM-50453 : Update CM Service Release

environments/values-usdf-cm.yaml
environment(usdf-cm): enable cm-service
=> DM-50543: Enable CM-Service in USDF-CM

applications/wobbly/Chart.yaml
No significant changes in the new release other than updated dependencies.
=> DM-51443: Upgrade wobbly to 1.0.0

applications/ook/Chart.yaml, applications/ook/values-roundtable-dev.yaml, applications/ook/values-roundtable-prod.yaml
See https://github.com/lsst-sqre/ook/pull/188
=> DM-51484: Update Ook

applications/giftless/templates/ingress.yaml, applications/ook/templates/ingress.yaml
Fix a couple of malformed ingresses that did not pass Gafaelfawr's syntax checking and thus produced errors in gafaelfawr-operator.
=> Fix malformed ingresses on roundtable

applications/rubin-rag/Chart.yaml
Change version from 0.1.2 to 0.2.0
=> SP-2363: Update CustomWeaviateVectorStore

applications/alert-stream-broker/charts/alert-stream-broker/templates/kafka-topics.yaml, applications/alert-stream-broker/values-usdfdev-alert-stream-broker.yaml
=> DM-50584: Remove unused topics in alert stream

applications/butler/values-idfint.yaml, applications/butler/values-idfprod.yaml
Unlock the DP1 Butler data to release it to end users.
=> DM-51513: Remove access restrictions for DP1 Butler

applications/next-visit-fan-out/README.md, applications/next-visit-fan-out/templates/deployment.yaml, applications/next-visit-fan-out/values-usdfprod-prompt-processing.yaml, applications/next-visit-fan-out/values.yaml
Add conditional to set secret for authenticating to summit.
=> Fan Out Conditional Sasquatch Auth Fix

applications/portal/Chart.yaml, applications/portal/templates/statefulset.yaml
appVersion: "portal-2025.3.2"
- set examples in statefulset.yaml
=> appVersion: "portal-2025.3.2"

applications/vo-cutouts/values-idfprod.yaml
Provide some extra because of the OOM kill problems.
=> Scale cutout workers up to 10 on idfprod

applications/sasquatch/charts/backup/values.yaml, applications/sasquatch/values-idfprod.yaml
- This fixes InfluxDB Enterprise backup path at USDF
=> [DM-51680] Bump Sasquatch backup to 1.3.2

applications/nublado/values-idfdev.yaml, applications/nublado/values-idfint.yaml, applications/nublado/values-idfprod.yaml
Add two new variables at IDF for tutorial convenience.
=> tickets/DM-51607: Add RUBIN_DIR and TUTORIAL_DATA to Nublado/IDF

applications/vo-cutouts/values.yaml
Tweak the memory requests and limits for the vo-cutouts frontend and database worker based on observation after DP1.
=> Adjust vo-cutouts memory requests and limits

applications/templatebot/Chart.yaml
This version uses Ook's /authors/ API to get author info from authordb.yaml rather than directly from authordb.yaml.
=> DM-51728: Update templatebot to 0.4.0

applications/templatebot/Chart.yaml
Adds feature for creating lsst-texmf submodules in new latex documents.
=> DM-51752: Update templatebot to 0.5.0

applications/squareone/values-idfint.yaml, applications/squareone/values.yaml
And drop the idf-int specific variant to allow previewing there.
=> Update /api-aspect for all endpoints

applications/argocd/values-usdfdev-prompt-processing.yaml
David Irving is working on a Butler microservice (DMTN-310 / DM-49670) for Prompt Processing and needs Argo CD access to test.
=> Add dirving to usdfdev-prompt-processing RBAC

applications/nublado/Chart.yaml
=> Newer nublado version

applications/sia/Chart.yaml
This upgrades the requirements (including picking up latest dax_obscore/daf_butler changes) and adds coosys/timesys to the self-description response.
=> DM-51564: Upgrade SIA application to version 1.0.1

applications/squareone/values.yaml
It was incorrectly copied from DP0.2.
=> Fix SIA endpoint documentation for DP1

applications/ook/Chart.yaml
This provides the initial implementation of Ook's resources API: https://github.com/lsst-sqre/ook/pull/189
=> DM-51522: Update ook to 0.18.0

environments/values-base.yaml, environments/values-summit.yaml
This is required to get credentials for applications that use Kafka.
=> Enable strimzi-access-operator at summit and base

applications/ook/Chart.yaml, applications/ook/README.md, applications/ook/templates/_helpers.tpl, applications/ook/templates/cronjob-audit.yaml, applications/ook/templates/cronjob-ingest-texmf.yaml, applications/ook/templates/cronjob-ingest-updated.yaml, applications/ook/templates/deployment.yaml, applications/ook/templates/job-country-code-migration.yaml, applications/ook/templates/job-schema-update.yaml, applications/ook/values-roundtable-dev.yaml, applications/ook/values-roundtable-prod.yaml, applications/ook/values.yaml
- Refactors Ook application templates to centralize volume and volume mount configuration
- Runs the `ook migrate-country-codes` command after the database migration to populate the country code column in the affiliation table.
=> DM-52065: Update Ook with address formatting

applications/cm-service/values-usdf-cm.yaml
Fixes name of value parameter.
=> DM-51586 - CM-SERVICE: fix value param name

applications/sasquatch/values-summit.yaml
=> OSW-819: Update resources for m2 telegraf connector and kafka exporter in Summit.

applications/squareone/Chart.yaml
https://github.com/lsst-sqre/squareone/pull/195
=> DM-52146: Update Squareone to Next 13

applications/next-visit-fan-out/values-usdfprod-prompt-processing.yaml
Update schema registry address after maintenace.
=> Fan Out: Update Schema Registry Address

applications/sasquatch/values-summit.yaml
=> OSW-845: Adjust resources for m2 telegraf connector 

applications/repertoire/.helmignore, applications/repertoire/Chart.yaml, applications/repertoire/README.md, applications/repertoire/secrets.yaml, applications/repertoire/templates/_helpers.tpl, applications/repertoire/templates/configmap.yaml, applications/repertoire/templates/deployment.yaml, applications/repertoire/templates/ingress.yaml, applications/repertoire/templates/networkpolicy.yaml, applications/repertoire/templates/service.yaml, applications/repertoire/templates/vault-secrets.yaml, applications/repertoire/values-idfdev.yaml, applications/repertoire/values.yaml, docs/applications/infrastructure.rst, docs/applications/repertoire/index.rst, docs/applications/repertoire/values.md, environments/README.md, environments/templates/applications/infrastructure/repertoire.yaml, environments/values-idfdev.yaml, environments/values.yaml, src/phalanx/services/application.py
Add the new Repertoire service discovery service. For now, enable it only on idfdev.
=> DM-52228: Add Repertoire

applications/nublado/Chart.yaml, applications/nublado/README.md, applications/nublado/secrets.yaml, applications/nublado/templates/controller-deployment.yaml, applications/nublado/templates/vault-secrets.yaml, applications/nublado/values-base.yaml, applications/nublado/values-idfdemo.yaml, applications/nublado/values-idfdev.yaml, applications/nublado/values-idfint.yaml, applications/nublado/values-idfprod.yaml, applications/nublado/values-summit.yaml, applications/nublado/values-tucson-teststand.yaml, applications/nublado/values-ukidacdev.yaml, applications/nublado/values-ukidacprod.yaml, applications/nublado/values.yaml, environments/templates/applications/rsp/nublado.yaml
Goes with this Nublado PR:
https://github.com/lsst-sqre/nublado/pull/576
=> DM-52391: nublado - Add Sentry

applications/prompt-keda-hsc/values-usdfdev-prompt-processing.yaml, applications/prompt-keda-latiss/values-usdfdev-prompt-processing.yaml, applications/prompt-keda-lsstcam/values-usdfdev-prompt-processing.yaml
Update all dev services to reference new Kafka cluster for S3 file notifications.
=> DM-52461: Update Prompt Dev address for S3 File Notifications

applications/envsys/values-base.yaml
Changed to match summit resource limits.
=> OSW-1162: Change resource limits for eas-sim on BTS

applications/plot-navigator/Chart.yaml, applications/plot-navigator/README.md, applications/plot-navigator/values-usdfdev.yaml, applications/plot-navigator/values-usdfint.yaml, applications/plot-navigator/values-usdfprod.yaml, applications/plot-navigator/values.yaml
I will switch from the branch to the tagged version once the plot-navigator changes are merged.
=> SP-2630: Bump plot-navigator, adjust resources.

applications/datalinker/secrets.yaml, applications/repertoire/secrets.yaml, applications/wobbly/Chart.yaml, applications/wobbly/README.md, applications/wobbly/secrets.yaml, applications/wobbly/templates/configmap.yaml, applications/wobbly/templates/cronjob-maintenance.yaml, applications/wobbly/templates/deployment.yaml, applications/wobbly/templates/job-schema-update.yaml, applications/wobbly/values.yaml, environments/templates/applications/rsp/wobbly.yaml
This release contains some fixes for metrics events and logging, plus optional Sentry support.
=> DM-52774: Update Wobbly version to 1.1.1
